### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by alexsurg** [aurelia-ui-toolkits/aurelia-kendoui-bridge#109]
Hi,

Can you please provide a full working example of the Grid.

**Comment by adriatic** [comment]
Sorry - not yet. Grid component is still under the development.

**Comment by JeroenVinke** [comment]
@alexsurg The grid will be part of our first release, so please bear with us! We need to resolve all issues in [this milestone](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/milestones/0.1.0) before we can release. Many examples will be provided

**Comment by alexsurg** [comment]
O.K thanks, please send me a message when you are ready

**Comment by JeroenVinke** [comment]
@alexsurg we have just created the release, but there will be an official announcement.

**Comment by alexsurg** [comment]
Great work, thanks alot.

**Comment by JeroenVinke** [comment]
Note, until [this pull request](https://github.com/jspm/registry/pull/719) gets merged, the installation instructions won't give you the right result, so please wait for the announcement
