### ISSUE TITLE
Improve the explanation of how to use Aurelia enhance feature

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#122]
The current **[text section](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/Using-Aurelia-internal-compiler-in-KendoUI-Grid-Custom-Element#a-few-words-on-using-aurelia-enhance-feature)** in **[Using Aurelia internal compiler in KendoUI Grid Custom Element](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/Using-Aurelia-internal-compiler-in-KendoUI-Grid-Custom-Element)** is unattractive. I propose the following to use a textual version of an "animated movie" that shows the morphing of
```html
<au-kendo-grid data-source.bind="datasource" auto-bind.bind="false" pageable.bind="pageable" sortable.bind="true">
  <au-col title="Contact Name" field="ContactName">
    <div class='customer-photo' css="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
    <div class='customer-name'>${ContactName}</div>
  </au-col>
  <au-col title="Contact Name" field="ContactName"></au-col>
  <au-col title="Contact Title" field="ContactTitle"></au-col>
  <au-col title="Company Name" field="CompanyName"></au-col>
  <au-col field="Country"></au-col>
</au-kendo-grid>
```
by showing several steps:
#### 1. Extraction of the custom elements content resulting with
```html
  <au-col title="Contact Name" field="ContactName">
    <div class='customer-photo' css="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
    <div class='customer-name'>${ContactName}</div>
  </au-col>
  <au-col title="Contact Name" field="ContactName"></au-col>
  <au-col title="Contact Title" field="ContactTitle"></au-col>
  <au-col title="Company Name" field="CompanyName"></au-col>
  <au-col field="Country"></au-col>
```
#### 2. Extraction of <au-col> atttributes for each row
```html
title="Contact Name" field="ContactName"
title="Contact Title" field="ContactTitle">
title="Company Name" field="CompanyName">
field="Country">
```
#### 3. Conversion to JSON
```javascript
{
    title: "Contact Name",
    field: "ContactName"
},
{
    title: "Contact Title",
    field: "ContactTitle"
},
{
    title: "Company Name", 
    field: "CompanyName"
},
{
    field: "Country"
}
```

**Comment by JeroenVinke** [comment]
This has nothing to do with enhance. This is just a fancy way to configure the columns of the grid, via html. It needs to be documented though, because I feel we can use this in other controls as well

**Comment by JeroenVinke** [comment]
But the steps you mentioned are completely correct though :+1;

**Comment by JeroenVinke** [comment]
This is explained in the html grid api article (in the bridge developers notes)
