### ISSUE TITLE
virtualization performance

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#124]
When we enable [virtualization](http://demos.telerik.com/kendo-ui/grid/virtualization-remote-data) on the grid, and we have a column with an `au-kendo-button`, the performance is noticably worse than without this column

this is slower:
![image](https://cloud.githubusercontent.com/assets/2189477/11715277/cf9a0fc4-9f40-11e5-97aa-a49c6c71e74b.png)

this is smooth:
![image](https://cloud.githubusercontent.com/assets/2189477/11715283/e2177bc8-9f40-11e5-9d9d-83537a709d13.png)

**Comment by charlespockert** [comment]
@JeroenVinke are you thinking this is related to using `enhance` rather than handling this using touchpoints in the kendo templating engine?

**Comment by adriatic** [comment]
@charlespockert - great question and the answer is "touch points a lot more likely". In order to verify that, I am tasked with writing the "problem statement" without "hiding" behind terms like `enhance` versus `template compiler`, so that Telerik guys get a clear picture of what would we need in terms of "touch points". Once we get Petyo's comments, we have the "appointment" with Rob to give us his analysis and suggestions how to deal with this

**Comment by JeroenVinke** [comment]
Yes, think so. With enhance, Aurelia compiles each row. If we can somehow use the view compiler to create a viewfactory per column, and using this viewfactory to create views for each cell in this column, then performance should be a lot better. Not sure if kendo supports this kind of approach. It's too bad angular's compiler is way faster than aurelia's, because they can just compile on a row to row basis

**Comment by adriatic** [comment]
> If we can somehow use the view compiler to create a viewfactory per column, and using this viewfactory to create views for each cell in this column, then performance should be a lot better. Not sure if kendo supports this kind of approach.

My [answer](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/124#issuecomment-166126319) assumes that we can do what @JeroenVinke writes above) and **then** we try to squeeze from Telerik "better touch point" whatever that means and if that is even possible

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/135#issuecomment-195710142
