### ISSUE TITLE
Confirm the correctness of the current grid.js and template-compiler.js

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#128]
As recently advised we switched the initial implementation of the KendoUI Grid Control wrapper to a **[better one](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/grid/grid.js)** based on this following explanation:

> Using @processContent allows you to hook into the owning view's compilation process. When the custom element is used in a view, the content that is placed inside of that element can be "custom compiled" using the processContent decorator. You custom function will receive an instance of Aurelia's compiler, the ViewResources dictionary which stores all custom elements and attributes that are visibly scoped to that owning view (needed if you want to compile something), the element whose content is being processed, and the internal compiler "insutruction unit" that stores all the data the compiler extracts for your custom element. You can use this instruction object to "cache" or store any custom data that you process in your function, so that you can read it later when the element gets instantiated. To get access to this later, you can have the TargetInstruction injected into the constructor of your element.
The custom element code you linked is using this technique to efficiently extract the kendo grid colums from the element content during compilation.
In the constructor, it retreives the extracted info with targetInstruction.behaviorInstruction[0].kendoGridColumns
However, it's more safely done with targetInstruction.elementInstruction.kendoGridColumns
(the first behavior instruction is likely to be the element instruction, but isn't guaranteed)
Notice that the extracted columns are passed along to create the options object in getOptions.

**Here is what we did:**

1. **[Kendo Grid control wrapper](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/grid/grid.js)**
2. **[Template compiler](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/template-compiler.js)**
3. **[<au-kendo-grid> Children parser](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/children-parser.js)**

As shown in **[Current implementation of KendoUI Grid control wrapper needs further improvements](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/129)** we already know that the above listed items are not "good enough", so this article is written to establish the context of our previous discussion.

**Comment by EisenbergEffect** [comment]
Not sure what to put here...this looks mostly like it is pointing to #129 for further comments.

**Comment by adriatic** [comment]
In it's original form, this issue was meant to get your confirmation that what was done with your initial suggestions was done right. Given the fact that we are quite sure that your confirmation is implicit, you are correct when saying 
> ..this looks mostly like it is pointing to #129 for further comments.
