### ISSUE TITLE
Improve the current Chart wrapper implementation

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#148]
If the user changes a single chart attribute (this takes place on the Aurelia side of course) there is no way to convey that single change to KendoUI side - instead we force the chart to reinitialize itself in order to pick up that single change

**Comment by JeroenVinke** [comment]
we should look into the `ng-model` of the angular-kendo implementation

**Comment by JeroenVinke** [comment]
this limitation is explained in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/0.4.0/sample/src/help/docs/app-developers-notes/introduction.md#two-way-binding-not-showing-any-effect. We added value binding to handle the ng-model use case
