### ISSUE TITLE
Sample app needs the performance tab

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#165]
We should think on how to automate the Chrome created performance data and feed it into the page that shows the that information per each control

![image](https://cloud.githubusercontent.com/assets/2712405/11916452/79ad0aaa-a6a5-11e5-9ba2-bde191728683.png)

**Comment by JeroenVinke** [comment]
We may create a timer to help us on the performance work of the grid, but I don't see the value of this elsewhere

**Comment by adriatic** [comment]
Regardless of the method we use, I think that is a good idea to have some performance comparisons between our bridge and Telerik's original implementation. Since we are adding some code on top of Telerik's internal use of jQuery, I expect that we ought to be slower, so the value of our solution is to enable Aurelia users to use KendoUI

**Comment by JeroenVinke** [comment]
lets track this in one issue: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/158
