### ISSUE TITLE
Async binding - is there a nicer way around this?

### ISSUE THREAD

**Issue by charlespockert** [aurelia-ui-toolkits/aurelia-kendoui-bridge#179]
In the basic-use demo for `DropDownList` you can change the colour of the cap using the first drop down.

However, the `value` property on the wrapper takes a moment to update to the newly selected value. This is likely due to async bindings.

example:

*template*
```
<input au-kendo-drop-down-list.ref="capColor" 
           au-kendo-drop-down-list="data-text-field: text;
                        			     data-value-field: value;
                        			     data-source.bind: data;
                        			     index.bind: 0;" 
           kendo-change.trigger="onChange()" value="1" style="width: 100%;" />
```

*viewmodel*
```
 onChange() {
    	var value = this.capColor.widget.value();
    
        $("#cap")
        	.toggleClass("black-cap", value == 1)
            .toggleClass("orange-cap", value == 2)
            .toggleClass("grey-cap", value == 3);
	}
```

For clarity - I'd expect to use `this.capColor.value` rather than `this.capColor.widget.value()`.

If we enqueue the `fireKendoEvent` on the micro task queue this ensures the binding is up to date by the time the event fires

e.g.

in `WidgetBase.js`

```
export class WidgetBase {
  constructor(controlName, element) {

    // access root container and get the task queue - don't want to disrupt the constructor sig so use the static container ref
    let container = Container.instance;
    this.taskQueue = container.get(TaskQueue);

    // ...

    // add an event handler 'proxy' to the options object
    options[event] = e => {
      // wrap the callback onto the queue
      this.taskQueue.queueMicroTask(() => {
        fireKendoEvent(this.target, _hyphenate(event), e);
      });
    }
```

This enables us to use the `value` property on the wrapper without any special handling rather than the `value()` method on the widget

Anyone see any problems with that?

**Comment by JeroenVinke** [comment]
Nope, should work.

We could also decide to remove the `value` property from our wrapper, and add a `value()` function which calls the `value()` function on the widget. Users should also be able to get the value from the event arg (after https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/178):

```
<input au-kendo-drop-down-list.ref="capColor" 
           au-kendo-drop-down-list="data-text-field: text;
                                         data-value-field: value;
                                         data-source.bind: data;
                                         index.bind: 0;" 
           kendo-change.trigger="onChange($event)" value="1" style="width: 100%;" />
```

```
 onChange(e) {
        var value = e.value();

        $("#cap")
            .toggleClass("black-cap", value == 1)
            .toggleClass("orange-cap", value == 2)
            .toggleClass("grey-cap", value == 3);
    }
```

**Comment by charlespockert** [comment]
Yeah, there's a `getValue()` and `setValue()` function on dropdownlist (which I've copy-pastad from Autocomplete)

Would probably be better to be consistent with the Kendo controls and just make this a `value()` function - agree?

**Comment by JeroenVinke** [comment]
Yes

**Comment by charlespockert** [comment]
Hopefully will be addressed by #182

**Comment by JeroenVinke** [comment]
Perhaps it would be better to look at angular's ng-model support of the angular-kendo implementation. They also face out of sync value properties, but they have two way binding if you use ng-model.

**Comment by JeroenVinke** [comment]
We will probably need this: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/263

Telerik has published an article about the angular implementation, stating that two-way binding is not supported by Kendo out of the box, but is "expected" because this is almost in any new Javascript framework. So angular is also having issues with the out of sync properties, and they make up for it by having ng-model binding.
