### ISSUE TITLE
Need a decent size sample application using Aurelia-KendoUI plugin

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#187]
Due to its very specific style, where **most pages show a single KendoUI control** instantiated from our "Aurelia context" using declarative approach, our current sample applications does not provide enough information for Aurelia developers planning to use our Aurelia-KendoUI bridge

Here are a few ideas:
1. http://demos.telerik.com/kendo-ui/websushi/#/
2. http://demos.telerik.com/kendo-ui/aeroviewr/
3. http://demos.telerik.com/kendo-ui/musicstore/ / https://github.com/telerik/kendo-music-store

Any other ideas? 

I could do this on a side, as I really need some basic experience writing Aurelia apps - and what could be more useful than doing this at this time?

**Comment by JeroenVinke** [comment]
:+1:

**Comment by adriatic** [comment]
One of the most important tasks in creating the documentation for Aurelia-KendoUI bridge (I decided not to call it plugin any more as plugin is really just a JavaScript version of a DLL, and that noun does not "project" the semantics of our project) is a detailed tutorial. I will use one of the above projects as the basis for that tutorial
