### ISSUE TITLE
How about removing the animation on view changes

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#195]
This is a setting somewhere deep down `<section class="au-animate"> ` ??? 

I do not like watching how each view "unwraps" itself so at least I would like a switch where I can disable this behavior for my own peace of mind

**Comment by JeroenVinke** [comment]
I'm not sure. It would seem that this is done by the animator-css plugin, but I don't see that anywhere in the code

**Comment by adriatic** [comment]
What is the situation with this now ? There is still a lot of animation present - for example change the view from HTML to JavaScript in any component catalog page and  observe that view roll up and then roll down

**Comment by JeroenVinke** [comment]
Ahh, that is a feature of Kendo. http://demos.telerik.com/kendo-ui/tabstrip/index See the animation property in the sample code. Thought you meant an animation when switching between pages

**Comment by adriatic** [comment]
What about response to click on these three buttons? I thought that these are "our private ones".

![image](https://cloud.githubusercontent.com/assets/2712405/12566628/9b16f71e-c388-11e5-85ff-f281028804c8.png)

**Comment by JeroenVinke** [comment]
this is in the 0.3.0 branch
