### ISSUE TITLE
Styles in custom elements are not disposed

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#198]
I have a feeling that the `<style>`'s within a custom element are not disposed properly

**Comment by JeroenVinke** [comment]
Seems like there is no solution: https://github.com/aurelia/framework/issues/234#issuecomment-151680428

So I'll just use id's to make sure they won't interfere with eachother

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/aa58fc3548ddbe600b94f3c786790b7a2f47d716

**Comment by JeroenVinke** [comment]
made an issue for this [here](https://github.com/aurelia/router/issues/267), just to be sure

**Comment by adriatic** [comment]
Curious to see the response :-)

**Comment by JeroenVinke** [comment]
We can try this if all else fails:

```
<template>
    <style>
        @import "/css/font-awesome.min.css";

        .container {
            display: block;
            position: relative;
        }
    </style>

    <div class="container">
        ......
    </div>
</template>
```

It seems that you can import inside a style tag. Style tags are disposed correctly

**Comment by JeroenVinke** [comment]
So I made a change to the sample-runner which runs the sample:

```
            <div id="${sample.control}-${sample.sample}">
              <compose view-model.bind="sample.path"></compose>
            </div>
```

I added `id="${sample.control}-${sample.sample}"`, which means that the API sample of the Button control is within a div with the `button-api` id. This ID can be used in css to narrow the scope of the css:

```
#button-api .demo-section {
    text-align: center;
}
#button-api .box .k-textbox {
    margin: 0;
    width: 80px;
}
```

that way we won't have collisions in other samples

**Comment by adriatic** [comment]
Very smart!
