### ISSUE TITLE
On user friendly links between the docs and samples

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#207]
I would like to add a `Notes` tab to each control sample that is "worthy" of that (read sufficiently complex that additional comments can benefit the user). Such notes need to have links to online help articles , which in turn know how to return back to the note that took the reader to the help page.

The purpose of this is obvious: folks will start looking at control pages first, may not understand how something works on the first glance, then select the related Notes tab, read that information, find the links to more detailed help articles - and all that travel, might enjoy the service that will take them back to the origin of that trip.

In addition to providing the standard links and anchors, this feature requites the `Back` button on top of every help article, that gets set when the user enters from notes articles

**Comment by JeroenVinke** [comment]
We don't know what Aurelia expects our docs to look like, so I propose we wait until we know more.

**Comment by adriatic** [comment]
Yes, for the same reason why it is better to be rich and smart than dumb and poor :-)

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/skeleton-bridge/issues/15 is our best bet because it would allow us to build this feature once and then have it available for all bridges
