### ISSUE TITLE
Create a blog about KendoUI bridge

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#236]
I would expect that this might end up as one of the Durandal hosted blogs - but initially we should stuff it in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki

A logical subtask of this issue is to clean the wiki first, simply by hiding **all** of the existing article (I have them all locally of course)

**Comment by adriatic** [comment]
Confirmed - this is specifically ordered and if we want to synchronize the release of KendoUI bridge with the appearance of the blog, it is pretty urgent

**Comment by JeroenVinke** [comment]
duplicate https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/270
