### ISSUE TITLE
Collect all pieces of information about plugin that we have so far

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#241]
Not yet sorted issues:

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/142 - referencing the article [Best practices in using Aurelia KendoUI plugin](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/Best-practices-in-using-Aurelia-KendoUI-plugin)

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/232#issuecomment-168301997
