### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#242]
1. __(1. introduction)__ 
    which page does this refer to?
    ![image](https://cloud.githubusercontent.com/assets/2189477/12149336/8045d980-b4a3-11e5-8a3c-4eaf68041185.png)

2. __(3. internal structure)__  
isn't this a list of 'samples'?
![image](https://cloud.githubusercontent.com/assets/2189477/12149432/06161b92-b4a4-11e5-9849-18740e41282a.png)

    That would make explanation in the paragraph below easier too:

    > ~~Each of the page showing a KendoUI control converted to an Aurelia component~~ Each sample     has the section that shows the component's view and view model. Here are three consecutive screen-shots showing that information for the Sample grid control on Image 1 above.

3. __(3. internal structure)__
    > The above screenshot indicates that the current version of the plugin wraps KendoUI autocomplete, button, chart, colorpicker, combobox, dropdownlist, grid, menu, progressbar, scheduler, slider, tabstrip and toolbar controls.
        
    this might be confusing. We won't update that image or the list of wrappers, and we won't be updating it much, so it is not a good reflection of the status of our project

    This may be better:

    > The above screenshot indicates that the version of the plugin (in the screenshot) wraps KendoUI autocomplete, button, chart, colorpicker, combobox, dropdownlist, grid, menu, progressbar, scheduler, slider, tabstrip and toolbar controls.

4. __(3. internal structure)__
    > The code in the plugin (which is the JavaScript equivalent of the more general concept of dynamic linker defines its content via the index.js file
    
     missing parenthese

5. __(6. theme selector)__
    > The above screen shot indicates that the Material theme is the default theme. This can be changed using this line.
    
    Should be
    
    > The above screen shot indicates that the Material theme is the __active__ theme. The __default__ theme can be changed using this line.

6. lets remove this page from the menu: __3. it’s easy to get started__

7. __(1. Introduction - App developers)__
    > This collectiom, of articles contained in the App developers tutorials help category presents several short

    collectiom -> collection
8. __(1. Introduction - App developers)__
    >  short tutorials on using the KendoUI components from Aurelia-KendoUI bridge Aurelia plugin.
    
    The "KendoUI components" link should lead to "#/help/docs/about_this_application/2._components_catalog", note the hash in front
    
9. __(2. Setup - App developers)__
    > At this point, while following the series of steps described next, it is assumed that you have the KendoUI package already installed on your computer as described in the vendors type of installation: 
    
    I believe you renamed __vendors__. The image may be out of date too

10. __(4. Button component - App developers)__
    > Observe that the button control, just like the autocomplete control are HTML native elements and that KendoUI Aurelia bridge adds several custom attributes ( k-enable, k-icon that are bound to KendoUI button "matching native properties" . Note also the definition of the event triggers that are activating the code in the view model:

    Missing parenthese
    
11. __(5. Chart component - App developers)__
    > since chart is non a native HTML element

    Typo (not a native HTML element)
    
12. Remove (7. Next actions -- app developers) from the menu?

**Comment by adriatic** [comment]
### ON 1
The reference **About KendoUI bridge** should point to **Bridge developers tutorials** (which was named **About KendoUI bridge** before my last major refactoring. 

**The problem** with referring to a **["category"](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/help/registry.json#L93)** is that this item is not "addressable" viaURL (meaning that it would be a nice thing to have -- unless we switch to Aurelia help **very soon**)

In the same venue, it would be nice that the "currently active category" remains selected navigating within that category. This might be more than trivial programming which does not make sense to spend the time on - had it not been the case that I already think how our own docs are in several ways better than Aurelia's :-)

**Comment by adriatic** [comment]
### ON 2
This comment should point to **Item 2** (Catalog of KendoUI controls as Aurelia components.) from **About this application** category (**not item 3** as you indicated).

**I cannot make sense of your comment here** - like `isn't this a list of 'samples'?` - does this refer to the sidebar items?

***Please explain some more***

**Comment by adriatic** [comment]
### ON 3
Good remark - I will rephrase or completely remove that text. Our docs should be as ***static*** as we can afford.

**Comment by JeroenVinke** [comment]
On 2: if we explain the menu at the left side as a list of samples (of the selected control) , then the description below becomes much clearer in my opinion.

**Comment by adriatic** [comment]
### ON 4

Love you for that catch (it tells me that you really are a methodical reader) :-)

**Comment by adriatic** [comment]
### ON 5

I had a bad feeling writing this sentence yesterday for not including both **active** and **default** theme

**Comment by adriatic** [comment]
### ON 6
No arguments from me :-)

(This is probably one of the oldest pages and if it stays I would have hard time writing it as it misses the point: _people, use KendoUI with Aurelia - not the original environment_)

**Comment by adriatic** [comment]
### ON 7

Same feedback as to **ON 4** above

**Comment by adriatic** [comment]
### ON 8

Thanks for catching this one

**Comment by adriatic** [comment]
### ON 9

Another great catch

**Comment by adriatic** [comment]
### ON 10

You meant to say `parenthesis` which is the singular form - plural is `parentheses` (silly language, with imperfect treatment of Latin words)

**Comment by adriatic** [comment]
### ON 11

I meant to say non-native - but your formulation is better

**Comment by adriatic** [comment]
### ON 12

I am not yet sure as I wanted to offer the articles from the **[related wiki](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki)** for additional reading - but at this time I do not know whether there is anything worth reading there and even if it is, whether it would not be better to put all such stuff in this online help section
