### ISSUE TITLE
Change the menubar to be the same as Aurelia Materialize Components Catalog

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#248]
![image](https://cloud.githubusercontent.com/assets/2712405/12341735/b77d1540-baf1-11e5-8a9b-89ca4a2785fe.png)

the above menu item list should match the current Aurelia KendoUI Components Catalog

![image](https://cloud.githubusercontent.com/assets/2712405/12341763/fb5f064c-baf1-11e5-992f-d5bb3217d819.png)

**Comment by JeroenVinke** [comment]
So basically rename `samples` to `Aurelia KendoUI Components` ? Theme and help/docs can't be removed from the menubar

**Comment by adriatic** [comment]
I think that what we have now is fine

![image](https://cloud.githubusercontent.com/assets/2712405/13203305/2f2014ea-d883-11e5-9faa-1ccecc450750.png)

**Comment by JeroenVinke** [comment]
I like it too :)
