### ISSUE TITLE
Rename this repository to aurelia-kendoui-bridge

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#252]
This change is needed for consistency across all planned (KendoUI, Materialize, Bootstrap) bridges as well as to fit the naming with the newly added **[Skeleton Bridge](https://github.com/aurelia-ui-toolkits/skeleton-bridge)**

**Comment by JeroenVinke** [comment]
We should do this soon then..

**Comment by adriatic** [comment]
Any time you see fit (and I will deal with the effects on the docs)

**Comment by JeroenVinke** [comment]
done
