### ISSUE TITLE
Implement MultiSelect

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#26]

**Comment by JeroenVinke** [comment]
in 0.5.0

**Comment by adriatic** [comment]
What the heck - I disappear for a few hours and you create everything ???

**Comment by adriatic** [comment]
Why 0.5.0? what happened to 0.4.0?

**Comment by JeroenVinke** [comment]
> What the heck - I disappear for a few hours and you create everything ???

I had some time on my hands yesterday so I decided do finish a few simple ones

> Why 0.5.0? what happened to 0.4.0?

0.4.0 was finished yesterday but I discovered that we need to do https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/371

**Comment by JeroenVinke** [comment]
and these controls were scheduled for [0.5.0](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/milestones)

**Comment by adriatic** [comment]
So, what branch can I use to **even try** to contribute something at the coding side ??

**Comment by JeroenVinke** [comment]
I plan to do https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/371, https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/43 and https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/35 tomorrow, so you can pick anything from the [0.6.0](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/milestones/0.6.0) milestone and create the 0.6.0 branch from the 0.5.0 branch

**Comment by adriatic** [comment]
Will do
