### ISSUE TITLE
Document conventions

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#260]
`k-` convention for properties, custom elements, and attributes and `k-on-` for events

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/help/docs/app-developers-tutorials/what-you-need-to-know.md

**Comment by adriatic** [comment]
Great addition! Note the use of au-col - this should be addressed by @charlespockert in his global search and replace, though

**Comment by JeroenVinke** [comment]
Yep, I have a strong feeling @charlespockert won't manually change all the references ;)
