### ISSUE TITLE
Expose widget property

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#262]
:point_up: [17 januari 2016 18:42](https://gitter.im/adriatic/Aurelia-KendoUI?at=569bd274da358920486f3519)

This would allow us to get rid of the [method proxies](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/grid/grid.js#L44-L234) and all the issues that come with this

**Comment by JeroenVinke** [comment]
@charlespockert @adriatic do you guys agree that this would be better?

**Comment by adriatic** [comment]
I see only upside (people **can** use it when and where needed) and no downside (nobody **has**) to use it. Besides, it is not difficult to do.

**Comment by charlespockert** [comment]
Agreed, we can always add an additional solution to proxy the widget
methods if we find we need to

**Comment by JeroenVinke** [comment]
Now in master
