### ISSUE TITLE
ng-model equivalent 

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#263]
The Angular implementation of the Kendo wrappers use `ng-model` as a means to two-way databind the `value` property of a widget to the view-model. Perhaps we can do the same?

![image](https://cloud.githubusercontent.com/assets/2189477/12397472/af669eb6-be0d-11e5-971c-3b4b80a4e50c.png)

**Comment by adriatic** [comment]
> Perhaps we can do the same?

I would say the answer is yes, at least as a first step towards a better solution that could be created working with Telerik. The assumption here is that Telerik will like our bridge and will be interested in working with us

**Comment by JeroenVinke** [comment]
this is in the 0.2.0 branch
