### ISSUE TITLE
Value converters inside <k-col>

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#268]
It seems that Kendo breaks on the pipeline (`|`) used in value converter expressions

**Comment by JeroenVinke** [comment]
we'll probably need to disable Kendo templating. Was hoping to avoid this. https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/115

**Comment by adriatic** [comment]
It seems that @souldrinker is able to keep you fully occupied with his problems (this issue being one of them). I would like to comment some more, but need to refresh my understanding of value converters firs.

**Comment by JeroenVinke** [comment]
So the issue is that Kendo is trying to parse (and compile) the template we're passing in.

For example:

```
      <au-col title="Contact Name" field="ContactName">
        <div class='customer-name'>${ContactName | test}</div>
      </au-col>
```

Above we see the `test` value converter on the `ContactName`.

It is parsed incorrectly by Kendo's templating system as:

![image](https://cloud.githubusercontent.com/assets/2189477/12495760/db97ec48-c091-11e5-9f55-15e8a01075d6.png)

Note that the javascript syntax is invalid and will result in an error.

So https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/115 is about disabling the Kendo templating system. This can be done by wrapping the template in a function.

From this column definition:

```
{
    field: "ContactName",
    template: "<div class='customer-name'>${ContactName | test}</div>"
}
```

to this:

```
{
    field: "ContactName",
    template: function () {
      return "<div class='customer-name'>${ContactName | test}</div>"
   }
}
```

I have tried this out, and value converters seems to work fine with this change. However, we are getting one other issue in return.

We have images in the Basic use sample:
![image](https://cloud.githubusercontent.com/assets/2189477/12495895/a94c0336-c092-11e5-929b-11c15b150dbf.png)

After passing the template via a function, I started getting 404's. One per render. 

![image](https://cloud.githubusercontent.com/assets/2189477/12495933/e617db32-c092-11e5-91a3-98554f18258d.png)

The page renders fine though. I'm not getting a 404 per row, but just one. Not sure what's happening here. The error is gone when I enable Kendo's templating system again.

**Comment by JeroenVinke** [comment]
I used this code in the grid wrapper:

```
  _beforeInitialize(options) {
    // allow for both column definitions via HTML and via an array of columns
    if (this.columns && this.columns.length > 0) {
      options.columns = this.columns;

      options.columns.forEach(c => {
        if (c.template) {
          let template = c.template;
          c.template = function() {
            return template;
          };
        }
      });
    }
  }
```

**Comment by Souldrinker** [comment]
Did you find out what caused your 404 errors? Because it would be really nice to be able to use value converters out of the box and when I changed the _beforeInitialize function in your grid.js to your example above everything seemed to work fine for me without errors including my image column (which I'm fetching from a webapi rather than from a fixed url).

It would be even better if I would be able to use locally "required" value converters rather than using globalResources, but at all being able to use value converters in au-cols like with the above code would help a lot.

**Comment by JeroenVinke** [comment]
Thanks for testing @Souldrinker. No I didn't figure out what caused the 404's. We could provide an option to disable the Kendo templating system. By default it would be disabled. When someone has issues, they could enable the Kendo templating system

**Comment by JeroenVinke** [comment]
> It would be even better if I would be able to use locally "required" value converters rather than using globalResources, but at all being able to use value converters in au-cols like with the above code would help a lot.

I agree, it's something we should try to implement :)

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/269

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/12649293/48606d18-c5de-11e5-8c18-d68569fce041.png)

So it turns out that Kendo's templating system also supports the ` ${}`  syntax.

If we use these column definitions:

``` 
      <k-col title="Contact Name" field="ContactName">
        <div class='customer-photo' style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
        <div class='customer-name'>${ContactName}</div>
      </k-col>
      <k-col title="Contact Name" field="ContactName" with-kendo-templates.bind="true">
        <div class='customer-photo' style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
        <div class='customer-name'>${ContactName}</div>
      </k-col>
``` 
note: the first has kendo templates disabled, the second one has them enabled. Meaning that the first template is not parsed by Kendo's templating system, and the second one is.

This results in the following HTML being added to the DOM:

``` 
<tr data-uid="966f7e1d-2589-4b61-8161-d1bf6c43c77e" role='row'>
            <td role='gridcell'>
                <div class="customer-photo" style=
                "background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);">
                </div>
                <div class="customer-name">
                    ${ContactName}
                </div>
            </td>
            <td role='gridcell'>
                <div class="customer-photo" style=
                "background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/ALFKI.jpg);">
                </div>
                <div class="customer-name">
                    Maria Anders
                </div>
            </td>
        </tr>
        <tr class="k-alt" data-uid="b7a85fbc-8c67-41e8-8890-03dced396468" role=
        'row'>
            <td role='gridcell'>
                <div class="customer-photo" style=
                "background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);">
                </div>
                <div class="customer-name">
                    ${ContactName}
                </div>
            </td>
            <td role='gridcell'>
                <div class="customer-photo" style=
                "background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/ANATR.jpg);">
                </div>
                <div class="customer-name">
                    Ana Trujillo
                </div>
            </td>
        </tr>
``` 

Note that the first `<td>` of every table row contains `style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"`  and the second one contains `style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/BERGS.jpg);"`. Aurelia's enhance feature is "triggered"  too late, causing the browser to load the image `http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg` , which doesn't exist.

**Comment by JeroenVinke** [comment]
this is in the 0.2.0 branch
