### ISSUE TITLE
Use named modules to import Kendo

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#272]
Due to the latest Kendo update, users of the plugin need to add a couple of path mappings:

```
    paths: {
      "*": "dist/*",
      "github:*": "jspm_packages/github/*",
      "npm:*": "jspm_packages/npm/*",
      "kendo.*": "vendors/js/kendo.*.js"        <----
    },
    "map": {
      "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1",
      "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.2",
      "jquery": "npm:jquery@2.2.0",             <----
      "kendo-ui": "/vendors",                   <----
      "jquery.min": "npm:jquery@2.2.0"          <----
    }
```

Perhaps we can let the wrappers import via named modules: `import 'kendo.grid'`, so we don't need the `kendo-ui` mapping anymore.

And we could perhaps remove the `jquery` dependency, as Kendo deploys their own `jquery.min` file which the Kendo controls depend on.

**Comment by adriatic** [comment]
Like I said yesterday (without being noted) - will this change disqualify the KendoUI users that have their bits older than the current KendoUI release?

**Comment by JeroenVinke** [comment]
> Like I said yesterday (without being noted) - will this change disqualify the KendoUI users that have their bits older than the current KendoUI release?

Hmm right, you could have an old license

**Comment by JeroenVinke** [comment]
we can't rely on the named mappings alone, as we still need a map for the [css files](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-vendors/blob/master/src/app.html#L4)

**Comment by JeroenVinke** [comment]
without the `"jquery.min": "npm:jquery@2.2.0"` we get a 404 for jquery, so that one is necessary too. Tried to add this map as a dependency to the package.json, and it was in the config.js of the consuming app, but wasn't working as I still got a 404 for jquery. I think the devDependencies feature of jspm (which has not been released yet as far as I know) may make this work

**Comment by JeroenVinke** [comment]
closed as it doesn't help much right now
