### ISSUE TITLE
ReadMe: change button "Live Demo" to something like "Component Catalog"

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-kendoui-bridge#275]
People looking on GitHub for things they can use often see the ReadMe file as a starting point of information.

Now that the first alpha release is out, maybe it would be better to rename the "Live Demo" button to "Component Catalog" (or something similar) and tell visitors that the information they need is there.

**Comment by adriatic** [comment]
I agree with this - it's good to use the consistent language. Component is an established word in Aurelia's world - catalog comes in naturally. Please do that for Materialize right away and I believe that it is not too late to do the same for KendoUI

**Comment by Thanood** [comment]
I guess I'll better do a button and text for a demo app when there's a demo-app. :smile:

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/00dd29786b8036d8368a08e3fe633dc9dbc759ee
