### ISSUE TITLE
Keeping the KendoUI Bridge tutorials in sync with the KendoUI bridge

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#280]
There are two tutorials in the Bridge online help pages:

1. [App developers tutorials](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_tutorials/1._introduction)
2. [Bridge developers tutorials](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/bridge_developers_tutorials/1._introduction)

Finished versions of these tutorials are in

1. https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo
2. https://github.com/aurelia-ui-toolkits/skeleton-plugin-kendo

Note that the names of these repositories are chosen to indicate how each of these tutorials is an extension of the Aurelia original [skeleton-navigation](https://github.com/aurelia/skeleton-navigation) and [skeleton plugin](https://github.com/aurelia/skeleton-plugin) samples, augmented by adding four controls (`autcomplete`, `button`, `chart` and `grid`) from KendoUI Bridge.

This text should likely be a part of the Bridge's README file and / or the document that defines Bridge building and release.

**Comment by adriatic** [comment]
I just ensure that these are in sync with the current Bridge code

**Comment by JeroenVinke** [comment]
no use of keeping this open so i'm closing this
