### ISSUE TITLE
Create a plan to move KendoUI from alpha to beta

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#284]

**Comment by adriatic** [comment]
Assuming that the [currently defined selection of KendoUI controls](http://aurelia-ui-toolkits.github.io/demo-kendo/#/project-status) we want to aureliaize is complete, we  still have 32 controls to do. 

Then given Rob's most recent assessment:
![image](https://cloud.githubusercontent.com/assets/2712405/12661547/3919dfec-c5e8-11e5-8858-29b74471186e.png)

combined with our common vision `we are doing it to help aurelia become what we all expect it to be` (apology if it sounds too corny), we should re-verify our current plan and revise it if necessary to get to the Beta quickly maintaining the quality level. 

Folks with most experience in writing wrappers (I am on the bottom of the totem pole) should pick some of the most impressive remaining controls (Spreadsheet, Diagram, Calendar, Scheduler, Gantt) and get them going.

Please state your preferences

**Comment by adriatic** [comment]
There is a different approach possible as the alternative to "each grab a KendoUI control and turn it into the matching Aurelia component". We could create a serial "production line" which starts with the definition of all bindables for a given KendoUI control and ends with implementation of a catalog page for the resulting Aurelia component -- and then "loop" over all remaining KendoUI controls.

This approach takes in account the "specific knowledge" of team members and might easily result with better productivity and higher quality.

**Comment by JeroenVinke** [comment]
Instead of doing a big-bang update with all the wrappers, I favor a more incremental approach. I propose we [finish the 0.2.0 milestone](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/milestones/0.2.0) and then work from there. Features (such as #269, #268, #263) are just as important as new wrappers IMO and we should release those rather sooner than later.

**Comment by Thanood** [comment]
I guess as a non-kendo person I can't do very much here.
But what about the catalog app itself? 

For instance the [project-status](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/src/project-status/controls.html) - which, as @adriatic mentioned, could be used as an overview in the future.

I changed it into a repeated list of cards, getting its contents from a [js object](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/src/project-status/controls.js#L2) - which may also be enhanced in the future if it makes sense.

**Comment by adriatic** [comment]
@JeroenVinke writes:
> I propose we [finish the 0.2.0 milestone](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/milestones/0.2.0) and then work from there

Starting this issue [Create a plan to move KendoUI from alpha to beta] was a bad idea as I was not aware of 0.2.0 milestone being defined (shame on me :-)). 

Since @JeroenVinke has the best understanding of the KendoUI bridge status, let's just follow his lead

**Comment by adriatic** [comment]
@Thanood writes
> For instance the [project-status](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/src/project-status/controls.html) - which, as @adriatic mentioned, could be used as an overview in the future.

I propose to put more focus on "wrapping" than presenting the wrapped things - it seems that we did more than good enough job packaging KendoUI bridge in a nice dress (based on some comments to Rob's blog on Aurelia KendoUI)

**Comment by JeroenVinke** [comment]
Just to explain, we now have 2 branches: `master` and `0.2.0`. The master branch contains the code for the 0.1.2 version. We're developing everything of the [0.2.0](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/milestones/0.2.0) milestone in the `0.2.0` branch.

That way, when we need to quickly create a patch for the "0.1.x" version, we can just create that from master. When the milestone is finished, we merge the `0.2.0` branch into the `master` branch.

**Comment by adriatic** [comment]
Thank you for the explanation. Good plan.
