### ISSUE TITLE
PanelBar contentUrl property missing from options object

### ISSUE THREAD

**Issue by charlespockert** [aurelia-ui-toolkits/aurelia-kendoui-bridge#285]
Will PR the Kendo core repo to add this.

**Comment by charlespockert** [comment]
For reference: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/src/common/decorators.js#L11

**Comment by JeroenVinke** [comment]
fixed with extraction of options out of the typescript definitions.  You can close the pr with Telerik I think
