### ISSUE TITLE
Quirk in catalog app Progress Bar

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-kendoui-bridge#292]
The button in "Progress Bar / Custom label" sample says "Rest password" but it doesn't. It alerts the user with the strength of the password.

I suggest either rename it to "Check password" or let it reset the form.

**Comment by charlespockert** [comment]
@Thanood this is actually how the Kendo demo is (the code is lifted directly from the site). http://demos.telerik.com/kendo-ui/progressbar/customlabel

I think the "Reset Password" text is simply an example of what the button might say in a real world app rather that a description of the buttons function.

**Comment by JeroenVinke** [comment]
what @charlespockert said, this is actually a copy of the sample Telerik made (which we're trying to stick to, but with a touch of Aurelia magic ;) )
