### ISSUE TITLE
Scheduler e.preventDefault() not working

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#294]
In [this sample](http://demos.telerik.com/kendo-ui/scheduler/restriction), `e.preventDefault` is used to revert a change when a restriction is in place:

```
        moveEnd: function(e) {
            if (!checkAvailability(e.start, e.end, e.event, e.resources)) {
                e.preventDefault();
            }
        },
```

However, this doesn't do anything when our wrapper is used: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/scheduler-wrapper/sample/src/samples/scheduler/restrictions.js#L26-L30

Not sure why yet. I have a feeling that this has to do with the DOM event and the Kendo control continuing the execution before we call `e.preventDefault()`

**Comment by adriatic** [comment]
Several comments:

- nice to see such early warning about something that might hit others (this has to do with my [issue on sharing stuff](https://github.com/aurelia-ui-toolkits/issues/issues/7) with everyone on the team.

- you could as well be right with your suspicion, since it finally uses `setTimeout` function and the wrapper "does not correctly handle this async behavior"). The 
```
    if (this.roomIsOccupied(start, end, event, resources)) {
      setTimeout(function() {
        alert('This room is not available in this time period.');
      }, 0);

      return false;
    }

    return true;
  }
``` 
function should have the same problem

**Comment by JeroenVinke** [comment]
So this is because we raise the event via the microtask queue: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/src/common/widget-base.js#L198-L202 which is basically "async"

The code of the Scheduler that raises the `moveEnd` event looks like this:

![image](https://cloud.githubusercontent.com/assets/2189477/12694697/b2e57bac-c736-11e5-80a4-ed080735b415.png)

With the taskqueue enabled it jumps right to that `if(!prevented` line without executing the [`moveEnd` handler](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/scheduler-wrapper/sample/src/samples/scheduler/restrictions.js#L26-L30) first. When I raise the even without the taskqueue the handler is executed first (we call preventDefault()) and then the `if(!prevented` is evaluated.

To illustrate why we use the taskqueue here I use a slider control which has a `value` property and raises a `change` event whenever this value changes.

`<input k-slider="k-value.two-way: theValue" k-on-change.delegate="valueChanged()"/>`

If we don't delay the `change` event, the change event will be triggered (and `valueChanged()`) will be called before the `theValue` binding is updated. So that means that in the `valueChanged` event, `theValue` is old

**Comment by JeroenVinke** [comment]
I propose a simple solution: some events needs to be delayed until bindings have updated, and some need to be called immediately.

```
if(event === "change") {
 options[event] = e => fireKendoEvent(element, _hyphenate(event), e);
} else {
      options[event] = e => {
        this.taskQueue.queueMicroTask(() => {
          fireKendoEvent(element, _hyphenate(event), e);
        });
      };
}
```

**Comment by adriatic** [comment]
Thank you for sharing this - quite cool approach

**Comment by JeroenVinke** [comment]
this is in the 0.3.0 branch

**Comment by arnederuwe** [comment]
I think the "change" check didn't cover all scenario's. I'm having a very similar issue with the kendo dropdownlist's filtering event. See this gist: https://gist.run/?id=9f6eec20cb434541d4119b11a4b629e2
As you can see, when I wire up the event the kendo way, the search doesn't do anything, which is desired. When I use the event wrapper, the search works, which shouldn't.
