### ISSUE TITLE
Improve the generation of bindable properties

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#296]
Currently we are using the options object defined within every Kendo control to generate `@bindable` properties:

![image](https://cloud.githubusercontent.com/assets/2189477/12695063/138f9112-c742-11e5-8883-e5c2aaab28df.png)

The `options` object is incomplete, forcing us to add `@bindable` properties in addition to the auto-generated properties: [A](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/scheduler-wrapper/src/scheduler/scheduler.js#L21-L23), [B](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/0.2.0/src/common/decorators.js#L20), [C]( https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/285).

We have a couple of options:
1. Create a pull request to Kendo core for every missing property in the `options` object. This process is slow as Kendo needs to merge the PR, and then go through the entire release process. Then our users have to update Kendo before the property becomes available.
2. Generate bindables from `options` object but also keep a manual list of properties next to it.
3. We could extract the propertynames from [the typescript definitions of Kendo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/kendo-ui/kendo-ui.d.ts)
4. options 2 & 3 and merge those propertynames to get an even more complete list of properties

In addition, as mentioned [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/177#issuecomment-166724280), instead of passing a complete options object with default values, we should only add properties which are not undefined to that object.

For example, we now do this:
```
$(this.target).kendoButton({
            name: "Button",
            icon: "",
            spriteCssClass: "",
            imageUrl: "",
            enable: true
});
```

While we should do this:
```
<button k-button="k-enable.bind: true"></button>
$(this.target).kendoButton({
            enable: true
});
```

This limits the amount of issues we have where default values are wrong. We also won't need to set the default values of bindable properties anymore

**Comment by JeroenVinke** [comment]
@charlespockert @adriatic thoughts?

**Comment by JeroenVinke** [comment]
we would extract them from [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/kendo-ui/kendo-ui.d.ts#L5200-L5212)

**Comment by charlespockert** [comment]
Sounds good, yes I don't think Telerik have even looked at my PR yet, the
more complete the options can be from the files we have available the
better.

Were you thinking of adding a build task to extract from the ts and keep
the lists up to date? Should just be able to gen a json in each components
directory which can be loaded when the component is configured/initialised

@charlespockert <https://github.com/charlespockert> @adriatic
<https://github.com/adriatic> thoughts?

—
Reply to this email directly or view it on GitHub
<https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/296#issuecomment-177138355>
.

**Comment by JeroenVinke** [comment]
> Were you thinking of adding a build task to extract from the ts and keep
the lists up to date? Should just be able to gen a json in each components
directory which can be loaded when the component is configured/initialised

this is exactly what I thought. Perhaps we can use gulp to download the latest DefinitelyTyped typescript definition.

**Comment by adriatic** [comment]
wonderful concept

**Comment by JeroenVinke** [comment]
We can use [this task](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/build/tasks/doc.js#L7-L19) to turn the Kendo typescript definition file into a JS object with [this format](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/doc/api.json)

then we can do some iteration over it and extract the props we need

**Comment by adriatic** [comment]
Becoming gulp task-meister, huh?

How reliable is the assumption that Kendo typescript definition **always** matches the content of all js files?

**Comment by JeroenVinke** [comment]
It is probably not 100% accurate, but remember: no option we have is. By combining the properties out of the typescript file with the Kendo options object and the ability to manually register properties, the chance of missing something is small.
