### ISSUE TITLE
Replace the old Aurelia logo with the current one

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#297]
This is the new Aurelia KendoUI Bridge logo - created by Rob
![image](https://cloud.githubusercontent.com/assets/2712405/12696713/a9a295b2-c73f-11e5-8129-d37f40c64f3e.png)

Being warned about the urgency of having that up ASAP, I will handle the "mobile first" aspects of this at a later time (by decomposing this image into three chunks that behave better when resizing the browser)

**Comment by JeroenVinke** [comment]
this is done
