### ISSUE TITLE
Distinguish between Kendo pro/core in the sample application

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#304]
Perhaps add a label somewhere in each sample that says PRO or CORE

**Comment by charlespockert** [comment]
Fixed in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/55af38074607a7898c475502aa7f7730a332bf33

**Comment by JeroenVinke** [comment]
Smart implementation :)
