### ISSUE TITLE
TreeList anomalies when sorting

### ISSUE THREAD

**Issue by charlespockert** [aurelia-ui-toolkits/aurelia-kendoui-bridge#308]
![image](https://cloud.githubusercontent.com/assets/9073518/12699278/939a6a10-c7ad-11e5-9ac2-33ca9f875cb2.png)

Only happens on columns with a custom Aurelia template:
```
  <k-tree-col field="FirstName" title="First Name" width.bind="280">
        <div class="employee-photo" style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/treelist/people/${EmployeeID}.jpg);"></div>
        <div class="employee-name">${FirstName}</div>
      </k-tree-col>
```
Using a remote datasource and sorting data from TreeList causes the above issue - looks like the original template is not being re-interpolated

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/12704062/aa829a04-c852-11e5-8ab6-fcd92b27ba6e.png)


it looks like the treeview is reusing divs, and I think the cleanup process isn't complete. I compared it with the Grid and the difference is visible [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/src/common/template-compiler.js#L114), where `$(element).data('viewInstance')` is undefined when sorting the grid, but returns a View instance when sorting the treelist

**Comment by JeroenVinke** [comment]
Yeah.. the template-compiler is asked to compile a div that has been previously compiled, so instead of compiling this:

```
"<td role="gridcell" style="white-space: nowrap;"><span class="k-icon k-i-collapse"></span>
        <div class="employee-photo" style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/treelist/people/${EmployeeID}.jpg);"></div>
        <div class="employee-name">${FirstName}</div>
      </td><td role="gridcell">Sweeney</td><td role="gridcell">CEO</td><td role="gridcell">(555) 924-9726</td><td role="gridcell">8253</td><td role="gridcell">P.O. Box 427, 5676 Arcu. Rd.</td>"
```

it wants to compile something that has been compiled before:

```
**<td role="gridcell" style="white-space: nowrap;"><span class="k-icon k-i-collapse"></span>
        <div class="employee-photo au-target" au-target-id="456" style="background-image: url(&quot;http://demos.telerik.com/kendo-ui/content/web/treelist/people/1.jpg&quot;);"></div>
        <div class="employee-name">Daryl</div>
      </td><td role="gridcell">Sweeney</td><td role="gridcell">CEO</td><td role="gridcell">(555) 924-9726</td><td role="gridcell">8253</td><td role="gridcell">P.O. Box 427, 5676 Arcu. Rd.</td>"
```

Note that the interpolation expressions are not there anymore, so Aurelia flips out

**Comment by adriatic** [comment]
Do you think that Aurelia is not smart enough to recognize what is it fed with?

**Comment by JeroenVinke** [comment]
I don't have much time to explain right now, but I believe the cleanup process is not doing enough, so when enhance is run for the second time on the same div, it throws an error. 

When you enhance an element, aurelia adds `au-target-id` attributes and `au-target` css clases to elements within. I guess this has to do with the binding engine needing some kind of reference point.

[Here it looks for the au-target-id attribute](https://github.com/aurelia/templating/blob/master/src/view-factory.js#L416-L421)

```
    for (i = 0, ii = instructables.length; i < ii; ++i) {
      instructable = instructables[i];
      instruction = instructions[instructable.getAttribute('au-target-id')];

      applyInstructions(containers, instructable, instruction, controllers, bindings, children, contentSelectors, partReplacements, resources);
    }
```

[here](https://github.com/aurelia/templating/blob/master/src/view-factory.js#L395) it looks for the au-target css class.

What I noticed is that the `au-target-id` atributes and `au-target` css classes were still on the element from the previous `enhance` call.

So I added a line to remove these in the `cleanupView` of our template-compiler:
```
  cleanupView(element) {
    // extract Aurelia's View instance from the element
    // we stored this in the enhanceView function
    let view = $(element).data('viewInstance');
    if (!view) return;

    $('.au-target', element).removeClass('au-target');

    // unbind and detach the view
    view.detached();
    view.unbind();
  }
```

This seems to be enough to get it working again. I'm not done looking into this by the way, but it is a start

**Comment by JeroenVinke** [comment]
This is what happened

1. template is enhanced (and bound and attached)
2. with every collapse/sort they are "cleaned up" by unbinding and detaching
3. after sorting again/expanding, we shouldn't enhance but simply bind and attach again

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/e40fc66cec1c98f03ff988a91a2dcd467149de75 seems to fix it
