### ISSUE TITLE
sidecar swallows errors

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#309]
Like @Thanood suggested, sidecar is the cause of some errors being swalled in the sample app.

**Comment by adriatic** [comment]
How is this conclusion verified?

**Comment by JeroenVinke** [comment]
I forgot to declare a variable in our generateBindables decorator, and I didn't get an error. After disabling sidecar the error became visible, and after enabling sidecar the error disappeared again.

**Comment by adriatic** [comment]
This means a bug in `browser-sync` or higher up from there - as having an app running in iframe should not cause such effects.

**Conclusion**: get rid of side-car - the sooner, the better. Otherwise we could have a nightmare tracing down bugs reported by bridge users.

**Comment by JeroenVinke** [comment]
Actually, this bug is only swallowing errors in our sample app, the plugin users should be fine. I only created this issue so that it can be investigated further, so I still have hope

**Comment by adriatic** [comment]
> Actually, this bug is only swallowing errors in our sample app

I believe that you knew that I know that, right :-)

**Comment by Thanood** [comment]
Just thinking..

These are all unresolved promise rejections, right? Bluebird has a feature which can catch these globally ([at least they say so](http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events)). I'm not sure but sidecar may use bluebird. Their master branch has bluebird commented but what if the dist version still has it?

There certainly is a part of sidecar which doesn't run in an iframe. That is at least the part which creates that iframe and attaches it onto a container element. Now if that part happens to catch promise rejections...

**Comment by JeroenVinke** [comment]
Hmm, in the Gitter sidecar source code I see they use `es6-promise`.

which has an issue with not throwing unhandled exceptions

https://github.com/jakearchibald/es6-promise/issues/70

**Comment by Thanood** [comment]
You're right.. I had too many "if"s in my thoughts anyway. Bluebird being commented doesn't necessarily mean anything.

There are a lot of "swallowing" issues mentioned in the issue you linked.

**Comment by JeroenVinke** [comment]
removed gitter sidecar in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/9f8097605c23c9d791e5f486e134e1fb6cc85ca4
