### ISSUE TITLE
support for kendoRangeSlider

### ISSUE THREAD

**Issue by flieks** [aurelia-ui-toolkits/aurelia-kendoui-bridge#311]
Hi, 

Thanks for great library.

Can you add rangeSlider to the controls list?
it seems to be almost same as the slider except the value property is an array [] of value1 and value2.
```
  $("#rangeslider2").kendoRangeSlider({
            change: ((e) => {
                this.yearStart= e.value[0];
                this.yearEnd = e.value[1];
            }),
            min: 1,
            max: 10,
            smallStep: 1,
            largeStep: 2,
            tickPlacement: "none"
        });
```

Thanks
Felix

**Comment by JeroenVinke** [comment]
Sure :+1: 

The only demo I can find on the kendoRangeSlider is [here](http://demos.telerik.com/kendo-ui/slider/api) 

![image](https://cloud.githubusercontent.com/assets/2189477/12703791/bde6e3b8-c84b-11e5-8b0c-7acdc0b34094.png)

**Comment by JeroenVinke** [comment]
It will be in 0.2.0 which will be released after we close all the issues in [this milestone](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/milestones/0.2.0)
