### ISSUE TITLE
create a complete Aurelia app using the bridge

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#314]
Here is what I would like to do

![image](https://cloud.githubusercontent.com/assets/2712405/12735306/bf077996-c914-11e5-9678-9124b32b49d1.png)

(screen shot taken from http://www.telerik.com/kendo-ui/sample-applications)

I do not care to see any source for that app of course (besides, Telerik does not provide it since it is likely a hack to make it look beautiful.)

Dependent on the success of this attempt I would also like to do it's mobile version

![image](https://cloud.githubusercontent.com/assets/2712405/12735366/4ef551cc-c915-11e5-923c-ddc048d194eb.png)

Note the lists of all KendoUI controls I would need aureliaized so, @JeroenVinke please schedule them as a part of our next release if possible.

I would like to have both these apps  deployed at [heroku](https://www.heroku.com/home) with the database at [mongolab](https://mongolab.com/)

**Note** [KendoUI Mobile](http://www.kendouimobileguide.com/) is a part of Kendo-core

**Comment by JeroenVinke** [comment]
Good idea :+1: I don't want to delay this release but I will add those for 0.3.0.  Abd if we don't make 0.3.0 too big then you won't have to wait for too long
