### ISSUE TITLE
updating all places when adding a new component

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#322]
There are several sub-issues that I folded into this one:

1. Whenever updating `sample/src/samples/index.js` file please maintain the alphabetical sort I twice put in place. It's a bitch to find if something is missing in a table of 37 rows otherwise. The case in point: I saw that the menu component, flagged yellow on project status page, cannot be accessed from there. It was not defined in `sample/src/samples/index.js` file.

2. There were two instances of treelist defined in  `sample/src/samples/index.js` - additional reason to do 1. above

3. We need to create a cheat-sheet that defined all places that need to be updated when a control is added to the bridge. Once I added the menu entry in `sample/src/samples/index.js`, it took me a while to realize that in addition, I need to define it in the `sample/src/samples/menu.json` file as well

**Comment by JeroenVinke** [comment]
1 & 2: agreed

3: 

- config-builder.js
- sample/src/samples/index.js
- sample/src/samples/menu.json
- sample/src/samples/<controlname>/registry.json
- sample/src/samples/<controlname>/index.js
- src/<controlname>/<controlname>js
