### ISSUE TITLE
value converters for kendo functions

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#324]
`#:kendo.toString(UnitPrice, "c")#` can be wrapped in a value converter:

`${UnitPrice | kendoToString:'c'}`

**Comment by adriatic** [comment]
so much more elegant - and we should all care about elegant :-)

**Comment by charlespockert** [comment]
@JeroenVinke yeah this looks cool - definitely a must have feature since kendo does provide some nice date/numeric utils without the user needing moment/numeral

**Comment by JeroenVinke** [comment]
this is now in 0.3.0

**Comment by adriatic** [comment]
I believe that this information should be packaged in the form of an article and add it to the new category (which needs to be added) **app developer notes**
