### ISSUE TITLE
normalize template custom elements

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#325]
Idea of @charlespockert was to reuse some template custom elements.

For example, the listview has a customizable template:

```
    <k-list-view k-data-source.bind="dataSource">
      <k-list-template>
        ${var}
      </k-list-template>
   </k-list-view>
```

The scheduler has one too:

```
    <k-scheduler>
      <k-event-template>
        ${var}
      </k-event-template>
   </k-scheduler>
```

The code of `k-event-template` and `k-list-template` is almost identical. For consistency and code reusability we should look into using a common custom element.

**Comment by adriatic** [comment]
That is a very natural idea, yes. 

This is also a good time to warn against too much optimization in the KendoUI bridge - at least until we have a few more bridges done (this comment has no bearing on "reuse some template custom elements" concept

**Comment by charlespockert** [comment]
@adriatic I'd say sooner is better though as this affects the API

@JeroenVinke I'm wondering if we can do something where we use a single custom element but maybe use dynamic properties (not sure what's possible as I've not looked at them yet). This way you'd always use `k-template` for example and it would be a single convention to follow throughout.

On quick glance it looks like all templates have the same pattern (grab the HTML content in the `@processContent` decorator) so they all share the same basic functionality.

If we took this approach, in the case that we find we need special functionality for a certain template type, we could just use composition again - we could add an edge case and make the `k-template` element aware of the parent element type and then handle accordingly

**Comment by JeroenVinke** [comment]
I believe there are two types: 

1. `<k-list-template>`, `<k-event-template>`
2. `<k-col>`, `k-tree-col`

The first category is simple: the innerHTML needs to be translated to the `template` property. Sometimes this is `editTemplate` instead of `template` though. The second category is more advanced, they contain bindable properties (which differ per widget)

What we can do for the first category is something like this:`<k-template for="editTemplate"></k-template>`

The second category could be via composition, yep. and we could create our own `@processContent` decorator

**Comment by adriatic** [comment]
out of my depth to contribute meaningfully - and even if I try I am not really needed here :-)

**Comment by charlespockert** [comment]
@JeroenVinke Yeah sounds good - I think this might also add some missing functionality to grid and related controls.

When there are multiple templates (group footer, header etc) I don't think you can specify that in the markup at the moment (unless you've done some more work on it) - it just sets the `template` property on `k-col`

If we kept `k-col` but added this generic template element, we could get the following working:

```
<k-grid>
  <k-col>
    This is the `template` property
    <k-template for='groupHeader'>Hello world</k-template>
    <k-template for='groupFooter'>Hello world</k-template>
  </k-col>
</k-grid>
```

What you think?

**Comment by charlespockert** [comment]
I'd say we'd have to keep `k-col` but we could merge it with `k-tree-col` maybe?

**Comment by JeroenVinke** [comment]
Very nice

**Comment by JeroenVinke** [comment]
Yep we can merge those imo

**Comment by charlespockert** [comment]
@JeroenVinke I'm sure you'll have implemented it before I even leave the office :)

**Comment by JeroenVinke** [comment]
No,  if you want it's all yours

**Comment by charlespockert** [comment]
@JeroenVinke time permitting I'll have a look tonight!

**Comment by charlespockert** [comment]
@JeroenVinke @adriatic have a look at: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/bd6ba4384efd06e89d2bea99aabe9c75d302755a

This allows you to do this:

```
<k-grid k-data-source.bind="datasource" k-pageable.bind="pageable" k-sortable.bind="true">
  <k-col title="Contact Name" field="ContactName">

    <!-- you must wrap with k-template at the moment but I'd like to remove this requirement for the default template -->
    <k-template>
      <div class='customer-photo' style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
      <div class='customer-name'>${ContactName}</div>
    </k-template>

    <!-- here's the new bit... -->
    <k-template for="headerTemplate">Test</k-template>
  </k-col>
</k-grid>
```

Which results in the header having "Test" in it and the columns having their usual "face picture" template:

![image](https://cloud.githubusercontent.com/assets/9073518/12863451/0b7c7590-cc6e-11e5-9e02-022912a891ac.png)

You can add this functionality to any control, it's supported by a decorator:

```
  @templateProperty()
  @bindable groupFooterTemplate;
  @templateProperty()
  @bindable groupHeaderTemplate;
  @bindable headerAttributes;
  @templateProperty()
  @bindable headerTemplate;
```

And the following 1 liner in attached (or bind as is needed in k-col due to the order of events):

```
  bind() {
    useTemplates(this, this.templateChildren);
  }
```

**Comment by charlespockert** [comment]
I'd like to make it so that that the inner HTML of the custom element is used as the template in the case that there are no `k-template` elements specified. 

Might be a little tricky as I will have to avoid any `k-template` elements when looking at the HTML. 

Maybe we force the user to wrap their actual templates in a `k-template`? I'd rather not but it makes this less technically fiddly

**Comment by JeroenVinke** [comment]
I believe it's better to have the column template in a k-template, tbh the footer template looks out of place otherwise.  It would be a breaking change, but we are not in beta yet and these things are needed to improve

**Comment by JeroenVinke** [comment]
I'd also like to use k-template for the dropdownlist, so please let me know when that's finished
