### ISSUE TITLE
ListView edit template not compiled

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#326]
Kendo's ListView control isn't calling angular to compile the template, so Aurelia's templating system can't be used in the editingTemplate: http://demos.telerik.com/kendo-ui/listview/editing

**Comment by JeroenVinke** [comment]
Nothing we can do about this unfortunately. This feature has to be requested at Telerik

**Comment by adriatic** [comment]
That is too bad :-(

This control was high on my list of desired ones

**Comment by JeroenVinke** [comment]
It is just the edit template that's not compiled, the rest of the control works fine
