### ISSUE TITLE
several kendo controls missing in original list of issues

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#332]
I remember creating a ton of issues at the beginning of his project (one issue per control to be aureliaized) and have not created a complete list at that time. here are the still missing controls:

- [button group](http://demos.telerik.com/kendo-ui/buttongroup/index)
- [qrcode](http://demos.telerik.com/kendo-ui/qrcode/index)
- [styling](http://demos.telerik.com/kendo-ui/styling/index)

**Comment by JeroenVinke** [comment]
Some of these have issues already, such as editor, gantt, spreadsheet

**Comment by adriatic** [comment]
**[This](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/332#issue-131986647)** is the updated list - quite a shrinkage !

**Comment by JeroenVinke** [comment]
issues created
