### ISSUE TITLE
maintaining the bridge infrastructure 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#333]
KendoUI bridge infrastructure (defined as all of the code created to simplify writing the control wrappers) is a lot more advanced than the similar code that exists in `skeleton bridge` and ongoing `materialize bridge`.

I suggest two actions to enable everyone to benefit from this development

1. Document this infrastructure (probably [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/wiki], with the follow-up action to add that same data to the catalog app)
2. Ensure that the `skeleton bridge` is upgraded appropriately.

**Comment by JeroenVinke** [comment]
can you be more specific? what is more advanced in this bridge that's not in the skeleton bridge?

**Comment by adriatic** [comment]
I will add this information in the process of creating the next wrapper. Everything related to autogeneration of bindables, resolving clashes between kendo and aurelia templating may or may not be just Kendo specific as similar problems and solutions could be encountered in some other bridge.

**Comment by JeroenVinke** [comment]
1. has been explained https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/help/docs/bridge-developers-notes/harvesting-bindable-variables.md

> It seems that we need to have a document describing a typical custom attribute wrapper and custom element wrapper (they are all nearly identical now - a great proof of excellent job of refactoring as the bridge gets more and more advanced

That can be included in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/338

**Comment by adriatic** [comment]
"harvesting" has very strong "smell" to "harvesting human organs" that I would really  like to replace this verb
