### ISSUE TITLE
restore the KendoUI bridge wiki site

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#334]
All of the content was moved **[here](https://github.com/aurelia-ui-toolkits/screenshots/wiki)** - in order to ensure the "clean environment" for writing and proofreading the **[Aurelia and KendoUI](http://blog.durandal.io/2016/01/28/aurelia-and-kendo-ui/)** article.

All the moved articles need to be checked and those that are worthy of maintaining need to be update and returned **[back](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/wiki)**

**Comment by JeroenVinke** [comment]
The articles in https://github.com/aurelia-ui-toolkits/screenshots/wiki/ are either already in the documentation (as developer notes/app developer notes) or are no longer necessary (such as the component checklist). I'm not going to remove the articles from https://github.com/aurelia-ui-toolkits/screenshots/wiki/ though, so we can always find it again if necessary

**Comment by adriatic** [comment]
> The articles in https://github.com/aurelia-ui-toolkits/screenshots/wiki/ are either already in the documentation (as developer notes/app developer notes) or are no longer necessary (such as the component checklist).

This is not a completely accurate statement - as the KendoUI catalog app hides the bridge developer notes. So, I will merge some of the articles from the ["old KendoUI wiki"](https://github.com/aurelia-ui-toolkits/screenshots/wiki/) to [Syncfusion wiki](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/wiki) and add the properly modified [KendoUI bridge developer notes](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/tree/master/sample/src/help/docs/bridge-developers-notes) to Syncfusion catalog app.

**Comment by JeroenVinke** [comment]
based on the articles on the [wiki](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/wiki) this seems finished
