### ISSUE TITLE
controls that need to be discussed with Telerik

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#335]
1. [ListView edit template not compiled](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/326#issue-131280927)

**Comment by JeroenVinke** [comment]
There are more of these controls that don't have full templating support (the [calendar](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/calendar/templates) or [datetimepicker](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/datetimepicker/customizing-templates)). These templates are not used much so they probably didn't want to dedicate too much time to it. These are all features that should be requested via telerik's uservoice
