### ISSUE TITLE
npm aurelia-kendoui-bridge: several details to polish

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#336]
The **[Getting Started with aurelia-kendoui-bridge](https://www.npmjs.com/package/aurelia-kendoui-bridge/tutorial)** page does not say anything about the bridge - it only describes the process of NodeJS installation.

The **[Try it out link ](https://tonicdev.com/npm/aurelia-kendoui-bridge)** makes no sense :-)

Both of the problems could be caused by some automatic process that runs once the bridge is registered to **[npm](npmjs.com)** -- even then we need to resolve them

**Comment by JeroenVinke** [comment]
NPM doesn't allow you to customize those pages so we can't do something about this unfortunately
