### ISSUE TITLE
Rewrite the control implementation walk-through article

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#338]
The current original is **[here](https://github.com/aurelia-ui-toolkits/screenshots/wiki/Control-Implementation-Walkthrough)** - and it is not even close to what it has to be (this is the compliment to the advancement of the bridge infrastructure (see the related issue https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/333)

I will use the experience in creating the **[KendoUI Editor](http://demos.telerik.com/kendo-ui/editor/index)** wrapper to rewrite this article - and it will be added to the `Bridge developers notes` Help category.

**Comment by JeroenVinke** [comment]
Also include:

> It seems that we need to have a document describing a typical custom attribute wrapper and custom element wrapper (they are all nearly identical now - a great proof of excellent job of refactoring as the bridge gets more and more advanced

**Comment by adriatic** [comment]
Why re-open? This article now exists in bridge developer's notes

**Comment by JeroenVinke** [comment]
ah, you are right
