### ISSUE TITLE
Kendo-ui-web old gpl version 2014.1.318 could kendoui bridge work? 

### ISSUE THREAD

**Issue by delebash** [aurelia-ui-toolkits/aurelia-kendoui-bridge#341]
Not sure were else to post this but I just wanted to let people know that the old gpl3 version is available it has the grid,schedular,treeview.  So if you don't mind using a a two year old framework that will not see any other updates, then this gives you the major components missing in the kendo-core.  I use this for non-profits, the kendo-core was a bummer for me since they dropped the grid and treeview.  I am not that familiar with kendoui-bridge, but its seems to be just a wrapper around the properties of each component so I would not think it wouldn't take to much to modify it for the old properties which I imagine are largely the same.

If you have a telerik account and previously downloaded the gpl version then you can download directly else it is still available via

bower install kendo-ui-web
nuget: https://www.nuget.org/packages/KendoUIWeb

This is not meant say you shouldn't support Telerik They are a great company and I have used there commercial products for years, way back when they were one of the first companies  out with controls for asp.net

**Comment by JeroenVinke** [comment]
Thanks for brining this up @delebash 

Can we see the source code of this anywhere?

**Comment by Thanood** [comment]
I've found something here: https://github.com/AbhishekGhosh/Kendo-Web-UI
Bower pulls it from here: https://github.com/StefH/bower-kendo-ui-web (only minified sources)

**Comment by JeroenVinke** [comment]
@Thanood 

Thanks, I just looked into it and found two differences.

Firstly, it uses the old way of declaring dependencies between modules (not named modules). Secondly, it doesn't have the angular hook. We use this hook to compile templates using Aurelia's templating system, so using Aurelia templates in these controls is not possible.

In addition, Telerik says they want to remove the jQuery dependency ([link](http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/9511848-integration-with-aurelia)). I'd rather not add support for Kendo-ui-web as I'd like to move away from the jQuery dependency as soon as it is possible.

**Comment by delebash** [comment]
@Thanood 

Here is the source https://github.com/delebash/kendo-ui-web-gpl
@JeroenVinke 

I believe this is the original angular hook used for kendo-ui-web.  
https://github.com/kendo-labs/angular-kendo

Hope this may help, it sure would be nice to be able to use the grid and treeview for non-commerical projects.

**Comment by JeroenVinke** [comment]
@delebash Thanks for the link to the source.

The [angular-kendo](https://github.com/kendo-labs/angular-kendo/blob/master/angular-kendo.js) implementation is quite different than the latest one, for example there are no `compile` and `cleanup` calls which our templating-compiler uses.

I don't think we should include kendo-ui-web in this bridge. The reason is that we want to be able to remove the jQuery dependency as soon as Kendo is ready and we can't do that if we still need to support something that depends on jQuery (and won't be updated). 

you could always fork this repository and create the implementation yourself though

**Comment by delebash** [comment]
Thanks for looking into it.
