### ISSUE TITLE
The installation and app developers tutorial need to define the starting application

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#342]
Based on the interaction with :point_up: [February 10, 2016 11:16 AM](https://gitter.im/adriatic/Aurelia-KendoUI?at=56bb627bfa79226456f97cee) - @fglebel our current instructions are insufficient - partially because of the new [Getting started](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.3/doc/article/getting-started) that became available after our first release. We need to require to use [Aurelia Navigation Skeleton](https://github.com/aurelia/skeleton-navigation) as the required application that is then "enhanced" by adding KendoUI bridge.

**Comment by JeroenVinke** [comment]
I  would not require the use of the skeleton navigation, just recommend it

**Comment by JeroenVinke** [comment]
We are doing this in the new tutorials
