### ISSUE TITLE
The latest ES6 version of the Aurelia Skeleton Navigation with the current Aurelia KendoUI bridge - vendors fails

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#343]
#### Summary
The latest [ES6 version of the Aurelia Skeleton Navigation](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-es2016) with the current [Aurelia KendoUI bridge - vendors](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/vendors) fails with `Unhandled promise rejection Error: Loader must implement loadTemplate(url).`

***
This issue started with this :point_up: [February 10, 2016 4:06 PM](https://gitter.im/adriatic/Aurelia-KendoUI?at=56bba6704dfe1fa71ffbfb80) message I got in the middle of the discussion with @fglebel. 

**The problem is that the bridge crashes at application start with the message**

`Unhandled promise rejection Error: Loader must implement loadTemplate(url).`

**I tried to search for the answer in Aurelia/Discuss group and got this response:**

:point_up: [February 10, 2016 4:15 PM](https://gitter.im/Aurelia/Discuss?at=56bba8670295dc53403d6cbd)

> @adriatic if you use viewcompiler you must use url template such as .html file address

**My response to Behzad**

> @behzad888 Yes, KendoUI bridge does use viewcompiler (successfully for a month at least) - until someone just now reported this problem. So, it must be that this user started from the most current Aurelia Navigation Skeleton app, added KendoUI plugin, which tripped on this "url template" problem that seems to be needed in the latest Aurelia patch.
Is this accurate deduction?

**He wrote back:**
> @adriatic i have this problem then solve it on factorycompiler function inhttps://github.com/FarFlow/au-designer/blob/master/src/services/compiler.js

* * *

I did not even try to establish whether his response fits our usage of the compiler - and equally did not want to bother Rob (who would certainly tell me what got changed since the released bridge was created)

If you manage to fix this and update the released kendo bridge (on npm / jspm) please let @fglebel know

:point_up: [February 10, 2016 4:23 PM](https://gitter.im/adriatic/Aurelia-KendoUI?at=56bbaa670295dc53403d6d3a)

**Comment by JeroenVinke** [comment]
@adriatic 
![image](https://cloud.githubusercontent.com/assets/2189477/12973638/14ef75c0-d0ae-11e5-82d5-55865b4e92f2.png)

whenever you get forks during jspm install, those should be resolved before trying anything else.

Forks were created because we didn't update the dependencies in package.json [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/package.json#L37-L43) after Aurelia released new updates

**Comment by adriatic** [comment]
I believe that we can close this problem as `jspm update` took care of it

**Comment by fglebel** [comment]
Yes, jspm update took care of the problem.
