### ISSUE TITLE
Cannot GET /jspm_packages/npm/aurelia-loader-default@1.0.0-beta.1.1.1.js

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#344]
### Summary

The fix consists of running 

`npm install` & `jspm install` & `cd sample` & `jspm update`

Read on for more details

***

I got the error message defined in the title of this issue, trying to run the freshly built aurelia-kendoui-bridge application (**master**) where I only changed the definitions of jspm version to be "jspm": "0.16.15" in both package.json files

This specific file referenced in the title of this issue is requested **[here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/config.js#L154)** - and it really does not exists after running the standard sequence:

 `npm install` & `jspm install` & `cd sample` & `jspm install`

Instead of this file, we now have `aurelia-loader@1.0.0-beta.1.1.0`

So, we have a bad situation where using the definitions (package.json) of the modules used in the application which worked before, the newly built application using these definitions **and the same code** does not work any more. In other word the specifications in package.json is not consistent with the information in config.js

**Comment by adriatic** [comment]
As expected - running `jspm update` fixes this problem and that brings my dislike for such build process where config.js is persisted in the repository, allowing the `jspm install` command to result with package.json and config.js in a conflicted state. This is simply dumb.

**Comment by Thanood** [comment]
I wonder if it's possible to provide a minimal config.js only including transpiler options, paths and manually added map entries.

Like this:
```javascript
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  paths: {
    "\*": "src/\*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "kendo.*": "src/root/vendors/js/kendo.*.js"
  },

  map: {
    ...
  }
});
```

So dependency mapping comes from package.json.

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/344#issue-132858239

you did run npm install **after** setting the jspm version to 0.16.15 right?

**Comment by adriatic** [comment]
I do not remember that any more - sorry. Since jspm version is locked in the **npm section** of the package.json logic would tell me that changing that data requires re-running npm install, yes.

**Comment by adriatic** [comment]
@Thanood - your idea (https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/344#issuecomment-182733553) seems very smart - if I was the creator of jspm, that is how I would do it :-) 

About three times a day, I am catching myself with the intense desire to write a "lint"-like utility that would check the package.json and congig.js for inconsistencies and then compare it with Aurelia release version names and make some sense from this nonsense

**Comment by JeroenVinke** [comment]
can this be closed?

**Comment by adriatic** [comment]
If keeping it open would "lessen my pain with jspm" -- I would say let's keep it open. As this is is not going to be the case, I closed it :-)

**Comment by Thanood** [comment]
WebPack integration is making progress.. :smile: 
https://github.com/aurelia/skeleton-navigation/issues/41#issuecomment-183978996
