### ISSUE TITLE
scheduler sample is "scrambled"

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#345]
This is true for all Scheduler examples

![image](https://cloud.githubusercontent.com/assets/2712405/12998612/e6fcfc4e-d113-11e5-90f8-6f84bbc47ca3.png)

**Comment by JeroenVinke** [comment]
Yep, seen this yesterday but couldn't figure it out. I just noticed that demo-kendo is using jQuery@2.2.0 and the sample app (inside the plugin) uses jQuery@2.1.4. This problem went away when I downgraded demo-kendo's jQuery to 2.1.4, so that would mean that jQuery 2.2.0 is doing some weird things

**Comment by Thanood** [comment]
jQuery  2.2.0 is also doing weird things to Materialize.

**Comment by JeroenVinke** [comment]
also with positioning?

**Comment by Thanood** [comment]
> also with positioning?

I didn't investigate it, tbh.. Can test it later, though.

**Comment by JeroenVinke** [comment]
http://www.telerik.com/forums/scheduler-display

**Comment by adriatic** [comment]
no need to keep this open
