### ISSUE TITLE
Loading kendo cultures results in 404 to kendo.core.js

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#346]
![image](https://cloud.githubusercontent.com/assets/2189477/13053596/9e23f5dc-d405-11e5-8455-bd0095c5e8b0.png)

We have seen this issue before (in the .112) release of Kendo with loading Kendo controls. In the current version of Kendo the kendo.core dependency in culture and message files are incorrect 

![image](https://cloud.githubusercontent.com/assets/2189477/13053626/c05a74fa-d405-11e5-8074-8f9d0928f101.png)

the 404 goes away when `../kendo.core` in the culture/message file is changed to `../kendo.core.min`. I have opened up a ticket with Telerik for this problem

**Comment by JeroenVinke** [comment]
keep an eye on https://github.com/telerik/kendo-ui-core/issues/1447

**Comment by underlog** [comment]
Fixed the problem. 

Check the example [over here](https://github.com/telerik/kendo-ui-core/blob/master/examples/requirejs-bundle.html)

I am really curious why RequireJS needs the `shim` configuration. I guess that it starts loading the `kendo.ui.core` and `kendo.culture` scripts simultaneously. 

@JeroenVinke - most likely you know how the equivalent with this in Webpack and SystemJS?

**Comment by underlog** [comment]
One more thing, we are going to release a Service Pack later this week, so the fix will be available for trial pro users, too.

**Comment by JeroenVinke** [comment]
@underlog thanks for the fix. I tried it out and it seems to work without the kendo.ui.core.min dependency:

![image](https://cloud.githubusercontent.com/assets/2189477/13290234/3bc754d2-db13-11e5-8ec4-108d89e1f75d.png)



[app.zip](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/files/144843/app.zip)


But if I were to add the dependency config i'd use https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta
