### ISSUE TITLE
ES6 Kendo dependencies with JSPM

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia-ui-toolkits/aurelia-kendoui-bridge#347]
Decided to give this library a try, and I'm running into multiple issues - mainly stemming from wanting to use a custom build of Kendo UI (kendo.custom.min.js).

The first issue is that the individual plugins have hard references to filepaths, like so:
```language-javascript
import 'kendo-ui/js/kendo.autocomplete.min'
```
This forces a specific structure on the directories that may not be wanted. Further, this makes it impossible to use a single bundled build. Finally, this means that one must include all of the specific dependencies in the vendor folder that the library references, or face errors at runtime due to SystemJS not being able to find the referenced files.

The next problem is that when referencing Kendo from a vendor directory, Kendo can't find jQuery unless a separate copy is kept in the vendor directory (which is far from ideal). With JSPM, this can be fixed by adding a meta section that includes a `deps` property, like the example here: http://stackoverflow.com/a/35234506/677526

To solve this, it might be better to do an `import 'kendo'` in index.js and allow the developer to specify the specific configuration in JSPM. Until Kendo supports true module exports, this approach might make the library more flexible.

**Comment by charlespockert** [comment]
@jedd-ahyoung we are importing the kendo bits module by module. As far as I recall, the only reason to use a custom build of kendo is to remove some dependencies that would bloat the file size of the js

Have you considered just using kendo in its constituent parts and allowing system js to load the required bits on demand?

That's the way I'm doing it, unless of course there's something I'm missing about custom builds

**Comment by underlog** [comment]
Kendo UI developer here – the custom build concept is not necessary if you are going to use modules. Just let the module loader pick the necessary parts for you.

**Comment by adriatic** [comment]
> Kendo UI developer here

Thank you Petyo for pitching in - it makes us all more comfortable knowing that you participate in our "Aurelia adventure" :-)

**Comment by jedd-ahyoung** [comment]
@charlespockert Would it be possible to do something like `import {Button} from 'kendo'` or even an `import {Button} from 'kendo.button'`? I realize that this would mean having a very large config.js file for mapping all of the individual files, but I think that would be better than the hardcoded alternative. Further, this would allow specifying the exports and dependencies in config.js, removing the `jquery.min` dependency. (Honestly not sure why the module name changes when it's minified.)

**Comment by adriatic** [comment]
@jedd-ahyoung - what is your purpose for trying to do that? How would your intent differ from what @underlog is suggesting:

> Just let the module loader pick the necessary parts for you

**Comment by JeroenVinke** [comment]
@jedd-ahyoung actually, we can do that as we have this mapping now:

`"kendo.*": "jspm_packages/github/kendo-labs/bower-kendo-ui@2016.1.120/js/kendo.*.js"`

**Comment by JeroenVinke** [comment]
I was a bit concerned that we'd break the plugin for Kendo versions < 2016 Q1 by doing `import 'kendo.button.min';` instead of `import 'kendo-ui/js/kendo.button.min'` but I tested this with 2015.3.930 and it works

**Comment by JeroenVinke** [comment]
This improved import syntax is now used.
