### ISSUE TITLE
using sublime linter correctly

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#349]
I did enable the linter and am now seeing this 

![image](https://cloud.githubusercontent.com/assets/2712405/13093843/5e6724e8-d4d5-11e5-95a3-7e2e11d07c56.png)

The error is `Strings must use singlequote`

I did not have that problem until I enabled this

**Comment by JeroenVinke** [comment]
That's great :)  you can ignore the suggestions in config.js. I think we can ignore this file by adding it to a .eslintrcignore file (or whatever it is called)
