### ISSUE TITLE
Bad url in kendo-bridge-init.html

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#355]
The problem is [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/0.3.0/sample/src/about/kendo-bridge-init.html#L9)

It results with
```
http://demos.telerik.com/kendo-ui/content/web/Customers/$%7BCustomerID%7D.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
```

Not sure why the images still appear

![image](https://cloud.githubusercontent.com/assets/2712405/13123631/1f22bfa2-d58b-11e5-8222-6c0f5c5254ce.png)

**Comment by JeroenVinke** [comment]
yep, this is a common issue in Aurelia, nothing to do with the plugin:

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/pull/281#issuecomment-176308266

it's harmless
