### ISSUE TITLE
Make the list of available attributes as a help page

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#356]
I propose to display the content of the **[bindable.js](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/src/common/bindables.js)** page 

"kendoAutoComplete":["animation","dataSource","dataTextField","delay","enable","filter","fixedGroupTemplate","groupTemplate","headerTemplate","height","highlightFirst","ignoreCase","minLength","name","placeholder","popup","separator","suggest","template","valuePrimitive","virtual"],

"kendoBarcode":
["background","border","checksum","color","height","name","padding","renderAs","text","type","value","width"],

"kendoButton":
["enable","icon","imageUrl","name","spriteCssClass"],

"kendoCalendar":
["culture","dates","depth","disableDates","footer","format","max","min","month","name","start","value"],

"kendoChart":["autoBind","axisDefaults","categoryAxis","chartArea","dataSource","legend","name","panes","pannable","pdf","plotArea","renderAs","series","seriesColors","seriesDefaults","theme","title","tooltip","transitions","valueAxis","xAxis","yAxis","zoomable"],

"kendoColorPalette":
["columns","name","palette","tileSize","value"],

"kendoColorPicker":
["buttons","columns","messages","name","opacity","palette","preview","tileSize","toolIcon","value"],

"kendoComboBox":["animation","autoBind","cascadeFrom","cascadeFromField","dataSource","dataTextField","dataValueField","delay","enable","filter","fixedGroupTemplate","groupTemplate","headerTemplate","height","highlightFirst","ignoreCase","index","minLength","name","placeholder","popup","suggest","template","text","value","valuePrimitive","virtual"],

"kendoContextMenu":["alignToAnchor","animation","closeOnClick","dataSource","direction","filter","hoverDelay","name","orientation","popupCollision","showOn","target"],

"kendoDatePicker":["ARIATemplate","animation","culture","dates","depth","disableDates","footer","format","max","min","month","name","parseFormats","start","value"],

"kendoDateTimePicker":["ARIATemplate","animation","culture","dates","depth","disableDates","footer","format","interval","max","min","month","name","parseFormats","start","timeFormat","value"],

"kendoDiagram":["autoBind","connectionDefaults","connections","connectionsDataSource","dataSource","editable","layout","name","pannable","pdf","selectable","shapeDefaults","shapes","template","zoom","zoomMax","zoomMin","zoomRate"],

"kendoDraggable":
["axis","container","cursorOffset","distance","filter","group","hint","ignore"],

"kendoDropDownList":["animation","autoBind","cascadeFrom","cascadeFromField","dataSource","dataTextField","dataValueField","delay","enable","filter","fixedGroupTemplate","groupTemplate","headerTemplate","height","ignoreCase","index","minLength","name","optionLabel","optionLabelTemplate","popup","template","text","value","valuePrimitive","valueTemplate","virtual"],

"kendoDropTarget":
["group"],

"kendoDropTargetArea":
["filter","group"],

"kendoEditor":
["domain","encoded","fileBrowser","imageBrowser","messages","name","pdf","resizable","serialization","stylesheets","tools"],

"kendoFlatColorPicker":
["autoupdate","buttons","messages","name","opacity","preview","value"],

"kendoGantt":["assignments","autoBind","columnResizeHandleWidth","columns","currentTimeMarker","dataSource","dependencies","editable","height","hourSpan","listWidth","messages","name","navigatable","pdf","resizable","resources","rowHeight","selectable","showWorkDays","showWorkHours","snap","taskTemplate","toolbar","tooltip","views","workDayEnd","workDayStart","workWeekEnd","workWeekStart"],

"kendoGrid":["allowCopy","altRowTemplate","autoBind","columnMenu","columnResizeHandleWidth","columns","dataSource","detailTemplate","editable","excel","filterable","groupable","height","messages","mobile","name","navigatable","noRecords","pageable","pdf","reorderable","resizable","rowTemplate","scrollable","selectable","sortable","toolbar"],

"kendoLinearGauge":
["gaugeArea","name","pointer","renderAs","scale","transitions"],

"kendoListView":
["altTemplate","autoBind","dataSource","editTemplate","name","navigatable","selectable","template"],

"kendoMap":["center","controls","layerDefaults","layers","markerDefaults","markers","maxZoom","minSize","minZoom","name","pannable","wraparound","zoom","zoomable"],

"kendoMaskedTextBox":
["clearPromptChar","culture","mask","name","promptChar","rules","unmaskOnPost","value"],

"kendoMenu":
["animation","closeOnClick","dataSource","direction","hoverDelay","name","openOnClick","orientation","popupCollision"],

"kendoMobileActionSheet":
["cancel","name","popup","type"],

"kendoMobileBackButton":
["name"],

"kendoMobileButton":
["badge","clickOn","enable","icon","name"],

"kendoMobileButtonGroup":
["enable","index","name","selectOn"],

"kendoMobileCollapsible":
["animation","collapsed","expandIcon","iconPosition","inset","name"],

"kendoMobileDetailButton":
["name"],

"kendoMobileDrawer":
["container","name","position","swipeToOpen","swipeToOpenViews","title","views"],

"kendoMobileLayout":
["id","name","platform"],

"kendoMobileListView":["appendOnRefresh","autoBind","dataSource","endlessScroll","filterable","fixedHeaders","headerTemplate","loadMore","messages","name","pullParameters","pullToRefresh","style","template","type","virtualViewSize"],

"kendoMobileLoader":
["name"],

"kendoMobileModalView":
["height","modal","name","width"],

"kendoMobileNavBar":
["name"],

"kendoMobilePane":
["collapsible","initial","layout","loading","name","portraitWidth","transition"],

"kendoMobilePopOver":
["name","pane","popup"],

"kendoMobileScrollView":["autoBind","bounceVelocityThreshold","contentHeight","dataSource","duration","emptyTemplate","enablePager","itemsPerPage","name","page","pageSize","template","velocityThreshold"],

"kendoMobileScroller":
["elastic","messages","name","pullOffset","pullToRefresh","useNative","visibleScrollHints","zoom"],

"kendoMobileSplitView":
["name","style"],

"kendoMobileSwitch":
["checked","enable","name","offLabel","onLabel"],

"kendoMobileTabStrip":
["name","selectedIndex"],

"kendoMobileView":
["model","name","reload","scroller","stretch","title","useNativeScrolling","zoom"],

"kendoMultiSelect":["animation","autoBind","autoClose","dataSource","dataTextField","dataValueField","delay","enable","filter","fixedGroupTemplate","groupTemplate","headerTemplate","height","highlightFirst","ignoreCase","itemTemplate","maxSelectedItems","minLength","name","placeholder","popup","tagMode","tagTemplate","value","valuePrimitive","virtual"],

"kendoNotification":["allowHideAfter","animation","appendTo","autoHideAfter","button","height","hideOnClick","name","position","stacking","templates","width"],

"kendoNumericTextBox":
["culture","decimals","downArrowText","format","max","min","name","placeholder","spinners","step","upArrowText","value"],

"kendoPager":["autoBind","buttonCount","dataSource","info","input","linkTemplate","messages","name","numeric","pageSizes","previousNext","refresh","selectTemplate"],

"kendoPanelBar":["animation","contentUrls","dataSource","expandMode","name"],

"kendoPivotConfigurator":
["dataSource","filterable","height","messages","name","sortable"],

"kendoPivotGrid":["autoBind","columnHeaderTemplate","columnWidth","dataCellTemplate","dataSource","excel","filterable","height","kpiStatusTemplate","kpiTrendTemplate","messages","name","pdf","reorderable","rowHeaderTemplate","sortable"],

"kendoPopup":
["anchor","animation","appendTo","name","origin","position"],

"kendoProgressBar":
["animation","chunkCount","enable","max","min","name","orientation","reverse","showStatus","type","value"],

"kendoQRCode":
["background","border","color","encoding","errorCorrection","name","padding","renderAs","size","value"],

"kendoRadialGauge":["gaugeArea","name","pointer","renderAs","scale","transitions"],

"kendoRangeSlider":
["largeStep","max","min","name","orientation","selectionEnd","selectionStart","smallStep","tickPlacement","tooltip"],

"kendoResponsivePanel":
["autoClose","breakpoint","name","orientation","toggleButton"],

"kendoScheduler":["allDayEventTemplate","allDaySlot","autoBind","currentTimeMarker","dataSource","date","dateHeaderTemplate","editable","endTime","eventTemplate","footer","group","groupHeaderTemplate","height","majorTick","majorTimeHeaderTemplate","max","messages","min","minorTickCount","minorTimeHeaderTemplate","mobile","name","pdf","resources","selectable","showWorkHours","snap","startTime","timezone","toolbar","views","width","workDayEnd","workDayStart","workWeekEnd","workWeekStart"],

"kendoSlider":["decreaseButtonTitle","increaseButtonTitle","largeStep","max","min","name","orientation","showButtons","smallStep","tickPlacement","tooltip","value"],

"kendoSortable":["autoScroll","axis","connectWith","container","cursor","cursorOffset","disabled","filter","handler","hint","holdToDrag","ignore","name","placeholder"],

"kendoSparkline":["autoBind","axisDefaults","categoryAxis","chartArea","data","dataSource","name","plotArea","pointWidth","renderAs","series","seriesColors","seriesDefaults","theme","tooltip","transitions","type","valueAxis"],

"kendoSplitter":
["name","orientation","panes"],

"kendoSpreadsheet":["activeSheet","columnWidth","columns","excel","headerHeight","headerWidth","name","pdf","rowHeight","rows","sheets","sheetsbar","toolbar"],

"kendoStockChart":["autoBind","axisDefaults","categoryAxis","chartArea","dataSource","dateField","legend","name","navigator","panes","pdf","plotArea","renderAs","series","seriesColors","seriesDefaults","theme","title","tooltip","transitions","valueAxis"],

"kendoTabStrip":["animation","collapsible","contentUrls","dataContentField","dataContentUrlField","dataImageUrlField","dataSource","dataSpriteCssClass","dataTextField","dataUrlField","name","navigatable","scrollable","tabPosition","value"],

"kendoTimePicker":
["animation","culture","dates","format","interval","max","min","name","parseFormats","value"],

"kendoToolBar":
["items","name","resizable"],

"kendoTooltip":
["animation","autoHide","callout","content","filter","height","iframe","name","position","showAfter","showOn","width"],

"kendoTouch":
["doubleTapTimeout","enableSwipe","filter","maxDuration","maxYDelta","minHold","minXDelta","multiTouch","name","surface"],

"kendoTreeList":["autoBind","columnMenu","columns","dataSource","editable","excel","filterable","height","messages","name","pdf","reorderable","resizable","scrollable","selectable","sortable","toolbar"],

"kendoTreeMap":
["autoBind","colorField","colors","dataSource","name","template","textField","theme","type","valueField"],

"kendoTreeView":["animation","autoBind","autoScroll","checkboxes","dataImageUrlField","dataSource","dataSpriteCssClassField","dataTextField","dataUrlField","dragAndDrop","loadOnDemand","messages","name","template"],

"kendoUpload":["async","enabled","files","localization","multiple","name","showFileList","template"],

"kendoValidator":["errorTemplate","messages","name","rules","validateOnBlur"],

"kendoWindow":["actions","animation","appendTo","autoFocus","content","draggable","height","iframe","maxHeight","maxWidth","minHeight","minWidth","modal","name","pinned","position","resizable","scrollable","title","visible","width"],

"GridColumn":["aggregates","attributes","columns","command","encoded","field","filterable","footerTemplate","format","groupFooterTemplate","groupHeaderTemplate","groupable","headerAttributes","headerTemplate","hidden","lockable","locked","menu","minScreenWidth","sortable","template","title","values","width","editor"],"TreeListColumn":["attributes","command","encoded","expandable","field","filterable","footerTemplate","format","headerAttributes","headerTemplate","hidden","lockable","locked","menu","minScreenWidth","sortable","template","title","width","editor"]

**Comment by adriatic** [comment]
This would be a nice service to our users - and it would be even better if we add the search option on that page, as this list is rather long

**Comment by JeroenVinke** [comment]
hmm, isn't Telerik's documentation much more extensive than what we can provide? Any property that is mentioned in Telerik's documentation should work with our plugin. They even have detailed information per property

**Comment by adriatic** [comment]
It seems that I am not clearly explaining what I want to do: offer an unofficial convenience for wrapper writers that presents the information from the bindables.js file in a nicer format

**Comment by JeroenVinke** [comment]
superseded by https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/384
