### ISSUE TITLE
Gulp watch using quite a lot of CPU

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#357]
![image](https://cloud.githubusercontent.com/assets/2189477/13153782/0baf3400-d676-11e5-8433-0fc68c144220.png)

**Comment by Thanood** [comment]
Interesting. It's a constant 3% for me and up to 16% after a change is actually detected.

**Comment by JeroenVinke** [comment]
same for me if I disable [this line](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/build/tasks/watch.js#L21). Weird

**Comment by Thanood** [comment]
I don't even have that. :smile: 
Maybe it's watching twice, although it's ```paths.sample + '/*'```?

**Comment by JeroenVinke** [comment]
that's very clever! :smile:

**Comment by Thanood** [comment]
No, that would trigger two outputs.

**Comment by JeroenVinke** [comment]
that commit saves me 25% cpu :rocket:

**Comment by adriatic** [comment]
> that commit saves me 25% cpu

This sounds as if you are now able to apply saved cycles to something else :-)

**Comment by Thanood** [comment]
:smile:
