### ISSUE TITLE
k-grid: recreate() function creates nested grid

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia-ui-toolkits/aurelia-kendoui-bridge#358]
Calling the `recreate` function on a `k-grid` object caused the grid to be rerendered - but because Kendo reruns its entire pipeline, this causes a problem - Kendo will create a wrapping `div` if the grid is not instantiated on a `div` element. This results in nested grid behavior when we recreate, because Kendo actually wraps the custom element.

Upon initial load:
![image](https://cloud.githubusercontent.com/assets/2175990/13158260/28e2e97a-d65a-11e5-8128-0eace2f83f76.png)

After two refreshes:
![image](https://cloud.githubusercontent.com/assets/2175990/13158074/327e0718-d659-11e5-8409-d76876bc7a9b.png)

![image](https://cloud.githubusercontent.com/assets/2175990/13158088/4eaea780-d659-11e5-9fa8-e6a277ebbe9e.png)

While I do believe that this is the fault of the Kendo library (instead of checking for a `div`, it should check for any block-level element, or specifically check that the element is not a table for instantiation purposes) the plugin may have to work around this.

**Comment by JeroenVinke** [comment]
Just like I wrote in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/350#issuecomment-185583044, we can allow the user to supply an element (`<div></div>`) in this case. So you can initialize the grid in three ways:

1. the grid gets initialized on the `<div>`:
    ```
    <k-grid>
      <k-col></k-col>

       <div></div>
    </k-grid>
    ```


2. the wrapper creates a `<div></div>` and initializes the grid on that:
    ```
    <k-grid>
       <k-col></k-col>
    </k-grid>
    ```


3. the wrapper sees that a table is provided and initializes the grid on the table (initialization on an existing table is a feature of the Kendo grid):
    ```
    <k-grid>
       <k-col></k-col>

       <table>
         <tr></tr>
       </table>
    </k-grid>
     ```
