### ISSUE TITLE
Both finished tutorials need to be rebuilt

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#359]
The KendoUI bridge catalog application contains `app developers` and `bridge developers` step by step tutorials.The finished versions of these tutorials are
https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo and https://github.com/aurelia-ui-toolkits/skeleton-plugin-kendo respectively.

These tutorials are based on Aurelia Skeletons (https://github.com/aurelia/skeleton-navigation and https://github.com/aurelia/skeleton-plugin, respectively) - which seem to be signifiicantly different to warrant rebuilding our tutorials from scratch, instead of patching the old aurelia skeletons that are embedded in our tutorials

**Comment by JeroenVinke** [comment]
This was finished
