### ISSUE TITLE
KendoUI bridge finished tutorials

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#360]
At the moment both tutorials are packaged with `vendors` folder as a part of the repo, to avoid any unnecessary complications for people that want to have something that runs out of the box.

Should we continue with this practice?

Also, how to define the access to KendoUI bridge? Via Github, or npm ?

**Comment by JeroenVinke** [comment]
>

At the moment both tutorials are packaged with vendors folder as a part of the repo, to avoid any unnecessary complications for people that want to have something that runs out of the box.

Should we continue with this practice?

perhaps it's better to have people follow the installation steps (download a trial version) as it's going to be a pain to keep these things up to date if we have vendor folders in different locations. we just need it for the aurelia-kendoui-bridge in order to get Travis CI working

> Also, how to define the access to KendoUI bridge? Via Github, or npm ?

not sure what you mean

**Comment by adriatic** [comment]
> perhaps it's better to have people follow the installation steps (download a trial version) 

Does this mean that the trial version is now OK to be used with the bridge? ("named modules" issue?)

**Comment by JeroenVinke** [comment]
No, but if people follow the installation instructions they should be fine (as we now have that warning in place)

**Comment by adriatic** [comment]
Makes sense

**Comment by adriatic** [comment]
The `finished tutorial` application is an Aurelia app that uses the KendoUI bridge (plugin, that is). So, at the moment any app can get that bridge via **[this line](https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo/blob/master/package.json#L65)** in `package.json` or via **[npm](https://www.npmjs.com/package/aurelia-kendoui-bridge)**

Do you have a preference for this? I believe you created the npm registration, so I assume we will continue to maintain it

**Comment by JeroenVinke** [comment]
Npm is the way to go. Aurelia uses it and it helps with the github rate limiting issue (that requires you to enter your github credentials into jspm)

**Comment by adriatic** [comment]
well, everything you say today makes sense :-)

**Comment by adriatic** [comment]
> Npm is the way to go

This implies that you need to define the process for making npm registration (and save the credentials in our private chat room)

**Comment by JeroenVinke** [comment]
I made screenshots of what I did for the first release 

![1](https://cloud.githubusercontent.com/assets/2189477/13188715/66100252-d753-11e5-86d4-43302af04007.png)
![2](https://cloud.githubusercontent.com/assets/2189477/13188713/660f7918-d753-11e5-8033-c9eac6bd6b8b.png)
![3](https://cloud.githubusercontent.com/assets/2189477/13188712/660f4dc6-d753-11e5-8630-0f280042aed0.png)
![4](https://cloud.githubusercontent.com/assets/2189477/13188711/660f3048-d753-11e5-9211-a7b58e7ca388.png)
![5](https://cloud.githubusercontent.com/assets/2189477/13188714/6610041e-d753-11e5-94de-0a85937aed07.png)

![6 exe](https://cloud.githubusercontent.com/assets/2189477/13188716/6611224a-d753-11e5-99ba-05493878e58b.png)

**Comment by adriatic** [comment]
This matches my own understanding of the Github release creation process. Thanks

**Comment by JeroenVinke** [comment]
Can this be closed?
