### ISSUE TITLE
Find replacement for panel bar

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#362]
![image](https://cloud.githubusercontent.com/assets/2189477/13196486/42b845c2-d7cf-11e5-9cec-dad8ca9d7d54.png)

if we replace the panelbar with a different Kendo control (or just use html/css/js) I think we can remove bootstrap completely

**Comment by adriatic** [comment]
Panelbar meaning the navigation sidebar?

There are several places where we use bootstrap layout (rows and cols)

**Comment by JeroenVinke** [comment]
No the [panel bar](http://getbootstrap.com/components/#panels-heading)

**Comment by adriatic** [comment]
Where is the [panel bar](http://getbootstrap.com/components/#panels-heading) being used?

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/13197291/2d5f98fe-d7ea-11e5-870f-5e8d1543e196.png)

The right side (the running sample and the code preview) use panelbars

**Comment by adriatic** [comment]
This **is** what I meant when asked "Panelbar meaning the navigation sidebar?" - it is used to navigate within the examples of using a given KendoUI component.

I am not wedded to using Boostrap panel bar - we can use KendoUI accordion instead - and we do not need to do it now :-)

**Comment by Thanood** [comment]
Doesn't the documentation use panelbar, too?

**Comment by adriatic** [comment]
Yes, it does - I believe that the catalog uses Bootstrap panelbar and docs use Telerik - or vice versa?

**Comment by JeroenVinke** [comment]
Yeah we use bootstrap for col's too so lets keep the bootstrap dep for now
