### ISSUE TITLE
k-editor custom attribute conflicting with k-editor property of k-col

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#365]
```
<template>
  <div id="example">
    <k-grid k-pageable.bind="true" k-height.bind="500" k-toolbar.bind="['create']" k-editable.bind="true" k-data-source.bind="dataSource">
      <k-col k-field="ProductName" k-title="Product Name"></k-col>
      <k-col k-field="Category" k-title="Category" k-width="180px" k-editor.bind="categoryDropDownEditor" k-template.bind="categoryTemplate"></k-col>
      <k-col k-field="UnitPrice" k-title="Unit Price" k-format="{0:c}" k-width="130px"></k-col>
      <k-col k-command="destroy" k-title=" " k-width="150px"></k-col>
    </k-grid>
  </div>
</template>
```

`k-editor` is conflicting with the `k-editor` custom attribute, causing the `kEditor` property of the `k-col` to be undefined, when it should be a function reference. Also, Kendo's Editor control is initialized on the k-col

**Comment by adriatic** [comment]
This does not seem to be big issue as nobody has seen the k-editor custom attribute used in the context of http://demos.telerik.com/kendo-ui/editor/index. Although the Kendo Editor has more "moral" right to use `k-editor` custom attribute, we could simply call it `k-edit` and problem solved

**Comment by JeroenVinke** [comment]
OK, that seems like a good solution. If we have more issues like this we do need to change the prefix

**Comment by adriatic** [comment]
A further improvement over k-edit !

**Comment by JeroenVinke** [comment]
I figured k-edit may also be a common property name :)
