### ISSUE TITLE
The top level menu item "Project status" should be changed to "Catalog index"

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#367]
Once we are done with this bridge, the project status page would make little sense as all entries would be "blue" (note that I did not write "green"). However, this page is **great** as it provides direct access to each component, without several layers of navigation.

Rather than just displaying component name as a link, we might consider to populate this page with "cards" (http://materializecss.com/cards.html)

ping: @Thanood

**Comment by Thanood** [comment]
Well, I have done this:
https://github.com/Thanood/skeleton-bridge/commit/6b3dfd457800034d28ff816658e72ad2efeaf97b

It also generates the menu and sample routes. It's in skeleton-bridge, so it uses bootstrap, not kendo and I guess that would be a bigger change for kendoui-bridge.

You could of course simple add some borders with box-shadows. :smile:

**Comment by JeroenVinke** [comment]
@Thanood that is pretty cool :smile:

**Comment by Thanood** [comment]
@JeroenVinke thanks. :smile: 
I've had the idea to also include registry.json into that file but that can wait.

If you think it's general enough to be included in KendoUI and skeleton-bridge, I will merge my own PR on skeleton-bridge. I just didn't want to do that without some feedback. :)

**Comment by adriatic** [comment]
@Thanood We will all agree that Aurelia-Toolkits bridges family is not all we want to do - it's rather a smart first step towards creating better Aurelia development tools, so every bridge feature that is compatible with our aim is worthwhile pursuing. At the same time, having very limited resource, we need to make sure that our bridges do not follow the fate Golden Gate bridge, which due to its size and amount of resources available to its maintenance is being painted in perpetuity, without a day of rest for the painters :-)

**Comment by Thanood** [comment]
Sounds a lot like Cologne cathedral. :smile: 

I just didn't want to merge stuff nobody wants to use and as skeleton-bridge is the future starting point for new bridges, I wanted to be extra careful.
