### ISSUE TITLE
samples/grid/editing-custom-editor cannot edit category field

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#369]
@fglebel reports:[February 22, 2016 2:41 PM](https://gitter.im/adriatic/Aurelia-KendoUI?at=56cb646b95f2abfa55e81cd9))

> I would love it if this example could be fixed... http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/editing-custom-editor as I am trying to achieve the same. The Category Field does not get populated correctly. thanks.

**Comment by Thanood** [comment]
That looks familiar. Could it be related to #251?

**Comment by JeroenVinke** [comment]
yeah it broke in #251 too. But I believe this time it's because we disabled angular templates on all `template` properties by default, so Aurelia's syntax should be used on that template

**Comment by adriatic** [comment]
Confirmed fixed to the customer [February 22, 2016 3:45 PM](https://gitter.im/adriatic/Aurelia-KendoUI?at=56cb735395f2abfa55e82071)
