### ISSUE TITLE
Catalog app loses the theme 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#370]
**Branch:** `master` - release 0.3.0 candidate

#### Steps to reproduce:

1. Start the Catalog
2. Click in `Installation` menu-item on main menu
3. Click on any of the tabs shown below:

![image](https://cloud.githubusercontent.com/assets/2712405/13240005/9e9d1fa0-d9ac-11e5-89fd-6afe49087e4b.png)

KendoUI chosen theme (Kendo default in our case) is lost.

#### Added on 2/23/2016 - expanding the step 3 above

Watch the top menu `Installation` item lose its color red (indication that it is the currently selected item) and the newly selected tab does not show red color.

**Comment by JeroenVinke** [comment]
How are you coming to this conclusion?

![image](https://cloud.githubusercontent.com/assets/2189477/13246181/42f7d2ec-da12-11e5-859c-65880b8210d0.png)

**Comment by JeroenVinke** [comment]
this is actually part of the theme, tabstrip's selected tabs are not highlighted with that color

**Comment by adriatic** [comment]
However - this is the only case where selecting a "child menu item" deselects the parent (Installation on the main menu bar).

**Comment by adriatic** [comment]
I looked at the fix - at the high level, it is perfectly clear, but it would take me some time to do it myself, as I still get sometimes lost with more complex routing issues.
