### ISSUE TITLE
Improve Two-way binding not showing any effect

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#376]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/0.3.0/sample/src/help/docs/app-developers-notes/introduction.md#two-way-binding-not-showing-any-effect

We can mention that two-way databinding is not possible with two exceptions: the `value` property and the `datasource` property (as long as it's a `kendo.data.DataSource` instance and not a plain javascript object)

:point_up: [February 25, 2016 9:17 AM](https://gitter.im/adriatic/Aurelia-KendoUI?at=56ceb8b4dbccfd8a4fd0509c)

**Comment by adriatic** [comment]
Let's use (perhaps enhanced) version of your post :point_up: [February 25, 2016 3:17 AM](https://gitter.im/adriatic/Aurelia-KendoUI?at=56ceb8b4dbccfd8a4fd0509c)
