### ISSUE TITLE
Provide real Aurelia-KendoUI skeleton application

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#378]
At the moment we maintain the **[Skeleton Application Kendo](https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo)** which is a logical part of the [aurelia-kendoui-bridge](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge) repository, since it contains the finished Aurelia KendoUI application  used in the [application developers tutorial](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_tutorials/1._introduction). This Skeleton Application Kendo](https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo) is also limited by using the [skeleton-plugin-kendo](https://github.com/aurelia-ui-toolkits/skeleton-plugin-kendo) which has only four Aurelia KendoUI components (autocomplete, button, chart and grid) created in the context of the [bridge developers tutorials](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/bridge_developers_tutorials/1._introduction).

We need to create a reasonably complex skeleton app - not by augmenting the [aurelia navigation skeleton](), but rather by "shrinking" the [Aurelia KendoUI catalog](http://aurelia-ui-toolkits.github.io/demo-kendo) application. This new skeleton app should be distributable via GitHub.

**Comment by adriatic** [comment]
Should we consider using that tool that creates the complete application structure?

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/314 seems similar
