### ISSUE TITLE
Link to Telerik documentation from samples

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#384]
The bridge is already a world class cheat sheet for app developers. Adding the app runner (aka plunker) will further increase the value of the bridge, making it gradually evolve to an IDE.

The plugin developers have great help from the built in `config-builder` which uses the data in `bindables.js`. It would be great to provide similar functionality to app developers, in a more explicit way.Here is the example coming from using a color picker 

```
<label for="borderColor">Border color</label>
<input k-color-picker="k-widget.two-way: colorPicker; k-tool-icon: k-foreColor; k-value.two-way: color" />
```

This code renders:

![image](https://cloud.githubusercontent.com/assets/2712405/13379805/83b425d4-ddfe-11e5-81b8-2a508b1fd244.png)

I would however like to set the default color to white - like this

![image](https://cloud.githubusercontent.com/assets/2712405/13379828/47ee0230-ddff-11e5-82e0-598de80dd4ba.png)

It would be nice to be able to see a list of attributes for each KendoUI `component` with the list of acceptable values

**Comment by JeroenVinke** [comment]
We need more information than what we have in bindables.js, so we need to parse files like https://github.com/telerik/kendo-ui-core/blob/master/docs/api/javascript/ui/colorpicker.md. We only store property names in `bindables.js` and it should stay that way as this is a feature for the catalog and not for the plugin (the plugin should not become larger due to this)

**Comment by adriatic** [comment]
I agree - because it is obvious that I am describing the added functionality to the Catalog app, which is to be perceived as a tool for application developers (**not bridge developers**)

**Comment by JeroenVinke** [comment]
I made a gulp task that extracts information from Kendo's mark down files ([link](https://github.com/telerik/kendo-ui-core/tree/master/docs/api/javascript)). The gulp task extracts the methods/properties/events and creates a JSON file for each control: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/tree/0.7.0/doc/kendo-api

So now we need a good way to display this data. Any idea's?

**Comment by JeroenVinke** [comment]
This is all in the 0.7.0 branch by the way

**Comment by adriatic** [comment]
#### Let's pick up the discussion for UI here:
> The gulp task extracts the methods/properties/events and creates a JSON file for each control - see https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/tree/0.7.0/doc/kendo-api

When it evolves sufficiently we will host this elsewhere.

@JeroenVinke followed his announcement (quoted above) with this image

![image](https://cloud.githubusercontent.com/assets/2712405/13436593/fb46328a-dfad-11e5-8f55-ab3303f6c5aa.png)

The best way to start this is to have @JeroenVinke state his expectations from being able to offer this data - and that is best to do with a few typical use cases

**Comment by JeroenVinke** [comment]
As the catalog is the site used by people to find out how to use our wrappers, it would be very convenient to get a list of possible options/events/methods in the same place.

**Comment by adriatic** [comment]
This is very much in line with what I think - it is the same type of service that the catalog offers already by presenting the Code Preview

![image](https://cloud.githubusercontent.com/assets/2712405/13436943/b4f72eea-dfaf-11e5-93bc-a1e0bdd0646f.png)
 
To offer maximum usability while maintaining the current UI - this new feature need to also include the current sidebar of course. 

So, the typical use case is this:

- I am an Aurelia developer that wants to use the KendoUI bridge in my app. Knowing that the KendoUI Bridge Catalog app can show me several different aspects of using any of the supported controls

- As these covered cases do not cover nearly enough from what I need, I really want find out details like complete API, list of supported events etc all in the context of using KendoUI Aurelia components - so peeking at http://docs.telerik.com/kendo-ui/api/javascript/kendo is not a solution.

Getting close?

**Comment by JeroenVinke** [comment]
Yep

**Comment by adriatic** [comment]
Let me peek around for some more ideas on this UI (although I believe that I have a pretty good idea already). I want to turn over and have a look under all stones :-)

**Comment by JeroenVinke** [comment]
Alternative: Add a link to every sample that points to the relevant Telerik documentation (just like we do with the kendo core/pro label)

**Comment by adriatic** [comment]
> Alternative: Add a link to every sample that points to the relevant Telerik documentation (just like we do with the kendo core/pro label)

Definitively acceptable solution **for this time** (we might resurface this again, if we have volunteers to add this feature)

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/13723166/1876540e-e85d-11e5-958e-3634090298f9.png)
