### ISSUE TITLE
Can Bridge be used as an Aurelia KendoUI skeleton application generator?

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#385]
At minimum, we could teach it how to create the **complete project** (folders / files hierarchy) for the Catalog app (this reminds me of the old puzzle: write a Fortran application that creates it's own code as output)

A more advanced approach would be to have the bridge being able to access a database of projects (templates) and allow the user to select one to be generated. Of course, the critical part of this feature is to get our "code generators" involved in the templates creation and maintenance.

**Note:** this is yet again a feature that evolves the bridge into the IDE, so I have no proposal at what time to deal with this.

**Comment by Thanood** [comment]
Would a yeoman generator be an option?

**Comment by JeroenVinke** [comment]
The bridge or the sample app should not be responsible for generating any code. We would need to use a yeoman generator of some kind. Besides, I think we should focus on integrating the bridge in existing aurelia apps, not creating one from scratch.
