### ISSUE TITLE
Destroy before recreate() ?

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#388]
It seems logical to destroy the widget before calling `recreate()`

[this sample](http://demos.telerik.com/kendo-ui/tabstrip/animation) does not work as it should I believe as there is no change in animation when you enable/disable options

That is probably because they are initializing the control without destroying it first

**Comment by adriatic** [comment]
Why did you not do this right away, from the beginning?

**Comment by JeroenVinke** [comment]
Always thought we already did this :smile:
