### ISSUE TITLE
Create the set of typical Aurelia-KendoUI application skeletons

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#392]
Until we get the bridge to be able to create such skeletons (this would be a really cool feature by the way, completely addressing the **[whole long discussion](https://gitter.im/adriatic/Aurelia-KendoUI?at=56d50c2f712bb6033acfb12f)** that took me hours to manage today, we need to provide a set of skeletons, as aurelia does **[here](https://github.com/aurelia/skeleton-navigation)**

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/13449917/ceb36c92-dffd-11e5-9049-064b20295015.png"></img>
 <br><br>
</p>

**Important** - all these skeletons should use **all** UI components from the KendoUI bridge (even the main menu should be Telerik's) so I will create them by stripping down the Catalog app (no intent to provide any of the Catalog's infrastructure innovations at this time)

This would be the best currently possible response to folks that were not capable of using the Bridge tutorials and installation notes to come up with a working skeleton for their apps

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-test-repositories seems like the right place

**Comment by adriatic** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-test-repositories it is (for now, as the name **test** might suggest lower quality products :-)

**Comment by JeroenVinke** [comment]
May be changed ofcourse

Op woensdag 2 maart 2016 heeft Nikolaj Ivancic <notifications@github.com>
het volgende geschreven:

**Comment by adriatic** [comment]
"volgende" is identically spelled as the matching german word.

**Comment by JeroenVinke** [comment]
Correct :)

**Comment by Thanood** [comment]
actually, it's "folgende" - but I'm sure it has the same roots :smile:

**Comment by JeroenVinke** [comment]
darn!!

**Comment by Thanood** [comment]
Some Dutch words are dangerous ... some years ago I had my mobile set to Dutch when I wanted to impress a girl whose parents are from the Netherlands. Never got far with the language, though. :smile: 

Anyway, she actually came to the point where she had a menu open on my mobile where it stated "alles wissen" ... which in German means something like "know everything"...

**Comment by adriatic** [comment]
> actually, it's "folgende" - but I'm sure it has the same roots

I was about to correct the writer (thinking it was Jeroen) that "folgende" is wrong - and then realized it was Daniel who wrote that, so my comment is the same as Jeroens: **Darn**

I also feel like "this cannot be possible, as there are few if any `f` characters in German language, to the point that 'v` is pronounced as "fau". Oh well

**Comment by adriatic** [comment]
An update on https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/392#issuecomment-191305065

I went ahead and created a new repo - **[kendoui-templates-repository](https://github.com/aurelia-ui-toolkits/kendoui-templates-repository)** as there ought to be a distinction between the collection of tests and the collection of "official" templates.

**Comment by JeroenVinke** [comment]
done: https://github.com/aurelia-ui-toolkits/kendoui-templates-repository
