### ISSUE TITLE
prettify dependency

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#396]
Do we still use the [prettify extension](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/config.js#L55)? Removing it would solve the isarray fork: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/377

**Comment by adriatic** [comment]
It would be good to know how did you find out that it is `prettify` that caused the fork. When I looked in the config.js map I found a bunch of modules that list isarray as dependency but had no idea that the top of that dependency tree is `prettify`.

I am sure that we need a better handle on the whole dependency tree.

**Comment by JeroenVinke** [comment]
[This](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/9464ec605eececfd80dc0dc413804444648d433f/sample/config.js) is the old config.js

We had two libraries that depended on isarray, one that depends on 0.0.1 and one that depends on 1.0.0, which causes jspm to install a fork. So we needed to find what depended on isarray@0.0.1:

![imgur](http://i.imgur.com/2Ttc2dg.png)

Then we find out what depends on `npm:readable-stream@1.1.13`:

![imgur](http://i.imgur.com/VoA3hH4.png)


Then what depends on `npm:stream-browserify@1.0.0`:

![imgur](http://i.imgur.com/Q5jtmDc.png)

then what depends on `github:jspm/nodelibs-stream@0.1.0`:

![imgur](http://i.imgur.com/TlGlgUP.png)

then what depends on `npm:nopt@2.1.2`:

![imgur](http://i.imgur.com/aAeeObv.png)

and finally, what depends on `npm:js-prettify@1.4.0`:

![imgur](http://i.imgur.com/RmF4N25.png)

Here we find that prettify is the villain

**Comment by adriatic** [comment]
This is a case of traversing the tree upstream - which would be a lot simpler if we can invert the tree first :-) 

Some possibly incorrect transitions in this logic

1 to 2  is correct only if the `readable stream` is the only entity declaring direct dependency of `isarray@0.0.1`

... and so on

I am writing this to you not to teach you logic or even tree traversal algorithms, but rather to indicate that creating an Aurelia specific tool that handles all such issue (version matching, consistency,...) might be of the added services that make a wide set of Aurelians happy. According to Rob, that is very true.

See **[ACT design ideas](https://github.com/aurelia-ui-toolkits/screenshots/issues/14)** if you have not yet.
