### ISSUE TITLE
About page needs some improvements

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#397]
In a typical browser size, there is too much accent on the "marketing data"

![image](https://cloud.githubusercontent.com/assets/2712405/13511615/e1e23796-e163-11e5-9d70-5c0f14bde3fc.png)

I would like to shrink the size of the area from the top to the Example label. As this may result with unreadable of that areaL

![image](https://cloud.githubusercontent.com/assets/2712405/13511713/46c2cee6-e164-11e5-9ad4-eabc129e823b.png)

I would propose to split this page horizontally in two halves, put each half in its own tab and make the upper part be the tab selected by default

**Comment by JeroenVinke** [comment]
@adriatic finished this
