### ISSUE TITLE
KendoUI catalog app tutorials need improvements

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#399]
At least one user seemed completely confused with the current tutorials that are equally split between app developers tutorials and bridge developers tutorials.

#### I am proposing this new approach:

Uncouple the bridge developers tutorials from app developers tutorial by:
1. Creating **new** app developers tutorials use the **real** KendoUI bridge (instead of the **mini-bridge** that is created in the process of running the bridge developers tutorial and supports("wraps" just a few (autocomplete, button, chart and bridge) components.
2. Using the current / old app developers ___finished___ tutorial in the **new** bridge developers tutorial **embedded* application - just as we use **[sample](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/tree/master/sample)** in the process of developing **real** bridge

The item 1 above becomes a lot more important than 2 as all KendoUI controls are all wrapped due to @JeroenVinke's heroic effort that I am still trying to comprehend -- so there is a little chance that we will need a new person to join the KendoUI bridge team and benefit from this bridge development tutorial

**Comment by adriatic** [comment]
### New developers tutorial

#### Section 1

**Enhancing standard Aurelia Skeleton Navigation app**

1. Start by fetching **[ES2016 variant](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-es2016)** of Aurelia's **[skeleton navigation](https://github.com/aurelia/skeleton-navigation)** application.

2. Connect this app with the KendoUI bridge using the **[KendoUI Core](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/core)** installation process.

3. Add autocomplete, button and tabstrip KendoUI components

#### Section 2

1. Upgrading the app built in **section 1** to a more complex app that uses only KendoUI components by replacing the Bootstrap UI elements from Aurelia's **[skeleton navigation](https://github.com/aurelia/skeleton-navigation)** with KendoUI components (nav-bar mainly)

2. Demonstrate how to upgrade the app to use the KendoUI PRO version (hopefully we will be able to advise the users to fetch the KendoUI trial version with **[vendors](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/vendors)** installation method

**Comment by JeroenVinke** [comment]
Great idea, and I think it's good that we get rid of the mini bridge for the reasons you mentioned. Can we just create one tutorial for Kendo core? I currently do not see the added value of upgrading that to Kendo PRO and replacing the bootstrap controls. In my opinion, the goal is to provide a tutorial on how to download skeleton navigation, how to install the bridge and how to get exactly "drop in custom elements" by giving some examples.

**Comment by adriatic** [comment]
> I currently do not see the added value of upgrading that to Kendo PRO and replacing the bootstrap controls

I listed that since I would value such data if I would be user of our bridge. This information might better fit in the README files in https://github.com/aurelia-ui-toolkits/kendoui-templates-repository (that has yet to be creeated)

**Comment by JeroenVinke** [comment]
ok then :+1:

**Comment by JeroenVinke** [comment]
I would not put that in the README of that repository though, I doubt anyone will find it there

**Comment by adriatic** [comment]
> I would not put that in the README of that repository though, I doubt anyone will find it there

This is a misunderstanding due to the use of "this" and "that" references - I will straighten this out once I implement the new tutorials defined next (below)

**Comment by adriatic** [comment]
### Definition of the new tutorials (for 0.5.1 Catalog app)

@JeroenVinke writes:
> we should keep in mind that there are two kinds of people, the ones that want to get it setup quickly and the ones that want to follow a tutorial
We got that "the ones that want to get it setup quickly" covered so the tutorial should cover the other use case.

1. Tutorial which guides people into cloning the skeleton-navigation, installing **[kendo core]()** and adding a few components from that (core) SDK.

2. Tutorial which guides people into cloning the skeleton-navigation,installing KendoUI Pro SDK using **[vendors](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/vendors)** approach and add grid and chart.

3. Explain the **[repository of all 4 flavors of aurelia setup](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/392)** where our plugin is already installed so people can refer to that.

**Comment by JeroenVinke** [comment]
Perfect

**Comment by adriatic** [comment]
Based on the above defined plan for **[bridge app developers tutorials](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_tutorials/1._introduction)**, the **[repository of all 4 flavors of aurelia setup](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/392)** will contain 8 samples by creating each of the original Navigation Skeleton samples:

![image](https://cloud.githubusercontent.com/assets/2712405/13551000/e2225a56-e2f8-11e5-853e-375bb4ce9c91.png)

In two flavors by either adding a few components from KendoUI core or KendoUI Pro collection. (___make a reference to [this document](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/help/docs/app-developers-notes/loading-subset-of-controls.md)___)

**Comment by JeroenVinke** [comment]
lets keep the vendors folder for PRO skeletons empty though, that can be downloaded as a trial from the Telerik site. Otherwise the repo would be quite large

**Comment by adriatic** [comment]
Yes, that way we cannot be guilty of actively pushing illegal substance :-)

**Comment by adriatic** [comment]
Aurelia just added Webpack based Navigation Skeleton, so I will add that as well

**Comment by JeroenVinke** [comment]
As this has been implemented by @adriatic, but only webpack is missing, I created https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/471 instead
