### ISSUE TITLE
Display for number of downloads in README misbehaves

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#400]
Here is the screenshot showing the problem:

![image](https://cloud.githubusercontent.com/assets/2712405/13533074/c8f2e8ae-e1fc-11e5-8c33-59bf87d19009.png)

This (downloads) entry is either completely invisible, in the state shown above, or present showing the number of downloads.

**Comment by JeroenVinke** [comment]
yeah it fails sometimes, not sure why. I like it though so i'd hate to remove it

**Comment by adriatic** [comment]
No suggestions for removal from me :-)

**Comment by JeroenVinke** [comment]
We are not the only one with issues :smile: 

![image](https://cloud.githubusercontent.com/assets/2189477/13534336/f27891f0-e234-11e5-881a-e87c6d002411.png)

So we'll just wait and hope for the problem to fix itself
