### ISSUE TITLE
Diagram component occasionally leaves "garbage" on the screen

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#401]
___This cannot be a bridge's component problem - it is very likely the problem with the native control. If it can be reproduced, it should be reported to Telerik (Petyo)___

I was playing with

![image](https://cloud.githubusercontent.com/assets/2712405/13534312/8b35b61c-e202-11e5-852c-8c0f6b42e03f.png)

then deleted the box shown as rotated above - resulting with the box gone and the "connection line" remaining. At that point I reloaded the whole bridge and saw this;

![image](https://cloud.githubusercontent.com/assets/2712405/13534447/2cdb73c6-e203-11e5-9666-58ba531422c6.png)

This connection can be selected and deleted:

![image](https://cloud.githubusercontent.com/assets/2712405/13534502/7c0e7e70-e203-11e5-87ea-72f32d29f6d0.png)

On subsequent refresh, that line was still rendered - but it was clear that it was not a part of the diagram as it was "glued" on the same spot, disregarding my subsequent interactions with the diagram

Today, this did not happen - instead I got this (correct view)

![image](https://cloud.githubusercontent.com/assets/2712405/13534615/00336ce2-e204-11e5-861b-fbe072703bff.png)

**Comment by JeroenVinke** [comment]
Yeah I'm seeing this too but I don't think it qualifies as a bug. The line not being removed after removing a box is clearly a design decision and after a refresh the line has nowhere to go so it draws it to a random location. Not pretty, but I don't think it's a bug either. The location of the boxes are not saved so it is not weird that the location of the lines aren't either

**Comment by adriatic** [comment]
> The line not being removed after removing a box is clearly a design decision and after a refresh the line has nowhere to go so it draws it to a random location.

That is not the problem I am trying to define - the line became completely detached from any of the diagram elements and would stay on the same spot despite scrolling.

**Comment by JeroenVinke** [comment]
A support ticket should be opened with telerik (not us) if someone sees this as a bug
