### ISSUE TITLE
Each section of the catalog app needs to be "URL addressable"

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#403]
This feature will be very helpful for support - as we could simply answer most questions in Gitter chatroom by saying `please check this` and continue from there. Either the reference will be sufficient, or will gather what other information needs to be added to online help section.

At the moment, the most important routing change would be to include the "top level entries" in the sidebar as shown below

![image](https://cloud.githubusercontent.com/assets/2712405/13551318/958305d2-e303-11e5-86c1-8cf49e123874.png)

Less urgent by still needed are Component catalog `categories` - see screenshot below:

![image](https://cloud.githubusercontent.com/assets/2712405/13551331/6acf15aa-e304-11e5-9542-186ca588b731.png)

**Comment by adriatic** [comment]
## Most important problem 

in this same issue #403 issue is visible by pointing the browser to `http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation` page and observe how to url tracks the clicks on the three tabs on that page. However if you use any of those urls and make the browser to point to that url - you will get the "base page" that is referenced by http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation.

**Comment by JeroenVinke** [comment]
Both the documentation and installation instructions are gitbooks now, so this issue is no longer relevant
