### ISSUE TITLE
kendoui elements not initializing on first load

### ISSUE THREAD

**Issue by geea789** [aurelia-ui-toolkits/aurelia-kendoui-bridge#406]
I have integrated the kendoui bridge with aurelia typescript application, however, once i start the app the kendoui elements are not loading. Only after i navigate the router the templates are loading. 

Any ideas on how to fix / debug further into this?

**This is before navigation:**
![screenshot from 2016-03-08 11 12 58](https://cloud.githubusercontent.com/assets/6891047/13597141/7540a4c8-e51f-11e5-809d-029559a5b298.png)

**This is the html without the divs (also before navigation)**
![screenshot from 2016-03-08 11 13 15](https://cloud.githubusercontent.com/assets/6891047/13597142/75419a86-e51f-11e5-803e-710ddd462afa.png)

**This is the html after navigation**
![screenshot from 2016-03-08 11 15 17](https://cloud.githubusercontent.com/assets/6891047/13597143/7542e972-e51f-11e5-85ea-e89773395354.png)

**Comment by JeroenVinke** [comment]
Yeah sorry, this seems to be a bug in Aurelia: https://github.com/aurelia/templating/issues/284#issuecomment-193628568

Some potential workarounds: :point_up: [8 maart 2016 08:02](https://gitter.im/adriatic/Aurelia-KendoUI?at=56de78e9817dfa1e41ed3d5d). I haven't tried these myself yet.

**Comment by JeroenVinke** [comment]
@geea789 perhaps the change in 0.5.1 will fix it for you. Can you check?
