### ISSUE TITLE
k-sortable property on grid collisions with k-sortable control

### ISSUE THREAD

**Issue by sirudog** [aurelia-ui-toolkits/aurelia-kendoui-bridge#409]
As the title says. The issue can be checked by visiting http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/basic-use

This grid is configured to be sortable:
`<k-grid` k-data-source.bind="datasource" k-pageable.bind="pageable" **k-sortable.bind="true"**>

I have checked it both in Chrome and Firefox

**Comment by JeroenVinke** [comment]
Tracking in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/412
