### ISSUE TITLE
Implement Spreadsheet

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#41]

**Comment by JeroenVinke** [comment]
We need to take a look at bundling when we add the spreadsheet, because adding the spreadsheet to the bundle caused the bundling process to get stuck

**Comment by adriatic** [comment]
I believe that we need to take a deep, long look at bundling irrelevant of the context it is applied to - as it should be a straightforward process with completely reliable outcome.

**Comment by JeroenVinke** [comment]
Also, I believe this control didn't exist in the 2015 version, so we can't load it via the pro() function of the config-builder

**Comment by JeroenVinke** [comment]
:rocket:
