### ISSUE TITLE
Highlighting search term

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#410]
Hi,

I'm using serverFiltering with client side grouping and was wondering how I can highlight the portion of text that was searched for in the results?

Thanks,
Jason

**Comment by JeroenVinke** [comment]
Not sure. Is this possible without the bridge? We simply wrap the Kendo controls so you could look for info in Teleriks forums/documentation. Then by adding the `k-` prefix you can use the option. More info about this translation is documented here: http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_tutorials/7._what_you_need_to_know

**Comment by jasonhjohnson** [comment]
Gotcha.

**Comment by smccrea** [comment]
Here is a link to the Telerik example [Highlight Matched Values](http://docs.telerik.com/kendo-ui/controls/editors/autocomplete/how-to/highlight-matched-values) for the autocomplete

**Comment by jasonhjohnson** [comment]
@smccrea In this example they use the template parameter on the JavaScript object itself along with some other weirdness inside the template that I'm not sure how I'd do the Aurelia-KendoUI way. Any ideas how to translate it?

**Comment by jasonhjohnson** [comment]
The following works but doesn't feel very Aurelia:

```javascript
onDataBound(e) {   
        let autocomplete = e.sender;

        var userTxt = autocomplete._prev.toUpperCase();
        var listItems = autocomplete.ul.children();

        if (listItems.length > 0 && userTxt.length > 1) {
            $(listItems).each(function (i, e) {
                var liTxt = $(e).text().toUpperCase();
                var highlightedTxt = "<strong style='color:blue;'>" + userTxt + "</strong>";
                e.innerHTML = liTxt.replace(new RegExp(userTxt, "g"), highlightedTxt);
            });
        }           
    }
```

**Comment by adriatic** [comment]
It doesn't solely because of packaging - as you could implement this as an additional custom attribute for autocomplete component and then it would look completely like Aurelia :-)

We would like to encourage you (and many other users of KendoUI bridge)  to consider contributing to this project as such approach is the best way to ensure that KendoUI bridge will continuously evolve becoming better and better. There are already "rumors" how using this bridge makes people a lot more productive than using KendoUI native controls.

**Comment by JeroenVinke** [comment]
OK, while messing with this sample I noticed that the template was compiled with a string as context (the name of the country). There was no way to bind to this from the template, which reminded me of the bug in aurelia where `<templates>` compiled with `enhance` do not support $item. I was able to create a $$item property though, that points to the object context: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/0.6.0/src/common/template-compiler.js#L104.

So with that in place I was able to put together the sample: [html](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/0.6.0/sample/src/samples/autocomplete/highlighting.html), [js](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/0.6.0/sample/src/samples/autocomplete/highlighting.js)

![image](https://cloud.githubusercontent.com/assets/2189477/13702521/9e62fe7e-e78f-11e5-8915-4bfefc280dcb.png)

So this should work as soon as we release 0.6.0
