### ISSUE TITLE
The KendoUI SDK (core / pro) installation data is not current

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#411]
I am talking about all three tabs on the **[installation](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/core)** page that needs to be updated with respect to the current Aurelia components versions.

Also, I do not believe that it is good practice to instruct our customers to edit the `config.js` file - they should edit the `package.json` file and then run `jspm install` right after that.

config.js should not be even "visible" to humans - it's a private data shared between jspm and systemjs loader.

**Comment by JeroenVinke** [comment]
> Also, I do not believe that it is good practice to instruct our customers to edit the config.js file - they should edit the package.json file and then run jspm install right after that.

Aurelia keeps the paths mappings in config.js, not in package.json (not sure if this is even possible). So users will always have to edit their config.js, unless there is a tool that could do something like that for them. Even if it would be possible to keep the `paths` section in package.json, it would mean that we would have to instruct people to first copy the `paths` section from config.js to package.json, and afterwards have them add a path map to it. We shouldn't make the installation more complex (involve more steps), as they are pretty complex already.

**Comment by JeroenVinke** [comment]
I presume https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/1ac5625d1049ed5e362d6fe002569bee9697287a fixed it. The installation instructions we currently have work, and we'll look for improvements (like setting paths in package.json) in the ACT project
