### ISSUE TITLE
Combobox is importing dropdownlist

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#415]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/src/combobox/combobox.js#L6

should import combobox, not dropdownlist

**Comment by adriatic** [comment]
How did you discover this?

**Comment by JeroenVinke** [comment]
By only loading the combobox in a different project, I noticed that it didn't import the combobox
