### ISSUE TITLE
Line chart basic use example: tooltip does work

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#416]
http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/line-charts

**Comment by JeroenVinke** [comment]
Probably a name collision with the tooltip kendo control

**Comment by JeroenVinke** [comment]
tracking in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/412
