### ISSUE TITLE
Demo with details view and filters

### ISSUE THREAD

**Issue by DanielBengtsson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#418]
We have tried to use the bridge for the KendoUI Grid, but didn't find any easy way to get it work with details view and filters. After some days we gave up and are now implementing it without bridge.
A demo how to implement it the "Aurelia-way" (with detail template and toolbar in HTML) would be very much appreciated.

Something liked 
http://demos.telerik.com/kendo-ui/grid/hierarchy
and
http://demos.telerik.com/kendo-ui/grid/toolbar-template

**Comment by JeroenVinke** [comment]
Hey @DanielBengtsson, thanks for the feedback :+1: 

I just started messing with the toolbar sample, and I added the possibility to configure a toolbar template via html:

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/grid-toolbar/sample/src/samples/grid/toolbar-template.html#L7-L19

![img](http://i.imgur.com/5948TC9.png)

Is this what you meant?

I still have to look into the hierarchical grid sample, so i'll report back on that later

**Comment by JeroenVinke** [comment]
By the way, the code I linked to above won't work just yet, it isn't released yet

**Comment by DanielBengtsson** [comment]
Thank you a lot Jeroen! You're awesome! Yes, it is basically what we are looking for. In our case we have the toolbar at details level (in the hierarchical grid), but I assume it will be the same concept?

**Comment by JeroenVinke** [comment]
It would be awesome if we can get this to work:
```
<ak-grid>
   <ak-template for='detailTemplate'>
     <ak-grid>
     </ak-grid>
   </ak-template>
</ak-grid>
```

Will check this out soon

**Comment by JeroenVinke** [comment]
This should be possible in 0.7.0: http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/detail-template

That sample uses the detailInit event to render a new grid, but you should be able to use `<ak-grid>` in the detailTemplate as I showed above.
