### ISSUE TITLE
Binding the grid and sequencing

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#422]
I'm trying to bind the grid on my view model in the `bind` method like so:

```javascript
 bind() {
        this.datasource = {
            type: 'json',
            data: this.entity.Vehicles,
            pageSize: 10          
        };       
    }
```

The data is bound in the `activate` method of the same view model like:

```javascript
activate(model) {  
        this.service.getSingle(model.Details.PolicyId)         
          .then(entity => {
              this.entity = entity;
              console.log(this.entity)
          });
    }   
```

It seems like the grid is being bound too soon and this.entity isn't available yet. I'm not sure how to sequence things so that the grid isn't bound until the data is ready. Any thoughts?

Probably not relevant but here's my grid:

```
 <k-grid k-data-source.bind="datasource"
                        k-pageable.bind="pageable"
                        k-scrollable.bind="false"
                        k-sortable.bind="true"
                        k-editable="popup"
                        k-selectable="true"
                        k-on-data-bound.delegate="onBound($event.detail)"
                        k-on-change.delegate="onSelect($event.detail)">    
```

Thanks,
Jason

**Comment by adriatic** [comment]
In what way is your need different from **[this example](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/binding-to-remote-data)**

**Comment by JeroenVinke** [comment]
Hey Jason,

When you say `data: this.entity.Vehicles,`, there is actually no binding whatsoever between the data of the datasource and the Vehicles array of `this.entity`. The value gets copied and the reference is gone. So when you say `this.entity = entity` in `activate()` the datasource does not know anything has changed.

I would do this like so:

```
export class BasicUse {
  datasource = new kendo.data.DataSource({
    type: 'json',
    pageSize: 10
  });

  activate() {
    new Promise(resolve => resolve())
    .then(() => {
      let entity = {
        Vehicles: [{ Name: 'a' }, { Name: 'b' }]
      };

      this.datasource.data(entity.Vehicles);
    });
  }
}
```

Note the `new kendo.data.DataSource(` which passes the reference of the datasource to the Kendo control ([more info](http://localhost:3000/#/help/docs/app_developers_notes/1._current_limitations)). Then as soon as you have data you can just call `.data()` on it and it will automatically refresh the grid for you

**Comment by jasonhjohnson** [comment]
Thanks that's exactly what I needed!

**Comment by adriatic** [comment]
@JeroenVinke - your answer is certainly a lot more valuable to @jasonhjohnson than my **[question](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/422#issuecomment-195561092)**

**Comment by jasonhjohnson** [comment]
@JeroenVinke This worked like a charm. Thanks again.
