### ISSUE TITLE
The Aurelia-kendoUI-bridge package from npm contains too much data

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#423]
Discovered in the process of creating the `webpack` version of the tutorial:

Command: `npm install aurelia-kendoui-bridge` results with the "standard" emission of a ton of errors of the kind
```
...
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string(462): fatal error C100 3: error count exceeds 100; stopping compilation [C:\work\aurelia-ui-toolkits\KendoUI\kendou i-templates-repository\skeleton-es2016-webpack-kendo-core\node_modules\utf-8-validate\build\ validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Nikolaj\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nikolaj\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\work\aurelia-ui-toolkits\KendoUI\kendoui-templates-repository\skeleton-es2016-webpack-kendo-core\node_modules\utf-8-validate
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
```
and ends with seemingly correct:
```
aurelia-skeleton-navigation-webpack@0.1.0 C:\work\aurelia-ui-toolkits\KendoUI\kendoui-templates-repository\skeleton-es2016-webpack-kendo-core
└── aurelia-kendoui-bridge@0.6.0  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
```

### Issue 1
Unlike all other entries in `node_modules` that are rendered as links to folders,the newly added `aurelia-kendoui-bridge` is shown as a real folder (no idea what that means)

![image](https://cloud.githubusercontent.com/assets/2712405/13724328/c9673192-e84f-11e5-90b7-408dc733b68b.png)

### Issue 2
The content of `aurelia-kendoui-bridge` folder hasz way too much stuff - it is identical to the content of the aurelia-kendoui-bridge GitHub repository:

![image](https://cloud.githubusercontent.com/assets/2712405/13724380/a91036da-e851-11e5-8760-2e15069fb394.png)

**Comment by JeroenVinke** [comment]
you shouldn't install it through npm but through jspm: `jspm install aurelia-kendoui-bridge`, which gets the bridge from npm servers, but only takes what it needs

**Comment by adriatic** [comment]
Note my problem report: Extending the es2016-webpack sample to use Aurelia-KendoUI bridge fails #344

**Comment by JeroenVinke** [comment]
This seems to be normal for Webpack
