### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by alexsurg** [aurelia-ui-toolkits/aurelia-kendoui-bridge#424]
Hi,

I just upgraded to version 0.5.1 and i noticed that there is a discrepancy with the multi select function naming.
While all the kendo function name are written in Camel Case the multi select function is not:

`plugin('aurelia-kendoui-bridge', (kendo) => {
        kendo.kendoMultiselect()
    })`

notice that the "s" in "select" is in lower case.

Maybe you should change it to be like the rest of the functions.

**Comment by JeroenVinke** [comment]
Thanks for reporting :+1:
