### ISSUE TITLE
Switch back to aurelia's aurelia-tools

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#425]
https://github.com/aurelia/tools/issues/24#issuecomment-197293829

**Comment by adriatic** [comment]
Can you tell me what is this about, please?

**Comment by JeroenVinke** [comment]
A very long time ago I got [this error](https://github.com/aurelia/tools/issues/24#issue-119348364) when I ran `gulp prepare-release`. I created a workaround [aurelia-tools](https://github.com/aurelia-ui-toolkits/tools) and we've used that since. That error just got fixed so I switched it back to the original aurelia-tools

**Comment by adriatic** [comment]
WOW - I had no idea about any of this. Thanks
