### ISSUE TITLE
Setting columns->filterable->cell->operator

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#427]
Hi,

I'm trying to set the filterable properties as defined here: http://demos.telerik.com/kendo-ui/grid/filter-row.

I'm not sure how to access this property. I tried something like:

`<ak-col k-title="Policy #" k-field="PolicyNo" k-filterable-cell-operator="contains"></ak-col>`

Is this possible?

Thanks,
Jason

**Comment by JeroenVinke** [comment]
`k-filterable.bind="{ cell: { operator: 'contains' } }"`

**Comment by jasonhjohnson** [comment]
@JeroenVinke perfect. thanks.
