### ISSUE TITLE
Button with custom behavior 

### ISSUE THREAD

**Issue by SamuelCaudenberg** [aurelia-ui-toolkits/aurelia-kendoui-bridge#429]
Hi,

I'm trying to create a button in a grid with custom behavior (eg log in console when button is clicked).
I can't find any documentation on how to do this, nor can I get it to work myself.
Can anyone provide me with a working example please?

Thanks in advance

```
<k-grid id="reservations" k-on-data-bound.delegate="onInventory()" k-pageable.bind="pageable" k-sortable.bind="true" k-selectable="row" k-editable.bind="true">
        <k-col k-title="No.Pack" k-field="NoPackagings"></k-col>
        <k-col k-title="Packaging" k-field="Description"></k-col>
        <k-col k-field="Quantity"></k-col>
        <k-col k-field="Unit"></k-col>
        <k-col k-title="Lot" k-field="LotCode"></k-col>
        <k-col k-title="Location" k-field="LocationCode"></k-col>
        <k-col k-field="Status"></k-col>
        <k-col k-template='<a class="k-button" onclick="return onInventory()">Inventory</a>' k-title="" ></k-col>  <!-- href="\\#" onclick="return Inventory()" --> 
                                                <!--onInventory not defined-->
    </k-grid>
```

**Comment by JeroenVinke** [comment]
http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/advanced is a sample that uses a button.

So the following should work:

```
<ak-col>
      <ak-template>
        <button ak-button click.delegate="showAlert('Button clicked')">Test</button>
      </ak-template>
</ak-col>
```

You may want to update to the latest version of aurelia-kendoui-bridge. There is a breaking change though: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/releases/tag/0.6.0

**Comment by SamuelCaudenberg** [comment]
I updated to the latest version and one of my other buttons in the application broke.
I will attempt to fix this button now and implement the button in my grid.
I will keep you posted.

**Comment by SamuelCaudenberg** [comment]
Everything is working perfectly now
Thanks =)

**Comment by JeroenVinke** [comment]
Great! :+1:

**Comment by danielmeza** [comment]
I can do the same whit any element on a ListView template like `
<ak-list-view k-data-source.bind="dataSource">
        <ak-template>
            <div style="height:50px;position:relative;cursor:pointer" click.delegate="OnConversationClick($this)">
                <div class="chat-conversation-icon-subject">
                    <i class="${Subject.CssIcon}"></i>
                </div>
                <div class="chat-conversation-subject">
                    <div style="width:100%">
                        <strong class="pull-left">${Subject.Name}</strong><span class="pull-right">${LastConversationDate | chatDateFormat: 'dd/mm h:mm tt'}</span> <br />

                        <span class="">${LastMessage}</span>
                    </div>
                </div>
              
            </div>
        </ak-template>
    </ak-list-view>
`

**Comment by JeroenVinke** [comment]
@danielmeza do you mean that it doesn't work?

if so, please open a new issue and create a gist.run ([instructions](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help)). That allows us to help you more quickly

**Comment by danielmeza** [comment]
@JeroenVinke My apologies, I've edited the comment.

**Comment by JeroenVinke** [comment]
@danielmeza you are hitting [this bug](https://github.com/aurelia/templating/issues/318)

the workaround is to wrap everything inside an `ak-template` in a `<div></div>`: https://gist.run/?id=ad06ecfdc8d7dff7e80e7673c78aac84
