### ISSUE TITLE
Config-builder broke with latest Aurelia (March 23rd) release.

### ISSUE THREAD

**Issue by Souldrinker** [aurelia-ui-toolkits/aurelia-kendoui-bridge#430]
After updating to the latest Aurelia release (2016-03-23) the kendo-ui-bridge won't work anymore, and looks for the resources in the app root folder rather than the kendo plugin folder causing 404 errors.

Changing the resources from ```this.resources.push('grid/grid');``` to ```this.resources.push('./grid/grid');``` in the config-builder.js seems to fix the issue.

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/5c0edd6b79d6012fa1a2215da6ebcea5766dccaa

**Comment by JeroenVinke** [comment]
Released in 0.6.2. Thanks for debugging and sorry for the delay
