### ISSUE TITLE
Datepicker click event

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#435]
Hi,

I'm experiencing an issue with the date selection closing the containing bootstrap `dropdown` element as described here: http://stackoverflow.com/questions/21307246/prevent-datepicker-from-closing-a-parent-dropdown.

How would I implement this solution with the aurelia-kendoui-bridge?

Thanks,
Jason

**Comment by JeroenVinke** [comment]
what about 
```
<input ak-datepicker="k-value.bind : '10/10/2000'" click.delegate="stopPropagation($event)"/>

stopPropagation(e) {
 e.stopPropagation();
}
```

**Comment by jasonhjohnson** [comment]
@JeroenVinke That didn't seem to work. That event doesn't get fired.

**Comment by JeroenVinke** [comment]
https://gist.run/?id=e2769b4244d71d2f27e87961f90d6574 seems to work. please reopen the issue if you want to keep working on this

**Comment by jasonhjohnson** [comment]
@JeroenVinke This did it for me. Thank you very much.
