### ISSUE TITLE
WebpackLoader fails trying to import css files

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#437]
**Note** this issue may be related to https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/428#issuecomment-201782189

**Note** Issue https://github.com/aurelia/webpack-plugin/issues/11 is a duplicate of this.

***
I am getting error message **`cannot read property fetch of undefined`** in the _import function as shown below
```
WebpackLoader.prototype._import = function _import(moduleId) {
    var _this = this;

    var moduleIdParts = moduleId.split('!');
    var path = moduleIdParts.splice(moduleIdParts.length - 1, 1)[0];
    var loaderPlugin = moduleIdParts.length === 1 ? moduleIdParts[0] : null;

    return new Promise(function (resolve, reject) {
      try {
        if (loaderPlugin) {
          resolve(_this.loaderPlugins[loaderPlugin].fetch(path));    <---- cannot read property fetch of undefined
        } else {
          __webpack_require__.e/* nsure */(1, function (require) {
            var result = __webpack_require__(85)("./" + path);
            if (typeof result === 'function') {
              result(function (res) {
                return resolve(res);
              });
            } else {
              resolve(result);
            }
          });
        }
      } catch (e) {
        reject(e);
      }
    });
  };
```

I believe that this is taking place in app.html
```
<template>
  <require from="nav-bar.html"></require>
  <require from="bootstrap/dist/css/bootstrap.css!">

  <require from="kendo-ui/styles/kendo.common.min.css!"></require>
  <require from="kendo-ui/styles/kendo.bootstrap.min.css!"></require>

  <nav-bar router.bind="router"></nav-bar>

  <div class="page-host">
    <router-view></router-view>
  </div>
</template>
```

This is further the consequence of the fact that `kendo-ui` reference is undefined, because I do not know how to define it - the app.html is a standard part of our bridge code, and in the case of jspm/systemjs setup, this "path component" is defined in the file config.js, processed by systemjs:

```
  paths: {
     ...
    "kendo.*": "jspm_packages/github/kendo-labs/bower-kendo-ui@2016.1.217/js/kendo.*.js",
    "kendo-ui": "jspm_packages/github/kendo-labs/bower-kendo-ui@2016.1.217/*"
  },
```

Should this be defined in the `resolve` section of `webpack.config.js`??
```
  resolve: {
    root: [
      path.resolve('./src'),
      path.resolve('./vendors/telerik.kendoui.2016.1.226.core/js')
    ]
```

**Comment by martijnboland** [comment]
Requiring a css file from the template means that it will be loaded by the aurelia loader. It's pretty hard to bundle all these files so aurelia can load these dynamically. Much easier is to import the css styles from the .js file (app.js). This way, webpack can resolve the dependencies itself without needing the help of aurelia's webpack plugin.

**Comment by adriatic** [comment]
Your comment, coming from the person that understands the details of the webpack's expected "cooperation" with aurelia loader certainly makes the perfect sense in this situation. This specific situation is not even "dynamic" in the sense described at http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_notes/3._lazy_loading_wrappers (disregarding the fact that this example deals with loading a javascript module, not css file) -- since app.js is the "root" of the whole tree and as such always loaded. 

If the above sentence is too long, my message is: **thank for for continuous care, I will try the change you proposed and let you know the outcome**.

**Comment by Thanood** [comment]
When dealing with loading css styles from a js file: how would you do that "loader independent"? I mean, loading with systemjs, you'd use something like this:

```javascript
import 'bootstrap.css!';
```

Which invokes systemjs` css loader. With webpack I managed to load a css file without the exclamation mark (it's configured to load ```/.css/``` with its css loader). Can you tell webpack to load ".css!" or what is the best way to achieve this?

Btw. when I tried this with webpack, it bundled that css file (according to console output) but didn't find it during runtime.

I'm afraid I cannot put up a repo and reproduce that behaviour right now.

**Comment by JeroenVinke** [comment]
@Thanood Good point

**Comment by adriatic** [comment]
If @Thanood is right saying that `import 'bootstrap.css!';` invokes systemjs loader and that it confuses webpack, that would be very easy for me to test and report back here.

**Comment by sickboy** [comment]
@adriatic I think @Thanood describes how the situation works when you use System.JS (having to use the trailing '!').
Not that it is using SystemJS and confusing webpack.

@martijnboland since we also load html files from html files (by using <compose etc) I think it's important that the loading of resources (incl .css) will work fine from html files.
The files are also automatically bundled by webpack, I can see them in my bundle. All .css and .html files from my app seem to get bundled appropriately.
But refering them from my html files, the loader fails to find them for some reason.

Somehow the aurelia (webpack) loader should be patched so that it uses the same logic as import/require does in js files.

**Comment by charlespockert** [comment]
Have you tried removing the exclamation point? Webpack uses a format which
expects the plugin name before the ! and therefore you will get load
failures for CSS.

You will need to do this in both js/ts files and HTML files as aurelia will
invoke the web pack loader when trying to resolve view resources

**Comment by adriatic** [comment]
@charlespockert 
> Have you tried removing the exclamation point? 

That is the very first thing I tried - same outcome though. I tried even some rain-dances and bat's blood - still no help.

**Comment by Thanood** [comment]
Rain dances only work when you're naked and bat blood must be boiled.

Also I can confirm that webpack bundles the referenced files (if I interpret the log correctly) but at runtime it doesn't find them inside the bundle.

**Comment by ggrimbert** [comment]
Hi,

I found a little workaround to get the app showing : 

in app.html comment the following lines : 
```
  <require from="bootstrap/dist/css/bootstrap.css!"> 

  <require from="kendo-ui/styles/kendo.common.min.css!"></require> 
  <require from="kendo-ui/styles/kendo.bootstrap.min.css"></require>
```

then rebuild, the app show, I have access to kendoui autocomplete without errors.
But the button page fails, having te following error : 
```
aurelia-logging-console.js:80 ERROR [app-router] Error: Failed loading required CSS file: kendoui/button/button.css
    at fixupCSSUrls (webpack:///./~/aurelia-templating-resources/dist/commonjs/css-resource.js?:28:11)
    at eval (webpack:///./~/aurelia-templating-resources/dist/commonjs/css-resource.js?:63:14)
```


In debug, it happens to fail here : 
```
![image](https://cloud.githubusercontent.com/assets/15869188/14557975/2954ea7a-0300-11e6-9bd0-d286ef9bf9e9.png)
```
Here, this.address ha the following value : "kendoui/button/button.css"
The weird thing is that after failing to read the css, the file appears in the sources  : 
```
![image](https://cloud.githubusercontent.com/assets/15869188/14558035/7c755154-0300-11e6-9501-73d07f06b2fd.png)
```
The error fails the loading of the page and then no navigation is available.

**Comment by JeroenVinke** [comment]
@ggrimbert I am not sure why it's trying to load button.css. Normally we only use minified .js and .css files

**Comment by JeroenVinke** [comment]
Got it running, continuing in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/567

**Comment by dkent600** [comment]
I never saw an answer to @Thanood's  question "Can you tell webpack to load ".css!" or what is the best way to achieve this?"  What format will work for both system.js and webpack?

**Comment by JeroenVinke** [comment]
@dkent600 out of the box? I don't think there is such format. Maybe there is a webpack plugin that fixes the import statement out there, or you could write your own.

**Comment by dkent600** [comment]
@JeroenVinke Do you know what plugin writers do to enable a plugin to load its own css files and also be bundleable&loadable with both webpack and jspm/system.js?

**Comment by JeroenVinke** [comment]
@Thanood do you have any thiughts?

**Comment by Thanood** [comment]
Not exactly, but when I remember correctly you can tell loaders to match any regex.
So if you create a regex to match `styles.css!` and set that as a rule for the `css-loader` (or `style-loader`) then it could work for webpack.
