### ISSUE TITLE
List of files with ak-upload

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#438]
Hi,

How do I get the list of attached files from ak-upload component when submitting a form?

Thanks,
Jason

**Comment by JeroenVinke** [comment]
you'd have to know how to do this in native kendo first, perhaps with an event? http://docs.telerik.com/kendo-ui/api/javascript/ui/upload#events

**Comment by jasonhjohnson** [comment]
@JeroenVinke I did something like
```javascript
onSelect(item) {        
        this.files.push(item.files[0]);   
    }

    onRemove(item) {
        let toRemove = this.files.find(x => x.uid == item.files[0].uid);
        this.files.splice(this.files.indexOf(toRemove), 1);   
    }
```

This works I just wasn't sure if this was the native way to accomplish it.

**Comment by JeroenVinke** [comment]
you'd think that Kendo's upload control keeps a list internally:

```
<ak-upload k-widget.two-way="upload">
  <input name="files" type="file"/>
</ak-upload>

<button ak-button click.delegate="logUpload()">Test</button>

logUpload() {
 console.log(this.upload);
}
```

if you can't find a list of files there I would stick to your current solution

**Comment by JeroenVinke** [comment]
I'd recommend to open a Telerik uservoice if you want to have this feature in the Kendo control suite. Perhaps they know of a workaround (for angular maybe?) and we can port that to Aurelia
