### ISSUE TITLE
Template and Virtualization (Dropdownlist, Autocomplete...)

### ISSUE THREAD

**Issue by Creadigme** [aurelia-ui-toolkits/aurelia-kendoui-bridge#440]
Hello,

I have an issue with virtualization and templating used by DropDownList / Autocomplete / MultiSelect (etc)  : 

Template seem to bug when virtualization is used. Wrong data is displayed.

Tested with **0.6.2** and Kendo Pro 2016.1.**226+SP1** and 2016.1.**322**.

To reproduce : 

1. Go to : http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/dropdownlist/virtualization
2. Look at the first row : "Vins et alcools Chevalier".
3. Scroll to the bottom of the dropdownlist.
4. Scroll to the top : "Ernst Handel, Austria" in the first row (!).
5. Select "Ernst Handel,Austria", "Vins et alcools Chevalier" is selected (!).

Thanks

**Comment by JeroenVinke** [comment]
@underlog

I am seeing that when you enable virtualization (on the dropdownlist for example), angular's `compile` hook sometimes gets called with elements that do not have the item template, but html from previous compiles. Is this expected? Also, I am unsure but shouldn't the `cleanup` hook be called too? 

To reproduce, open [this page](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/dropdownlist/virtualization) and input the following code in the console:

```
var ptr = kendo.ui.Widget.prototype.angular;
kendo.ui.Widget.prototype.angular = function (_event, _args) {
  if (_event === "compile") {
    var args = _args();
    var elements = args.elements;
    for(var i = 0; i < elements.length; i++) {
      console.log(elements[i].outerHTML);
    }
  }

  // call original 
  ptr.call(this, _event, _args);
};
```

![image](https://cloud.githubusercontent.com/assets/2189477/14137698/47b65fb0-f669-11e5-90b6-665bc35d4bfb.png)

**Comment by JeroenVinke** [comment]
By the way, after you input the javascript in the console, you can just scroll through the list (up and down) and it will show

**Comment by underlog** [comment]
I am not the subject matter expert on the murky waters of the editors virtualization; @ggkrustev should be able to help once he's back. From what I see, this sounds like a hard-to-catch case and a potential bug on our side. If we can get a simplified case that demoes the problem with Kendo UI/Angular, we should be able to address it.

**Comment by JeroenVinke** [comment]
That's OK. I have reproduced it with angular: http://dojo.telerik.com/OQayE. If you scroll down (until the virtualization kicks in) and scroll back up again, the first item is different

**Comment by JeroenVinke** [comment]
Not much we can do here as this is a problem with Kendo, so closing this
