### ISSUE TITLE
Kendo Pro won't load using "vendors" local file configuration

### ISSUE THREAD

**Issue by srkinyon** [aurelia-ui-toolkits/aurelia-kendoui-bridge#444]
In a chat with adriatic  [here](https://gitter.im/adriatic/Aurelia-KendoUI?at=56fee285d39de41b495fd10d), I asked for help configuring the 'vendor' method because I was getting 404 error when changing from kendo.core() to kendo.pro() in main.ts.

I'm uploading the wwwroot of the project, but it part of a whole VS2015 solution so if the whole project is required, I'll have to make a trimmed down version.
[aurelia-kendo-pro-fail-404.zip](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/files/200524/aurelia-kendo-pro-fail-404.zip)

**Update: **
Here is a full sample solution that has the issue.  It is VS 2015 with the latest ASP.NET.
[Aurelia_kendo_pro_vs2015_sln.zip](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/files/200561/Aurelia_kendo_pro_vs2015_sln.zip)

**Comment by JeroenVinke** [comment]
@srkinyon thanks for the sample solution

So it turns out that the files you got 404's on do exist within kendo, they just aren't real files:

![image](https://cloud.githubusercontent.com/assets/2189477/14225035/5cf03a70-f8b4-11e5-86d5-df0b344687eb.png)

What goes wrong is that the `packages` section in `config.js` is causing SystemJS to load these files with their `ts` extension. So I added an additional package which doesn't use typescript:

 ```diff
  packages: {
    "../src": {
      "main": "app",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        },
        "*.js": {
          "loader": "ts"
        },
        ".html": {
          "loader": null
        }
      }
    },
+    "../vendors": {
+      "defaultExtension": "js"
+    }
  },
```

With this package the page loads:

![image](https://cloud.githubusercontent.com/assets/2189477/14225049/cff1c232-f8b4-11e5-9fa5-5dccc57596d4.png)

**Comment by adriatic** [comment]
@jeroen: how does this solution explain that the app works with kendo-core subset of tke kendo widgets?

**Comment by JeroenVinke** [comment]
Probably because the files @srkinyon was getting 404's on are only used in the PRO version of Kendo

**Comment by adriatic** [comment]
That cannot be the explanation as @srkinyon specifically stated how the **same** app with only changes in `main.js` and `config.js` (`paths` settings) **works** in core and **does not work** in pro.

**Comment by JeroenVinke** [comment]
Switching from `.core()` to `.pro()` will cause the plugin to pull in more files. For example, the `pdf/ttf.min.js` file:

![image](https://cloud.githubusercontent.com/assets/2189477/14225035/5cf03a70-f8b4-11e5-86d5-df0b344687eb.png)

This file (`pdf/ttf.min.js`) is only pulled in whenever a control supports PDF exports. I assume that no Kendo core controls support exports to PDF which is is why this file is not requested with `.core()` but is with `.pro()`

**Comment by adriatic** [comment]
A convoluted but also accurate explanation :-) I did not think about dependencies causing the problem - and I should have since I did not recognize any of the missing module names

**Comment by srkinyon** [comment]
I was able to try this out and it works, thanks!
