### ISSUE TITLE
kendo bridge does not work after upgrade to 0.7.0

### ISSUE THREAD

**Issue by Leonidnei** [aurelia-ui-toolkits/aurelia-kendoui-bridge#446]
We have upgraded today to the latest aurelia version working with babel 6 and to the latest kendo bridge.

Now all controls using the bridge are not displayed while no JS errors appear on the console. (it worked before the upgrade).

Any clue?

**Comment by JeroenVinke** [comment]
what version of the bridge did you update from?

**Comment by Leonidnei** [comment]
From 0.5.0

**Comment by JeroenVinke** [comment]
Please read the info [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/releases/tag/0.6.0). You have to change the prefix of all custom elements and custom attributes from `k-` to `ak-`.

**Comment by Leonidnei** [comment]
Thanks, updating <k- to <ak- helped.

**Comment by JeroenVinke** [comment]
Great :+1:
