### ISSUE TITLE
fyi:  bundler is missing / deploy.js

### ISSUE THREAD

**Issue by disruptiveware** [aurelia-ui-toolkits/aurelia-kendoui-bridge#447]
noticed this whilst running tests on various dockers.  not sure if intentional or otherwise

i.e.-

var gulp = require('gulp');
var jspm = require('jspm');
var exec = require('child_process').exec;

/**
 * Bundle aurelia-framework into one file
 */
gulp.task('bundle', function (done) {

  jspm.bundle(
    [
      'aurelia-bootstrapper',
      'aurelia-http-client',
      'aurelia-dependency-injection',
      'aurelia-framework',
      'aurelia-router',
      'github:zloirock/core-js@0.8.1',
      'github:aurelia/history-browser@0.3.0',
      'github:aurelia/templating-router@0.11.0',
      'github:aurelia/templating-resources@0.10.0',
      'github:aurelia/templating-binding@0.10.0',
      'github:aurelia/loader-default@0.6.0'
    ].join(' + ') + " - core-js",
    'dist/aurelia.js',
    {inject:true,minify:true}
  ).then(done);

});

/**
 * unbundle the aurelia-framework and use separate files
 */
gulp.task('unbundle', function (done) {
  exec('jspm unbundle', function() {
    done();
  });
});

**Comment by JeroenVinke** [comment]
@disruptiveware we talked about this in the chat, can we close this issue?

**Comment by disruptiveware** [comment]
@JeroenVinke ya I mean it would be nice to have a gulp process that minified and concat'd everything.  I'm working on one if you want when I'm finished I can PR... but I know u had said that you automate that... there's just not a prod build type deal for this kit yet
