### ISSUE TITLE
The disable datetimepicker example on the bridge website is not functioning properly

### ISSUE THREAD

**Issue by cdaniel77** [aurelia-ui-toolkits/aurelia-kendoui-bridge#448]
The datetimepicker Disable dates example on the bridge website doesn't seem to be working. When I look at Disable Weekends, all weekends are selectable. Also when I look at Disable Federal Holidays in 2015, I can still select July 4th in 2015

**Comment by JeroenVinke** [comment]
@adriatic can you give us an update on this?

**Comment by adriatic** [comment]
Fixed with 9429c7f1e40abb8267ecb16bbaef8ccbdfca744b
