### ISSUE TITLE
k-format on dates

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#449]
It doesn't appear my dates are being formatted correctly. Given the following:

Markup

```html
<ak-col k-title="Effective" 
        k-field="EffectiveDate" 
        k-format="{0:MM/dd/yyyy}"
        k-filterable.bind="false">                                  
</ak-col>
```
ViewModel:

```javascript
policiesDataSource = new kendo.data.DataSource({
    type: 'json',
    schema: {
            model: {
                fields: {      
                    EffectiveDate: { 
                        type: 'date'                        
                        //template: "#= kendo.toString(kendo.parseDate(EffectiveDate, 'yyyy-MM-dd'), 'MM/dd/yyyy') #"
                    }                   
                }
        }
}

activate() {
[...]
    this.policiesDataSource.data(data); 
},
```

The date from data.EffectiveDate is in the following format:
`EffectiveDate:"09/30/2015 12:00:00 AM"`

The date shows in the grid exactly as it is in my model (includes the time).

Thanks,
Jason

**Comment by JeroenVinke** [comment]
I may be wrong but it could be because the schema is not applied when using .data().

**Comment by jasonhjohnson** [comment]
@JeroenVinke. Is there any way to apply the schema with data()? Or, is there another way (besides using their transport) to load my data in that would honor the schema?

**Comment by JeroenVinke** [comment]
@jasonhjohnson I don't know
