### ISSUE TITLE
Add support for running each of the catalog samples

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#453]
The equivalent statement can be stated using the image below:

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/14397400/25eb415e-fdab-11e5-950c-8cfc012114dd.png"></img>
 <br><br>
</p>

Click on the newly added "RUN" button activates the `gist-run` tool (in a new window), with the specific `gist` as the argument. This implies that there is a prebuilt gist owned by KendoUI Bridge app for all samples for each of the supported Aurelia components in the catalog app.

Just like the `argument` for the API button, the url to the prebuilt gist becomes a part of the `registry.json` file:

```
{
  "title": "Autocomplete",
  "documentation": "http://docs.telerik.com/kendo-ui/api/javascript/ui/autocomplete",
  "samples": {
    "basic-use": {
      "title": "basic use",
      "route": ["", "basic-use"],
      "gist-run-url": "https://gist.run/?id=fa0f189d809a9577661e861b27c5a15e",
    },
    "api": {
      "title": "API",
      "gist-run-url": "https://gist.run/?id=80e5b934a8c696934301ae86e7cc2070",
      "files": ["html", "js", "css"]
    },
    "customizing-templates": {
      "title": "customizing templates",
      "gist-run-url": "https://gist.run/?id=b926d8d58a7f38e6c00dae1a4ca626d7",
      "files": ["html", "js", "css"]
    },
    "events": {
      "title": "events",
      "gist-run-url": "https://gist.run/?id=d8965c0f8e7f2ac747fca9c7dc7189f6"
    },
    "server-filtering": {
      "title": "server filtering",
      "gist-run-url": "https://gist.run/?id=acd80c1a535217e1dbee32153942ace0"
     },
    "virtualization": {
      "title": "virtualization",
      "gist-run-url": "https://gist.run/?id=bbcb2cbf2a2db6edd7adab2054c3779a"
     },
    "grouping": {
      "title": "grouping",
      "gist-run-url": "https://gist.run/?id=78f1e9f838e6b83a631dfa43776b526a"
    },
    "value-binding": {
      "title": "value binding",
      "gist-run-url": "https://gist.run/?id=6e0824daeeaa3098c4829ec07119eb21"
      },
    "highlighting": {
      "title": "highlighting",
      "gist-run-url": "https://gist.run/?id=3802d4c3bccb13a7d9f8dda5060192e3"
    }
  }
}

```

Since the gist-run-url is the function of the **selected example** for the selected control the `sample-runner.html` needs to be changed from it's current form, as the `RUN` button's `href` needs to be set for each selected example (basic use, api, ...). As checked in today, I set the RUN button to point to the same (documentation) url that is constant for the whole `autocomplete` section

**Comment by adriatic** [comment]
I will do this in the run-gist branch to avoid any possible conflicts by holding the master branch hostage

**Comment by JeroenVinke** [comment]
This is done
