### ISSUE TITLE
Add the explanation about using run-git tool in the context of the KendoUI bridge support

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#454]
The information should be presented here:

![image](https://cloud.githubusercontent.com/assets/2712405/14397842/dad8bf90-fdad-11e5-8d59-0b9bc4b8e432.png)

It should start with the simple case, where the question is related to the "isolated" use of a specific component in the bridge. The user should simply fork the gist that already exists for that specific sample of the specific component.

A more complex cases where the folks have an application that uses multiple components (like today's example of destroying a widget that **contains** other widgets, we should create a nice set ot tutorials how to compose a gist and how to make it a part of the issue being reported.

Solved support issues include the gist with the correct solution.

### This scenario should be used as the "model" for a more generic Aurelia support tool that would be used by everyone.

**Comment by JeroenVinke** [comment]
This is in the current catalog
