### ISSUE TITLE
How to maintain the relationship between KendoUI catalog app and the bridge version

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#455]
It is very obvious that the bridge used by the catalog have to correctly support all components presented by the catalog app - meaning that the bridge version number has to be greater or equal of the catalog app version number. This could also be a source of the confusion - as someone know knows that the current bridge version is 0.7.1 might be surprised that catalog shows 0.7.0 - because he / she may not realize that catalog 0.7.0 does not need the fix that bridge 0.7.1 contains.

Adding the support for using gist-run from the catalog (and I am quite sure that we need to provide this functionality and am ready to spend the time to do this) **may** even increase the confusion since we are adding the version of the bundle used by gist-run - which could not be the same version of the released bridge.

The simplest solution might be to add the getVersionString API to the bridge and the bundle, so that both catalog and gist-run can always show the version of the actual runtime (bridge / bundle) is being used.

As a consequence catalog app today would show version 0.7.1, for example

**Comment by JeroenVinke** [comment]
Yeah that could become confusing. But in gists, the catalog and applications using the bridge `config.js` can easily show you the currently installed version.

**Comment by adriatic** [comment]
WOW (love it)
