### ISSUE TITLE
Grid footer columns/aggregates/templates

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#456]
Hi,

I'm trying to sum columns and display the value in the footer. Telerik provides some examples of doing this using aggregates, but, I wanted to see if there was some reference material on accomplishing this with the kendoui-bridge?

Thanks,
Jason

**Comment by jasonhjohnson** [comment]
I found this example of using aggregates (for the TreeView) which was exactly what I was looking for. https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/7a0563f28efbf0e45b39f560e74e073fc2c69ae8/sample/src/samples/treelist/aggregates.html

**Comment by adriatic** [comment]
Note that you can **see* it **[here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/treelist/aggregates)*
