### ISSUE TITLE
Kendo grid datasource not binded from class function

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#458]
Hey guys
I have app.html with Kendo grid, 

1. click on a row  ,going out to service to retrieve data based on Id.
2.data retrieved, and EventAggregator is publish event with the retrieved data.
3. data is published to subscriber in AdditionalInfo.js calss.
4. in AdditionalInfo class  i have another grid that that need to be populate with the income data.
` 
setGameDetails(game) {
        if (game) {
            this.game = game;

            if (this.game) {
                this.datasource = new kendo.data.DataSource({
                    data: game,
                    schema: {
                        model: {
                            fields: {
                                id: {type: 'number'},
                                dateGMT: {type: 'date'},
                            }
                        }
                    },
                    pageSize: 15
                });
            }
        }

    }`

binding to grid not working.
**But when i create the datasource in constructor  of the class the binding goes well**.
Any idea?

**Comment by eliavmaman** [comment]
anyone?

**Comment by adriatic** [comment]
Most likely your issue has to do the problem described **[here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_notes/1._current_limitations)** - but from the amount of information you provided, that is just a guess.

If you expect a more detailed analysis of your issue, please do the following:

1. Extract the minimal subset of your application that still reproduces the behavior of your app.
2. Use this gist,(https://gist.run/?id=3d1b9646fcbe33a58ce7a52a628aab0a) prepared for you and put your application code into this gist (do not forget the update the gist at the moment it demonstrates your issue)
3. Update your problem report (this thread) saying that the gist is ready

**Note:** you can find more information about the GistRun application **[here](https://github.com/gist-run/gist-run/blob/master/README.md)**.

**Note:** the gist referenced in item 2 above is "prebuilt" in the sense that it contains all of the Aurelia bootstraping (see `main.js`) and runtime (see `index.html`)

**Comment by JeroenVinke** [comment]
> Most likely your issue has to do the problem described here - but from the amount of information you provided, that is just a guess.
I think @adriatic is right

What I would do is create a single datasource and just call functions like .data() and .refresh() on that:

```
<ak-grid k-data-source.bind="datasource"></ak-grid>

export class Sample {
   datasource = new kendo.data.DataSource() {};

   setGameDetails() {
     this.datasource.data(newDataArray);
     this.datasource.refresh();
   }
}
```

**Comment by eliavmaman** [comment]
Hey @adriatic and @JeroenVinke .
First ,thanks for the help it is really appreciated.

I've created the Gistrunner program but didnt knew how to connect it to that thread.
any way @JeroenVinke , i did what you sayed, creating datasource  property and call the
`  setGameDetails() {
     this.datasource.data(newDataArray);
     this.datasource.refresh();
   }`

from what i've saw , you cant call refresh on the datasource, **(this line cause an  error )** you have to call it on the grid instance.
and i don't know how to point to grid instance on the class, or worth then that , i don't know if the grid is loaded in the DOM at that time?!

**Comment by eliavmaman** [comment]
This one also not working for
` activate() {
        var self = this;
        this.api.getGameList().then(games=> {
            self.gridData = games;
            self.datasource1 = new kendo.data.DataSource({
                transport: {
                    read: function (options) {
                        if (self.gridData !== '') {
                            options.success(self.gridData);
                        }
                    }
                },
                schema: {
                    model: {
                        fields: {
                            id: {type: 'number'},
                            dateGMT: {type: 'date'},
                            dateMember: {type: 'date'},
                            type: {type: 'string'},
                            action: {type: 'string'},
                            tableName: {type: 'string'},
                            amount: {type: 'number'},
                            bankRollBRC: {type: 'number'},
                            bankRollDollar: {type: 'number'}
                        }
                    }
                },
                pageSize: 15
            });
            self.datasource1.read();
            $('.k-grid').data("kendoGrid").refresh();
        });
    }`
I'm really out of any ideas.. :(

**Comment by JeroenVinke** [comment]
@eliavmaman you can copy the link from the url (after you click the create public gist button) 

![image](https://cloud.githubusercontent.com/assets/2189477/14523634/02416998-0235-11e6-8d55-4cb78fb95a97.png)

**Comment by eliavmaman** [comment]
hope it will work - here is the gist :https://gist.run/?id=1a13e511487755d4ff56a1547d256d1f

**Comment by eliavmaman** [comment]
@JeroenVinke , Here is another Gist https://gist.run/?id=3d1b9646fcbe33a58ce7a52a628aab0a,
I've tried to make it work with your suggestion. 
**(hope you want be mad at me by that but )** i use to work with angular b4 , and binding the grid after retrieving new data was easy.
something here is too difficult here. and i really like the idea of Aurelia and the minimalistic frame work.
please help me stay there.

**Comment by JeroenVinke** [comment]
Yes, you are right in saying that the grid has a refresh function but the datasource has not.

you can do something like this though:

```
<ak-grid k-widget.bind="grid" k-data-source.bind="datasource"></ak-grid>

export class Sample {
 datasource = new kendo.data.DataSource();

 someFunction() {
   this.datasource.read();
   this.grid.refresh();
 }
}
```

**Comment by JeroenVinke** [comment]
or with data:

```
<ak-grid k-widget.bind="grid" k-data-source.bind="datasource"></ak-grid>

export class Sample {
 datasource = new kendo.data.DataSource();

 someFunction(data) {
   this.datasource.data(data);
   this.datasource.read();
   this.grid.refresh();
 }
}
```

**Comment by eliavmaman** [comment]
@JeroenVinke  i wasn't aware of the attr  k-widget.bind, thats what i was i was looked for, but 
in the function `this.grid` is undefined. 
any idea?

**Comment by JeroenVinke** [comment]
Are you running that from the `attached` function? In that case, read [this](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_tutorials/7._what_you_need_to_know). 

you need to delay these things with the taskqueue if you want to run something from `attached()`: 

```
import {TaskQueue, inject} from 'aurelia-framework';
@inject(TaskQueue)
export class Sample {
    constructor(taskQueue) {
        this.taskQueue = taskQueue;
    }
    attached() {
        this.taskQueue.queueTask(() => {
          this.autocomplete.enable(false); // or the grid
        });
    }
}
```

**Comment by eliavmaman** [comment]
@JeroenVinke 
at the end ,the problem was that when the first component published an event, the listener component was got in action with the data.
what's happens then is that the Kendo grid was not available at the time, thats the reason no binding was happens.
what i did is to fire the event after all components were loaded and the fire the event.

**BUT**
I've would expect that if the view model has a property `this.datasource` and you initialize data in it, when the DOM is loaded its suppose to look for  `this.datasource` and then bind it.
What do you think?

**Comment by JeroenVinke** [comment]
> I've would expect that if the view model has a property this.datasource and you initialize data in it, when the DOM is loaded its suppose to look for this.datasource and then bind it.
What do you think?

@eliavmaman could you explain that a bit more?

From what I understand that should work. Could you maybe prepare a gist?

1. Click the run button on any [sample](http://localhost:3000/#/samples/grid/basic-use) we have
2. edit the sample to reflect your situation
3. click "Fork gist" button in the top right corner
4. copy the URL here

**Comment by alastair-mcdonald** [comment]
I had this problem and found the solution by creating a new dataSource and assigning it to setDataSource, as follows...
Here is the grid:

```
<ak-grid k-data-source.bind="datasource"
		 k-pageable.bind="{ input: true, numeric: false}"
		 k-filterable.bind="true"
		 k-sortable.bind="true"
		 k-scrollable.bind="true"
		 k-widget.bind="clientgrid"
		 k-selectable.bind="true"
		 k-on-data-bound.delegate="onDataBound($event)">
	<ak-col k-title="First Name" k-field="firstName" k-width="120px"></ak-col>
	<ak-col k-title="Last Name" k-field="lastName" k-width="120px"></ak-col>
	<ak-col k-title="Email Address" k-field="primaryEmail" k-width="230px"></ak-col>
	<ak-col>
		<ak-grid-command k-name="details" k-text="Details" k-click.bind="details"></ak-grid-command>
	</ak-col>
</ak-grid>
```
And here is the code that updates the dataSource
```
public getClients()
{
	console.log("ClientService.getClients");
	this.clientService.getClients()
		.then(result =>
		{
			this.clientList = result;
			let ds: kendo.data.DataSource = new kendo.data.DataSource({
				data: this.clientList,
				schema: {
					model: {
						id: "id",
						fields: {
							firstName: { type: 'string' },
							id: { type: 'number' },
							lastName: { type: 'string' },
							primaryEmail: { type: 'string' }
						}
					}
				},
				pageSize: 10
			});



			this.clientgrid.setDataSource(ds);
			this.clientgrid.refresh();
		})
		.catch(err => console.log("Error returned from getClients " + err));   
   
}
```
