### ISSUE TITLE
cannot get "context menu" working

### ISSUE THREAD

**Issue by Leonidnei** [aurelia-ui-toolkits/aurelia-kendoui-bridge#459]
Hi.

I'm trying to use context menu from kendoui bridge. When html contains: 
ak-contextmenu.ref="contextVM"

execution throws exception:
No Aurelia APIs are defined for the referenced element.

if I remove the 'ref', the menu is not shown (right-click shows browser's context menu).

How do I use ak-contextmenu.ref?

**Comment by JeroenVinke** [comment]
Have you seen [this](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/menu/context-menu)?

**Comment by Leonidnei** [comment]
Yes, I took that sample as a basis for my code but got "No Aurelia APIs are defined for the referenced element." message.

I updated kendo bridge version to 0.7.1 but this did not help

**Comment by JeroenVinke** [comment]
@Leonidnei can you join us in our [gitter channel](https://gitter.im/Aurelia/Discuss)?

**Comment by Leonidnei** [comment]
joined

**Comment by JeroenVinke** [comment]
Closing this issue as the wrapper was not loaded via main.js
