### ISSUE TITLE
Instructions for bundling not working

### ISSUE THREAD

**Issue by Tim-Erwin** [aurelia-ui-toolkits/aurelia-kendoui-bridge#460]
I followed the [instructions for bundling](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/notes_on_the_bridge/5._on_bundling) in the catalog help. However, I couldn't get it working. I'm only using the grid, so I don't want all the modules to be included. First I tried these includes:
```
        "aurelia-kendoui-bridge",
        "aurelia-kendoui-bridge/grid/*.js",
        "aurelia-kendoui-bridge/grid/*.css!text",
        "aurelia-kendoui-bridge/grid/*.html!text",
```
That included a lot of `kendo.*.min.js` files already, but more were needed. This would be my favorite approach: let the dependencies of the bridge determine the includes.

Next I tried the "Bundling via JSPM" option with
````
"includes": [
    "kendo-ui",
    "kendo-ui/**/*.js"
]
```
The first line gave me an error because I didn't have a `kendo-ui.js` file. So I simply removed it. However, this option did not include *any* of the kendo files.

In the end this include worked for me: `"kendo.*",` (By the way, I removed all unneeded files from the directory, so I don't need any excludes.) This works for the .js files, couldn't manage to also include the css files.

So, my requests are to fix the instructions and if possible/reasonable to make the single components depend on all kendo.*.min.js files that are actually needed.

**Comment by JeroenVinke** [comment]
You should have a `kendo-ui` map in `config.js` as shown in the instructions [here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/vendors)

**Comment by Tim-Erwin** [comment]
You mean the paths? I do.

**Comment by JeroenVinke** [comment]
Hmm, we could certainly improve the instructions to use named module paths. Thanks for opening the issue :+1:

**Comment by Tim-Erwin** [comment]
In your instructions you have 2 path maggings, the second one being `"kendo-ui/*": "vendors/*"`. I suppose that is for CSS etc? What do I have to put into the include in order to get the CSS? I tried `kendo-ui/styles/*.css`, but that doesn't include anything.

**Comment by JeroenVinke** [comment]
> In your instructions you have 2 path maggings, the second one being "kendo-ui/*": "vendors/*". I suppose that is for CSS etc? 

Yes, see step 7 of the instructions in which we use the kendo-ui map:

```
<require from="kendo-ui/styles/kendo.common.min.css!"></require>
<require from="kendo-ui/styles/kendo.bootstrap.min.css!"></require>
```

**Comment by JeroenVinke** [comment]
I have updated the docs and added a step by step document: https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/app_developers_notes/bundlingstep_by_step_instructions_md.html. The completed version of the tutorial is found [here](https://github.com/JeroenVinke/skeleton-navigation-kendo-bundled)

**Comment by Tim-Erwin** [comment]
Thanks 👍
