### ISSUE TITLE
How to get current item?

### ISSUE THREAD

**Issue by Leonidnei** [aurelia-ui-toolkits/aurelia-kendoui-bridge#461]
I'm looking at the context menu demo at http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/menu/context-menu and do not understand how can I find on which item the menu was clicked. For example when "forward" menu item is clicked and I defined click.trigger for it to call some method, how do I know the current item in the list in that method?

**Comment by JeroenVinke** [comment]
There is a [select event](http://docs.telerik.com/kendo-ui/api/javascript/ui/menu#events-select), which you can implement via `k-on-select.delegate="someFunction($event.detail)"`: https://gist.run/?id=d69a01440fd7ec6ddaa5021ba7b60358

**Comment by Leonidnei** [comment]
Thanks Jeroen.
I tried to use contextMenu in our application as you suggested, it worked.
However when I change the DOM (add an item to the list or delete an item), the right click menu disappears. I tried to use .ref and call recreate() when DOM changes, but this did not help.
How do I recreate menu after DOM changes?

**Comment by JeroenVinke** [comment]
Glad that it works. Can you reproduce your issue in a [gist](https://gist.run/?id=d69a01440fd7ec6ddaa5021ba7b60358)? You can make changes and when you're done click the "Create Public Gist" button. After clicking the button the URL will change and you can paste the new URL in this issue

**Comment by Leonidnei** [comment]
Hi.
I succeeded to get it work. The problem was that I assigned target to class of the item while it worked when I assigned target to outer element and filter to the specific class.

Now I have the following problem that I recreated on https://gist.run/?id=534da8efd229545c63dd5a2663d17755

I added second menu to the same list and targeted 'date' field. When I open main menu for an item and then open 2nd menu, the first is not closed.

**Comment by Leonidnei** [comment]
Jeroen suggested to:
https://gist.run/?id=8c6a36e695a2ed1902e1479f80337b41
it is a bit manual but maybe that works for you. If not, you should confirm this works in kendo without the aurelia-kendoui-bridge. If it doesn't work in "native" kendo either, you should open up an issue with Telerik instead.

I'm closing the issue.

**Comment by Leonidnei** [comment]
Sent from my Samsung Galaxy smartphone.

-------- Original message --------
