### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#462]
Today, @karthickthangasamy (member of Syncfusion team) created **[this issue](https://github.com/aurelia-ui-toolkits/skeleton-bridge/issues/26#issuecomment-211412692) which led me to create this issue, which I verified with KendoUI bridge.

I do not understand the interaction between the section of catalog app's `index.html` file
```
    System.import("root/package.json!").then(function(m) {
    var cfg = {
       packages: {}
    };

    // Create a new systemjs package with the package name
    cfg.packages[m.name] = {
        "main": "index",
          "dependencies": m.jspm.dependencies
        };

    System.config(cfg);

  });
```

and the line in catalog app's `main.js` file

![image](https://cloud.githubusercontent.com/assets/2712405/14608765/039ce542-0555-11e6-9564-1036d13b2792.png)

****

My understanding was so far that the above defined section of catalog app's `index.html` file sets the dependency on the `name` aurelia-kendo-ui as fetched from the `package.json` below:

![image](https://cloud.githubusercontent.com/assets/2712405/14609009/014da082-0556-11e6-8993-7b7965081479.png)

However `config.js` does not include that dependency definition.

One could say that this dynamic creation of the dependency is a "leftover" from the past, and could be eliminated. Well, not so, as commenting that code in `index.html` crashes the app:

```
DEBUG [aurelia] Loading plugin aurelia-kendoui-bridge.
system.src.js:4597 GET http://localhost:3000/src/aurelia-kendoui-bridge.js 404 (Not Found)I @ system.src.js:4597(anonymous function) @ system.src.js:4597e._execute @ bluebird.min.js:29r._resolveFromExecutor @ bluebird.min.js:30r @ bluebird.min.js:30(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597(anonymous function) @ system.src.js:4597r @ bluebird.min.js:31r._settlePromiseFromHandler @ bluebird.min.js:30r._settlePromise @ bluebird.min.js:30r._settlePromise0 @ bluebird.min.js:30r._settlePromises @ bluebird.min.js:30r._drainQueue @ bluebird.min.js:29r._drainQueues @ bluebird.min.js:29drainQueues @ bluebird.min.js:29(anonymous function) @ bluebird.min.js:30
bluebird.min.js:29 Unhandled rejection Error: XHR error (404 Not Found) loading http://localhost:3000/src/aurelia-kendoui-bridge.js
    at o (http://localhost:3000/jspm_packages/system.js:4:12694)
    at XMLHttpRequest.s.onreadystatechange (http://localhost:3000/jspm_packages/system.js:4:13219)
```

where `http://localhost:3000/src/aurelia-kendoui-bridge.js` is nonsense (meaning that some of the `paths` are bad most likely

QUESTION: why is it that both "Load the package.json from the root to get the package name" code and the inclusion of the plugin ` .plugin('aurelia-kendoui-bridge', (kendo) => kendo.pro().kendoSpreadsheet());` line from main.js are both needed (aside from the definition of which kendo (core / pro) to use

**Comment by Thanood** [comment]
> Well, not so, as commenting that code in index.html crashes the app:

Interesting enough that is **does not** crash the skeleton bridge.
At least if you also eliminate the ```.plugin(...)``` call from main.js

**Comment by adriatic** [comment]
> At least if you also eliminate the .plugin(...) call from main.js

That should not be surprising - as not loading the plugin is completely legal (and leaves the catalog app dumbfounded :-)

**Comment by Thanood** [comment]
Uhm, yes.. I think I need :coffee:

**Comment by JeroenVinke** [comment]
Not an issue here
