### ISSUE TITLE
ak-template is not a valid template

### ISSUE THREAD

**Issue by avizcaino-newuibcn** [aurelia-ui-toolkits/aurelia-kendoui-bridge#463]
Hi,

I'm using your [example](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_tutorials/4._typescript) but I'm having trouble with the `ak-template`. I have the next error in my console:
```
aurelia-logging-console.js:80 ERROR [app-router] Error: Invalid template property name: "undefined", valid values are: footerTemplate, groupFooterTemplate, groupHeaderTemplate, headerTemplate, template(…)
```

This is solved if I delete
```
<ak-template>
<div class='customer-photo' style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
<div class='customer-name'>${ContactName}</div>
</ak-template>
```

Seems that this should be solved with the plugin but it is not working...

Any clue?

**Comment by JeroenVinke** [comment]
Are you using .core() or .pro() in main.js? If not, you have to use .kendoTemplateSupport() in addition to the controls you wish to use

**Comment by avizcaino-newuibcn** [comment]
Yeah! That solved my problem, I was just loading kendoGrid(). Adding .kendoTemplateSupport() solved it.

**Comment by JeroenVinke** [comment]
Great!
