### ISSUE TITLE
ak-drop-down-list does not have an id that selects it from a form label

### ISSUE THREAD

**Issue by patrek** [aurelia-ui-toolkits/aurelia-kendoui-bridge#464]
In plain html, if you add a label tag with the for="elementId" attribute, and have an form element (input, textarea, select), you can click on the label and it will select, put focus on the element with the corresponding id.

This does not work when adding an id attribute to ak-drop-down-list 

See: https://gist.run/?id=c7d347dc41f9f22e9f19849d1736558d

**Comment by JeroenVinke** [comment]
Thanks for the gist :+1: 

I just checked and saw that this doesn't work with "native" Kendo either (without the bridge): https://gist.run/?id=301075357b601ea088818b5d77e921f7

So this feature is missing from the Kendo control suite and I don't think the bridge is the appropriate place to add this feature.

**Comment by JeroenVinke** [comment]
@patrek perhaps you can create a Telerik uservoice to have them add this feature. Or maybe the Telerik folks can give you a workaround that we can translate back to Aurelia
