### ISSUE TITLE
Telerik Report Viewer

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#466]
Hi,

Any chance that you'd develop a wrapper for the Telerik Report Viewer? http://docs.telerik.com/reporting/html5-report-viewer-embedding. Alternatively, any instruction on how best to implement and include the required scripts/libraries for the report viewer assuming we're already using the Aurelia KendoUI bridge?

I tried doing something like this but it didn't work. Everything appears to be loaded, but the report doesn't show up. No errors, but the "loading..." message never goes away:

```html
<require from="kendo-ui/styles/kendo.common-material.min.css!"></require>
<require from="kendo-ui/styles/kendo.material.min.css!"></require>
<require from="kendo-ui/styles/telerikReportViewer.css!"></require>

<div id="reportViewer1">
 loading...
</div>

```

```javascript
import 'kendo-ui/js/telerikReportViewer-10.0.16.204.min';

export class MyReport {
 activate() {
        $("#reportViewer1").telerik_ReportViewer({          
            serviceUrl: "http://xxx/api/reports/",
            templateUrl: "/dist/vendors/templates/telerikReportViewerTemplate-FA.html",
           // ....
  }
}
```

Thanks,
Jason

**Comment by adriatic** [comment]
Why don't you join our team and do this yourself, Jason. Using the just introduced support for gists, you could even prototype this as a gist that is using the bridge wrappers. For example **[this gist](https://gist.run/?id=19146d44294ecbb000467fdfd40856f2)** will allow you to do whatever you want with the treeview component - so the first requirement from 

![image](https://cloud.githubusercontent.com/assets/2712405/14724372/ac420c50-07e3-11e6-910f-430e5e6e2062.png)


is already here :-)

**Comment by JeroenVinke** [comment]
I don't think we'll add this to the bridge as it is not part of Kendo. But on the documentation page I noticed this:

```
The minimum required widgets:
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.core.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.data.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.calendar.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.popup.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.datepicker.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.userevents.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.selectable.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.listview.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.menu.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.panelbar.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.treeview.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2015.3.930/js/kendo.touch.min.js"></script>
```

This means that some Kendo controls have to be loaded before you load the report viewer. To confirm this is the issue (some controls not being loaded) you can try to add `import 'kendo-ui/js/kendo.all.min';` to `main.js`. If the report viewer works then you could try this:

```
// imports.js
import 'kendo-ui/js/kendo.core.min';
import 'kendo-ui/js/kendo.data.min';
// etc

// report-viewer.js
import './imports.js';
import 'kendo-ui/js/telerikReportViewer-10.0.16.204.min';
```

**Comment by jasonhjohnson** [comment]
Thanks @JeroenVinke . I tried this to no avail. It's really odd, if I don't include `import 'kendo-ui/js/telerikReportViewer-10.0.16.204.min';` then my `$("#reportViewer1").telerik_ReportViewer` line throws an error stating that telerik_ReportViewer is undefined, just as it should. When I include the telerikReportViewer js the error goes away but nothign happens. I tried:

```javascript
// report-viewer.js
import 'kendo-ui/js/kendo.all.min';
import 'kendo-ui/js/telerikReportViewer-10.0.16.204.min';

export class ReportViewer {
    activate() {
        $("#reportViewer1").telerik_ReportViewer // ...
   }
}
```

**Comment by JeroenVinke** [comment]
Could you try and run `import 'kendo-ui/js/kendo.all.min';` a bit earlier, like in main.js?

**Comment by jasonhjohnson** [comment]
Sorry I should have mentioned that I actually did try that as well. Same results.

**Comment by JeroenVinke** [comment]
oh wait, try running that core from attached() and not activate()

**Comment by jasonhjohnson** [comment]
@JeroenVinke Oh my goodness. I'm an idiot. We're getting errors now! Never been so excited to get errors. Thanks a bunch!

-J
