### ISSUE TITLE
Please update jquery version

### ISSUE THREAD

**Issue by denimaaark** [aurelia-ui-toolkits/aurelia-kendoui-bridge#467]
Please update jquery version dependency to new version.

**Comment by JeroenVinke** [comment]
OK, I checked and Kendo seems to work fine with jQuery 2.2.1. The issue we had with the scheduler and jQuery 2.2.0 seems to be fixed. So I removed the lock and released 0.8.0. You can install it with `jspm install aurelia-kendoui-bridge`

**Comment by adriatic** [comment]
I am assuming that @denimaaark needed this lock removal as it interfered with some dependencies in his app that uses the KendoUI bridge. At the same time, we had set the lock because of the problem @JeroenVinke just stated above. Clearly there is no perfect solution available.
