### ISSUE TITLE
Error invoking AutoComplete. Check the inner error for details.

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#469]
Hi,

I ran `jspm update` this morning and have now started to recieve this error: `Error invoking AutoComplete. Check the inner error for details. inner error: Error: The name of control kendoAutoComplete is invalid or not set` I get it for any control, not just AutoComplete. I'm not sure what happend. I tried jspm uninstall, jspm clean, jspm update again, but with no resolution.

Any ideas what might be happening?

Thanks,
Jason

**Comment by JeroenVinke** [comment]
@jasonhjohnson 

We removed the jQuery version lock as Kendo now works with jQuery 2.2.1. Do you have any forks for jQuery (jspm inspect --forks)? Are you loading jQuery elsewhere?

**Comment by JeroenVinke** [comment]
Although, `jspm update` wouldn't update our bridge. So what version of the bridge, kendo and jQuery are you using?

**Comment by jasonhjohnson** [comment]
@JeroenVinke No jquery forks found when I ran jspm inspect--forks (only two, npm:isarray and npm:readable-stream). I don't think I'm loading jquery anywhere else, though it's possible bootstrap or something is pulling in a different version. Maybe.
Bridge: `npm:aurelia-kendoui-bridge@^0.6.3`
Kendo (taken from your vendors folder on github): `Kendo UI v2016.1.118`
Jquery: `github:components/jquery@2.1.4`

I un-did checkout of my project and I'm no longer getting that error. I'll try jspm update again and see if it breaks things. Is there something I should do before running jspm update?

Thanks,
Jason

**Comment by JeroenVinke** [comment]
Weird, I don't know Jason. Perhaps with version control you could see what changes when you do `jspm update`. I know that `jspm update` will update the Aurelia libraries but it won't update our bridge. You could try running `jspm update` and `jspm install aurelia-kendoui-bridge` and maybe it will work then

**Comment by adriatic** [comment]
@jasonhjohnson I believe that your issue is no different from what @rocknet asked in Gitter chat room. So, perhaps my **[response](https://gitter.im/adriatic/Aurelia-KendoUI?at=571eabea4bbb6abf7d5f057f) **to his issue may be worth looking at.

**Comment by JeroenVinke** [comment]
please open another issue if this is still relevant because a lot has changed since April
