### ISSUE TITLE
DropDownList with remote data shows empty current value after data load

### ISSUE THREAD

**Issue by smax48** [aurelia-ui-toolkits/aurelia-kendoui-bridge#470]
In the example for DropDownList with remote data (http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/dropdownlist/binding-to-remote-data) the control displays an empty current value after loading.

The original KendoUI example correctly displays the first item from the attached datasource (http://dojo.telerik.com/UCebi).

With local data everything works OK.

**Comment by JeroenVinke** [comment]
I used the following code to test the differences between local and remote data:

```
export class BindingToRemoteData {
  dataSource = {
    transport: {
      read: {
        dataType: 'jsonp',
        url: '//demos.telerik.com/kendo-ui/service/Products'
      }
    }
  };

  dataSource1 = {
    data: [
      {ProductName: 'a', ProductID: 1},
      {ProductName: 'b', ProductID: 2},
      {ProductName: 'c', ProductID: 3}
    ]
  };
}

<template>
            <ak-drop-down-list k-data-text-field="ProductName"
                              k-data-value-field="ProductID"
                              k-data-source.bind="dataSource"
                              k-value.two-way="val"
                              style="width: 100%">
            </ak-drop-down-list>

            ${val}

            <ak-drop-down-list k-data-text-field="ProductName"
                              k-data-value-field="ProductID"
                              k-data-source.bind="dataSource1"
                              k-value.two-way="val1"
                              style="width: 100%">
            </ak-drop-down-list>

            ${val1}
</template>
```

This example code showed that remote databinding didn't set the initial value of the dropdownlist but local databinding did. Angular does [a check for empty strings](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js#L465) and we didn't. So after adding that check and waiting for the dataBound event for remote databinding scenarios made it work.

**Comment by smax48** [comment]
Thanks for such a quick fix! :)

**Comment by JeroenVinke** [comment]
you're welcome :+1: this is now in 0.8.1 and can be installed with `jspm install aurelia-kendoui-bridge`
