### ISSUE TITLE
Combining with Aurelia Validation

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#474]
Hi,

Is it possible to use a control from the bridge in conjunction with the Aurelia Validation plugin? 

I tried:
```html
<input id="effectiveDate"
       ak-datepicker="k-value.two-way: effectiveDate; k-format.bind: 'MM/dd/yyyy';"  />
```

```javascript
 this.validation = validation.on(this)
    .ensure('effectiveDate')
        .isNotEmpty()
```

Is there a way to get at the underlying `effectiveDate` binding?

Thanks,
Jason

**Comment by JeroenVinke** [comment]
Hey Jason,

We don't have integration for aurelia-validation and will probably not work on one as aurelia-validation is about to be renewed completely. I know that Kendo has a validator, maybe that works for you?

Once I used a hidden one-way bound `<input>` tag that allowed aurelia-validation to work and show error messages, while using a kendo control for changing the value.

**Comment by jasonhjohnson** [comment]
Understood. Would you happen to have an example of the workaround you described?

**Comment by JeroenVinke** [comment]
I can't seem to find it but I believe it was something like this:

```
<input type="hidden" value.one-way="effectiveDate" />
<input id="effectiveDate"
       ak-datepicker="k-value.two-way: effectiveDate; k-format.bind: 'MM/dd/yyyy';"  />
```

**Comment by JeroenVinke** [comment]
you have to use a custom renderer that's specific to the css framework you're using (bootstrap/materialize). The only thing you have to look out for is that the validation error is displayed in the right spot. Some kendo controls modify the HTML structure when initializing a control, so you need to take that into consideration by appending or prepending the error to the parent element of the widget:

```
    const message = document.createElement('span');
    message.classList.add('help-block');
    message.classList.add('validation-error');
    message.textContent = error.message;
    let elem = $(message).appendTo($(target).parents('.col-lg-6, .col-lg-8, .col-md-6, .col-md-8')[0]);
    (<any>elem[0]).error = error;
```

Check the [blog](http://blog.durandal.io/2016/06/14/new-validation-alpha-is-here/)
