### ISSUE TITLE
Investigate adding systemjs/plugin-css a dependency of the bridge

### ISSUE THREAD

**Issue by rocknet** [aurelia-ui-toolkits/aurelia-kendoui-bridge#476]
Currently, to get the Pro tutorial to work (haven't tried others), you need to do `jspm install css`.  Perhaps this can be a dependency in aurelia-kendoui-bridge?

**Comment by JeroenVinke** [comment]
I wonder if we can add the css plugin to the [JSPM dependencies](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/package.json#L37-L46) section, without messing up webpack

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/9863677541b749d701543e2371a3467187c77acd

I have also simplified the installation instructions a bit, because the css plugin is now installed automatically when installing the bridge

**Comment by JeroenVinke** [comment]
ahh, tried this out but it didn't work (it gave me a 404 on `dist/css.js`. The css plugin is installed but it isn't put as a top level dependency in config.js. So I reverted this
