### ISSUE TITLE
Apply manual filter on Kendo grid fail to filter.

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#477]
Hey guys
Using the grid, i'm trying to apply filter on button click here is my code 
`onApplyGridFilter(filter) {
        this.gridTextFilter = filter;
        var ds = this.gridInstance.element.parent().find(".k-grid").data("kendoGrid").dataSource;
        var $filter = [
            {field: "id", operator: "contains", value: filter},
            {field: "type", operator: "contains", value: filter},
        ];
        ds.filter({logic: "or", filters: $filter});
    }`

**and the error is "TypeError: (d.id || "").toLowerCase is not a function(…)".**
my guess it because, when i search for string ("AAA") there are column that defined as  type 'number' and no right comparison  is made.
Any ideas?

**Comment by JeroenVinke** [comment]
Sounds like an issue with Kendo and not with the bridge: http://www.telerik.com/forums/filtering-causes-uncaught-typeerror-object-xxx-has-no-method-tolowercase#rc3ndeFuZUuItrypFOA7Bg

**Comment by eliavmaman** [comment]
@JeroenVinke Thanks . i thought it's a bridge problem.

**Comment by eliavmaman** [comment]
F*ck.. the problem was i was trying to apply "contains" operator on numeric field.
Sorry my bad.

**Comment by JeroenVinke** [comment]
No problem, glad you got it working
