### ISSUE TITLE
Improve two-way binding limitation explaination

### ISSUE THREAD

**Issue by Vizer** [aurelia-ui-toolkits/aurelia-kendoui-bridge#479]
Hello guys,

I am trying to implement localization and I need interpolation in attributes, but seems it does not work. Example is [here](https://gist.run/?id=29b3b8e73f35af0edec19278e5f3b15b). I have tried to interpolate `k-title` value in `ak-window` attribute.
How can I dynamically set this value?

**Comment by JeroenVinke** [comment]
https://gist.run/?id=79df7fa4ba21a5c31e89243111b0717c, there is no two-way databinding for this property though, so if you need to change it after the window has been initialized then you need to use API functions like [title()](http://docs.telerik.com/kendo-ui/api/javascript/ui/window#methods-title)

```
<div ak-window="k-widget.two-way: myWindow"></div>

changeTitle() {
   this.myWindow.title('Hello world');
}
```

**Comment by Vizer** [comment]
@JeroenVinke, thank you. It works for me

**Comment by adriatic** [comment]
One of the examples of what needs to be added to our tips and hints section in the catalog (all related to http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_notes/1._current_limitations

**Comment by JeroenVinke** [comment]
This is actually the general rule of thumb (Kendo doesn't support two way binding, so use API methods instead). There are a few exceptions (datasource, value binding, enable binding), but that's it. i'm not sure if this is mentioned very clearly

**Comment by eliavmaman** [comment]
@JeroenVinke your solution worked for me 10x

**Comment by JeroenVinke** [comment]
Added two-way binding instructions to https://www.gitbook.com/book/aurelia-ui-toolkits/kendoui-bridge-docs/edit#/edit/master/what_you_need_to_know.md
