### ISSUE TITLE
Connecting Aurelia's binding system with Kendo's Observable

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#484]
Run the following gist and change the textbox in the grid, note that the first column isn't updated with the change
https://gist.run/?id=8d56ee77f1b3ebc17dcc6e9e6219421c

Kendo works with Observable objects, that all have a `.set()` function. With this function you can change a property of the object, and Kendo will know about this change. When used in the context of a grid, Kendo will set the dirty flag of the row accordingly.

The problem with custom column templates is that Aurelia's binding system is making changes to the object directly, and is therefore not using the `.set()` function. Because of this, Kendo is not aware of any changes, so when you tell the grid to save it thinks that nothing has to be saved

This function is a workaround for this issue:

```
  <input type="text" value.bind="someProp" change.delegate="updateProp($this, 'someProp');"/>

  updateProp(item, property) {
    item.trigger('change', { field: property });
    item.dirty = true;
  }
```

Although I think we can come up with a nicer solution. I tried the following binding behavior and it worked, but there was an issue:

```
export class NotifyBindingBehavior {
  bind(binding, scope, observable, field) {
    if (!binding.updateSource) return;

    var intercept = binding.updateSource;
    binding['intercepted-updateSource'] = intercept;
    binding.updateSource = function(value) {
      if (observable.set && observable.trigger) {
        // setTimeout(() =>
        //   observable.trigger.call(observable, 'change', { field: field }),
        // 100);

        observable.trigger.call(observable, 'change', { field: field })

        if (observable.dirty === false) {
          observable.dirty = true;
        }
      }
      // debugger;
      return intercept.call(binding, value);
    };
  }

  unbind(binding, scope) {
    if (!binding['intercepted-updateSource']) return;

    binding.updateSource = binding['intercepted-updateSource'];
    binding['intercepted-updateSource'] = null;
  }
}
```

It is used like this:  `<input type="text" value.bind="ProductName & notify:$this:'ProductName'"/>`. Now whenever `someProp` changes, it will notify Kendo of this change. But what I observed was that when you trigger the `change` event, the grid recompiles all templates and that throws an error. Because Aurelia is doing all sorts of parsing, I think we can simplify this even more:

`<input type="text" value.bind="ProductName & notify"/>`

**Comment by JeroenVinke** [comment]
added initial support (and sample)

**Comment by alastair-mcdonald** [comment]
I am having the problem which is exactly described by this issue: when editing a listview item the underlying bound variable is updated but it's dirty flag remains false so the update event is not fired. I tried the proposed solution in this post and altered the binding to include `& notify` as in `value.bind="noteText & notify"`, however this caused the error `Uncaught Error: No BindingBehavior named "notify" was found!`

I looked for documentation on how to solve this problem with no success - please could you provide information on how to implement the solution?

Many thanks,
Alastair

**Comment by JeroenVinke** [comment]
Hey @alastair-mcdonald 

In main.js, try the following:

```
.plugin('aurelia-kendoui-bridge', config => config.notifyBindingBehavior());
```

Let me know how that goes

**Comment by alastair-mcdonald** [comment]
Hi @JeroenVinke  - that was a perfect fix! The changed data is now arriving in the database. Ace job - many thanks!
Alastair
👍
