### ISSUE TITLE
improve support workflow

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#486]
This issues is at the moment a collection of tasks that all need to be done in one sweep:

#### 1. make help/support accessible via url:

![image](https://cloud.githubusercontent.com/assets/2712405/15120323/23630958-15e3-11e6-9a04-8c4218dc4c2b.png)

**Note** such feature already exists on http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation page

_(I am never sure what is the proper term for this feature (make it routable??))_

#### 2. enhance help/support page

_I will define this part a a separate issue so we can discuss this in isolation of the rest of the issues on this page_

#### 3. fix up app version numbers 

In particular this is important to do for:

http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/core
http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/jspm-git
http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/vendors

#### 4. coalesce the following documents into a meaningful collection

[2. using gist-run to experiment with Aurelia components and report problems](http://aureliauitoolkits.github.io/demokendo/#/help/docs/troubleshooting/2._using_gists_and_gistrun)

[4. Running Aurelia-KendoUI components as gists](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_notes/4._running_gists)

[10. Creating gists for KendoUI bridge catalog application](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/notes_on_the_bridge/10._creating_gists_for_catalog_app)

**Comment by adriatic** [comment]
#### Need help with item 1 [above](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/486#issue-153819881)

I tried to improve the code for the [help page](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help), by using the same approach that exists for the [installation page](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation). See my [changes](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/3417d2412fcb9a11251122afa6c1ba486ac5707b) on the newly added `user-support` branch.

I stopped pursuing this even before making the complete transformation (as I understand the way it has to be completed), once I got the error message:

```
aurelia-binding.js:1945 Uncaught Error: tabSelected is not a functiongetFunction @ aurelia-binding.js:1945evaluate @ aurelia-binding.js:1539callSource @ aurelia-binding.js:4950(anonymous function) @ aurelia-binding.js:4974handleDelegatedEvent @ aurelia-binding.js:3185fireEvent @ util.js:90fireKendoEvent @ util.js:98options.(anonymous function) @ widget-base.js:192r.extend.trigger @ kendo.core.min.js:25f.extend._click @ kendo.tabstrip.min.js:25(anonymous function) @ kendo.tabstrip.min.js:25jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
``` 

when clicking on the `support tab` (see screenshot below)

![image](https://cloud.githubusercontent.com/assets/2712405/15133404/87561688-1630-11e6-9397-7c51a0c3d5fa.png)

I do not understand how did this code work before my today's changes -- because [the line that causes this error](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/help/help.html#L5) could not find the 'tabSelected` method, as the file [help.js](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/help/help.js) is "empty".

So, I concluded that I am missing something in my attempt to make the two routes `help/components docs` and `help/support` be "reflected" on the url.

**Comment by JeroenVinke** [comment]
that conclusion is correct :) I took the code from the installation page and applied it to the help page

**Comment by adriatic** [comment]
Thank you!
