### ISSUE TITLE
remove jquery dependency

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#487]
That way you can use any jquery version and you can get that version from anywhere (without causing forks in JSPM)

**Comment by JeroenVinke** [comment]
when this change is released we should test this in a clean install in skeleton-navigation

**Comment by adriatic** [comment]
> when this change is released we should test this in a clean install in skeleton-navigation

Skeleton navigation? Where will this removal of jquery dependency take place then?

**Comment by JeroenVinke** [comment]
in the [bridge](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/package.json#L45). JSPM won't install jQuery automatically when they install our bridge. Instead, you would have to install jquery yourself (but this allows you to get it from anywhere and use any version you like). Testing in skeleton-navigation makes sure that this process is working OK

**Comment by adriatic** [comment]
still confused - as skeleton navigation does not use the bridge :-)

**Comment by JeroenVinke** [comment]
this change affects the installation process of our bridge, so we can't test that in an application that already has the bridge installed

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/35c1cb04f0e32aa29f6254ee88004e5b1a914ad1

and 

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/5bed8e7cf8202827305d412d743a623607df74f1
