### ISSUE TITLE
support post-processing tasks and issues

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#488]
This section lists all support issues that should be "post processed"

1. https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/479#issuecomment-217959148
2. https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/487#issuecomment-217958523
3. https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/484#event-654689826
4. https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/481#event-654690786
5. https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/476#event-654706358
6. https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/475#event-654707508

**Comment by adriatic** [comment]
In preparation for this feature, just added **[these changes](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/072bf68deefbb8bcde6baf5ff78d6612e570ac58)** which describe two modifications:

1. Rewritten the article on **[creating and running gists](https://#/help/docs?category=troubleshooting&file=2._using_gists_and_gistrun)** to better fit the support needs

2. Reformatted the **[support](http://#/help/support)** page to present the three ffered modes of support.

**Comment by JeroenVinke** [comment]
The gists I make end up in issues such as https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/578 and whenever I work on Kendo I add these gists to the bridge.  As this issue has not been maintained for a while, I think we should apply common sense and document things when something is unclear to people

**Comment by adriatic** [comment]
Agreed - this issue was not adequately maintained :cry:
