### ISSUE TITLE
Bundling process ignores kendo.core.min.js

### ISSUE THREAD

**Issue by smax48** [aurelia-ui-toolkits/aurelia-kendoui-bridge#490]
I am trying to bundle all relevant kendo ui controls in one single bundle. But regardless of any configuration settings, the file `kendo.core.min.js` **is not included** and always requested by the full path by systemjs during runtime (in my case from `"jspm_packages/kendo/bower-kendo-ui@2016.1.412/js/kendo.core.min.js"`).
Versions of jspm / systemjs: 0.16.15 / 0.19.6
I tested this with different kendo ui pro builds, the result is always the same.

I am not sure whether this is a jspm / aurelia / bridge or kendo ui issue :).

Maybe everything will be resolved with jspm 0.17 when it is released, but maybe I am just missing something very obvious... 

Bundle config:
```
        "dist/kendo-build": {
            "includes": [
                "kendoui/js/*.min.js",
                "kendoui/styles/kendo.common.min.css!text",
                "kendoui/styles/kendo.bootstrap.min.css!text"
        ],
            "excludes": [
              "kendoui/js/angular.min.js",
              "kendoui/js/jquery.min.js",
              "kendoui/js/kendo.angular.min.js",
              "kendoui/js/kendo.angular2.min.js",
              "kendoui/js/kendo.spreadsheet.min.js",
              "kendoui/js/kendo.all.min.js",
              "kendoui/js/kendo.web.min.js",
              "kendoui/js/kendo.dataviz.min.js",
              "kendoui/js/kendo.dataviz.mobile.min.js",
              "kendoui/js/kendo.mobile.min.js"
            ],
            "options": {
                "inject": true,
                "minify": true,
                "rev": false
            }
        }

```

**Comment by JeroenVinke** [comment]
took some time to figure this out, but if you put `[` and `]` around the excludes kendo.core.min.js is included again:

```
        "[kendo-ui/js/angular.min.js]",
        "[kendo-ui/js/jquery.min.js]",
        "[kendo-ui/js/kendo.angular.min.js]",
        "[kendo-ui/js/kendo.angular2.min.js]",
        "[kendo-ui/js/kendo.spreadsheet.min.js]",
        "[kendo-ui/js/kendo.all.min.js]",
        "[kendo-ui/js/kendo.web.min.js]",
        "[kendo-ui/js/kendo.dataviz.min.js]",
        "[kendo-ui/js/kendo.dataviz.mobile.min.js]",
        "[kendo-ui/js/kendo.mobile.min.js]"
```

**Comment by smax48** [comment]
Thanks a lot! I will try this magic tomorrow :)

**Comment by JeroenVinke** [comment]
https://github.com/JeroenVinke/es2015-kendo-bundle shows a working bundling setup
