### ISSUE TITLE
Fix the [support](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/support) page

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#492]
This is the [support](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/support)  page that needs fixing

![image](https://cloud.githubusercontent.com/assets/2712405/15274295/7b050d94-1a7c-11e6-8516-439b0ce5634b.png)

The button `Create Public Gist` will not appear in the general case - as the person running this workflow will be the owner of the original gist being copied, so the the actual view will be:

![image](https://cloud.githubusercontent.com/assets/2712405/15274343/735d3c14-1a7d-11e6-8659-d3e6e77f149a.png)

Since you cannot create this screenshot yourself (see the explanation below), I suggest you use this screenshot above and replace it in the catalog app help/support page.

***

**My failed attempt to create a different user to be able to create the correct screenshot**

![image](https://cloud.githubusercontent.com/assets/2712405/15274407/6e23c99c-1a7e-11e6-986e-6c9b58999880.png)

**Comment by JeroenVinke** [comment]
When you log out you see "Create Public Gist" and when you login you see "Fork Public Gist". So we could change the image to say "Fork Public Gist" but then it's incorrect for users who aren't logged in.

**Comment by adriatic** [comment]
> When you log out you see "Create Public Gist" and when you login you see "Fork Public Gist".

That is a really a very detailed design - the key behavior is to ensure that the original gist is read-only. While I could say that we do not care about the difference between `copy` and `fork`, there would be people that do care. I will likely add some additional explanations in the [longer text](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs?category=troubleshooting&file=2._using_gists_and_gistrun) that explains the use of gists.

**Comment by adriatic** [comment]
The key intent with this addition is to allow you to simply say: please check http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/support page :-)

**Comment by adriatic** [comment]
I believe that this is done now
