### ISSUE TITLE
Error in import {delayed} from 'aurelia-kendoui-bridge/common/decorators'

### ISSUE THREAD

**Issue by RichardDeckard** [aurelia-ui-toolkits/aurelia-kendoui-bridge#493]
In typescript this results in `Cannot find module 'aurelia-kendoui-bridge/common/decorators'`.

**Comment by JeroenVinke** [comment]
You should be able to import like so: `import {delayed} from 'aurelia-kendoui-bridge'`.It should pick up the typescript definition now
