### ISSUE TITLE
Dynamically change options of multiselect

### ISSUE THREAD

**Issue by Tim-Erwin** [aurelia-ui-toolkits/aurelia-kendoui-bridge#495]
Is there a way to change the options of a multiselect dynamically via a repeater? I retrieve the available options from a backend so that they are not available immediately. However, the dropdown does not change after the initial setup. I can hack my way around that somehow, but I'd prefer a clean solution.

**Comment by charlespockert** [comment]
@Tim-Erwin not with a repeater, but you can certainly refresh the datasource that provides a multi-select with its data

Are you initialising the multi-select via DOM nodes?

**Comment by Tim-Erwin** [comment]
My code looks like this, hope it answers the question. It seems there is another way to do it that I'm not aware of.

```
                            <ak-multiselect k-auto-close.bind="false" k-value.two-way="functions">
                                <select multiple="multiple" data-placeholder="Funktionen..." ref="funcElem">
                                    <option repeat.for="f of allFunctions" model.bind="f">${f}</option>
                                </select>
                            </ak-multiselect>
```

**Comment by charlespockert** [comment]
Once the Kendo widget has been initialised from the DOM, it won't get any updates (it doesn't maintain any link with the DOM/watch the DOM)

One option is to re-initialise the widget when your list of options changes in your viewmodel, the other is to update the data source object on the widget

view.html
```
<ak-multiselect ak-multiselect.ref="myMultiSelect" k-data-source.bind="allFunctions"> 
</ak-multiselect>
```

view-model.js
```
this.myMultiSelect.kWidget.dataSource.add({ new item here });

// you can also set the datasource again if you want to refresh all options
this.myMultiSelect.kWidget.setDataSource(newDataSource);
```

**Comment by Tim-Erwin** [comment]
The latter works perfectly. Thanks a lot. Is there any documentation about those properties?

While this allows me to do what I want to do, it would be nice to be able to do it the (a) aurelia way. Either with a repeater or with a bindable.

**Comment by charlespockert** [comment]
@Tim-Erwin docs are here: http://docs.telerik.com/kendo-ui/api/javascript/ui/multiselect#methods-setDataSource

**Comment by Tim-Erwin** [comment]
@charlespockert I know about that documentation, but what about `kWidget`?

**Comment by JeroenVinke** [comment]
@Tim-Erwin you can also bind to k-widget, which is the equivalent of the kWidget shown by @charlespockert 

http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/multiselect/api
and if you need to use a widget from attached() you can use the @delayed decorator: http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/generic

**Comment by Tim-Erwin** [comment]
Thanks a lot for the quick responses. Keep up the good work.
