### ISSUE TITLE
How to use webpack with KendoUI bridge

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#496]
@charlespockert - this is the place where I am impatiently waiting for your explanation of "how to use Webpack with Aurelia/KendoUI app"

**Note:** I just saw the post from @niieani **[here](https://github.com/aurelia/webpack-plugin/issues/11#issuecomment-220214971)**, where I asked him to add his solution to this thread for the benefit of our team.

**Comment by niieani** [comment]
Please see my explanation here: https://github.com/aurelia/skeleton-navigation/pull/440#issuecomment-220823441.

**Comment by EisenbergEffect** [comment]
Changes now applied to our plugins and kits on master.

**Comment by adriatic** [comment]
As I am out of office for a few days, I left the instructions how to verify that our problem is solved to Jerone and our new team member, Adam

@ping @JeroenVinke

**Comment by JeroenVinke** [comment]
Got it running, continuing in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/567
