### ISSUE TITLE
Let the catalog use gists as the source for samples

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#497]
based on this working:

```
<template>
    <compose view-model="https://gist.githubusercontent.com/JeroenVinke/51a5c66eeb1cdcdce8447ec6053fa6f9/raw/605ac1bb6c74607988b244d757fca8d691df5e63/app"></compose>
</template>
```

we can use a .json file in a github repository to generate our menu structure, and use <compose> to render samples from gists. The same gist is used by gist.run

**Comment by JeroenVinke** [comment]
did this

**Comment by adriatic** [comment]
What do you mean by "Did this"? Seriously?

**Comment by JeroenVinke** [comment]
Yes, in the beta branch there are no more samples in the catalog. The catalog only has a list of gist id's that's used to render the samples

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/beta/sample/src/samples/samples.json is the file from which the menu's are generated and contains all sample gist id's

**Comment by adriatic** [comment]
but, but ... when did you do that??

**Comment by adriatic** [comment]
Samples, documentation - pretty soon the catalog will be the container of pieces defined and changeable elsewhere. I believe that this whole concept is incredibly powerful and we need to think how to enable monterey to support it.

This also increases the pressure to GistRun integration

**Comment by adriatic** [comment]
There is a slight (less than a second) delay, obviously caused by a fetch of a gist from GitHub, which was not present before. At the same tome, KendoUI catalog app is still a lot more agile than Syncfusion's :+1:

**Comment by JeroenVinke** [comment]
Yes, something we could look into is a adding a spinner.
