### ISSUE TITLE
create and discuss the design for new catalog app

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#498]
I want to make use of several @JeroenVinke's ideas

1. [Let the catalog use gists as the source for samples](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/497)
2. [host all docs in gitbook](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/499)
3. [Support post-processing tasks and issues](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/488)

that would result with the drastic reduction in catalog's size, by converting it from the monolithic "fat blob" into an elegant, slim **hub**. Details coming soon in this thread, by defining a new structure and proposing the design that should be first discussed and improved by all team members

**Comment by JeroenVinke** [comment]
Closing this for now, please reopen if you still want to use this issue

**Comment by adriatic** [comment]
I agree with temporary closing - while the item 3 might be revived in the context of Monterey
