### ISSUE TITLE
host all docs in gitbook

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#499]
https://github.com/GitbookIO/gitbook

https://gitbookio.gitbooks.io/documentation/content/

**Comment by adriatic** [comment]
Added first draft of the book - without any use of gitbook plugins of other customization feature

**Comment by JeroenVinke** [comment]
Also: add algolia: https://blog.algolia.com/announcing-instantsearch-js-everything-you-need-for-great-search-in-one-library/

**Comment by JeroenVinke** [comment]
all docs are in gitbook now

**Comment by adriatic** [comment]
:+1:
