### ISSUE TITLE
redesign of the catalog app due to using GitBooks

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#501]
**Here is the issue:** once the help docs are hosted outside the catalog app (and there are very many excellent reasons for this architecture), the typical page like this

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/15456805/42450a72-2049-11e6-9c7b-37afe9535e22.png"></img>
 <br><br>
Image 1
</p>

using the iFrame based approach, which is very easy to do (see the code commented out):
```html
           ...
          <!-- Components Docs Tab content-->
          <div style="height: 790px;">
            <!-- <doc></doc>-->

            <iframe src="https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/index.html"
                    width="96%" height="780px" >
                    <p>Your browser does not support iframes.</p>
            </iframe>

          </div>
          ...
```

gets the "new look" shown below

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/15456917/5cdd68cc-204c-11e6-931a-8a1f8e99531e.png"></img>
 <br><br>
Image 2
</p>

While I did this implementation initially  to get the sense for what it would look like, @JeroenVinke warned me immediately that this is a bad approach - as we could not "navigate to docs pages via URL" and without that feature the whole new approach is flawed 

Running the docs book in different browser instance / different tab, solves that problem as one can see below:

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/15456948/659ee7dc-204d-11e6-900c-24f59a64d9e8.png"></img>
 <br><br>
Image 3
</p>

### Now the question is this:

a) do we leave the iFrame based approach (which is just fine for reading and does not change the previous user experience) **and** use the gitbok urls like https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/troubleshooting/using_gists_and_gistrun.html to tell people asking for support

b) ensure that click on the help/docs tab looks better than this

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/15457028/6f9aa65c-204f-11e6-869b-add9a73369ed.png"></img>
 <br><br>
Image 4
</p>

**Comment by adriatic** [comment]
My preferred solution would actually be this:

1 Separate docs from help on the main menu:

![image](https://cloud.githubusercontent.com/assets/2712405/15458717/aab826da-206b-11e6-94f1-c7018b6b6794.png)

2 Use iFrame for **`Documentation page`** (with the reasoning stated above (after Image 2).

3 Use iFrame for **`Installation`** page (referencing the Installation book at GitBook)

4  Use iFrame for the **`Support Exchange`** tab on **`Help`** page:

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/15458811/8716ae58-206c-11e6-8246-96adda460c96.png"></img>
 <br><br>
Image 5
</p>

**Comment by Thanood** [comment]
> 2 Use iFrame for Documentation page (with the reasoning stated above (after Image 2).

Did you mean
> 2 Use new tab for Documentation page (with the reasoning stated above (after Image 2).

?
Because you're writing about opening a new tab there. :smile: 

I like the separation of docs and help.
Initially, I thought: Is GitBook capable of displaying tabs? That way we could even display the free support options (which are just links to Gitter, GistRun and GitHub issues) and the exchange in GitBook.

But that has some drawbacks. The support options are more prominent if we do it like Nik suggested. The poll is also easier to see. So I say let's go with this proposal.

**Comment by adriatic** [comment]
Thanks for the comments, Daniel :-) - and let me be more precise in my above post:

#### On:
> 2 Use iFrame for Documentation page (with the reasoning stated above (after Image 2).

I meant this **precisely as written**: the Documentation is now on it's own page (not in a tab on a page), for reasons explained above (to separate help from documentation - each entity has its own menuItem on the main menu, as indicated on the Image 5 above)

**Comment by JeroenVinke** [comment]
we can stick with the current approach of showing the gitbook in an iframe until we have reason to change this approach
