### ISSUE TITLE
add support for algolia in all books

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#502]
https://blog.algolia.com/announcing-instantsearch-js-everything-you-need-for-great-search-in-one-library/

**Comment by flieks** [comment]
Their search is so fast but doesn't it only work when you put all your data (creating indexes) on their server and then you have to pay no?

**Comment by adriatic** [comment]
Depends on the volume - I was assured that their free tier will allow more searches than application like ours could ever need.

Our policy is to provide the best tools available (take KendoUI as an example) with two tiers - free and paid license.

**Comment by flieks** [comment]
ok, then it would be nice if there was some kind of integration in the bridge :). 
You can integrate this in the kendo autocomplete and not use the instantsearch searchBox ?
Thanks

**Comment by adriatic** [comment]
Coming soon :-)

**Comment by JeroenVinke** [comment]
added this task to https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/499
