### ISSUE TITLE
Upgrade all versions of Navigation Skeleton Kendo to current aurelia release

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#506]
As a good support tool, we should continuously maintain **[this code](https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo)** and add a section about using it to **[kendoui-bridge-docs](https://www.gitbook.com/book/aurelia-ui-toolkits/kendoui-bridge-docs/details)**

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo is being recreated, so this is no longer necessary

**Comment by adriatic** [comment]
Agreed
