### ISSUE TITLE
Refreshing data on Kendo Grid

### ISSUE THREAD

**Issue by rajivbala** [aurelia-ui-toolkits/aurelia-kendoui-bridge#508]
Hi,
I have been trying to refresh the data that is bound to the kendo grid. I have not been successful in my attempts. I tried the approaches below

- Binding the array of objects directly to the grid data source
- Refreshing the grid

I have a gist here ([https://gist.run/?id=503e393084cde30b66cc81969d14c0cd]) that reproduces my problem. In short i want to clear the grid on click of the empty Button.

**Comment by genericuser-me** [comment]
Try this:

 this.datasource.data([]);

**Comment by rajivbala** [comment]
This issue is solved by suggestion from @JeroenVinke .
Thanks!!

i'd always use kendo.data.DataSource so the Kendo grid doesn't clone the datasource object (and gets rid of the reference). then you have 3 options:
-	transport read: https://gist.run/?id=7873b19c1c23860671c1bf641a1f766a
-	this.datasource.data([]) works but when you refresh the data returns (I don't know why), but this works: https://gist.run/?id=e7642fc69ea868c44abe96702e19386c
-	kendo.data.ObservableArray: https://gist.run/?id=3c6e7099c349ab10315539cd23a641cc , just don't reset the array because that'll destroy the reference the datasource has
I like the transport.read option, because you can even call a method on a service from there that gets the data

**Comment by JeroenVinke** [comment]
Great!
