### ISSUE TITLE
Loading icon for ListView

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-kendoui-bridge#509]
How to show loading or processing icon for Listview programatically? If anything is added to the ak-template other than the div with class product, the data is not laoded correctly. There is nothing specified in the docs for the same. Can anyone please help?

**Comment by JeroenVinke** [comment]
Hey @genericuser-me, in order for us to help you more quickly, would you please follow the steps mentioned [here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/free-support) and create a gist that shows the problem you're describing? Thanks!

**Comment by genericuser-me** [comment]
Hi Added the code here:
[GistRun](https://gist.run/?id=809bf843b45efdf8589179f88fd1e507``)

**Comment by genericuser-me** [comment]
Here is the code: https://gist.run/?id=3bdaf916c3f27f15c98514052fa83328

**Comment by JeroenVinke** [comment]
Thanks, are you trying to show a loading icon per product or just one loading icon for the entire listview. It would also help if you were able to find an example that does the same without the bridge (so native kendo) because our bridge doesn't add many features on top of native kendo.

**Comment by genericuser-me** [comment]
I was just trying to add it on the listview. I found this [example](http://www.telerik.com/forums/how-to-manually-show-and-hide-loading-or-spinning-image), however it was for grid.

**Comment by JeroenVinke** [comment]
Hmm, this is tricky for the listview because it doesn't have many events. I was able to get [this working](https://gist.run/?id=3545dc67dd0c1f869c071d5adbc1ed11) though. Could that help you?

**Comment by genericuser-me** [comment]
Yes, it did! Thanks a lot! Updated my code just in case!

**Comment by JeroenVinke** [comment]
Great! :smile:
