### ISSUE TITLE
Request to enhance charts by adding patterns for series

### ISSUE THREAD

**Issue by cdaniel77** [aurelia-ui-toolkits/aurelia-kendoui-bridge#510]
I would like to put in a request for the bridge. Currently kendo-ui doesn't handle this but it could be something for the bridge. Can we have a way of using patterns on chart series? Currently, Telerik has stated that this is not in kendo. However, I found an article of how to hack it in here [kendo chart pattern hack](http://stackoverflow.com/questions/36012520/kendo-bar-chart-with-texture-pattern). While this could work, there could be a better way to add something in the config to call a predefined set of patterns, for now?

**Comment by JeroenVinke** [comment]
thanks for the [gist](https://gist.run/?id=18666b1d7f86114bdd4da9c508f51747) :+1:

**Comment by JeroenVinke** [comment]
This seems like an edge case and like you said, Telerik does not support this. I'd rather not take this on right now, but if more people request this feature then we can give it a shot
