### ISSUE TITLE
Custom element binding in listview template

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-kendoui-bridge#511]
Hi,

I am trying to bind the values in the custom element which I added in the template of the listview. However, the bindings are not getting the values. Here is the code:

https://gist.run/?id=3bdaf916c3f27f15c98514052fa83328

Thanks in advance!

**Comment by JeroenVinke** [comment]
https://gist.run/?id=ef1d067516f14c8b8dff04d7c4bf24ce seems to work

**Comment by JeroenVinke** [comment]
I am going to take a guess that you forgot to use dashes in html instead of capital letters:

`<convert fileName='filename'>` -> `<custom file-name.bind="filename">`

**Comment by genericuser-me** [comment]
I feel so silly about this!!

Thanks

**Comment by JeroenVinke** [comment]
glad that it works!
