### ISSUE TITLE
Sample tests using aurelia-testing

### ISSUE THREAD

**Issue by rinobatin** [aurelia-ui-toolkits/aurelia-kendoui-bridge#513]
Anyone who has an example of a unit test using aurelia-testing? The component under test must have a kendo widget.

My component works fine when browsing the site but not with unit test (jasmine/karma). ```kendoTree``` is undefined in ```attached()``` and aborts the test. But even if ```attached()``` is removed, ```kendoTree``` is still undefined and the test fails.

```
//VIEW
<template> 
    Tree
    <div ak-treeview="k-data-source.bind: treeDS; 
        k-data-text-field.bind:'label';
        k-widget.bind:kendoTree;"
        id="tree">         
    </div>
 </template>
```

```
//VIEW MODEL
export class Tree {
    private kendoTree: kendo.ui.TreeView;

    @delayed() 
    attached() {
        this.kendoTree.expand('.k-item'); 
    }
}
```

```
//TEST
import {StageComponent} from 'aurelia-testing';
describe('tree', () => {
    let component;
beforeEach(done => {

    component = StageComponent.withResources('app/tree').inView(`<tree></tree>`);
    done();
  });

it('test', done => {
   component.create().then({       
       expect(component.viewModel.kendoTree).toBeDefined()
   }).then(done)

});
}
```

**Comment by JeroenVinke** [comment]
@rinobatin would you mind to create a clone to skeleton-navigation where you demonstrate this issue?

**Comment by JeroenVinke** [comment]
Please track https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/551
