### ISSUE TITLE
double click on listview item

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-kendoui-bridge#514]
```
<template>
    <require from="./selection.css"></require>
    <ak-list-view k-data-source.bind="dataSource"
                 k-selectable="multiple"
                 k-widget.bind="listView"
                 k-on-data-bound.delegate="dataBound()"
                 k-on-change.delegate="change()">
      <ak-template>
        <div class="product" k-on-dblclick.delegate="onListviewItemDblClick()">
            <img src="${ProductID}.jpg" alt="${ProductName} image" />
            <h3>${ProductName}</h3>
            <p>${UnitPrice}</p>
        </div>
      </ak-template>
    </ak-list-view>

    <div ref="pager" class="k-pager-wrap"></div>
</template>
```

Is is possible something like this: k-on-dblclick.delegate="onListviewItemDblClick()"

to have double click here for each item of the listview?

Thanks!

**Comment by JeroenVinke** [comment]
I looked at the [API](http://docs.telerik.com/kendo-ui/api/javascript/ui/listview#events) and there doesn't appear to be a dbl click event. Try the DOM event `dblclick` though:

`dblclick.delegate="onListviewItemDblClick()"`

**Comment by genericuser-me** [comment]
dblclick is not triggered as it goes for onchange event.

**Comment by JeroenVinke** [comment]
https://gist.run/?id=ea101b1acd0e9a1c64cd82efab47b0f6 demonstrates this issue. I think that this is related to https://github.com/aurelia/templating/issues/318

**Comment by JeroenVinke** [comment]
OK, if you put a div around the template it works:

https://gist.run/?id=487e703dbd235480ea1da5ae5dae727c

``` 
        <div>
          <div class="product" dblclick.delegate="dblClicked($event)">
              <img src="http://demos.telerik.com/kendo-ui/content/web/foods/${ProductID}.jpg" alt="${ProductName} image" />
              <h3>${ProductName}</h3>
              <p>${UnitPrice}</p>
          </div>
        </div>
```

**Comment by genericuser-me** [comment]
Works! Thanks a lot!
