### ISSUE TITLE
Kendo PRO is now available on NPM

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#518]
http://docs.telerik.com/kendo-ui/intro/installation/npm

**Comment by smax48** [comment]
I tried to use kendo pro from the telerik's npm repository with the bridge, but there is a problem:
aurelia-kendoui-bridge uses kendo components with the ".min" suffix (e.g. kendo.data.min).
But the kendo ui npm repository doesn't contain any minified files at all... So nothing works :(

**Comment by JeroenVinke** [comment]
@smax48 are you using jspm or webpack?

**Comment by smax48** [comment]
I am using jspm... I can switch to webpack in theory, but AFAIK aurelia-kendoui-bridge haven't supported this yet.

**Comment by JeroenVinke** [comment]
I strongly recommend using the bower endpoint instead: https://aurelia-ui-toolkits.gitbooks.io/kendoui-sdk-installation/content/jspm_based-installation/kendoui_pro/using_bower.html as we have had success with it before. 

But if you really want to use the npm endpoint then try the following. No guarantees though:

`npm install jspm-git --save-dev`
`jspm registry create kendo-npm jspm-git`
Enter the base URL of your git server: https://bower.telerik.com
Set advanced configurations? [no]: yes
Enable authentication? [no]:yes
Username: << your telerik username >>
Password: << your telerik password >>

`jspm install kendo-npm:npm-kendo-ui`

Even though it threw me an error it still downloaded Kendo all right
![image](https://cloud.githubusercontent.com/assets/2189477/16609128/99bf1880-4351-11e6-8386-97cae50dae62.png)

Now add the following path map to config.js's  `path` section: ``"kendo.*.min": "jspm_packages/kendo-npm/npm-kendo-ui@2016.3.607/js/kendo.*.js"``. This maps all `kendo.button.min` imports to `kendo.button` so the unminified files are used.

This one too: `"kendo-ui/*": "jspm_packages/kendo-npm/npm-kendo-ui@2016.3.607/js/*"`


Then add the following statements to your app.html:

```
 <require from="kendo-ui/css/web/kendo.common.css!"></require>
 <require from="kendo-ui/css/web/kendo.bootstrap.css!"></require>
```

**Comment by JeroenVinke** [comment]
Just noticed that the endpoint is actually the same as mentioned [here](https://aurelia-ui-toolkits.gitbooks.io/kendoui-sdk-installation/content/jspm_based-installation/kendoui_pro/using_bower.html). So it's not a real npm endpoint. I'd just follow these instructions: https://aurelia-ui-toolkits.gitbooks.io/kendoui-sdk-installation/content/jspm_based-installation/kendoui_pro/using_bower.html

**Comment by smax48** [comment]
Well, my reasons to use npm are slightly different :)
We have a private npm repository where I put a copy from `bower.telerik.com/npm-kendo-ui.git` (This is NOT the same repo as the default bower repo from Telerik).
Now I want to use this instead of the bower's one only because it is a bit easier to set up a dev environment (you can use a direct pre-authenticated url instead of jspm-git configuration everywhere)
Thanks for the suggestion about path map - I will try this!
