### ISSUE TITLE
Implement Effects

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#52]

**Comment by JeroenVinke** [comment]
I'm not sure if we can do this one

http://demos.telerik.com/kendo-ui/fx/expand

These effects are all initialized from code and I do not see a way to let a custom element / custom attribute do it (at least not in a way that's going to be useful for anyone). For example, effects are done when on a mouse click or when something has loaded. Our wrappers makes the initialization part of controls easier, and I believe we already agreed that wrappers won't help with these sort of use cases

**Comment by adriatic** [comment]
You **are right** in my opinion as well. Let's skip that for now (at least)
