### ISSUE TITLE
Kendo menu inside grid toolbar - context lost

### ISSUE THREAD

**Issue by mbenedyk** [aurelia-ui-toolkits/aurelia-kendoui-bridge#520]
Im  trying to use 'ak-menu' inside 'ak-grid-toolbar' but aurelia is loosing context and throws errors:

`filter is not deined`

example:
```
<ak-grid k-widget.two-way="ordersGrid"
							k-sortable.bind="true"
							k-selectable.bind="true"
							k-on-change.delegate="onOrdersGridChange()"
							k-on-data-bound.delegate="onOrdersGridDataBound()">
	<ak-grid-toolbar>
		<label class="category-label" for="category">${filter.orderStates}</label> <!--HERE OK-->
		<ak-template>
			<label class="category-label" for="category">${filter.orderStates}</label> <!--HERE ERROR-->

			<ul ak-menu>
				<li>
					test
				</li>
			</ul>
		</ak-template>
	</ak-grid-toolbar>
	....
```

does someone enforced similar problems?

**Comment by adriatic** [comment]
Can you please try the same "composition" with original KendoUI? This is more likely bug in KendoUI itself

**Comment by JeroenVinke** [comment]
I looked at this issue and found that it is a bug in the bridge. Apparently there can only be one toolbar, and when there is a toolbar template it needs to be passed to kendo like this:

```
{
   toolbar: () => 'some template'
}
```

What we passed was this:

```
{
  toolbar: [{ template: () => 'some template'}]
}
```

**Comment by JeroenVinke** [comment]
@mbenedyk can you update to 0.10.5 (jspm install aurelia-kendoui-bridge) and verify that it works for you?

**Comment by mbenedyk** [comment]
im having problems with update but asap ill let you know

**Comment by mbenedyk** [comment]
im unable to update aurelia bridge now, its breakes my aurelia setup

**Comment by JeroenVinke** [comment]
Is it something we can help you with?

**Comment by mbenedyk** [comment]
Soon I`ll update all aurelia components... so if you can wait
