### ISSUE TITLE
Bootstrap's JavaScript requires jQuery, due to documentation error

### ISSUE THREAD

**Issue by len-ro** [aurelia-ui-toolkits/aurelia-kendoui-bridge#522]
It can be replicated as follows:

- install aurelia typescript skeleton navigation beta 1.2.6
- run npm install && jspm install -l
- run jspm install css jquery aurelia-kendoui-bridge (as specified in the doc)
- run jspm update
- run gulp watch

The skeleton will show the following error:
`Bootstrap's JavaScript requires jQuery`

The is due to the jquery update to 3.0.0 instead of 2.x. The solution is to run jspm install css aurelia-kendoui-bridge (without jquery) since jquery is already installed. Should update: http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/vendors

**Comment by JeroenVinke** [comment]
Thanks for reporting this :+1: 

Previously the bridge had a dependency on jquery. This allowed us to lock down jquery to a specific version when there were compatibility problems with a jQuery version, but it also caused some problems. For example, it was difficult to use a different jQuery version than what the bridge had as a dependency. It was also difficult to use jQuery from a different location, or not through JSPM at all. So we removed the dependency.

What if we modify `jspm install css jquery aurelia-kendoui-bridge` to `jspm install css jquery@2.2.3 aurelia-kendoui-bridge`?

**Comment by len-ro** [comment]
As far as I can see, jquery is also installed in the typescript skeleton navigation app. At a quick look it seems to be installed in the others also. I would specify that the install doc described here applies to the skeleton navigation app. 
It seems to be a related issue: https://github.com/aurelia/bundler/issues/92 maybe the solution described here can be extended for the bridge also.

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/527#issuecomment-228662120
