### ISSUE TITLE
Support for filtermenu

### ISSUE THREAD

**Issue by mbenedyk** [aurelia-ui-toolkits/aurelia-kendoui-bridge#524]
Hi,
is there any support for kendos [filterMenu](http://docs.telerik.com/kendo-ui/api/javascript/ui/filtermenu) or [popup](http://docs.telerik.com/kendo-ui/api/javascript/ui/popup)?
Or is it planned to be?

**Comment by JeroenVinke** [comment]
Thanks, we will add those

**Comment by JeroenVinke** [comment]
these are now in the beta branch. instructions will follow about when (and how) to update your app to the beta bridge
