### ISSUE TITLE
Need a Custom element for handling Treeview Node Manipulation

### ISSUE THREAD

**Issue by ajdisalvo72** [aurelia-ui-toolkits/aurelia-kendoui-bridge#526]
The Treelist has the custom element, "ak-tree-col", that can be used to manipulate a specific column for a Treelist. 

There is no comparable custom element for manipulating a specific node in a treeview. 
We need a custom element, such as "ak-tree-node", that will meet this need.

**Comment by JeroenVinke** [comment]
[here](https://gist.run/?id=2bbb4594dcc6fcd6a779c9afbb6532b8) is a workaround

**Comment by JeroenVinke** [comment]
Tried to convert `ak-treeview` to a custom element but the drag and drop functionality broke (not sure why yet):

![image](https://cloud.githubusercontent.com/assets/2189477/17275773/afd221a0-5713-11e6-926e-4ad9346338e5.png)

parked this in the tree-view-custom-element branch to investigate

**Comment by JeroenVinke** [comment]
The treeview custom attribute has been converted to a custom element so `ak-template` can be used:

```
<template>
  <ak-treeview k-data-source.bind="dataSource" id="treeview">
    <ak-template>
      <span class="title">${text}</span> 
    </ak-template>
  </ak-treeview>
</template>
```

This is in the beta version of the bridge which is currently a prerelease, I'd recommend to wait for instructions on when (and how) to update to beta as it contains a few breaking (but necessary) changes

**Comment by adriatic** [comment]
> The treeview custom attribute has been converted to a custom element so ak-template can be used:

I like this a lot!

**Comment by ajdisalvo72** [comment]
I am now using this feature on my application.. I really appreciate the time put into this.. It is making development a of my app a lot easier.. Thanks
