### ISSUE TITLE
jQuery 3 not working with Kendo

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#527]
```
es6.promise.js:94 Error: jQuery is not defined
    Error loading http://localhost:4703/jspm_packages/npm/aurelia-kendoui-bridge@0.10.5.js
    at http://localhost:4703/vendors/js/kendo.core.min.js:26:17871
```

- Doesn't seem to work with bootstrap either (https://gitter.im/adriatic/Aurelia-KendoUI?at=575ade826092456f6632ee8c)
- Adding custom metadata doesn't seem to  work:
```
  meta: {
      "jquery/dist/jquery.min": {
          "format": "global",
          "exports": "jQuery"
      }
  },
```

**Comment by Thanood** [comment]
I didn't see it anywhere but did they change it so jQuery doesn't add a global when loaded in a modular environment? Like UMD does..

**Comment by JeroenVinke** [comment]
That's my guess :)

**Comment by JeroenVinke** [comment]
Perhaps the [override](https://github.com/jspm/registry/blob/master/package-overrides/npm/jquery%402.1.4.json) isn't applied anymore because it is a major version update?

**Comment by Thanood** [comment]
When I create a local override it gets removed.

`Removing unused package.json override npm:jquery@^3.0.0`

tried this:
```
  "overrides": {
    "npm:jquery@^3.0.0": {
      "format": "amd"
    }
  }
```

**Comment by JeroenVinke** [comment]
This is now a known issue with jspm/systemjs: https://github.com/monterey-framework/shell/issues/2#issuecomment-228120359.
