### ISSUE TITLE
Problem with bundling aurelia-kendoui-bridge

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#531]
Hey,
i m using the es6 skeleton and try to bundle all files now.
i have a vendor folder that include all Kendo core files. 
When i type `gulp bundle`, i get ` gulp-notify: [Error running Gulp] Error: C:/projects/skeleton-es2016/src/vendors/js/kendo.all.min.js: Argument name clash in strict mode (76:3565)`.

Should i change anything to make it work?

**Comment by JeroenVinke** [comment]
Please check [this article](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/bd-notes/on_bundling.html and [this config with bundling](https://github.com/aurelia-ui-toolkits/demo-kendo/blob/master/build/bundles.js#L66-L85)

**Comment by eliavmaman** [comment]
@JeroenVinke i still find it difficult to implement.
here is my skeleton project
![image](https://cloud.githubusercontent.com/assets/6911449/16176304/c4f55be0-3613-11e6-8284-4082d5f3baa4.png)
the vendors folder contains all kendo file which failed to bundle.
This is my bundle.js
![image](https://cloud.githubusercontent.com/assets/6911449/16176324/67218c9a-3614-11e6-887c-5d002a5b50c0.png)
I've added the exclude section and declare the src/vendor folder to do not get bundle.

Any idea mate?

**Comment by JeroenVinke** [comment]
I would put the vendors folder outside of the src folder ([link to instructions](https://aurelia-ui-toolkits.gitbooks.io/kendoui-sdk-installation/content/jspm_based-installation/kendoui_pro/using_%60vendors%60_folder.html)), then you need to make sure you have a this line in the `paths` section of config.js:

`"kendo-ui/*": "vendors/*"`

You will probably need to change your `app.html` as well so that it uses the `kendo-ui` map:

```
 <require from="kendo-ui/styles/kendo.common.min.css!"></require>
 <require from="kendo-ui/styles/kendo.bootstrap.min.css!"></require>
```

Then you can add [this bundle configuration](https://github.com/aurelia-ui-toolkits/demo-kendo/blob/master/build/bundles.js#L66-L85) and you probably don't need this anymore:

```
"excludes": [
  "[src/vendors/**/*.js]"
]
```

**Comment by eliavmaman** [comment]
10x man i'll try that

**Comment by eliavmaman** [comment]
@JeroenVinke sorry for not reply yesterday, was struggled with the bundle issues.
i did exactly what u said,
i get this error now when i bundle. 
It's looks like the 
the jquery.min.map file in vendor folder cozing the issue..

![image](https://cloud.githubusercontent.com/assets/6911449/16194936/e80a8528-36ff-11e6-9b40-7498131c81ea.png)


have u seen that b4?

**Comment by JeroenVinke** [comment]
Nope, haven't seen that before. It's weird because it shouldn't be bundling .map files.What does your bundle config look like now? Also, if you don't mind you could also remove the .map files from the folder

**Comment by eliavmaman** [comment]
remove the map files from vendor folder?

**Comment by JeroenVinke** [comment]
Yes

**Comment by eliavmaman** [comment]
my bundle.js:
![image](https://cloud.githubusercontent.com/assets/6911449/16195880/3b7d6c80-3704-11e6-8863-384949011593.png)

**Comment by eliavmaman** [comment]
my jspm v is 0.16.15

**Comment by eliavmaman** [comment]
@JeroenVinke sorry for asking that, but i feel i quite misunderstood the integration between the config.js and bundle.js. when i first saw aurelia movie, it's sayed that we don't really need to touch it. but it seem that there is a lot to deal with the config files.

and i don't mind to to that ' it just i really want to understand the configuration of an aurelia project a bit more then JSPM install this and that.
May b a good article or short explanation and i'll buy u a beer.

**Comment by eliavmaman** [comment]
I dont know what to do...
now gulp bundle ,watch ,build they are all stuck after css
![image](https://cloud.githubusercontent.com/assets/6911449/16197011/03e512f0-3709-11e6-8b5c-98511c1031c7.png)

**Comment by JeroenVinke** [comment]
@eliavmaman keep an eye on https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/534, hopefully that will help you out

**Comment by JeroenVinke** [comment]
@eliavmaman https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/app_developers_notes/bundlingstep_by_step_instructions_md.html should help you out, and if it still doesn't work then something is probably wrong in your setup
