### ISSUE TITLE
Slots timing issue

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#532]
> I was away with other stuff for a while, but have been trying to understand what goes wrong here. It seems like there are some timing issues in aurelia-templating 3.x, your 0.11.1 bridge or my code (not sure which)... I tried some other promise libraries, but nothing changed, also I realized that core-js (which I'm using in this project) also has a promise polyfill.
Anyhow, my app is based on "tabs" with different "widgets" on them, which means I load/unload the grid widgets using compose bindings and I noticed that when I switch to my second "tab" and then back to the first my first grid looks fine. Both with bluebird running in Chrome and in Firefox/IE11/Edge without it. The other grids on the page however still stay ugly as do all grids the first time they're loaded.

**Comment by charlespockert** [comment]
@JeroenVinke  This might be related to this: https://github.com/aurelia/templating-router/pull/29

Was a bug in the layouts feature I added where viewslots were not being cleared down properly when you switched routes - not sure if related but worth a look. 

Who was it that had the issue?

**Comment by JeroenVinke** [comment]
ping @Souldrinker

**Comment by charlespockert** [comment]
Might not be that - but just a hunch, if some viewslot trickery was going on kendo might have got upset...

**Comment by Souldrinker** [comment]
It seems like you fixed my issue with the latest kendoui-bridge (0.11.2) and aurelia-templating (3.0.6), now it works in all browsers with or without bluebird :-)

The only issue I ran into was that your ```@delayed``` decorator doesn't seem to work as it should anymore.

Before I knew about that decorator I had to have a ```setTimeout, 0``` block with stuff I wanted to do with the grids in attached (remove some column based on configuration, add tooltips etc.). Now with the latest releases the grid wasn't initialized in attached, so I had to re-add the setTimeout to get stuff working.

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/templating/issues/379#issuecomment-228553570

**Comment by JeroenVinke** [comment]
Getting mixed results here

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/templating/issues/403

**Comment by JeroenVinke** [comment]
closing this as we don't need `@children` anymore
