### ISSUE TITLE
ak-menu kendoUI openOnClick

### ISSUE THREAD

**Issue by mbenedyk** [aurelia-ui-toolkits/aurelia-kendoui-bridge#533]
Hi,

1. I`m unable to bind this option on HTML element
2. when I set this option via javascript its behave indeterministic

- hover on menu element - menu does not appear: as expected
- click on menu element - menu appears: as expected
- click again on menu element to close it: as expected
- open menu again
- close menu by clicking outside menu content
- hover on menu element: menu appears! bug?

only way to get back to correct state is to click on menu element when its open

**Comment by JeroenVinke** [comment]
Hi @mbenedyk 

I can't seem to reproduce this: http://screencast.com/t/ZFq57ObxK

The following gist is used: https://gist.run/?id=4a6466618ab48f20101202a4bdee9b62

**Comment by mbenedyk** [comment]
Hello @JeroenVinke 
It`s seems that i made mistake in my html, thanks for help.

But im wondering why I have to bind certain options in different way, eg:

`<ul ak-menu="k-open-on-click.bind: true" k-on-open.trigger="beginEdit()" k-on-close.trigger="cancelEdit()">`

k-on-open and k-on-close works only if I bind them in such a way, inside ak-menu="..." they just dont work

**Comment by JeroenVinke** [comment]
@mbenedyk glad that it works :)

The difference between `k-open-on-click` and `k-on-open` is that the former is a property on the Kendo control and the latter is an event that's raised by the kendo control. I always use the [API documentation](http://docs.telerik.com/kendo-ui/api/javascript/ui/menu#configuration-openOnClick) of Telerik to know which properties and events are available for a specific control. Then I apply our [conventions](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/what_you_need_to_know.html) to be able to use the properties/events on our wrappers.

In the API documentation we see that `openOnClick` is a property (it's in the configuration section of the docs):
![image](https://cloud.githubusercontent.com/assets/2189477/16221057/f6be1da0-3790-11e6-88e5-b9fdb6fbf802.png)

and that open is an event:
![image](https://cloud.githubusercontent.com/assets/2189477/16221052/ecc1aefc-3790-11e6-807b-153242a60a93.png)

So we set the `k-open-on-click` property and subscribe to the `k-on-open` event.

The bridge delegates events through DOM events, which means that event handlers for events should be registered on the HTML element (`<ul>` in this case).

To add to the complexity is that setting properties on custom attributes is different than setting properties on custom elements.

```
<ul ak-menu="k-open-on-click.bind: true">
```

vs

`<ak-grid k-sortable.bind="true">`

Hopefully that helps you a bit

**Comment by mbenedyk** [comment]
Thanks a lot
