### ISSUE TITLE
Create grid dynamically

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-kendoui-bridge#535]
Hi,

Is there any way to create grid dynamically using aurelia kendo bridge, here is the example of regular kendo grid: http://jsbin.com/viqaxoxi/1/edit?html,css,js,output

Thanks!

**Comment by JeroenVinke** [comment]
Something like this perhaps? https://gist.run/?id=cd61743f6173270e4220a7422180423b

**Comment by genericuser-me** [comment]
Cool, that works!

I am having difficult to get create/update/delete to work. Can you please help?

```
data = getData();
 this.datasource = new kendo.data.DataSource({
      transport: {
        read: function(e){
          e.success(data);
        },
        update: {
         // how to get update to be called when there is inline editing without the edit button on the grid. 
        },
        destroy: {
       // to remove the element from the db as well, not just the dataset
        },
        create: {
          url: crudServiceBaseUrl + '/Products/Create',
          dataType: 'jsonp'
        },
        parameterMap: function(options, operation) {
          if (operation !== 'read' && options.models) {
            return {models: kendo.stringify(options.models)};
          }
        }
      },
});
```

**Comment by JeroenVinke** [comment]
Please refer to the official kendo documentation, we are not Kendo experts so we can't always help you with issues that are not related to the bridge.

But to answer your question: if you want to handle update/destroy and create events of the datasource you need to supply a function:
```
update: function(e) {
  // update entities here
},
```

**Comment by genericuser-me** [comment]
That didnt work. Thanks for your help!
