### ISSUE TITLE
grid data source not working after bundle

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#536]
using es6 skeleton,
i success to bundle my app to dist folder correctly.
the bundling cox an error with reading the datasource.
![image](https://cloud.githubusercontent.com/assets/6911449/16233370/c651bc8a-37d6-11e6-8c42-16387132ba1d.png)

and here is the grid
![image](https://cloud.githubusercontent.com/assets/6911449/16233545/74e68f96-37d7-11e6-92d1-28824cd8f4a4.png)
before bundle everything works just fine.

the error i get after bundle
`app-build.js:1 Uncaught (in promise) TypeError: Cannot read property 'setDataSource' of undefined`

it's look like that the `this.grid.setDataSource(this.datasource1);`  grid variable is undefind from some reason.

What to do?

**Comment by eliavmaman** [comment]
any idea?

**Comment by JeroenVinke** [comment]
I was just working on a gist for this :)

I guess that timing issues are most likely. Because it is bundled now, everything loads more quickly and that may give you different results when the app is bundled vs when it is not bundled. 

Try using [this pattern](https://gist.run/?id=76e2e1185908703dfb9d917edcf506fc) instead

**Comment by JeroenVinke** [comment]
The idea is that the datasource gets created once in the constructor, and the datasource instance never changes again. That way, the grid will never lose the connection to the datasource.

**Comment by eliavmaman** [comment]
@JeroenVinke 10x for reply.
my problem is that if i dont create ` new kendo.data.DataSource` every time i retrieve new data. the grid is not change.
with your solution i can retrive the data only once..

**Comment by eliavmaman** [comment]
i guess my question is , how can change the data of the kendo datasource evry time without creating new datasouce ?

**Comment by eliavmaman** [comment]
@JeroenVinke  i'm still checking...

**Comment by eliavmaman** [comment]
@JeroenVinke your [Gist](https://gist.run/?id=76e2e1185908703dfb9d917edcf506fc) did solved my problem 10x.

what I've noticed now is that for every row in the grid i have a click event that fire event with params.
There is a component that listening to that event and takes the param and fetch data, same way we did b4 (as you suggested and works amazing).

the problem is i `console.log(data)` and i see the data correctly fetching, but the grid component not loaded and there is no error at all.
i was trying to improve your GIST but after long straggle i quit. 
what could be the reason that the grid not loded?

**Comment by eliavmaman** [comment]
the inner component
![image](https://cloud.githubusercontent.com/assets/6911449/16267629/87e905d0-3893-11e6-8354-33699075d16e.png)

this is the api object
![image](https://cloud.githubusercontent.com/assets/6911449/16267698/d6318096-3893-11e6-8fb0-fe7a43100708.png)


And the constructor:
![image](https://cloud.githubusercontent.com/assets/6911449/16267735/fe03df42-3893-11e6-9bd2-9034bec607be.png)

**Comment by JeroenVinke** [comment]
don't you need to return the promise?

```
return new Promise(resolve => {
  return this.api.getPokerCashData().then(res => resolve(res));
});
```

But why are you doing this through a new `apiObj`?

You should be able to do this:

```
transport: {
  read: (options) => {
     this.api.getPokerCashData()
     .then(data => options.success(data));
  }
}
```

**Comment by eliavmaman** [comment]
Well , basically they both works, but you right.
just thought it will b more organized having this object with all requests.  
any way the inner grid still not loaded. and the data is fetching.
What else can i check?

**Comment by JeroenVinke** [comment]
I don't know man, could you [gist](https://gist.github.com/) your entire .html and .js for that screen?

**Comment by eliavmaman** [comment]
will try again

**Comment by eliavmaman** [comment]
@JeroenVinke  this is the [gist](https://gist.run/?id=e5303ea29918fb732d4a7e665e7e2ce3) i have created. the inner component not rendered for some reason.

it there any way i can share my project with u?

**Comment by eliavmaman** [comment]
Problem solved. my problem  was  after bundling the app-build had an error , which fucked up every thing. 

@JeroenVinke u r KING.
10x for everything

**Comment by JeroenVinke** [comment]
:+1:
