### ISSUE TITLE
problem with custom attribute after bundling

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#537]
hey 
I created custom attribute to show and hide grid column based condition.
here is [gist ](https://gist.run/?id=603a3da95476ab07078a31fde1bd1d5f) show my problem.
after bundle the `this.grid = this.parent.element.find(".k-grid").data("kendoGrid");`

after bundle - `this.grid` is undefined.

@JeroenVinke sorry for all the questions :)

**Comment by JeroenVinke** [comment]
Perhaps [this solution](https://gist.run/?id=23208d9db6a09c7ab6ac2e1dbc0f65b6) works better. I also believe that this is caused by timing issues..

**Comment by eliavmaman** [comment]
@JeroenVinke it's solved my problem.  you r genius :) 10x.
How come i didn't thought of that.
