### ISSUE TITLE
Missing TypeScript definitions in 0.11.2

### ISSUE THREAD

**Issue by smax48** [aurelia-ui-toolkits/aurelia-kendoui-bridge#538]
After update to version 0.11.2 of the bridge & aurelia RC 1.0.0 I have the following TypeScript compilation issues:
```
aurelia-kendoui-bridge@0.11.2/aurelia-kendoui-bridge.d.ts(33,5): Module ''aurelia-binding'' has no exported member 'Lexer'.
aurelia-kendoui-bridge@0.11.2/aurelia-kendoui-bridge.d.ts(34,5): Module ''aurelia-binding'' has no exported member 'ParserImplementation'.
aurelia-kendoui-bridge@0.11.2/aurelia-kendoui-bridge.d.ts(598,28): Cannot find name 'BindingToKendo'.
```

It seems that the first two are just not declared in aurelia-binding.d.ts, the last one (BindingToKendo) previously was declared as interface in aurelia-kendoui-bridge.d.ts ...

**Comment by JeroenVinke** [comment]
Both errors should be gone in 0.11.4: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/dist/system/aurelia-kendoui-bridge.d.ts
