### ISSUE TITLE
Investigate integration with aurelia-cli

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#539]
https://github.com/aurelia/cli/issues/187

**Comment by JeroenVinke** [comment]
the following issues are preventing this from working right now:

1. requirejs doesn't support wildcards in path mappings, so the named modules of Kendo have to be added to the config one by one
2. kendo files aren't bundled, even though I added them to a bundle
3. module is not defined error for every loaded Kendo file (this may be resolved if the above issue gets fixed)
4. path mappings are ignored by aurelia-cli. I have locally fixed this so we should be able to create a PR for that

**Comment by adriatic** [comment]
I am adding to this thread with the intent to synchronize several different but related issues:

1. Our today's discussion in `shell chat room` starting form [June 30, 2016 9:28 AM](https://gitter.im/monterey-framework/shell?at=57751e91bb1de91c54b772aa)

2. [create full stack skeleton for @bdenham](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/541)

3. Work I am doing to verify that most interesting skeletons work with webpack (this work will be published in [this book](https://www.gitbook.com/book/aurelia-ui-toolkits/verifying-webpack-support-for-aurelia-bridges/details).

**Comment by JeroenVinke** [comment]
new bridge works with aurelia-cli, the installation instructions are tracked https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/570

**Comment by prsmith1** [comment]
Hi - Are there any instructions for adding the kendo bridge to a virgin Aurelia CLI project? Also, is it possible to do this only using NPM, not JSPM?

I have tried this a few different times in a few different ways but am having no luck.

**Comment by JeroenVinke** [comment]
@prsmith1 Hi, we have some instructions [here](https://aurelia-ui-toolkits.gitbooks.io/kendo-ui-sdk-installation-beta/content/installation/installing%20the%20bridge/requirejs.html)

**Comment by prsmith1** [comment]
Great - thanks. I forgot about the beta version of the bridge!
