### ISSUE TITLE
create full stack skeleton for @bdenham

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#541]
#### Continuation of [Add integration of aurelia-kendoui-bridge](https://github.com/aurelia/cli/issues/187)
***
Ok. I need to integrate with this existing project:
ASP.NET Web Application project using .NET framework 4.5.2.

Current structure:
[asp net_project_structure](https://cloud.githubusercontent.com/assets/1828494/16319239/04a27eb6-3958-11e6-9c1d-0950a074e1af.png)

Client (aka, src or app) can be setup however is best. Currently it looks like this, a feature-based hierarchy:
[client_folder](https://cloud.githubusercontent.com/assets/1828494/16319404/c6517198-3958-11e6-857e-d37b62a35769.png)

**Comment by bdenham** [comment]
Just for clarity, common things to integrate into project:

1. Any/All Aurelia modules.
2. KendoUI Pro controls.
3. Bonus: CSS module loader for scoping CSS to components.

Let me know if you need any more details. And many thanks!

**Comment by JeroenVinke** [comment]
@bdenham do you still need this?

As you may now, we are working on a new version of the bridge that makes the installation process much easier. In addition we are rewriting the installation instructions.

**Comment by JeroenVinke** [comment]
Closing this for now, the beta bridge (and documentation) is about to be released
