### ISSUE TITLE
k-widget binding doesn't work with bridge 0.11.2 and Aurelia RC 1

### ISSUE THREAD

**Issue by smax48** [aurelia-ui-toolkits/aurelia-kendoui-bridge#542]
I have a binding like `k-widget.bind="kendoList"` and try to access `this.kendoList` in the `@delayed() attached(){...}` event. It worked with previous versions of bridge and aurelia, but doesn't work now (`this.kendoList` is undefined). This happens at least for DropDownList & Grid.

**Comment by JeroenVinke** [comment]
Hey @smax48, thanks for reporting this issue. Can you try and update the bridge to 0.11.3? `jspm install aurelia-kendoui-bridge`

**Comment by smax48** [comment]
Hi @JeroenVinke, thanks for the fix! With 0.11.3 it seems to be working as before :).
However, at the moment I have to manually edit aurelia-kendoui-bridge.d.ts because of the issue #538 ...

**Comment by JeroenVinke** [comment]
Great :+1:  we'll get the typescript definition fixed
