### ISSUE TITLE
make all gists owned by aurelia-tools-gists

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#544]
This way the team can share this account's credentials whenever having to edit these gists

**Comment by adriatic** [comment]
Created the new GitHub account `gist-master` with the email `aurelia-tools-gists@aureliatools.com`

See @adriatic or @JeroenVinke for the password

**Comment by adriatic** [comment]
I started this task by creating the **[list](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/files/335912/gists-list.txt)** of all gists in the catalog app and planned to use the context menu in sublime editor:

 
![gist-run](https://cloud.githubusercontent.com/assets/2712405/16397354/ed3ec03a-3c91-11e6-923e-50d202e8f960.png)

This click results with 

![gist-run-1](https://cloud.githubusercontent.com/assets/2712405/16397472/b105b44c-3c92-11e6-84ab-966020036519.png)

Alternatively, if I use gist editor, I cannot find the gist that I know exists. Even if it was created as secret, I believe that I should be able to get it if I request it by its id ???

![image](https://cloud.githubusercontent.com/assets/2712405/16397511/e97114d4-3c92-11e6-9ac6-47fb8ebab767.png)

___At this point I created support request to GitHub.___

**Comment by adriatic** [comment]
I am getting nowhere with Github support:

![image](https://cloud.githubusercontent.com/assets/2712405/16420378/13b9ae68-3d1f-11e6-89de-8732532dcf47.png)

and then

![image](https://cloud.githubusercontent.com/assets/2712405/16420426/49b36734-3d1f-11e6-9631-9e3422fef362.png)

**Comment by adriatic** [comment]
It might be best to create a small electron app that can handle this and other similar issues that might pop-up in the future. Making it an electron app will allow someone to practice electron development.

As a start, use https://github.com/fxding/greader application - and make the needed changes (using gists API: https://developer.github.com/v3/gists/)

This app should:

1. Authenticate itself to GitHub using the `gist-master` account.

2. Read the list of KendoUI Bridge Catalog applications gists

3. For each element of this list:

 3.1. Fetch the gist by ID defined in that element.

 3.2 Create a new gist (which will be owned by `gist-master`

 3.3 Copy the content of the original gist to this new `gist-master` owner gist

 3.4 save the ID of the old gist and ID  of the new gist (for subsequent processing)

This task will result the list of ID pairs that would then used to replace all old gist IDs with new gist IDs in the catalog app.

**Comment by JeroenVinke** [comment]
+1

**Comment by adriatic** [comment]
Since we now know that electron applications are not very different from browser applications we should write all electron applications (which could run in the browser - the above one is a good example), in the way that "moving" them between electron and browserify would result with minimal pain

**Comment by JeroenVinke** [comment]
This is done
