### ISSUE TITLE
Update/Delete/Add event for Datagrid

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-kendoui-bridge#545]
In reference to [535](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/535)

Only able to bind data using "read". None of the other functions seem to work:

```
data = getData();
 this.datasource = new kendo.data.DataSource({
      transport: {
        read: function(e){
          e.success(data);
        },
        update: {
         // how to get update to be called when there is inline editing without the edit button on the grid. 
        },
        destroy: {
       // to remove the element from the db as well, not just the dataset
        },
        create: {
         // to get the item created in the db
        },
        parameterMap: function(options, operation) {
          if (operation !== 'read' && options.models) {
            return {models: kendo.stringify(options.models)};
          }
        }
      },
});
```

**Comment by JeroenVinke** [comment]
do you mean this? https://gist.run/?id=cd61743f6173270e4220a7422180423b

**Comment by adriatic** [comment]
### @genericuser-me  
Allow me please to add a comment intended to ensure better communications in the future

If you ask for advice and present the sample in the form you wrote [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/545#issue-162516469), it is completely impossible to understand what is the problem you want to report / discuss. Basically you are saying that

```
        update: {
         // how to get update to be called when there is inline editing without the edit button on the grid. 
        },
```

does not work :-)

Luckily, @JeroenVinke was willing to spend more time on this question, guess what you actually need and propose the solution.

As you know, all members of our team do this work to help Aurelia "movement", and the major part of that work is development of new tools, leaving ___some___ extra time to ensure that the software we created is also supported, but most of the support is expected to come from our users community.

**Comment by genericuser-me** [comment]
I figured that for update to be called we need to provide schema too. However, if we connect this with 535, I was looking to create a dynamic grid, where providing schema at runtime becomes difficult.

**Comment by genericuser-me** [comment]
Also, just tried creating a json string with fields dynamically and then doing a `JSON.parse(columns)` worked just fine.

Thanks for all your time, help and guidance.
