### ISSUE TITLE
Dropdown list in kendo UI grid

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-kendoui-bridge#546]
Here is the dropdown code, which I got from [here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/editing-custom-editor):
```
myDropDownEditor(container, options) {
//var fieldName="";
            $('<input required data-text-field=\"myType\" data-value-field="id" data-bind="value:name"/>')
                .appendTo(container)
                .kendoDropDownList({
                    autoBind: false,
                    dataSource: {
                      data: this.myList
                    }
                });
    }
```
At runtime, when I click on edit button on the grid, I get the following error:
```
my-type.ts:138 Uncaught TypeError: Cannot read property 'myList' of undefined
```

Any idea?

**Comment by JeroenVinke** [comment]
The following workaround can be used here: https://gist.run/?id=3c1a0aab9ef1a0aaf037518b5d61c803

Lets keep this issue open so we can see if this can be improved in the bridge

**Comment by genericuser-me** [comment]
Thanks so much!

**Comment by genericuser-me** [comment]
When I do add new on this, the CategoryId is null, how do we get value in it for the selected item? Thanks in advance.

**Comment by JeroenVinke** [comment]
Please refer to Telerik documentation / support

**Comment by genericuser-me** [comment]
Thanks, I will look into it. Just curious, Does it work for you? I need to do this:

  ```
create: (e) => {
              e.data.CategoryId = e.data.Category == "" ? null : e.data.Category.id;
...
}
```

**Comment by genericuser-me** [comment]
The way foriegn key column is handled in traditional Telerik is: http://demos.telerik.com/kendo-ui/grid/foreignkeycolumn

They use CategoryId instead of category as shown in your example.

**Comment by JeroenVinke** [comment]
@genericuser-me not sure if I understand, are you trying to provide a default?

Because that seems possible via the schema:

![image](https://cloud.githubusercontent.com/assets/2189477/16656545/638de5e8-445f-11e6-8b18-b75a2bd578f8.png)

**Comment by genericuser-me** [comment]
When the update button is clicked on the grid, while adding a new record. The values in e.data is something like this:

`{"productId":0, "productName":"test1", category:{"id":2, name:"bbbbb"}, categoryId:"", unitPrice:10}`

I am asking why categoryId is blank and not getting the id.

**Comment by JeroenVinke** [comment]
the fix is now in the beta branch. instructions will follow about when (and how) to update your app to the beta bridge
