### ISSUE TITLE
unable to view checkbox while editing grid 

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-kendoui-bridge#547]
I am using aurelia-materialize-bridge along with aurelia-kendoui-bridge. any idea why checkbox is not shown?

 https://gist.run/?id=8c9525d604a14b0c2bb90ba3f6e5abc8-

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/199#issuecomment-229574769

**Comment by genericuser-me** [comment]
You are awesome @JeroenVinke , Thanks a ton!
