### ISSUE TITLE
null field value for kendo grid dropdown column

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-kendoui-bridge#548]
http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/editing-custom-editor

In this example what if Category is null? How do we handle that in template. I am getting error "Cannot read property 'name' of null(…)"

**Comment by JeroenVinke** [comment]
https://gist.run/?id=3c1a0aab9ef1a0aaf037518b5d61c803

**Comment by genericuser-me** [comment]
Thanks a lot!
