### ISSUE TITLE
Suport click binding inside the ak-template for the ListView control 

### ISSUE THREAD

**Issue by danielmeza** [aurelia-ui-toolkits/aurelia-kendoui-bridge#549]
When wee try to handle a click event inside the <ak-template> for the ListView control the binding not work, the event is not triggering.
```html
<template>
        <ak-list-view k-data-source.bind="dataSource">
        <ak-template>
            <div style="height:50px;position:relative;cursor:pointer" 
                 click.delegate="OnConversationClick($this)">
                    My content
            </ak-template>
    </ak-list-view>
    <div ref="pager" class="k-pager-wrap"></div>
</template>
```
```javascript
export class Example {
    dataSource = new kendo.data.DataSource({
        data: products,
        pageSize: 21
    });
    OnConversationClick(conversation: ChatConversation)
    {
        alert(conversation.Subject.Name);   
    }
    attached() {
        $(this.pager).kendoPager({
           dataSource: this.dataSource
        });
    }
}
```

**Comment by JeroenVinke** [comment]
Thanks for providing all this info! I have responded [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/429#issuecomment-230427511)

**Comment by danielmeza** [comment]
@JeroenVinke thanks you very much, it work, it is a issue or just a behavior?

**Comment by JeroenVinke** [comment]
it's not completely clear yet, hopefully it will be resolved in Aurelia but if not i'm sure we can find a solution that makes it work for everyone

**Comment by JeroenVinke** [comment]
Amazing timing from the aurelia team as a fix as just been pushed to the templating repo :smile: You'd need to wait for a release to take place though which will be announced on the aurelia blog
