### ISSUE TITLE
signal the attempt to use pro features having only core sdk

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#552]

**Comment by JeroenVinke** [comment]
I don't think there is a way to check whether kendo core or kendo pro is used. The only thing we can detect (and should given that we're about to remove the kendo imports from the bridge) is if a specific control has been loaded. We could add this warning: "Control 'kendoAutoComplete' has not been loaded. If you are using Kendo Core, please verify that the kendoAutoComplete control is part of Kendo Core".

**Comment by adriatic** [comment]
Good thinking!

**Comment by JeroenVinke** [comment]
I thought we had this check though. You are probably calling `.plugin('aurelia-kendoui-bridge', kendo => kendo.core())` in main.js, and because the bridge knows that the treeview is not part of kendo core it will therefore not load the bridge's treeview custom attribute. So when you use the treeview custom attribute in an aurelia view, aurelia takes `ak-treeview` as a simple html attribute (not an aurelia custom attribute) and will ignore it. That's probably why you're not getting an error

**Comment by JeroenVinke** [comment]
BTW, I don't like the `kendo => kendo.core()` and `kendo => kendo.pro()` calls as much as I did when we started. For example, in the installation instructions we tell people to use `kendo => kendo.pro()` which loads ALL of the control's, making the startup time of the app extremely slow, while you may only want to use the Kendo Button. Besides, the user of the application may not even hit a screen that contains a Kendo control, so why load all wrappers up front?

**Comment by adriatic** [comment]
That is precisely what happened - and it is painful to discover as I had to look into bindings of the "downloaded" instance of the bridge to find that out. This pain led me to think how to prevent this for others (I do not want to see you do that same digging for a future customer)

**Comment by adriatic** [comment]
> BTW, I don't like the kendo => kendo.core() and kendo => kendo.pro() calls 

This will all go away now - as the user will be able to create the custom-kendo.min.js and use it at the app side.

**Comment by adriatic** [comment]
My remaining problem in this bridge conversion project is how to pass the application loaded custom-kendo.min.js thing to the wrappers - like 

```
import {inject} from 'aurelia-dependency-injection';
import {customElement, ViewResources} from 'aurelia-templating';
import {WidgetBase} from '../common/widget-base';
import {generateBindables} from '../common/decorators';
import {constants} from '../common/constants';
import 'kendo.autocomplete.min';
import 'kendo.virtuallist.min';

@customElement(`${constants.elementPrefix}autocomplete`)
@generateBindables('kendoAutoComplete')
@inject(Element, WidgetBase, ViewResources)
export class AutoComplete {
...
```

unless you have some dynamic compiling trick in your slave, we should simply have the same `import 'custom-kendo.min.js'` line in all wrappers, hard-coded

**Comment by JeroenVinke** [comment]
> This will all go away now - as the user will be able to create the custom-kendo.min.js and use it at the app side.

That loads the Kendo control suite yes, but users still have to load our wrappers. I am all for loading our wrappers in the views where the controls are being used, because that means you don't have to load anything at startup time (so startup will be quick) and it will load only wrappers that are actually being used. 

```
<require from="aurelia-kendoui-bridge/grid/grid"></require>
<ak-grid>

</ak-grid>
``` 

This presents one usability issue, as the user has to know the exact path to the grid wrapper. I still think this is the best solution, so what if we remove the `kendo => kendo.pro()` thing entirely and convert all samples on the catalog to use `<require>` to import wrappers. Alongside a table in the documentation containing all `<require>` statements per Kendo control.

**Comment by JeroenVinke** [comment]
> My remaining problem in this bridge conversion project is how to pass the application loaded custom-kendo.min.js thing to the wrappers - like

We can remove the imports for kendo controls entirely, and users have to load the controls themselves:

```
import 'kendo.grid';

export class MyPageContainingAGrid {

}
```

The above would be used if they want to load Kendo through JSPM. But they can just as easily add a `<script src="custom-kendo.min.js"></script>` tag in their `index.html`

**Comment by adriatic** [comment]
A lot better approach, Jeroen. Given that even core users can run that telerik's custom builder that emits the `custom-kendo.min.js`, we could use the form of the `require` which extracts the needed widget from `custom-kendo.min.js` (like `grid` in the grid-view)

**Comment by adriatic** [comment]
I will start with `<script src="custom-kendo.min.js"></script>` tag in their `index.html` and see what else would make sense in addition to this

**Comment by JeroenVinke** [comment]
well the problem with this custom builder is that it emits a single javascript file. So you'd have to load the entire javascript file at once. The advantage of using JSPM to download Kendo (or the vendors approach) is that you're able to import a single kendo control. The downside of this approach is that it requires you to configure more (in config.js)

**Comment by JeroenVinke** [comment]
let me know if i'm not making any sense :P

**Comment by adriatic** [comment]
As always in such situations, we will leave this choice to the app developer. They can run the telerik builder in the one file per widget fashion - or all bundled in a single file. Our docs will explain the pros and cons and provide "templates" to help with configurations

**Comment by adriatic** [comment]
> let me know if i'm not making any sense :P

I will always do that - but you never give me a chance, my friend

**Comment by adriatic** [comment]
Also: Petyo will issue free pro version for the account admin@aureliatools.com, so we will be able to try all these trick in an official way.

**Comment by JeroenVinke** [comment]
> As always in such situations, we will leave this choice to the app developer. They can run the telerik builder in the one file per widget fashion - or all bundled in a single file. Our docs will explain the pros and cons and provide "templates" to help with configurations

+1

**Comment by JeroenVinke** [comment]
I think this is done
