### ISSUE TITLE
bad gitbook links in kendoui-sdk-installation book

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#555]
https://aurelia-ui-toolkits.gitbooks.io/kendoui-sdk-installation/content/jspm_based-installation/kendoUI_core/using_github.html

**Comment by JeroenVinke** [comment]
seems to be fixed

**Comment by adriatic** [comment]
Yes, but not by me or you - I am quite sure that this was a bug in GitBook server which was fixed without us knowing about it.
