### ISSUE TITLE
k-on-change.delegate not passing dataItem to viewModel

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#557]
@JeroenVinke hey.
i've added the on change event to the grid.
`k-on-change.delegate="rowSelected($event.detail)`

int the viewModel i try to get the dataItem of the selected row.  it just impossible!!!
this is how the sender looks like:
![image](https://cloud.githubusercontent.com/assets/6911449/16757715/5d07ae10-4816-11e6-891c-57c3702e6bfc.png)

in angular what i did is just get the dataItem. 
how to do the same with aurelia?

**Comment by JeroenVinke** [comment]
https://gist.run/?id=21df15d6ebd1bb7fdb342fc93398def6

**Comment by eliavmaman** [comment]
@JeroenVinke Aurelia team lucky to have you. 
10x man you save me

**Comment by JeroenVinke** [comment]
I'm not on the aurelia team but glad that it helped you :+1:

**Comment by eliavmaman** [comment]
![3845823](https://cloud.githubusercontent.com/assets/6911449/16759004/7d176dc4-481d-11e6-87a0-267933fd9f96.png)

**Comment by JeroenVinke** [comment]
Hahaha :smile:
