### ISSUE TITLE
Need to add support for webpack bundling to package.json

### ISSUE THREAD

**Issue by charlespockert** [aurelia-ui-toolkits/aurelia-kendoui-bridge#558]
See here: https://github.com/aurelia/templating-resources/blob/master/package.json#L133

This needs to add any additional files that should be included in the bundle to the package.json so that the webpack plugin knows to bundle them.

**Comment by niieani** [comment]
Just note that you should probably only globally include those resources that users will always use. In case you want modularity, you should specify in your readme, so that users declare only those resources they need. 

/maintainer of aurelia-webpack-plugin

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/2f6f4e87a53c1ef5b827467dd98427f7c20c43f4
