### ISSUE TITLE
refresh data & binding grid not working

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#561]
@JeroenVinke sorry again mate...
i have that dataSource
![image](https://cloud.githubusercontent.com/assets/6911449/16799245/819ab6f4-48f8-11e6-9fab-ab4ee526908c.png)

and there is an event listener in the view model that populate thegrid datasource like that:
```
eventAggregator.subscribe('gameSelected', response => {
            let gameAdditionalInfo = response.game;
            self.additionalInfoDatasource.read({data:gameAdditionalInfo});
        });
```

after resd function i console.log the data the grid is getting and data looks just fine.

this is my html
```
  <ak-grid k-widget.two-way="grid"
                     k-data-source.bind="additionalInfoDatasource">
                <ak-col k-hidden="true" k-field="RoundID"></ak-col>
                <ak-col k-title="Currency" k-field="Currency"></ak-col>
            </ak-grid>
```

the grid empty
![image](https://cloud.githubusercontent.com/assets/6911449/16799428/76fff6fe-48f9-11e6-870f-940f276c998e.png)

**Comment by JeroenVinke** [comment]
the only thing that looks off is `options.success(options.data)` which I think needs to be `options.success(options.data.data)`: https://gist.run/?id=a2b11925a0001bbf1ac5a37411f79a8c

**Comment by eliavmaman** [comment]
and again @JeroenVinke ... 10x man... i finally understood how to refresh the grid data hanks to u.
