### ISSUE TITLE
ak-multiselect bind to object

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#568]
Hey
I'm trying to bind the object to multiselct value. my code is
```
 <ak-multiselect
           k-auto-close.bind="false"
           k-value.two-way="selected">
            <select multiple="multiple">
                <option repeat.for="gf of list" value.bind="gf">${gf.Name}</option>
               </select>
  </ak-multiselect>
```
 what i get in `this.selected` is list of `"[Object Object]"`?
what is the right way to bind object?

**Comment by JeroenVinke** [comment]
Hey @eliavmaman 

well, the multiselect should give you an array of selected objects, which appears to be happening if you get `[Object Object]`, so i'm not sure what you're trying to achieve. [here](https://gist.run/?id=894bfe612419adff104f223a7ec002f9) you can see that it's an array of selected objects, which you can display with `repeat.for`. Can you create a [gist](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help) and tell me what you expect to happen?

**Comment by JeroenVinke** [comment]
scratch that, looks like `k-value` gives you the array of **values** (the id's)

I think youre looking for [this](https://gist.run/?id=a06ef35dd40b09e051c7bd982dc8ef8a)

**Comment by eliavmaman** [comment]
@JeroenVinke 10x man your solutions works as alwayes :)
but just a question to understand, i created this [Gist](https://gist.run/?id=9e8b786f51514f9a3c9b4b4ec8bcc2b2).
in that gist i wanted the value of the multi select to be the actual object.

in angular for e.g -
```
<select ng-model="operator">
    <option ng-repeat="operator in operators" value="{{operator.value}}">
      {{operator.displayName}}
    </option>
</select>
```
what i'm trying to achieve is that option to bind the selected object to viewModel property.
**so the second solution worked for me :) .**

but the dataItems() of the multiselct retun the object with extra data like that:

![image](https://cloud.githubusercontent.com/assets/6911449/17082448/6d1632f2-5187-11e6-9912-a83aa09c6d75.png)
.
so for now i'm using the second solution of this.multiSelect.dataItems() anf b4 sending thatselcted data to the server  i remove the extra data.
10 again
