### ISSUE TITLE
Checkboxes within listview gets unchecked

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-kendoui-bridge#569]
Hi,

I followed this example and created the listview with checkbox:
http://fiddle.jshell.net/davidmartin/epN9j/?utm_source=website&utm_medium=embed&utm_campaign=epN9j

However, here the checkbox works fine, but in aurelia the checkbox gets unchecked. Can you please help?

https://gist.run/?id=cd271837402eb9148f62a7f94186236a

updated the gist

**Comment by genericuser-me** [comment]
after removing " k-selectable="multiple" I am able to select a row once only (when click on the div ot h3 and not on the checkbox). Once I unselect, I cannot select it again. Also, I still cant check on the checkbox

**Comment by JeroenVinke** [comment]
this was resolved on gitter

**Comment by genericuser-me** [comment]
adding it for reference : https://gist.run/?id=3e68125d8fe58fe04d96e1035aab5e91
