### ISSUE TITLE
bad links from catalog app to documentation book

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#572]
I created the new branch `links-to-books` to allow @JeroenVinke to merge it with the master at proper time.

**Comment by JeroenVinke** [comment]
can I merge this? or is there more work to be done

**Comment by adriatic** [comment]
I believe that I still need to fix some links.

**Comment by JeroenVinke** [comment]
Also updated all the links in the beta documentation book
