### ISSUE TITLE
where to keep the kendo-sdk folder>

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#574]
The branch `user-installable-sdk` has this folder at the root of the catalog app - we need to define this location for the new beta bridge release

**Comment by JeroenVinke** [comment]
any reason why we shouldn't keep it in the sample app?

**Comment by adriatic** [comment]
No - I just wanted to see agreement 🤓

**Comment by JeroenVinke** [comment]
:+1:

**Comment by adriatic** [comment]
:+1:
