### ISSUE TITLE
IE9 with latest bridge: XHR error (404 not found) loading widget-base

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#577]
Hi,

I'm trying to use IE 9 with the latest bridge and I'm getting this error in IE 9 only:  XHR error (404 not found) loading widget-base

Any ideas?

Thanks,
Jason

**Comment by JeroenVinke** [comment]
Need more info, do you have a stack trace / full url that it is trying to load?

**Comment by jasonhjohnson** [comment]
@JeroenVinke Thanks for caring about me/IE9 :-) Unfortuently IE9 doesn't give much in the way of a stacktrace, but, this is probably useful: https://monosnap.com/file/CHaI29SacjiCePrsJShcIi6zbyqaiJ

**Comment by JeroenVinke** [comment]
from the looks of it i'd say this is a problem with systemjs. it should not resolve `../common/widget-base` to `http://localhost:5000/common/widget-base.js`. Are you running JSPM 0.16.15?

**Comment by jasonhjohnson** [comment]
`0.16.39`

**Comment by jasonhjohnson** [comment]
Sorry I've never locked the version before. Is this a command I run now to resolve the issue, or do I have to uninstall/reinstall all my packages?

**Comment by JeroenVinke** [comment]
In package.json remove the `^` in front of the version of jspm, then run `npm install jspm@0.16.15`. Then i would remove jspm packages folder and jspm install

**Comment by jasonhjohnson** [comment]
After doing all that I now get: https://monosnap.com/file/2P6liFoqnDkoc3VakGcDyVWu9CSFa6

**Comment by JeroenVinke** [comment]
Looks like the same issue but with a different package, not sure if we can help you with this
