### ISSUE TITLE
Gists to add

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#578]
grid - row click event
https://gist.run/?id=8a50734f4d26a8ed163c41ebf9fb78f7

**Comment by JeroenVinke** [comment]
drag drop 
https://gist.run/?id=353b0269649cc7273dcbda011a41be8f

**Comment by JeroenVinke** [comment]
listbox with checkboxes
https://gist.run/?id=3e68125d8fe58fe04d96e1035aab5e91

probably need to clean this gist up

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-samples/commit/ee074d2e0dd858694ef107fc51bb7697371aa9cf :smile:

**Comment by adriatic** [comment]
Why don't wee keep this open so I can remind myself which new gists are added?

**Comment by JeroenVinke** [comment]
Now that we can edit [this file](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-samples/blob/gh-pages/samples.json) to add gists very quickly, I'm not sure if this issue is needed to remind us to add gists to the catalog

**Comment by JeroenVinke** [comment]
will be a part of https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/662
