### ISSUE TITLE
sortable component fails to drop when hint is configured.

### ISSUE THREAD

**Issue by codermrrob** [aurelia-ui-toolkits/aurelia-kendoui-bridge#579]
I successfully have the sortable component running with drag and drop between 2 linked lists.

However, when I try to style or replace the hint the drop functionality in sortable-listB appears to fail. I also notice the placeholder disappears from both lists.

My view has one list of available items ("availablelist") and one of selected ("selectedlist") :

```html
<div class="row">
     <div class="list-wrapper">
            <div class="col-lg-3">
                  <ul id="sortable-listA" ref="availablelist" class="dragAndDropZone" style="min-height: 250px"; ak-sortable="k-connect-with: #sortable-listB; k-placeholder.call: placeholder($event)">
                          <li class="linked-list-item" repeat.for="property of properties">
                               <h4>${property.propertyRef}</h4>
                               <p>${property.addresses[0].address}</p>
                           </li>
                     </ul>
              </div>

            <div class="col-lg-3">
                 <ul id="sortable-listB" ref="selectedlist" class="dragAndDropZone" style="min-height: 250px"; ak-sortable="k-connect-with: #sortable-listA; k-placeholder.call: placeholder($event)">
                  </ul>
             </div>
       </div>
</div>
```

and in my VM I bind with the ref and access it in bind()

```javascript
bind() {
   $(this.availablelist).kendoSortable({
       hint: function (element) {
           return $("<span>drag text</span>").css("color", "#fa6e00");
            }
        });
    }

placeholder(e) {
      return $("<li class='linked-list-item' id='placeholder'>Drop Here!</li>");
}
```
This successfully changes the hint as expected and the available list can be sorted and works as expected but the selected items list cannot be dropped into and the placeholder no longer shows in either list.

No errors are showing in the console, so maybe my expectations of how this works are incorrect but I have no problem getting hint styling to work outside of the Aurelia bridge.

**Comment by JeroenVinke** [comment]
Hey @codermrrob 

Could you create a [gist](https://gist.run/?id=08b38c06b1499fb8cf32bccf8dc91cef) that shows this issue? This allows us to help you more quickly

More information about creating gists can be found [here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help).

**Comment by codermrrob** [comment]
Thanks for prompt reply.

Here’s the gist:

https://gist.github.com/codermrrob/5f71ad2f3aaf3fc4a432dc7868ea5725

and

https://gist.run/?id=5f71ad2f3aaf3fc4a432dc7868ea5725

it is currently configured to fail. You can configure to work simply by comment out the attached() method in app.js

Cheers.

**Comment by codermrrob** [comment]
Currently configure to fail. Comment out the attached() method to see the component work.

https://gist.run/?id=5f71ad2f3aaf3fc4a432dc7868ea5725

**Comment by JeroenVinke** [comment]
@codermrrob thanks a lot!

Check out https://gist.run/?id=353b0269649cc7273dcbda011a41be8f, What the `ak-sortable` custom attribute does is that it calls `$().kendoSortable()` on that `<ul>` for you. So when you call `$().kendoSortable()` in `attached()` it will override what ak-sortable has done. I added `k-hint.call: availableHint($event);` to the `ak-sortable` and it seems to be working.

Also: some kendo controls can handle being initialized from `bind()`, but the recommendation is to initialize jQuery based controls from `attached()`.

**Comment by codermrrob** [comment]
Fantastic – thx for fast turnaround. Been loving the bridge work and will be going with the Pro license soon.

I know is early days for the bridge and some docs not complete yet, so your support is greatly appreciated.

Thanks for advice on attached/bind. Figured attached() was correct place for jQuery initialization but good to get a confirmation.

Looking forward to trying out your flux plug-in, I think will be perfect match for us.

**Comment by JeroenVinke** [comment]
:+1:
