### ISSUE TITLE
Support rowTemplate/ altRowTemplate

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#580]
Turns out that Kendo's grid **does** call the `angular` hook for these templates. However, with this rowTemplate:

```
        <tr>
          <td>
            <p>
              ${ContactName}
            </p>
            <button ak-button>Test</button>
          </td>
        </tr>
```

The browser (atleast in chrome) sees a `<tr>` without a `<table>` and removes the `<tr>` tag, breaking compilation

Possible solution: the browser ignores anything inside of a `<script type="text/x-kendo-temp">` tag so we could get the template from a script tag for cases where the browser messes with a template

**Comment by adriatic** [comment]
Another case of 

> take 3 milligrams of medroxyprogesterone and keep your eyes closed for two minutes

solution. You are a witch :-)

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/c399bfb2509bf9e997258d4e8d28f70ef72d6eca

```
    <ak-grid k-data-source.bind="datasource">
      
      <ak-col k-field="ContactName"></ak-col>
      <ak-col k-field="ContactTitle"></ak-col>

      <ak-template for="rowTemplate">
          <!-- everything inside a script tag gets ignored by the browser
           we can't define a row template in <ak-template> as the browser sees <tr>'s outside a table as bad html
           and it tries to fix it by removing the tr tag, which is not what we want. Therefore we wrap it in a script tag -->
        <script type="text/x-kendo-temp">
          <tr>
            <td>
              <p style="display: inline;">
                ${ContactName}
              </p>
              <button ak-button>Test</button>
            </td>
            <td>
              <p>
                ${ContactTitle}
              </p>
            </td>
          </tr>
        </script>
      </ak-template>
    </ak-grid>
```

**Comment by mr-alede** [comment]
I noticed that groups aren't collapsed when clicking on  k-group-cell.
Here is my template:
		<ak-grid k-data-source.bind="dataSource"  k-widget.bind="grid"  
			k-toolbar.bind="['pdf']" k-pdf.bind="pdfExportSettings"
			k-pageable.bind="pageable" k-filterable.bind="true"
			k-sortable.bind="true" k-groupable.bind="true" k-resizable.bind="true" k-reorderable.bind="true"
			class="kendo-grid">

			<ak-col k-title="Date" k-field="CallTime" k-filterable.bind="{ui: 'datetimepicker'}">
				<ak-template  for="groupHeaderTemplate">
					Date: ${CallTime | dateFormat:'MMM DD HH:mm:ss A' }
				</ak-template>
			</ak-col>
			<ak-col k-title="H" k-field="H" k-width.bind="43"></ak-col>
			<ak-template for="rowTemplate">
				<script type="text/x-kendo-temp">
					<tr>
						<template repeat.for="gr of ( dataSource.group().length )">
							<td  class'k-group-cell'></td>
						</template>							
						<td>
							${CallTime | dateFormat:'MMM DD HH:mm:ss A' }
						</td>
						<td>
							${H}
						</td>			
					</tr>
				</script>
			</ak-template>
		</ak-grid>
Though the grid is rendered correctly.
