### ISSUE TITLE
Document how to stop JSPM from loading jquery

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#582]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/526#issuecomment-236420740 was caused by jquery being loaded twice. 

I managed to add an override to package.json:

```
    "overrides": {
      "github:twbs/bootstrap@3.3.6": {
        "dependencies": {}
      }
    }
```

When `jspm install` is ran it does not add the `jquery` dependency of bootstrap to config.js's map section

And in the `map` section I had to map jquery to `@empty`: `"jquery": "@empty",`. This is necessary because Kendo controls have a dependency on `jquery` and JSPM will try to load it

You'd say that by mapping `jquery` to `@empty` you wouldn't need the override in bootstrap...

**Comment by JeroenVinke** [comment]
Did this https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs-beta/content/app_developer_notes/prevent_jspm_from_loading_jquery.html

**Comment by adriatic** [comment]
Thank you!
