### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#583]
- Removed import statements

Renamed functions:
> .kendoButtonGroup() -> .kendoMobileButtonGroup()
.kendoCombobox() -> .kendoComboBox()
.kendoScrollView() -> .kendoMobileScrollView()
.kendoSwitch() -> .kendoMobileSwitch()
.kendoToolbar() -> .kendoToolBar()

- Converted treeview to custom element https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/526

**Comment by adriatic** [comment]
We could probably issue warnings in the log about these name changes (`deprecated`) and still recognize them for a while

**Comment by JeroenVinke** [comment]
great idea! I like it
