### ISSUE TITLE
Create new bundle and update the index.html of all gists

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#584]

**Comment by JeroenVinke** [comment]
I wonder if we can remove kendo from the bundle and have kendo in index.html of the gist as well

**Comment by JeroenVinke** [comment]
Interesting thought, we probably can remove kendo from the bundle and pull it in from a CDN. Aurelia is going to be on a CDN as well. If we can host aurelia-kendoui-bridge on a cdn, does this mean that we don't need bundles?

**Comment by adriatic** [comment]
> If we can host aurelia-kendoui-bridge on a cdn, does this mean that we don't need bundles?

Quite fascinating series of shrinking both the bridge and the catalog app. We could certainly host the bridge - question is how much will that cost us

**Comment by JeroenVinke** [comment]
Check https://rawgit.com/, it is free and we already use it in gists

**Comment by adriatic** [comment]
Let's do this then

**Comment by JeroenVinke** [comment]
created new bundle and updated all index.html's of the gists with https://github.com/aurelia-ui-toolkits/gist-tool
