### ISSUE TITLE
TS error when compiling with beta.1.0.4 (aurelia-kendoui-bridge/version not found)

### ISSUE THREAD

**Issue by smax48** [aurelia-ui-toolkits/aurelia-kendoui-bridge#586]
During typescript compilation I get the error:
```
.../jspm_packages/npm/aurelia-kendoui-bridge@1.0.0-beta.1.0.4/aurelia-kendoui-bridge.d.ts(161,10): Cannot find module 'aurelia-kendoui-bridge/version'
```

**Comment by adriatic** [comment]
@smax48 - it seems that Jeroen forgot to add the very latest change (which allows the application to query the bridge about its version).

@JeroenVinke will be back in a few hours and will take care of this (it's too late for me, sorry)

**Comment by smax48** [comment]
@adriatic  Thanks! This is not urgent at all, just to let you know about the problem :)
The main folder contains version.js, but there's something wrong with the .d.ts declaration.

**Comment by JeroenVinke** [comment]
@smax48 Thanks! can you try 1.0.0-beta.1.0.5?

**Comment by smax48** [comment]
Yes, now it compiles fine! Thanks!
