### ISSUE TITLE
How to use aurelia-kendoui-bridge with Aurelia CLI?

### ISSUE THREAD

**Issue by smax48** [aurelia-ui-toolkits/aurelia-kendoui-bridge#589]
With the latest beta of the bridge, in theory, it should be possible to build & bundle app using aurelia cli.
However, I couldn't make it working (of course, I looked at the demo sample that @JeroenVinke published some time ago). 
1) When I add a bundle dependency for the kendo-ui bridge in the form:

```
          {
            "name": "aurelia-kendoui-bridge",
            "path": "../node_modules/aurelia-kendoui-bridge/dist/amd",
            "main": "index"
          }
```

All widget wrappers are not bundled at all (neither js nor html).
2) If I change this to:

```
          {
            "name": "aurelia-kendoui-bridge",
            "path": "../node_modules/aurelia-kendoui-bridge/dist/amd",
            "main": "index",
            "resources": [
              "**/*.js",
              "**/*.html"
            ]
          }
```

In this case at least _some_ js wrapper components are duplicated in the resulting bundle (e.g. buttongroup): 
a) one copy in the "right" form, with the correct moduleId:
`"define('aurelia-kendoui-bridge/buttongroup/buttongroup' ,['exports', ...`
b) another copy as `define(['exports', ...`
Because of this, nothing works at runtime (requirejs error).

It's very likely that this is a bug in au cli, but maybe I am doing something wrong.
Is there any "right" way to bundle _all_ components from the kendoui-bridge using Aurelia CLI?..

**Comment by JeroenVinke** [comment]
Opened this issue: https://github.com/aurelia/cli/issues/270

**Comment by pkozul** [comment]
Added some more information to aurelia/cli#270
