### ISSUE TITLE
Problems with maintaining a gitbook book on github

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#590]
I had all kinds of problems trying to clone from gitbook to github "directly"; I tried to push from gitbook and pull from github - nothing good happened. So, I tried the indirect way using my PC as the intermediary

**Current situation**: I managed to make a local clone of the [kendoui-bridge-docs book](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/) using this process
```
C:\work\aurelia-ui-toolkits\KendoUI\kendo-books
λ git clone https://git.gitbook.com/aurelia-ui-toolkits/kendoui-bridge-docs.git
Cloning into 'kendoui-bridge-docs'...
Username for 'https://git.gitbook.com': adriatic
Password for 'https://adriatic@git.gitbook.com':
remote: Counting objects: 1094, done.
remote: Compressing objects: 100% (1027/1027), done.
Receiving objects: 100% (1094/1094), 151.56 KiB | 0 bytes/s, done.
Resolving deltas: 100% (626/626), done.
Checking connectivity... done.
```
The, I created a new GitHub (empty) repository - https://github.com/aurelia-ui-toolkits/aurelia-kendoui-books initialized with the README.md file only.

Note that my local clone of the **_whole book_** from gitbook is in the **kendo-book** folder and that the local clone of the **_empty_** book from github is in **aurelia-kendoui-books** folder.

Now, I copied (windows explorer) complete content of the **kendo-book** folder into the (almost empty) **aurelia-kendoui-books** folder.

Lastly I commited all changes in **aurelia-kendoui-books** folder and pushed it to `https://github.com/aurelia-ui-toolkits/aurelia-kendoui-books` repository.

This means that we have a clone of the book at `https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/` in Github - and that is a good thing.

**What is still missing?** Well, what happens if I open this book for edit? Which sources are used by the gitbook web editor? sources from github or sources from github? It seems that it reads from the latter, based on this view:

![image](https://cloud.githubusercontent.com/assets/2712405/17348691/fe701f00-58e5-11e6-86b8-e3d308c60889.png)

This matches the setting I put in `https://www.gitbook.com/book/aurelia-ui-toolkits/kendoui-bridge-docs/settings/github` - 

![image](https://cloud.githubusercontent.com/assets/2712405/17349114/436ebb4a-58e9-11e6-824b-885e01501035.png)

However, the repo `https://github.com/aurelia-ui-toolkits/aurelia-kendoui-books` is a clone of the gitbook original - **so why am I not seeing the same content now?**

**Comment by adriatic** [comment]
### How not to have to copy the whole book content into a new branch?

The key purpose of the above exercise was to create a clone of the current book and pare it down **using the Gitbook Editor** to the minimum needed for the KendoUI bridge beta documentation.

Other than installing gitbook desktop editor and use it to massage my local clone of the book, I do not see other alternative. The gitbook support is completely ignoring my questions so far (probably because we have the free OSS account ??)

**Comment by adriatic** [comment]
### Temporary summary:

#### Cloning
- The git url for the instance hosted by GitBook is definitively `https://git.gitbook.com/aurelia-ui-toolkits/kendoui-bridge-docs.git`. I successfully used this url to clone this instance to my PC.

- There is very likely a problem with  Single Sign-On at GitBook. I created all books using my GitBook account and my initial attempt to clone this book (form GitBook) failed at the point pf presenting my authentication in the process of running the command 
 ```
git clone https://git.gitbook.com/aurelia-ui-toolkits/kendoui-bridge-docs.git
```
 Only after I created my "direct credentials" with GitBook, (using the same username / password - something dat is not likely relevant in this context), was I able to clone the book.

#### Editing
- If there is no Github address specified at `https://www.gitbook.com/book/aurelia-ui-toolkits/kendoui-bridge-docs/settings/github` then the GitBook web editor correctly shows the book content in the edit mode:

 ```
https://www.gitbook.com/book/aurelia-ui-toolkits/kendoui-bridge-docs/edit#/edit/master/README.md
```

- If I specify the Github address using this specific format **`aurelia-ui-toolkits/aurelia-kendoui-books`** in the field at `https://www.gitbook.com/book/aurelia-ui-toolkits/kendoui-bridge-docs/settings/github` and then open the GitBook Editor in the edit mode, it would show **empty** Table of Content and the **correct** content of the Files Tree.

**Comment by adriatic** [comment]
I believe that this task is in a good shape and that **all** problems were caused by SSO authentication (I always used the GitHub account to login to GitBook) Only when I created the GitBook "local account" things started to behave normally.

At the moment, I created the [beta branch](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-books/tree/beta) and verified that the GitBook editor properly uses that branch (https://www.gitbook.com/book/aurelia-ui-toolkits/kendoui-bridge-docs/edit#/edit/beta/README.md)

**Comment by JeroenVinke** [comment]
:+1:
