### ISSUE TITLE
 Main entry point not found for github:google/code-prettify@master.

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#592]
The warning message says:

```
warn Main entry point not found for github:google/code-prettify@master.
     Adjust this property in the package.json or with an override, setting "main": false if this is the intention.
```

**Comment by Thanood** [comment]
Try to add this to `package.json/jspm`:

```javascript
    "overrides": {
      "github:google/code-prettify@master": {
        "main": "src/prettify"
      }
    }
```

https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/package.json#L35-L39

**Comment by JeroenVinke** [comment]
also a nice website: http://jarreddebeer.github.io/jspm-package-override-generator/public/

**Comment by adriatic** [comment]
Thanks Daniel (Jeroen added the fix, I think)

**Comment by adriatic** [comment]
@JeroenVinke 
> also a nice website: http://jarreddebeer.github.io/jspm-package-override-generator/public/

A mini-mini monterey (it does not surprise me that there are other folks trying to improve on "cli-only" world).

**Comment by Thanood** [comment]
That would actually be a nice addition to Monterey.
