### ISSUE TITLE
export grid to excel without prompt save...

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#594]
Hey
when export grid to excel ,i get this prompt message asking whether  to save the file or not.
![image](https://cloud.githubusercontent.com/assets/6911449/17392730/e3dbd236-5a27-11e6-948c-bd06cc6ce234.png)
how can i save the excel file automatically to downloads folder?

**Comment by JeroenVinke** [comment]
This is probably a setting in the browser. You cant force a download to a specific location (security reasons)
