### ISSUE TITLE
Is it possible to embed other component under "ak-col"?

### ISSUE THREAD

**Issue by miaFan** [aurelia-ui-toolkits/aurelia-kendoui-bridge#595]
Hi all,

This could be a question. I am doing a grid view using this bridge, and I have created some components(like text-field, drop down list etc.) with some customized validation rules. I am wondering if there is a way that I can use these components in the grid cell?

Thanks!

**Comment by JeroenVinke** [comment]
you could definitely use your own custom elements inside the grid (check the first <ak-col> of [this sample](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/advanced)).

Not so sure about the validation. I don't know how the validation works internally of the grid

**Comment by JeroenVinke** [comment]
make sure that you have loaded `<ak-template>` either via `.kendoTemplateSupport()` in main.js, or `<require from="aurelia-kendoui-bridge/common/template"></require>`

if this solves the issue, then we should to improve the error message

**Comment by miaFan** [comment]
Cool! It works. Thank you for your help:D

**Comment by JeroenVinke** [comment]
:+1:
