### ISSUE TITLE
mention builder pattern in "what you need to know"

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#596]
https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/what_you_need_to_know.html#592-how-to-load-aurelia-kendoui-bridge-custom-elements--attributes

we should mention the builder pattern on the above page, then point to https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs-beta/content/app-developers-notes/loading_a_subset_of_controls.html for more info

```
.plugin('aurelia-kendoui-bridge', kendo => { 
        kendo.kendoDropDownList()
        .kendoMenu()
        .kendoTabStrip()
        .kendoGrid()
        .kendoTemplateSupport();
    })
```

**Comment by JeroenVinke** [comment]
@adriatic can you make sure this gets in?

**Comment by JeroenVinke** [comment]
just added this, was in the gitbook editor anyway

**Comment by adriatic** [comment]
Thank you
