### ISSUE TITLE
align version of bundles with version of the bridge

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#597]

**Comment by JeroenVinke** [comment]
starting from now the version of the bundle of the gist is equal to the version of the bridge

**Comment by adriatic** [comment]
This is done in a manual fashion, I believe

**Comment by JeroenVinke** [comment]
Yep, the versions [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bundles/releases) are the ones used in the gists
