### ISSUE TITLE
Draggable typo

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#603]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/3b6d4285e5441eee00824b31477663681d7b4cb4/src/draggable/draggable.js#L11

**Comment by adriatic** [comment]
Great find. I always had a suspicion that something is broken in the catalog app that uses D&D, but never really pursued this

**Comment by adriatic** [comment]
So, this fix is not in the just installed demo-kendo-beta catalog, right?

**Comment by JeroenVinke** [comment]
Correct, but this is not why the drag and drop samples didn't work anymore.

Turns out that the hint you see when dragging an element is now compiled.

If you'd have `<div ak-draggable="k-widget.two-way: draggable;></div>` then the `draggable` variable would be set twice (once on load, and once when dragged).

So I removed the ak-draggable attribute of the hint:

``` 
  onHint(e) {
    // when using k-widget, remove the ak-draggable attribute of the hint as it is
    // not going to work otherwise
    return $($(this.draggableDiv).removeAttr('ak-draggable')).clone();
  }
``` 

And I added this note to all draggable samples

**Comment by adriatic** [comment]
> the hint you see when dragging an element is now compiled

Very good catch - this ought to be a bug in the bridge, right?

**Comment by JeroenVinke** [comment]
Well the draggable kendo control now tells "angular" to compile the hint, so unless that's a recent change I don't see how this ever worked

**Comment by adriatic** [comment]
My point, exactly
