### ISSUE TITLE
Deploy KendoUI Bridge catalog beta (gh-pages)

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#604]
Since we do not want to create any service disruption for existing KendoUI bridge users, we need maintain the **[current catalog app](http://aurelia-ui-toolkits.github.io/demo-kendo)** for as long as one person wants to used it. 

This requires that the https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/tree/beta  gets deployed to gh-pages as http://aurelia-ui-toolkits.github.io/demo-kendo-beta, so that all references from beta documentation can point to this new catalog app.

@JeroenVinke please do this rather sooner than later, as I am trying to put this beta bridge out of the door :smile:

**Comment by JeroenVinke** [comment]
Since the beta bridge is the recommended (and default) after we officially release it, we should rename `demo-kendo` to `demo-kendo-old` and then name the beta `catalog` demo-kendo. If we don't, then we'll never be able to get rid of the "beta" name as we have pointed everyone to the catalog url with "beta" in its name

**Comment by adriatic** [comment]
I was thinking about it also, and it seemed to me that the beta bridge will stay labelled as beta for some time. While this is true, we cannot rename the current bridge to be "old bridge" for several reasons:
- We never know if and when Rob's big shot customer may jump in and ask immediate availability. This chance may be small but we can eliminate any potential discomfort by following this strategy I am proposing.
- There may be some number of existing users who would not care about new - and that should also be respected at least until new gets promoted from beta to release.

So, I will repeat:
 
1. **new** bridge deployed to npm and gh-pages with the string beta in its name. Through that period the online documentation (referenced from **beta** catalog references the **beta** bridge and the current bridge and catalog stay unmodified.

2. When the **beta** bridge gets released, it gets the version 1.0.0 (without beta) and it continues to coexist with bridge with the today's version 0.11.9 (we have yet to decide whether to freeze it at that version number). The catalog app associated with bridge 1.0.0 changes the document references to appropriately renamed books - and these books change their references to this new bridge (where appropriate).

If you have a better solution for this, I will gladly discuss this issue some more :smile:

**Comment by JeroenVinke** [comment]
did this yesterday
