### ISSUE TITLE
Samples should use <require>

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#606]
The recommended approach is to use `<require>` so we should take this recommendation to heart and use `<require>` in samples as well. 

If you copy the following code in your app without using `kendo => kendo.all()` then it won't work. 

![image](https://cloud.githubusercontent.com/assets/2189477/17509047/4e60cdca-5e18-11e6-9682-6f38a4bfe673.png)

**Comment by adriatic** [comment]
Yes, that **has to be done** - regardless of the difficulties involved. I am happy to do that once we describe the protocol 

1. I need to be authenticated to GitHub as `GistMaster` (is that the name of that account?)
2. Can i edit the existing samples as gists? (that way the gist ID stays the same)
3. Anything else?

**Comment by JeroenVinke** [comment]
1. Gist-master
2. The ones on the beta catalog. If you just use the update gist button (and not fork) then the id will stay the same and changes should be reflected on the catalog after a page refresh. Make sure to remove kendo => kendo.pro() from main.js of the gist to confirm you got all the necessary require statements

**Comment by adriatic** [comment]
+ack
