### ISSUE TITLE
clean up repository

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#607]
![image](https://cloud.githubusercontent.com/assets/2189477/17509372/eee9f4aa-5e19-11e6-851c-cce3148c7443.png)

npm installs the entire directory, so we should make sure that the repository is as small as possible

**Comment by adriatic** [comment]
Quite a big file, yes. Clearly I need to get up to speed on KendoUI & aurelia-cli.
