### ISSUE TITLE
ak-button is not styled in treeview custom templates sample

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#609]
I think we may need to add the viewresources to the treeview wrapper ([here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/beta/src/treeview/treeview.js)). Works fine if using kendo.pro() though

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/beta/src/toolbar/toolbar.js as well (Toolbar: integration with editors)

**Comment by adriatic** [comment]
I understand nothing of the above - except that you ought to be working on all gists starting from the end :-)

**Comment by JeroenVinke** [comment]
Basically, the wrapper needs to pass the `<require>'s` to aurelia's templating compiler.

**Comment by JeroenVinke** [comment]
> except that you ought to be working on all gists starting from the end :-)

Yep :smile:

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/0213de52431b3d8aea6030019be028d8e86d8090 and https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/14a379765748ff9e7b933288aa0723fbc5e1cc35
