### ISSUE TITLE
"kendo is not defined" when using kendo.pro() while using JSPM to load Kendo

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#612]
kendo.pro() causes the the `@generateBindables()` decorator to execute on the wrappers, which uses the kendo global ([here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/beta/src/common/control-properties.js#L62). The error "kendo is not defined" is caused when you use a module loader to load kendo, at which point the `kendo` global is not available when `kendo.pro()` is called

**Comment by adriatic** [comment]
> kendo.pro() causes ...

Is that a reference to [this line](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/main.js#L9)?

How do you want to fix that? kendo.pro() should be allowed in the beta bridge
