### ISSUE TITLE
"k-locked.bind" is not working with repeat.for ak-col

### ISSUE THREAD

**Issue by miaFan** [aurelia-ui-toolkits/aurelia-kendoui-bridge#613]
Hi,

I want to implement a dynamic column grid, so I use something like:
`
 <ak-col repeat.for="field of fieldColumns" k-field="${field.code}"></ak-col>
`

It works well. But when I was trying to fix the first column using `k-locked` attribute, it cannot parse correctly:
`
this.fieldColumns = [
      {
        code: 'col1',
        width: 500,
        locked: true
      },
      {
        code: 'col2',
        width: 500,
        locked: false
      },
      {
        code: 'col3',
        width: 500,
        locked: false
      }
]
`

HTML:
`
 <ak-col repeat.for="field of fieldColumns" k-field="${field.code}" k-locked.bind="${field.locked}"></ak-col>
`

same thing with 'k-width.bind'. The error is:
`
aurelia-logging-console.js:54 ERROR [app-router] Error: Parser Error: Missing expected : at column 8 in [${field.locked}]
`

Any idea?

**Comment by JeroenVinke** [comment]
Can you reproduce this in a gist? Instructions can be found [here](https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/help).

**Comment by miaFan** [comment]
Example: https://gist.run/?id=d7fdb51e0982aef65dc07ad74b081726

Error is in the console. Removed "k-locked" it works.

**Comment by Thanood** [comment]
Is that correct? `k-locked.bind="${field.locked}"`
I thought it was either `k-locked.bind="field.locked"` or `k-locked="${field.locked}"`..

**Comment by JeroenVinke** [comment]
In addition to what @Thanood said it looks like it's necessary to provide a k-width as well: https://gist.run/?id=cbf7d31a4aab313b887d66ad169a1f0a

**Comment by miaFan** [comment]
OK! Got it. Thanks for help! @JeroenVinke and @Thanood
