### ISSUE TITLE
Why aurelia-kendoui-bridge.d.ts has declaration of aurelia-binding module?

### ISSUE THREAD

**Issue by smax48** [aurelia-ui-toolkits/aurelia-kendoui-bridge#614]
aurelia-kendoui-bridge.d.ts starts with code that causes problems in some situations:

```
declare module 'aurelia-binding' {
export class Lexer {}
export class ParserImplementation {}
}
```

As I understand, typescript actually doesn't support external module declarations over multiple files.
For some reasons this works OK with the jspm setup, but for both au cli & webpack - it gives compilation errors. When I remove this code, everything compiles OK.

Is there a particular reason that this code exists at all?

UPDATE:
It seems that the "typings" element in the package.json references "dist/amd/...d.ts" (which contains that strange declare section). The root .d.ts file (in /dist) doesn't have it, but still has unresolved import for Lexer & ParserImplementation from aurelia-binding).

**Comment by JeroenVinke** [comment]
can you confirm that it works with the latest version?

**Comment by smax48** [comment]
Yes, I confirm that webpack-typescript setup works OK with beta.1.0.13
Thanks!
