### ISSUE TITLE
upload async.withCredentials

### ISSUE THREAD

**Issue by codermrrob** [aurelia-ui-toolkits/aurelia-kendoui-bridge#615]
Has the option to upload files with async.withCrdentials been implemented?
If it has what is the attribute k- attribute name?

I have tried various attribute names (k-async-with-credentials="false", k-upload-async, etc) in the <ak-upload> element but have not had any success.

Or should i set this directly on the widget in the afterAttached() method?
thanks.

**Comment by JeroenVinke** [comment]
the `withCredentials` property is on the `async`  object which means that you should bind the `k-async`  property to an object `k-async.bind="{ withCredentials: false }"`.

In this gist it uses different properties on the async object but the idea is the same: https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/samples/upload-asynchronous-upload

**Comment by codermrrob** [comment]
great - makes perfect sense now!

**Comment by JeroenVinke** [comment]
Excellent :+1:
