### ISSUE TITLE
aurelia-cli expects a main property

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#617]
With this config:

```
    {
         "name": "kendo-ui-core",
         "path": "../node_modules/kendo-ui-core"
    },
```

aurelia-cli shows this error:

`error C:\spikes\Aurelia-CLI\NettWeb\node_modules\kendo-ui-core.js`

This is because aurelia-cli expects a main property for all dependency configurations, but kendo does not have such a thing

I've seen that it works even though it displays an error

**Comment by avrahamcool** [comment]
as you already mentioned, the bridge is working fine even with the error, but seeing that error annoied me, so I found a workaround.

I created an empty `dummy.js` file in the kendo rrot folder. (file should be litterally empty for it to work),
and add a `main` property pointing to it.

```
{
         "name": "kendo",
         "path": "../node_modules/kendo/",
         "main": "dummy"
    },
```

**Comment by JeroenVinke** [comment]
Thank you! Will definitely try this out

**Comment by JeroenVinke** [comment]
Closing this in favor of https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/660.
