### ISSUE TITLE
Load jszip using webpack

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia-ui-toolkits/aurelia-kendoui-bridge#618]
Hi folks,

I've tried in many ways to bundle and load jszip with webpack but I ended up referencing it manually into index.html. I just started a brand new project using the latest typescript-webpack skeleton and following the instructions for demo-kendo-beta.

Does anyone got this work?

**Comment by JeroenVinke** [comment]
I haven't used webpack myself, so I can provide no help here :(

**Comment by enrico-padovani** [comment]
Ok, I got it!

since kendo is referencing JSZip as global, you have to use ProvidePlugin as following:

```
config.plugins.push(new webpack.ProvidePlugin({
  'JSZip': 'jszip',
  'window.JSZip': 'jszip' // this doesn't expose JSZip property for window, but exposes it to every module
}));
```

I'd a look at this file: [https://github.com/easy-webpack/config-global-jquery/blob/master/src/index.ts](url) thanks to @niieani and easy-webpack!

I'm still new to webpack and learning along the way the basics to just make my app run!

Cheers

**Comment by JeroenVinke** [comment]
Thanks for updating the issue with the solution :+1:

**Comment by enrico-padovani** [comment]
I'm evaluating this bridge since I've used the kendo and angular directives for a while now, I feel really the same way using them with Aurelia bindings ... awesome work!
