### ISSUE TITLE
Kendo grid layout broken

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia-ui-toolkits/aurelia-kendoui-bridge#619]
Hi,

I've got the kendogrid succesfully run starting from the latest typescript webpack skeleton, but the layout is really broken!

![image](https://cloud.githubusercontent.com/assets/7766472/17815478/c45b8082-6634-11e6-8839-443bee4cb30b.png)

Functionally speaking everything seems to work fine. Some css issue there?

Thanks for any tip!

**Comment by JeroenVinke** [comment]
did you maybe forget to close a tag? Please try and reproduce your issue in a gist. Instructions are here: https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/help

**Comment by enrico-padovani** [comment]
I got it...

changed this:
`<link rel="stylesheet" href="node_modules/kendo/css/web/kendo.common.core.min.css">`
to this:
`<link rel="stylesheet" href="node_modules/kendo/css/web/kendo.common.min.css">`

into index.html

**Comment by adriatic** [comment]
This is a mistake that many people make (myself included)
