### ISSUE TITLE
Preventing autocomplete dropdown from closing on scroll

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#620]
Hi,

I'm tryign to follow Telerik's official solution to this problem as documented here: http://docs.telerik.com/kendo-ui/controls/editors/dropdownlist/how-to/prevent-close-on-scroll. The main area I'm stuck on is this: 
` var widget = $("#products").data("kendoDropDownList");`

I'm not sure how I can access this object if I'm utilizing the bridge. Any help is appreciated.

Thanks,
Jason

**Comment by JeroenVinke** [comment]
This is the k-widget property

**Comment by jasonhjohnson** [comment]
Ok. Do you know if there's anything else I'd need to do differently than the official kendo documentation shows for disabling the dropdown on scroll?

**Comment by JeroenVinke** [comment]
Not sure, if you can create a gist that does not work then I can take a quick look

**Comment by adriatic** [comment]
KendoUI official documentation is official for all of us - bridge builders and users. You should just do what Telerik recommends.

**Comment by JeroenVinke** [comment]
please reopen with gist if this is still an issue
