### ISSUE TITLE
Correct way to import kendo css when using webpack

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia-ui-toolkits/aurelia-kendoui-bridge#621]
Referencing kendo *.min.css directly from index.html causes webpack to produce a wrong production bundle after running `npm run build:prod`.

In order to fix the problem, I removed direct references from index.html and add import into main.ts instead.

So the full kendo setup will be:
```
import 'kendo/css/web/kendo.common.min.css';
import 'kendo/css/web/kendo.default.min.css';
import 'kendo';
```

Hope this helps others!

PS: update the docs

**Comment by JeroenVinke** [comment]
Thanks, will do :+1:
