### ISSUE TITLE
dialog instance not recognize in custom component

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#624]
@JeroenVinke 
i'm almost sure i'm doing that wrong or don't understand the new instance issue, but will still try...
I've created that [Gist](https://gist.run/?id=93b31fb2cb6df849a478a8559dc180ac) to show my problem.

I have custome component of window and i'm require it from parent view-model.
then when button click i would like to open that dialog, but the dialog instance is undefined inside the custom component.. 
Why?

**Comment by eliavmaman** [comment]
ok.. anyone?

**Comment by JeroenVinke** [comment]
@eliavmaman it's been pretty busy lately.

I would recommend going through the docs as there is a lot of information on how to create custom elements and how to reference them (http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-basics/5 shows that you can use view-model.ref on a custom element). https://gist.run/?id=f77da890504f725dc986d91846234205
