### ISSUE TITLE
Grid - Virtual Scrolling

### ISSUE THREAD

**Issue by deliberaligiacomo** [aurelia-ui-toolkits/aurelia-kendoui-bridge#625]
How can I implement virtual scrolling (to remote data) in the bridge?
I read [this](http://demos.telerik.com/kendo-ui/grid/virtualization-remote-data) demo and tried the [setOption](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#methods-setOptions) method, but I cannot reference the widget. Is in the grid missing the `k-widget` attribute?

**Comment by JeroenVinke** [comment]
Hey @deliberaligiacomo 

I have added [this sample](https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/samples/grid-virtualization) which uses virtual scrolling. Let me know if that helps

**Comment by deliberaligiacomo** [comment]
Thank you!
