### ISSUE TITLE
Using kendo-ui bridge with jquery already loaded

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-ui-toolkits/aurelia-kendoui-bridge#626]
I have an existing application which loads jquery at startup.

This seems to be conflicting with the jquery that is loaded by the kendo-ui bridge.

It appears that jquery gets loaded by the controls, which then kills the original jquery.  So no jquery code runs.  I don't get a kendo button created, and my other controls that use jquery do not run.

I am not sure how to resolve this.

**Comment by JeroenVinke** [comment]
https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs-beta/content/app_developer_notes/prevent_jspm_from_loading_jquery.html may contain some clues

**Comment by gregoryagu** [comment]
Thanks very much, this is now resolved.
