### ISSUE TITLE
How do I set the encoded property of the editor to false?

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-ui-toolkits/aurelia-kendoui-bridge#628]
I believe the following is the correct way to set encoded to false for the editor.  But I still get encoded text when I use the value() method.

Is there another way to do this?

```
<textarea value.bind="entity.content"
                ak-rich-editor="k-encoded: false"
                ref="editor"
                style="height: 440px">
                                
            </textarea>
```

**Comment by gregoryagu** [comment]
By binding it to a property called "encoded" on the viewmodel, it set the value as expected.

<textarea value.bind="entity.content"
                ak-rich-editor="k-encoded.bind: encoded"
                ref="editor"
                style="height: 220px">
                                
            </textarea>

**Comment by JeroenVinke** [comment]
Hey @gregoryagu ,

ak-rich-editor="k-encoded.bind: false" would yield the same effect. [here](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs-beta/content/what_you_need_to_know.html#594-when-to-bind-and-not-to-bind) we have some more examples
