### ISSUE TITLE
Item added to data does not show in treeview

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-ui-toolkits/aurelia-kendoui-bridge#629]
I have followed the steps to show local data in the treeview and it shows just fine.

Now I want to add an item to the list. So I add an item to the "data" array.

I would then expect to see the item added to the treeview since the datasource is bound to it. However, it does not display the item.

I can confirm in the debugger that the "data" array has the new item:

```
addItem() {
        this.inlineData.data._add({
            categoryName: 'More',
            subCategories: [
                { subcategoryName: 'Item 1' },
                { subcategoryName: 'Item 2' }
            ]
        });
        
    }
```

How do I get the item to display?

What I want to be able to do is fetch items through the Aurelia Fetch client, and then add or remove items at various locations in the list.

**Comment by adriatic** [comment]
Please check [this document](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/app-developers-notes/current_limitations.html) which explains the limitations on two way binding

**Comment by gregoryagu** [comment]
Ah Thank you!

**Comment by gregoryagu** [comment]
I am struggling to get this to work.

```
export class Test {
    element:HTMLElement;
    dataSource: any;
    treeview:any;

    @delayed()
     attached() {
         this.dataSource = new kendo.data.DataSource({
             data: [
                 {
                     text: 'Furniture', items: [
                         { text: 'Tables & Chairs' },
                         { text: 'Sofas' },
                         { text: 'Occasional Furniture' }
                     ]
                 },
                 {
                     text: 'Decor', items: [
                         { text: 'Bed Linen' },
                         { text: 'Curtains & Blinds' },
                         { text: 'Carpets' }
                     ]
                 }
             ]
         });
         this.treeview.dataSource = this.dataSource;
     }
}
```

```
<div ak-treeview.ref="treeview" ak-treeview id="treeview-left"></div>
```

Am I doing something wrong?

**Comment by adriatic** [comment]
Perhaps - as I do not have the time to handle your problem at the moment. So, let me ask you for a couple of favors:

1. Check the sample at https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/samples/treeview-binding-to-local-data being very close to what you are doing (by the way, please do always look into all similar existing samples as the first attempt to bail yourself from a problem).

2. If our samples to not help, please go to http://demos.telerik.com/kendo-ui/ site, where you could run this sample without the additional possible side-effects of the KendoUI bridge, using their Dojo environment. If your sample works there and fails in with the KendoUI bridge, this would be a solid indication that the problem is in our bridge, and you should create the problem report with Gist - as described [here](https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/help).

**Comment by gregoryagu** [comment]
1.  Yes, I started with the sample.  It works great.  But when I try to add something to the array it is bound to nothing shows.  So I was told to create my own data source. So that is what I did in the above.

2.  I don't think the issue is with the bridge itself.  It's something with how I am putting the parts together but I don't see what it is.

**Comment by gregoryagu** [comment]
Ok, I finally figured this out.  Instead of adding directly to the array, I add the item through the Treeview. Not true binding, but still is workable.

```
this.treeview.kWidget.append([
        { text: "qux" },
        { text: "cat" }
    ]);
```
This added two items.  The key was using the append method of the widget.

**Comment by JeroenVinke** [comment]
Hey @gregoryagu, may be a bit too late but I have prepared a sample: https://gist.run/?id=3bb6deae573bac08dfa85fc919d89be9

It is recommended to create the datasource from the constructor, and then not to replace it with a different instance (the two-way binding problem).

**Comment by gregoryagu** [comment]
@JeroenVinke This is great.  Because then I can add items through the dataSource instead of the treeview!

I modified your gist slightly: https://gist.run/?id=337a4a29454de6fc59ab95251cf55bca

```
addItem() {
    this.dataSource.add({ text: 'Something else' });
  }
```

**Comment by JeroenVinke** [comment]
you're right :smile:

**Comment by gregoryagu** [comment]
@JeroenVinke I don't understand something:

This works in the gist:
`<ak-treeview k-data-source.bind="data" k-widget.bind="treeView"></ak-treeview>`

But in my app, the treeview is not created.

This does work:

<div ak-treeview="k-data-source.bind:data"></div>

Am I missing some set-up step?  Or is there a later version?

**Comment by adriatic** [comment]
Several comments (first of them repeated)

1. Please do not assume that any member of our team has the time to respond questions like the one above . **Always** add gists that indicate your problem. For example, you very likely made a typo in your report above, where 
<br>
 This does work:
`<div ak-treeview="k-data-source.bind:data"></div>`
<br>
 should be
<br>
 This does **not** work:
<br>
`<div ak-treeview="k-data-source.bind:data"></div>`

2. You should switch to the new KendoUI (https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/about/about) - as the one you are using will soon be deprecated.

**Comment by gregoryagu** [comment]
1.  Ok.

2.  Ah, thank you! With the beta version, all is working.

Greg
