### ISSUE TITLE
Is there a way to use a template with the TreeView

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-ui-toolkits/aurelia-kendoui-bridge#631]
I have looked through the documentation, but I can't find how to use a template with the TreeView

Here is the gist: https://gist.run/?id=7a86945586fec05a96c4cbbb7832a909

This is an example I am trying to get to work.
```
<ak-treeview k-data-source.bind="dataSource"
    k-template="<a>${text}</a>"
    k-widget.bind="treeView"></ak-treeview>
```
Or if there is a way to bind to a template, that would be fine.  Just any way to use a template.

**Comment by JeroenVinke** [comment]
Something like this? https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/samples/treeview-custom-templates

**Comment by gregoryagu** [comment]
Yes, exactly.  Thank you so much.
