### ISSUE TITLE
How to bind menu to a datasource

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-ui-toolkits/aurelia-kendoui-bridge#632]
I would like to bind a menu to a datasource.

This [gist](https://gist.run/?id=c993dca1a30c45eb958f0b0b6e5df8ba) shows the menu is being created, but no items show up in it.

This is a fiddle from Telerik that shows it being done:  [bound menu](http://jsfiddle.net/mmrcf/8/)

**Comment by JeroenVinke** [comment]
this is the correct syntax: https://gist.run/?id=425faa63ba8b2975e956d89482884a65

**Comment by gregoryagu** [comment]
Ah, thank you.
