### ISSUE TITLE
ResponsivePanel Demo does not work correctly.

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-ui-toolkits/aurelia-kendoui-bridge#633]
https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/samples/responsivepanel-basic-use

If you run this demo, and then make the browser window narrow, the panel converts to a hamburger menu as expected.

However, if you then click the hamburger, the hidden items do not appear.  They do in fact appear, but the position is in the very top left of the browser window where the navigation bar is.

**Comment by JeroenVinke** [comment]
Thanks, updated the sample.
