### ISSUE TITLE
k-title.bind="<column-name>" not working

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#634]
@JeroenVinke hey
we have some values that contains long text, so i added the style of  
`.k-grid tbody tr td { white-space: nowrap;}`

and i want the title of the cell to be the cell value... i thought 
`k-title.bind="<column-name>"` will work but it didn't.

Any idea?

**Comment by JeroenVinke** [comment]
Could you create a gist that shows what you're trying to do? thanks

**Comment by eliavmaman** [comment]
@JeroenVinke Hey man. 10x for the quick answer
I think i found a solution look at that [gist](https://gist.run/?id=e53738d2c479b9427391de8660f0a416).
now i have title attribute.
10x for helping
