### ISSUE TITLE
Dynamic k-connect-with

### ISSUE THREAD

**Issue by federico-galfione** [aurelia-ui-toolkits/aurelia-kendoui-bridge#635]
I'm trying to set dynamically the k-connet-with from a bindable property into my component. but it seems not working.

I have written a simplified example of my code with same problem in gist

https://gist.run/?id=e57aa8c75d56982136a88f6dc3c6ad48

**Comment by JeroenVinke** [comment]
Hey @federico-galfione. Does [this](https://gist.run/?id=26b73e3628f7a844ce1be64b9a6a9fe0) help you?

**Comment by federico-galfione** [comment]
Perfect! Now everything work. Thank you @JeroenVinke
