### ISSUE TITLE
Cannot set custom command inside a grid

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia-ui-toolkits/aurelia-kendoui-bridge#637]
Hi,

I'm trying to create a custom command inside a column. Here's how to do it using kendo for jquery: http://demos.telerik.com/kendo-ui/grid/custom-command.

Is it possible to define it in HTML, something like:

```
<ak-grid ...>
      <ak-col k-title="Col 1" k-field="Col1"></ak-col>
      <ak-col k-command="???"></ak-col>
</ak-grid>
```

or do I have to use row template? Any suggestion?

**Comment by enrico-padovani** [comment]
Sorry, I've just noticed that you can use .bind in order to pass an object, like so:
`<ak-col k-command.bind="{text:'text', click:showAlert}">`

inside showAlert method in my vm, I'd like to access to the row data item, using jquery something like:
` var dataItem = this.dataItem($(e.currentTarget).closest("tr"));`

Is there a better way? In typescript classes "this" does not work nicely!

**Comment by JeroenVinke** [comment]
@enrico-padovani it is difficult to say. Would you mind creating a gist ([instructions here](https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/help)) that shows what you would like to do?

**Comment by enrico-padovani** [comment]
Here is [an example](https://gist.run/?id=be8beb86916f3e0a6fdebd4690a379a2).

editItem is a function defined into class constructor and this is referring to the grid. I'd like to have a "classic" method in my vm class that could intercept the data item without "the this hack".

Not sure if it's possible!

**Comment by JeroenVinke** [comment]
`{ 'name': 'editItem', text: 'Edit', click: editItem }` would perfectly translate to a custom element: ```
<ak-col>
  <ak-command k-name="editItem" k-text="Edit" k-click.bind="editItem"></ak-command>
  <ak-command k-name="something" k-text="Something" k-click.bind="editSomething"></ak-command>
</ak-col>
```

So there is no better workaround now, but the custom element is something we can add

**Comment by enrico-padovani** [comment]
Ok, at least it looks better than putting js inside HTML. I tried to add
```
<ak-col>
  <ak-command k-name="editItem" k-text="Edit" k-click.bind="editItem"></ak-command>
</ak-col>
```
but it does not display the button. Do you know why? In order to access the dataItem inside my vm do I have to use jquery or is there a better way?

Thanks!

**Comment by JeroenVinke** [comment]
`<ak-command>` does not exist yet, sorry for confusing you. 

> In order to access the dataItem inside my vm do I have to use jquery or is there a better way?

No I think you need to use jQuery

**Comment by enrico-padovani** [comment]
Ok, thanks for explanation. I've been using kendoui with angular1 directives for a while now, so I guess It's working the same unless jquery is there!

Do you have plans for adding <ak-command> custom element? Indeed it'll be a cleaner option.

Thanks for the quick reply!

**Comment by JeroenVinke** [comment]
> Do you have plans for adding custom element? Indeed it'll be a cleaner option.

Yes, I'll keep the issue open until it is ready

> Thanks for the quick reply!

:+1:

**Comment by jasonhjohnson** [comment]
+1
