### ISSUE TITLE
Row template and dataItem

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia-ui-toolkits/aurelia-kendoui-bridge#638]
I've created a [sample](https://gist.run/?id=23aadba69476bb389efdfe8c2a4a34a4) in which I try to create a button that pass the current dataItem as argument into a method in my vm.

I cannot make it work, ideas?

**Comment by JeroenVinke** [comment]
@enrico-padovani In every aurelia template you can use `$this` to get the reference to the context: https://gist.run/?id=eac422b028c1128f9859873d2380194c. So this will work in `<ak-template>` inside `<ak-col>`'s as well,

**Comment by enrico-padovani** [comment]
Cool!
