### ISSUE TITLE
Export to Excel 

### ISSUE THREAD

**Issue by johntom** [aurelia-ui-toolkits/aurelia-kendoui-bridge#640]
I just became aware to this issue (Export to Excel, Grid with Footer Aggregate #457) and see that it was closed as a kendoui issue yet there demo seems to work fine http://demos.telerik.com/kendo-ui/grid/excel-export. Unless I'm missing something, I think it should be re-opened and hopefully fixed.
Thanks

**Comment by JeroenVinke** [comment]
The issue with #457 is only occuring when aurelia/angular templates are used, which is why it does not show up in that demo
