### ISSUE TITLE
Localization documentations is missing instructions to call "kendo.culture()"

### ISSUE THREAD

**Issue by xenod** [aurelia-ui-toolkits/aurelia-kendoui-bridge#641]
The documentation for the localization of Kendo UI is missing instructions to call "kendo.culture()"- method to tell kendo to use your imported cultures file.

https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs-beta/content/localization.html

The following code does it:
"kendo.culture('nl-NL');"

Also, information on how to get kendo to use the imported messages file (for example in the grid, or in the scheduler) would be nice!

**Comment by avrahamcool** [comment]
I found that importing the `message` file in the `main.js` module doesnt do the trick.

but when I imported it in the `js` files of the modules who were creating the content using kendo, it worked.
it would be nice if we coul'd call the message file once in the main module for all sub modules.

**Comment by JeroenVinke** [comment]
@avrahamcool from [this post](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/617#issuecomment-260921435) I gather that you are using aurelia-cli. Are you loading kendo via requirejs (via import statements in your js code) or are you loading kendo from index.html?

**Comment by avrahamcool** [comment]
Indeed I'm using the CLI.
I'm loading kendo using requirejs, using import in my js files (each one of my modules loads only what he needs).

**Comment by JeroenVinke** [comment]
@avrahamcool sorry, I may have missed your reply. Have you been able to resolve it in the meantime or do you want me to look into it?

**Comment by avrahamcool** [comment]
I didn't really had the time to look into it until now.
But some other issues were solved when i upgraded from cli 18 to cli 22. so it might worth a re-check to see if it's still buggy.
i'll be happy if you also looked into it, and update me here.

**Comment by JeroenVinke** [comment]
I have tried setting the localization in an aurelia-cli application and it works when you load `kendo.core`, `cultures/kendo.culture.nl-NL`, and then call `kendo.culture('nl-NL')` to set the default localization.

I have updated the [documentation](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/localization.html)

**Comment by arvadevy** [comment]
And how to include your messages? My culture file works, but my messages are not displayed in the right language?

**Comment by JeroenVinke** [comment]
@arvadevy did you call `kendo.culture('nl-NL');` ? where nl-NL is the new default culture

**Comment by arvadevy** [comment]
main.ts:

```
import { Aurelia, Container } from 'aurelia-framework';
import { UserService } from 'user/user-service';
import 'kendo/js/kendo.core';
import 'kendo/js/messages/kendo.messages.nl-BE';
import 'kendo/js/cultures/kendo.culture.nl-BE';
import environment from './environment';

//Configure Bluebird Promises.
//Note: You may want to use environment-specific configuration.
(<any>Promise).config({
    warnings: {
        wForgottenReturn: false
    }
});


export function configure(aurelia: Aurelia) {
    aurelia.use
      .standardConfiguration()
      .feature('resources')
      .globalResources('resources/value-converters/null-nodata')
      .plugin('aurelia-kendoui-bridge')
      .plugin('aurelia-hammer')
      .plugin('aurelia-dialog');

    if (environment.debug) {
        aurelia.use.developmentLogging();
    }

    kendo.culture('nl-BE');

    aurelia.start().then(() => aurelia.setRoot(aurelia.container.get(UserService).isAuthenticated() ? 'shell/shell' : 'user/login/loginShell'));
}
```

**Comment by JeroenVinke** [comment]
I see, this is tricky when using a module loader as the messages file overrides some properties on the prototypes of Kendo controls. This means that all controls have to be loaded before you load the messages file, or else it will not have any effect. 

Without a module loader (see the index.html in [this gist](https://gist.run/?id=8826bc5f6c915575d9176406882fd791)) you can very easily load the messages file after you load the controls (kendo.all.min.js). With a module loader it is a bit more difficult as you can't say at which point all controls have been loaded.

I am not sure how to solve this in a nice way, but you could try and move the `import` statements of the kendo controls `import 'kendo/js/kendo.grid.min'` to `main.js`, and import the messages file after that

**Comment by arvadevy** [comment]
That seems to work, thanks a lot!
