### ISSUE TITLE
Row and column template don't use child router when using route-href custom attribute

### ISSUE THREAD

**Issue by MT-PL-SWF-Dev** [aurelia-ui-toolkits/aurelia-kendoui-bridge#643]
Hi,

I noticed that when you have child router configured and you use Kendo Grid in its scope, "route-href" attribute uses only AppRouter when resolving route name.

Gist reproduction:
https://gist.run/?id=019624d75846da4a1113fe0af7a1a680

Thanks!

**Comment by JeroenVinke** [comment]
Just need to update the unit tests before I can release this patch

**Comment by JeroenVinke** [comment]
patch is relaesed as aurelia-kendoui-bridge@1.0.0-beta.1.0.17. Let me know if you have issues

**Comment by MT-PL-SWF-Dev** [comment]
Sorry for trying this so lately but it works perfectly now. Thank you!
