### ISSUE TITLE
Panel Bar Loading with Ajax sample misses files

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#645]
URL: https://aurelia-ui-toolkits.github.io/demo-kendo-beta/#/samples/panelbar-ajax

Click on the `BODY` item results with 

```
jquery.min.js:4 GET https://aurelia-ui-toolkits.github.io/demo-kendo-beta/srcajaxContent1.html?_=1476197373813 404 (Not Found)
```

All 4 `Content<n>.html` files are missing on`gist-serve.jeroenvinke.nl` server

**Comment by JeroenVinke** [comment]
fixed, gist.run seems to not be serving files when a query string is used 

![image](https://cloud.githubusercontent.com/assets/2189477/21743174/0b0553a0-d4fd-11e6-8eb9-9f9f1da9b346.png)

Kendo uses $.ajax with `cache: false`, which adds a query string to prevent the browser from caching. And we can't disable it unfortunately. So I have updated the sample to grab the .html files directly from github which does serve them correctly
