### ISSUE TITLE
Autocomplete value property is missing from bindables

### ISSUE THREAD

**Issue by smccrea** [aurelia-ui-toolkits/aurelia-kendoui-bridge#648]
I was trying to debug why my kValue wasn't initializing the autocomplete and realized that the value property was missing in bindables.js - adding it back initialized the control properly.

**Comment by JeroenVinke** [comment]
Nice catch. Strange though, as this file is generates from teleriks api documentation.

Will take a look

**Comment by smccrea** [comment]
Very strange - the bindings.js hasn't changed in quite a while and the "Value Binding" example that sets k-value works fine. Currently running bridge beta.1.0.16 and Kendo 2016.3.914.

**Comment by JeroenVinke** [comment]
we actually have two lists of bindables. The first list comes from the bindables.js file that we generate from teleriks api documentation, the one you found. In addition we look at the `options` property on the prototype of kendo controls from which we get a second list of properties we want to create @bindable's for. This is done at runtime and should have resulted in the `value` bindable to be created, even though it is not in bindables.js (the first list)

We merge both two lists to get an accurate list of bindables

There is a scenario in which we couldnt read the prototype of kendo controls, but I do not quite remember the conditions exactly... are you using a module loader (import statements) combined with `kendo => kendo.pro()` from main.js or something similar?

**Comment by smccrea** [comment]
Yes, I'm using import statements (import 'kendo.autocomplete.min') and selectively specifying the controls (kendo => kendo.kendoAutoComplete().kendoButton().kendoDatePicker()...)

**Comment by JeroenVinke** [comment]
Ok. I think that you can do two things (in the meantime until we can fix the issue) 

- Add the import statements to main.js
- use require statements in views where you use the bridge and remove the selective control specification from main.js

**Comment by JeroenVinke** [comment]
Telerik fixed it in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/ad537776dbcfa2dd4bfbc32dc87041d649068179#diff-a957eca1382f9b57c1a833b4264d680cR1647

A new bindables.js file will be created as part of the fix for https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/637
