### ISSUE TITLE
Layout-View issue

### ISSUE THREAD

**Issue by Creadigme** [aurelia-ui-toolkits/aurelia-kendoui-bridge#650]
Hello,

I have an issue with the bridge and aurelia **layout-view** :
(http://aurelia.io/hub.html#/doc/article/aurelia/router/latest/router-configuration/10)

The gist for demonstration :
https://gist.run/?id=83095be4b585f57c7dcea7806feaa4c5

If we remove the layout-view attribute from the router the bridge work again.

Any idea ?

**Comment by JeroenVinke** [comment]
Hi,

I believe this is not limited to aurelia-kendoui-bridge, as the simplest custom element does not work either: https://gist.run/?id=32cd1350e912cd99c45155bf91aec633

**Comment by Creadigme** [comment]
With customElement decorator, it work : 

https://gist.run/?id=770e064b9906a5a7761fde27f8360cc1

**Comment by Creadigme** [comment]
Ok, it's not a kendo-bridge issue : 
( #https://github.com/aurelia/framework/issues/556)

I search a workaround...
