### ISSUE TITLE
Bad link on the help page

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#651]
![image](https://cloud.githubusercontent.com/assets/2712405/19728754/95e69a6c-9b62-11e6-8cf5-ee1ffd6f4675.png)

**Comment by adriatic** [comment]
___I am building beta branch of the bridge to fix it there___

**Comment by JeroenVinke** [comment]
So we just need to update the gh-pages?

**Comment by adriatic** [comment]
Yes, **but only as a function of the planned transition** from beta to production and retiring the old bridge:

1. Change the catalog version `Version 0.12.1` to `Version 0.12.1 - not supported` and remove the `Announcing KendoUI Bridge version 1.0.0 Beta` in the title.
2. Change the catalog version `1.0.0-beta.1.0.17 - beta` to version `1.0.0`

**Comment by adriatic** [comment]
I can do all that (except pushing these to gh-pages because I always failed in that step; I am pretty sure that there is some access rights issue that I do not have).

OK?

**Comment by adriatic** [comment]
This problem was fixed several releases before the current - just the catalog app (hosted at gh-pages) was not updated.
