### ISSUE TITLE
Retiring kendoui-bridge  0.12.4

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#652]
### Tasks:
1. Remove the reference to KendoUI beta **catalog** from the current production version of the catalog and replace it with the clear announcement that this version is not support from Nov 1, 2016 (Use at your own risk).
   
   1.1 I do not have a good idea on how to make this "retired" notice appear in front of the developer that uses it in his application. Certainly making a warning appear in the console when building and running it is something that we can and should do.
2. Change the version of the beta from '1.0.0-beta.1.0.17' to '1.0.17' (I believe that '1.0.0' would be looked at with suspicion)
3. Push this new version '1.0.17' of the bridge to npm
4. Put this new version of the catalog to gh_pages.

I would not remove any of the `0.x.x` series from npm registry since the version '1.0.17' will be picked as the newest one.

**Comment by adriatic** [comment]
I wanted to help by doing the above and failed miserably trying to change the version number in the new catalog app - I though that the version string is encoded [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/beta/package.json#L3) - but that does not seem to be the case. Searching for this string with sublime editor (after the build finished, alas) resulted with more matches than molecules in our galaxy - so I finally decided to leave it to @JeroenVinke 😢

**Comment by JeroenVinke** [comment]
> 1.1 I do not have a good idea on how to make this "retired" notice appear in front of the developer that uses it in his application. Certainly making a warning appear in the console when building and running it is something that we can and should do.

Yeah we should be able to create `0.13.0` with a deprecation warning

>  Change the version of the beta from '1.0.0-beta.1.0.17' to '1.0.17' (I believe that '1.0.0' would be looked at with suspicion)

No I don't think so, from `1.0.0-beta.1.0.17` we should go to `1.0.0`. Aurelia did it this way as well, and it would look like we skipped versions `1.0.0` to `1.0.17`

> I would not remove any of the 0.x.x series from npm registry since the version '1.0.17' will be picked as the newest one.

There are two tags on npm: stable and beta. I think we should remove the beta tag, and set the `stable` tag to 1.0.0. All versions on NPM will be kept, just the stable tag would point to 1.0.0

**Comment by adriatic** [comment]
> No I don't think so, from 1.0.0-beta.1.0.17 we should go to 1.0.0. Aurelia did it this way as well, and it would look like we skipped versions 1.0.0 to 1.0.17

Good argument!

**Comment by JeroenVinke** [comment]
We will probably need to change references of `demo-kendo-beta` to `demo-kendo`

Also, the should we move the demo-kendo-beta gitbook contents to the demo-kendo gitbook?

**Comment by adriatic** [comment]
Yes, to both - leave all that "crap" to me, you have more important things to do.

**Comment by adriatic** [comment]
Everything before **[these two comments](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/652#issuecomment-257162064)** was done long time ago.

> We will probably need to change references of demo-kendo-beta to demo-kendo

![image](https://cloud.githubusercontent.com/assets/2712405/21719495/23ac86ec-d3ec-11e6-8e92-27515b782366.png)

> Also, the should we move the demo-kendo-beta gitbook contents to the demo-kendo gitbook?

![image](https://cloud.githubusercontent.com/assets/2712405/21719400/a15644da-d3eb-11e6-8f8e-5ebc09162717.png)
