### ISSUE TITLE
Kendo grid with more then 1000 rows in IE have a very bad preformance

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#653]
@JeroenVinke Hello friend.
we are about going to production and we noticed that in IE11 kendo grid with more the 1000 rows have a very bad preformance.
i have generated a some sample and every time i select row , it's take about 2-3 seconds for the row to become selected.
i've tried to create a GIST but gist doent work in IE
What can we do PLEASE????? :(

**Comment by JeroenVinke** [comment]
Have you looked at [virtualization](https://gist.run/?id=8dc9218a2a5a8e9cdbae501b5833f9d5) ?

**Comment by eliavmaman** [comment]
@JeroenVinke i've looked at that but because the data in the server come from lots of apis it's a bit of a problem for us...( the api's doesn't pageables).
so i have to get all the data to grid...

**Comment by JeroenVinke** [comment]
Are you using custom column templates? If so, see if you can so without

**Comment by eliavmaman** [comment]
well after remove templates the grid is get better and still not reasonable ,and i also need to use those template...
arrrrgggg i m so confused

**Comment by JeroenVinke** [comment]
Well we aren't going to be able to reproduce, investigate and come up with a fix for this right away, it takes time. So you should consider using a workaround until we can look into this

**Comment by JeroenVinke** [comment]
Have you actually tried virtualization? Take a look at this sample: http://demos.telerik.com/kendo-ui/grid/virtualization-local-data

**Comment by eliavmaman** [comment]
10x @JeroenVinke  for your help ... we currently trying w2ui grid just as partial solution.
but 10x you r very kind
