### ISSUE TITLE
DropDownList Bind to Object

### ISSUE THREAD

**Issue by obeacons** [aurelia-ui-toolkits/aurelia-kendoui-bridge#655]
Is it possible to bind to an object in a similar manner to this?

http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-selects/4

The following code doesnt seem to work. If binding directly to the id all seems to work.

**View**
<ak-drop-down-list k-data-text-field="description"
                       k-data-value-field="id"
                       k-data-source.bind="countries"
                       k-value.two-way="criteria.countryid"
                       style="width: 100%">
    </ak-drop-down-list>

**Model**
constructor() {
        this.countries = [
            { id: 0, description: "Please Choose.." },
            { id: 1, description: "Canada" },
            { id: 2, description: "UK" },
            { id: 3, description: "Australia" }
        ];
        this.criteria = { countryid: this.countries[1] };
        
    }

**Comment by adriatic** [comment]
It may be worthwhile to first check **[Current limitations](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs-beta/content/app-developers-notes/current_limitations.html)** which explains the KendoUI bridge binding limitations. 

If this article does not provide the information you need, please present your issue as described **[Report a problem to Aurelia-UI-Toolkits team](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs-beta/content/troubleshooting/using_gists_and_gistrun.html#22-report-a-problem-to-aurelia-ui-toolkits-team)**? This format supports the immediate verification of your issues as well as providing our answers, without any time being wasted on misunderstandings. 

Lastly (to satisfy my own curiosity) are you aware of the **[KendoUI bridge online manual](http://aurelia-ui-toolkits.github.io/demo-kendo/#/about)**?

**Comment by obeacons** [comment]
I have read about the limitations and have read the online manual, but thought I would check to see if it is possible to bind an object to a drop down list. I didn't see this mentioned as being unsupported.

I made a gist that identifies what i'm trying to do. 
https://gist.run/?id=2d9ea71288885882e91f1f8b1dca643d

I was hoping the the field labeled (Kendo DropDownList bound to object) would actually have the value selected. Right now it doesn't seem to work.

Thanks

**Comment by JeroenVinke** [comment]
Hi @obeacons 

The Kendo dropdownlist control does not seem to support binding to objects (the `value` property is always the id, not the object). Therefore when you use `k-value.bind` it always uses the id, not the object. 

I think you could create a custom attribute that would build something like what you are asking for. I wouldn't add this as a feature to the bridge, but if you want I can create an example

**Comment by obeacons** [comment]
If its not too much trouble, it would be nice to have an example to work with.

**Comment by JeroenVinke** [comment]
@obeacons Take a look at [this gist](https://gist.run/?id=8407b6e2fc27b4bcccb9f6cee3f2b7d6)

**Comment by obeacons** [comment]
Much appreciated. Thanks for your help.
