### ISSUE TITLE
Kendo icons are not displayed?

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#656]
@JeroenVinke hey friend..
I don't understand why, but the k-icons all over the Aurelia Kendo controls  disappear ( not displayed).
what could be the reason?

**Comment by eliavmaman** [comment]
I m using version 0.11.9

**Comment by JeroenVinke** [comment]
Hi @eliavmaman,

Please update to 1.0.0, anything older than that is no longer supported. If you still have this issue, let us know

**Comment by eliavmaman** [comment]
ok will try that

**Comment by eliavmaman** [comment]
@JeroenVinke when update to version 1.0.0 that updates the dependencies of aurelia-templating  and a few others.
and after that our project stop working.
is there any guide of how to update aurelia-kendo-bridge without brake our project?

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/releases/tag/1.0.0-beta.1.0.1 explains what has changed. 

https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/what_you_need_to_know.html#591-who-loads-kendo explains that you now need to load Kendo yourself, either by including Kendo in `index.html`, or by configuring your module loader (JSPM in your case).

One example: if you want to use the `ak-button`, you need to `import kendo.button.min` in your view-model (so jspm loads the kendo button control) and

```
<require from "aurelia-kendoui-bridge/button/button"></require>
<button ak-button></button>
```

in your view. The `<require>` statement loads our button wrapper. In main.js we strongy recommend not to use `.pro()` anymore, but instead use `<require>` as shown above. So your main.js should look like this:

```
 export function configure(aurelia) {
   aurelia.use
     .standardConfiguration()
     .developmentLogging()
     .plugin('aurelia-kendoui-bridge'); // <-- here you don't use .pro() anymore

   aurelia.start().then(a => a.setRoot());
 }
```

**Comment by adriatic** [comment]
@JeroenVinke what do you think about adding this explanation into [this chapter](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/what_you_need_to_know.html) of the [Aurelia KendoUI Bridge Documentation](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/) book?

**Comment by JeroenVinke** [comment]
@adriatic yes that sounds like a good idea

**Comment by eliavmaman** [comment]
@JeroenVinke we all love u :)

**Comment by adriatic** [comment]
@eliavmaman who is included in "we all"?

**Comment by eliavmaman** [comment]
@adriatic me and u

**Comment by JeroenVinke** [comment]
Closing this issue, please reopen if kendo icons are still not displayed with the latest bridge
