### ISSUE TITLE
Kendo renders the whole grid during update/add of a single row

### ISSUE THREAD

**Issue by thakursagar** [aurelia-ui-toolkits/aurelia-kendoui-bridge#657]
When I try to use .set(propertyName, value) to update value for a single row, kendo re-renders the whole grid. Please refer to [this gist](https://gist.run/?id=8d155f6ab2ca9fde630769094ebd85a7)

**Comment by JeroenVinke** [comment]
Hmm, this is interesting: https://gist.run/?id=5617b297ce2ea4fc6e64856dddab5557

when using .set() the entire grid is rerendered, but when simply changing the property directly it only rerenders that row

**Comment by thakursagar** [comment]
Look at this case where I am trying to update the status, it does not update it. [Here is the gist](https://gist.run/?id=c77bd84b3d2ac6c204314850124ee0ec)

**Comment by thakursagar** [comment]
Also, is there any way that on .push(item) I can add the item to the grid without the grid being redrawn?

**Comment by JeroenVinke** [comment]
Sorry, I do not know. I recommend you contacting Telerik for this question.

**Comment by JeroenVinke** [comment]
Closing this as we do not know enough about the internals of the kendo grid to help
