### ISSUE TITLE
Grid example in about page needs require statements

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#667]
http://aurelia-ui-toolkits.github.io/demo-kendo/#/about does not use `<require>` statements, which will not work when you aren't loading the entire kendo bridge via main.js

**Comment by adriatic** [comment]
There is no reason for keeping this sample in a different form than the rest of them - however, I would argue in favor of keeping it where it lives now, with some additional explanation about why is it there and the reference to its second instance deep in the catalog.
