### ISSUE TITLE
Can't Change grid column name from parent 

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#668]
@JeroenVinke Hey
I've created that [GIST](https://gist.run/?id=d8379cc5ae403a636bdaba199e064d48) to describe my problem.

I'm trying to change the column name after the grid is loaded on button click,  it doesn't change.
any idea mate?

**Comment by JeroenVinke** [comment]
This is two-way binding, and it is not supported

**Comment by eliavmaman** [comment]
so if i want to achieve that i have to load the grid first in the constructor and when button click i need to use declarative jQuery to change that?

**Comment by JeroenVinke** [comment]
Yes, or you would have to recreate the grid just like you would do without the bridge

**Comment by eliavmaman** [comment]
10x man for the very quick response.
will take your advice.. :)
