### ISSUE TITLE
Stopping event propogation

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#669]
https://github.com/monterey-framework/prototyper/pull/10#discussion_r94164960

**Comment by JeroenVinke** [comment]
`.trigger` combined with `stopImmediatePropagation()` does the trick: https://gist.run/?id=7bfdbb5606cc01f1565bedf775b2a9cd

**Comment by adriatic** [comment]
Nice 😄
