### ISSUE TITLE
Ready DOM event

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#670]
Can we raise a 'ready' DOM event when the control is initialized? This will allow the user to interact with the control as soon as possible

**Comment by JeroenVinke** [comment]
Idea: we could set the initial value of `k-widget` to:
```
{
    "busy": "The control has not yet been initialized. <link to the documentation>"
}
```

Now `k-widget` stays `undefined` until the control gets initialized, making you wonder what is going wrong (does `k-widget` work, should I have used two-way binding, did I make a typo)

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/049e189af44ce865895b7abfced523f4295b6a96

Could not set the initial value to a warning message since it is overridden with `undefined` from the parent view model

**Comment by adriatic** [comment]
> Can we raise a 'ready' DOM event when the control is initialized? 

I guess that besides being a rhetorical question, this really introduces a great idea, since the issue is about the comfort of the aurelia-bridge user - not aurelia framework (where we need to drag the user through the intricacies of the aurelia life-cycle.

> Could not set the initial value to a warning message since it is overridden with undefined from the parent view model

I do not understand this completely, but feel that you know what to do without me 😏

**Comment by JeroenVinke** [comment]
Created https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/generic-on-ready-event, which doesn't work until we create the release and update the catalog (it works locally for me)

**Comment by JeroenVinke** [comment]
We should document this more, such as in the documentation (the "what you need to know" page should offer this as the solution for the problem where `k-widget` is still undefined in `attached()`

**Comment by adriatic** [comment]
I hope you implemented [this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/670#issuecomment-270073090) as well 😄

**Comment by JeroenVinke** [comment]
No, that can't be done, that way atleast. Very early on the value of `kWidget` in the wrapper is reset to whatever is the value of k-widget in the parent view-model (the screen that uses the control), which is undefined.

**Comment by adriatic** [comment]
Darn! (a nice variant of the chicken and egg problem)

**Comment by JeroenVinke** [comment]
This was added and is mentioned in the docs
