### ISSUE TITLE
Gantt sample does not work

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#674]
https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/gantt-basic-use

**Comment by adriatic** [comment]
This one works for me - but the next few (column resizing, Exporting to PDF, Resources) fail the same way: no error indications and the rendered view looks like

![image](https://cloud.githubusercontent.com/assets/2712405/21727508/c06948a8-d40f-11e6-9b88-bece10034e53.png)

**Comment by JeroenVinke** [comment]
ugh, it has to do with the way we render these gists in the catalog (hiding the target div in which the gist is rendered caused the issue)

**Comment by adriatic** [comment]
The explanation makes sense of course, the way it was set to be rendered perpahs not 😏
