### ISSUE TITLE
Review the current installation instructions for accuracy

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#679]
### [Installing kendo - JSPM](https://aurelia-ui-toolkits.gitbooks.io/kendo-ui-sdk-installation/content/installation/installing%20kendo/advanced/core/jspm.html)

1. `jspm install jquery css kendo-ui` should not include jquery (_the KendoUI SDK version's copy gets installed automatically_)

***
### [Installing the bridge - Webpack](https://aurelia-ui-toolkits.gitbooks.io/kendo-ui-sdk-installation/content/installation/installing%20the%20bridge/webpack.html)

1. The file `webpack.config.js` does not exist any more - likely renamed to `webpack.config.babel.js`

2.  `npm install kendo-ui-core jquery --save ` should not include `jquery` (_the KendoUI SDK version's copy gets installed automatically_)

3.  There is no `baseConfig` entry property in `webpack.config.babel.js`, so where should we set this

    ```
    'aurelia-kendoui-bridge': ['aurelia-kendoui-bridge']
    ```
4. Where should the two lines below be added? (_these are grid specific - we need to provide more explanation what and where to add_).

    ````
    <require from="aurelia-kendoui-bridge/grid/grid"></require>
    <require from="aurelia-kendoui-bridge/grid/col"></require>
    ````
___likely more to come___

**Comment by adriatic** [comment]
Did you close this because of the new [tutorials](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/developers_tutorials.html), corrections in [installation section](https://www.gitbook.com/book/aurelia-ui-toolkits/kendo-ui-sdk-installation/details) or both?

**Comment by JeroenVinke** [comment]
Both
