### ISSUE TITLE
Wrong parent context is used

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#685]
The bridge uses the bindingContext of the wrapper ([link](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/src/combobox/combobox.js#L27-L29)), which is often the parent context as well (the context of the parent view-model), but this is not always the case.

For example, in https://gist.run/?id=3ed6a711c5cd2b678af41025d2c53346 a repeat.for is used which causes the `bindingContext` of the `<ak-grid>` to be equal to the value of `a` in `repeat.for`.  This is not what the bridge needs, it needs the last parentContext (which __is__ the correct view-model)

**Comment by JeroenVinke** [comment]
cc @martyns

**Comment by JeroenVinke** [comment]
@martyns please see if it is fixed in 1.1.1. The gist mentioned in the first post of this issue now works with 1.1.1: https://gist.run/?id=60d1afb7f5f0b7cf63fc0e0a32c79be7

**Comment by martyns** [comment]
@JeroenVinke that does indeed fix the issue. Thank you very much!
