### ISSUE TITLE
Mapping all kendo requests to one file

### ISSUE THREAD

**Issue by brandonseydel** [aurelia-ui-toolkits/aurelia-kendoui-bridge#686]
Could be useful for someone who just wants kendo.all.min.js and have everything work.  I put a comment on the website already.

        <script>
            var systemLocate = System.locate;
            System.locate = function (load) {
                var System = this;
                return Promise.resolve(systemLocate.call(this, load)).then(function (address) {
                    var kendoIndex = address.indexOf('kendo.');
                    if (kendoIndex < 0) { return address;}
                   return address.substring(0, kendoIndex + 6) + 'all.min.js';
                });
            };
            System.import('aurelia-bootstrapper');
        </script>

**Comment by JeroenVinke** [comment]
Nice one. I'll keep this in mind, but overriding System.locate does not seem like the safest thing to do, so I don't think we should add this to the docs
