### ISSUE TITLE
using controls on initialization

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#688]
since `view-model.ref` is available on attached(), perhaps we can allow users to subscribe to a promise that gets resolved when the control has been initialized.

like

```
<ak-grid view-model.ref="myGrid">
```

```
attached() {
  this.myGrid.ready
  .then(grid => {
      // use grid kendo instance
  });
}
```

**Comment by vegarringdal** [comment]
👍 

Sounds very useful to know when the grid is ready to be used

**Comment by adriatic** [comment]
Because you used the word **`perhaps`** - I would say that this **`might be`** the most elegant solution (it is still pub-sub, but the user does not have to do much to use it)

**Comment by JeroenVinke** [comment]
k-on-ready has been implemented a while ago as displayed in https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/generic-use-widget-on-initialization
