### ISSUE TITLE
Missing component: dialog

### ISSUE THREAD

**Issue by Reverbe** [aurelia-ui-toolkits/aurelia-kendoui-bridge#690]
There's a relatively new [dialog](http://docs.telerik.com/kendo-ui/api/javascript/ui/dialog) component in Kendo. Would be cool to have it in the bridge :)

**Comment by JeroenVinke** [comment]
Released as 1.2.0 (http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/dialog-basic-use)
