### ISSUE TITLE
Update numerictextbox value on keyup

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#693]
Hi,

Currently, the value bound in `ak-numerictextbox` will only update after losing focus on the element. I noticed there was a `spin` event which I could tap into to automatically update the value when a user clicks the up/down arrow, however, I was wondering if there was a way to update the underlying value on the `keyup` event rather than doing anything hacky like that?

Here's something for Angular that seemed to be down the right path: http://docs.telerik.com/kendo-ui/controls/editors/numerictextbox/how-to/AngularJS/update-value-on-keyup

Thanks,
Jason

**Comment by JeroenVinke** [comment]
Hi Jason,

What do you think about a custom attribute like [this](https://gist.run/?id=21ae74c4fd990b319707ed5993650946)?

**Comment by jasonhjohnson** [comment]
@JeroenVinke That's awesome! Should I update the attribute to work for spin and keyup events, or, use the attribute and the spin event that's part of the bridge?

**Comment by JeroenVinke** [comment]
Great, that would have been my recommendation
