### ISSUE TITLE
destory prototye called on receate() is taking in two-way bind name instead of reference object

### ISSUE THREAD

**Issue by cdaniel77** [aurelia-ui-toolkits/aurelia-kendoui-bridge#696]
I upgraded my version of the bridge from 1.0.1 to 1.2.0 and all my charts that calls recreate() are erroring out saying.

![image](https://cloud.githubusercontent.com/assets/16883653/22431485/aa3cca7c-e6df-11e6-9dac-c94185c633ba.png)

I dug into the code and found the issue with the widget prototype.destroy(widget) call.  I traced the code and found that in widget-base.js on line 153, it is passing in the widget name (string) and not the entire viewModel object.  The viewMOdel object has the element object that the destroy is looking for.

![image](https://cloud.githubusercontent.com/assets/16883653/22431689/6d7f9cda-e6e0-11e6-8c02-4f4c33d11dc8.png)

**Comment by JeroenVinke** [comment]
This is not an issue of the bridge
