### ISSUE TITLE
How to catch the grid's onDataBound event

### ISSUE THREAD

**Issue by alastair-mcdonald** [aurelia-ui-toolkits/aurelia-kendoui-bridge#698]
I need to respond to the grid's dataBound event but cannot get it to work. Initially I got an error to the effect the grid does not have a databound event, but this error stopped when I  used the attribute `k-on-data-bound`. Previously I had been trying `k-on-databound`, `k-on-DataBound` and the like and it was only by chance I found the right syntax. Some documentation on this would be very welcome.

However while I no longer get any errors when the grid loads and displays its data, the onDataBound event is not fired, or not responded to. Hopefully I have a simple syntax error which you can see. Here is the html for the grid.

```
<template>
    <require from="aurelia-kendoui-bridge/grid/grid"></require>
    <require from="aurelia-kendoui-bridge/grid/col"></require>
    <require from="aurelia-kendoui-bridge/grid/grid-toolbar"></require>
    <require from="aurelia-kendoui-bridge/grid/grid-command"></require>
    <require from="aurelia-kendoui-bridge/common/template"></require>

    <div class="container">
        <h1>${heading}</h1>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <input type="search" placeholder="firstname, lastname or email" />
                <button class="btn">Search</button>
            </div>
            <div class="col-md-4" >
                <button class="btn" click.delegate="newClientNav()">New Client</button>
            </div>
        </div>
        <div class="row rowspace5">
            <div class="col-md-10">
                <ak-grid k-data-source.bind="datasource"
                        k-pageable.bind="{ input: true, numeric: false}"
                        k-filterable.bind="true"
                        k-sortable.bind="true"
                        k-scrollable.bind="true"
                        k-widget.bind="clientgrid"
                        k-on-data-bound="onDataBound($event)">
                    <ak-col k-title="First Name" k-field="firstName" k-width="100px"></ak-col>
                    <ak-col k-title="Last Name" k-field="lastName" k-width="100px"></ak-col>
                    <ak-col k-title="Email Address" k-field="primaryEmail" k-width="230px"></ak-col>
                    <ak-col>
                        <ak-grid-command k-name="details" k-text="Details" k-click.bind="details"></ak-grid-command>
                    </ak-col>
                </ak-grid>
            </div>

        </div>
    </div>
</template>

```
Here is the view model

```
import {inject} from 'aurelia-framework';
import {Router, RouterConfiguration} from 'aurelia-router';

@inject(Router)
export class Clients
{

    public heading = 'Clients';
    private router: Router;
    private datasource;
    private clientList;
    public clientgrid: kendo.ui.Grid;

    constructor(router: Router)
    {
        this.router = router;

        this.loadData();

        this.datasource = {
            data: this.clientList.clients,
            schema: {
                model: {
                fields: {
                    firstName: { type: 'string' },
                    lastName: { type: 'string' },
                    primaryEmail: { type: 'string' }
                }
                }
            },
            pageSize: 10
            };

    }

    private loadData()
    {
        this.clientList = { "clients" : [
                {
                    "firstName"     : "Alan",
                    "lastName"      : "Jones",
                    "primaryEmail"  : "alan.jones@example.com"
                },
                {
                    "firstName"     : "Peter",
                    "lastName"      : "Smith",
                    "primaryEmail"  : "peter.smith@eample.com"
                },
                {
                    "firstName"     : "Sue",
                    "lastName"      : "Williams",
                    "primaryEmail"  : "sue.williams@example.com"
                },
                {
                    "firstName"     : "Jackie",
                    "lastName"      : "Evans",
                    "primaryEmail"  : "jackie.evans@example.com"
                }
            ]
        }
    }

    public newClientNav()
    {
        this.router.navigateToRoute("clientadd");
    }

    public select(id)
    {
        return true;
    }

     // remove the href="#" from anchors
  // http://www.telerik.com/forums/grid-command-and-href=#rlBCjx-3y0OmKjBB0AfSEw
 // This function is never called 
  onDataBound(e) {
    console.log('in onDataBound');
    let grid = e.sender;
    $('a[href*=\'#\']', grid.tbody).removeAttr('href');
  }

  details(e) {

    console.log(this.clientgrid);
    this.router.navigate('help');
    console.log(e);
  }
}
```

The expected outcome is that the `onDataBound(e)` method is called when the grid has loaded its data, however the method is never called. The `details(e)` method does get called when the `Details` button is clicked.

Is there a syntax error that you can see?
is there any documentation on how to use the bridge to respond to grid events like this? Or samples to show correct usage? 

Thanks,
Alastair

**Comment by JeroenVinke** [comment]
Hi Alistair,

> I need to respond to the grid's dataBound event but cannot get it to work. Initially I got an error to the effect the grid does not have a databound event, but this error stopped when I used the attribute k-on-data-bound. Previously I had been trying k-on-databound, k-on-DataBound and the like and it was only by chance I found the right syntax. Some documentation on this would be very welcome.

We have documented the conventions (and examples) in this [article](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/what_you_need_to_know.html). I recommend reading it entirely as there quite some useful information in there.

Events, such as `dataBound` have the `k-on-` prefix, and capital letters are dashed, resulting in `k-on-data-bound`. Kendo events are raised as DOM events, and with Aurelia you can subscribe to DOM events using `.delegate`. So the correct syntax would be `k-on-data-bound.delegate="onDataBound($event)"`. [Autocomplete](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/autocomplete-events) has a similar event. On the [catalog website](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/generic-use-widget-on-initialization) we have loads of samples, so I recommend taking a look at those as well.

Let me know if anything else is unclear

**Comment by alastair-mcdonald** [comment]
Hi Jeroen, I have read the article you suggest carefully and several times, have been through many examples on the catalog website,  and am using the correct syntax as you suggest but it is still not working. Sounds like the next step is a Gist?
Thanks,
Alastair

**Comment by JeroenVinke** [comment]
Yes, please create a gist and I will take a look

**Comment by alastair-mcdonald** [comment]
I have created a gist here -  [https://gist.run/?id=304078107715e1ed0340e588044b348e](https://gist.run/?id=304078107715e1ed0340e588044b348e) -  which reproduces the behaviour; the `onDataBound` event does not fire. When it fires an alert box should pop up with the message "onDataBound event ran" and the message "in onDataBound" should be written to the console.  I'd appreciate an insights you may have. 

I noticed that the version of the plugin used in the gist does not include the fix for the ak-grid-command bug which was fixed recently (many thanks for that excellent fix). 

The version of kendo ui in my project is 2017.1.118 and in the gist it defaults to 2016.1.226, however the onDataBound event fails to fire in both versions.  

Thanks for having a look.

**Comment by JeroenVinke** [comment]
@alastair-mcdonald thank you for the gist. Here is the working version: https://gist.run/?id=de7e8d50fe4f922ffde38adafa705a71.

I have changed
`k-on-data-bound="onDataBound($event)"`

to 

`k-on-data-bound.delegate="onDataBound($event)"`

**Comment by alastair-mcdonald** [comment]
Many thanks, my mistake, I thought I made that change already. (too many trial and error changes made to get the event recognised).

Your docs are great, so are the samples, but it is worth noting that the conventions section makes no mention of event name camelCasing mapping to dashes (onDataBound => k-on-data-bound). This omission proved very time consuming and frustrating to get past until I encountered the answer by chance. A mention about this convention in the docs would be well worth it.

Thanks for all your excellent work on the bridge, very appreciated.

**Comment by JeroenVinke** [comment]
> Your docs are great, so are the samples, but it is worth noting that the conventions section makes no mention of event name camelCasing mapping to dashes (onDataBound => k-on-data-bound).

I was under the impression that we mentioned that, but I now see that we don't. We'll update that article

**Comment by alastair-mcdonald** [comment]
Many thanks again, this can certainly be closed from my perspective.
