### ISSUE TITLE
mention resources property in aurelia-cli installation instructions

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-bridge#700]
https://aurelia-ui-toolkits.gitbooks.io/kendo-ui-sdk-installation/content/installation/installing%20the%20bridge/requirejs.html

this should be added: `"resources": ["autocomplete/*.*", "dropdownlist/*.*"]` so that the wrappers are included in the bundle

**Comment by BikashDas19** [comment]
Thanks Jeroen.
