### ISSUE TITLE
Color picker control in a kendo window repeats after multiple close/open's

### ISSUE THREAD

**Issue by pmarchio** [aurelia-ui-toolkits/aurelia-kendoui-bridge#701]

**Comment by pmarchio** [comment]
closing this issue as the same code does not exhibit the problem in the gist.

**Comment by JeroenVinke** [comment]
Just to confirm, what version of the bridge was in the index.html of the gist? 

![image](https://cloud.githubusercontent.com/assets/2189477/22568651/f5afc68c-e994-11e6-915a-2af0f0905221.png)
