### ISSUE TITLE
Gist.run & Kendo bridge Catalog both fails to start using IE 11 on windows 10

### ISSUE THREAD

**Issue by pKrav75** [aurelia-ui-toolkits/aurelia-kendoui-bridge#704]
Hello,
I m running IE 11.576.14393.0CO (evergreen) on WIN10-64.

Trying to access to gist.run fails with promise undefined (missing import ??)
![image](https://cloud.githubusercontent.com/assets/17618403/22702358/b1c4eb3a-ed60-11e6-9dbb-a76e44d6479c.png)

Trying to access to Kendo bridge catalog hangs with console stack over flow error. 
Donot know if it is the same source of error.

![image](https://cloud.githubusercontent.com/assets/17618403/22702475/1eab77f0-ed61-11e6-8308-a69db4ec2f41.png)

**Comment by pKrav75** [comment]
Sorry for French logs !

**Comment by pKrav75** [comment]
Actually the 1st one is a duplicate of https://github.com/gist-run/gist-run/issues/38

**Comment by Thanood** [comment]
I wonder how it's missing a Promise polyfill (and it does) although you've included bluebird..

**Comment by JeroenVinke** [comment]
Tracking the IE issues regarding the catalog here: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/441
