### ISSUE TITLE
Can't change chart series 

### ISSUE THREAD

**Issue by tonercart** [aurelia-ui-toolkits/aurelia-kendoui-bridge#705]
Trying to change the series in a chart in response to user input but can't work out how. See the Gist for an attempt using recreate. Nothing happens on first few button clicks then it seems to start working. Not sure if this is the way to go and would appreciate some guidance.

https://gist.run/?id=1f9fe2c814db54c75c4180d9cb5abb87

**Comment by tonercart** [comment]
oops wrong url. Try this one

https://gist.run/?id=1f9fe2c814db54c75c4180d9cb5abb87

**Comment by JeroenVinke** [comment]
Hi @tonercart, thank you for the gist

I see two issues here where one is slightly less obvious than the other. Firstly, the first time you click the button the showVisitors flag is still true and therefore will not apply a different chart series (the flag is flipped after the if, while you expect it to be flipped before the if)

The second issue is that aurelia's binding system needs some time to process the modification of the `this.series` variable. This happens asyncronously meaning that when you call `.recreate()` the old series is used to initialize the control. You can delay the .recreate() call (either with setTimeout or Aurelia's TaskQueue). I have demonstrated it with the taskqueue here: https://gist.run/?id=6f16b017bb514682f4c188f8b20e52fa. Good luck and let me know if there are more issues

**Comment by tonercart** [comment]
@JeroenVinke - Thanks for the speedy response, that works a treat.
