### ISSUE TITLE
Converter not working in a slotTemplate of the scheduler.

### ISSUE THREAD

**Issue by Xenope** [aurelia-ui-toolkits/aurelia-kendoui-bridge#708]
Here is the gist : https://gist.run/?id=7422b2adcec995d65fa4b7d1f8171820

If we only show the date in the slotTemplate it's fine but as soon as we use a converter it fails completely :  "movieTime is not defined". (movieTime is the converter).

It's strange because it works in the eventTemplate.

**Comment by JeroenVinke** [comment]
I believe it is the same issue as with the groupHeaderTemplate. I forwarded your request to [here](https://github.com/telerik/kendo-ui-core/issues/2749#issuecomment-278727510). I think you need to resort to using kendo's templating syntax for this one

**Comment by Xenope** [comment]
Hi, 

just to inform you, we have a commercial licence with kendo so i opened an issue on the telerik site as well.
The guys came back to me with this answer : 

> Currently, Scheduler does not support angular template directives for the groupHeaderTemplate. Have a look at this article showing the supported template directives among the widgets:
>
> http://docs.telerik.com/kendo-ui/AngularJS/introduction#template-directives
>
> You could use the groupHeaderTemplate as follows: http://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler#configuration-groupHeaderTemplate or modify the current function:
>
> groupHeaderTemplate: function (e) {
       return e.text + "@@";
},
> 
>Regards,
>Joana 
>Telerik by Progress

With the info provided I managed to do what i wanted. It's up to you if you wanna close this one.

Thanks.
