### ISSUE TITLE
k-data-source binding not working in TreeView when data is not set on initialize

### ISSUE THREAD

**Issue by IngoBleile** [aurelia-ui-toolkits/aurelia-kendoui-bridge#713]
Hi,

I am changing the k-data-source (changing data only, not the structure) in a TreeView depending on what gets selected in a combobox. It workes only if I do it by calling .setDataSource() like so:

this.treeview.setDataSource(dataSource);

Shouldn't the binding system automatically trigger a refresh of the TreeView? How would I test such a module when I need to reference and operate on the control?

```
  <ak-treeview id="treeview"
    k-data-source.two-way="dataSource"
    k-widget.bind="treeview"
    k-on-select.delegate="onSelect($event.detail)"
    >
  </ak-treeview>
```

```
private dataSource: kendo.data.HierarchicalDataSource;

// Refresh data when user chooses another mandator
private refresh(mandatorId: number) {
  this.spService.SpObjectExplorer(mandatorId)
    .then(items => {
      this.dataSource = new kendo.data.HierarchicalDataSource({
        data: this.createTreeDataStructure(items)
      });
      this.treeview.setDataSource(this.dataSource);   // This should not be necessary, right?
    });
};
```
Thanks for your help

**Comment by JeroenVinke** [comment]
Hi, yes the `setDataSource` is necessary, we have explained the need in [this article](https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs/content/what_you_need_to_know.html#596-two-way-binding).

**Comment by IngoBleile** [comment]
Thank you very much, Jeroen!
