### ISSUE TITLE
Responsive Panel

### ISSUE THREAD

**Issue by joakimhallberg** [aurelia-ui-toolkits/aurelia-kendoui-bridge#715]
I have tried using the ResponsivePanel, but can't really make anything work with it accept the default behavior.
How to setup the configuration for the panel?
How to call methods on the panel?

**Comment by JeroenVinke** [comment]
Hi @joakimhallberg 

Take a look at this gist: https://gist.run/?id=699494d52b9e1883b01797eb20c0277b

The responsive panel is one of the lesser used controls, so we also don't have many samples for this control. But you should be able to look at other controls to see how to configure them, such as the [datepicker](https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/datepicker-api)

**Comment by joakimhallberg** [comment]
Thank you, that helped a lot.
Now I have the second problem. I think it's due to the autoClose property doesn't work as expected.
I did try this with kendo only code and had to use latest version for it to work
When opening the responsive panel and selecting an item in the multi-selects, the responsive panel closes. 
Also it looks like I'm not able to set the autoclose configuration to false, since it always behaves as it is true. I think setting it to false might do the trick (does in a kendo only page).
[Gist](https://gist.run/?id=d1c6bc036fa4633fd37bd8ecb42a579f)

**Comment by joakimhallberg** [comment]
That works, even if its annoying to have to have the auto-close set to false to get it to work, but that is a Telerik bug.
Had read the chapter, but it wasn't clear what attribute would be called (autoClose, autoclose or auto-close). In this case I also missed that it was in an JSON structure and would need to have quotes around it.
