### ISSUE TITLE
Unable to change width of DropDownList

### ISSUE THREAD

**Issue by alastair-mcdonald** [aurelia-ui-toolkits/aurelia-kendoui-bridge#717]
I need to increase the width of a DropDownList to accommodate longer text however nothing I have tried  achieves this. I have tried the same with the bare KendoUI control and the width increased no problem using `style="width: 100%"` so I expected to be able to use the same method with the wrapped control.

Here is a [link to a gist](https://gist.run/?id=ebfa22be90d4d342c238a342f6a9dbd5&sha=ad0d59a9e57ca8b10192948e072a9bf7bc03c6f7) which demos the problem.

I expected the following to work ( `style="width: 100%"`)
```
<ak-drop-down-list k-data-text-field="description"
				   k-data-value-field="id"
				   k-data-source.bind="serviceDataSource"
				   k-enable.bind="true"
				   k-widget.bind="serviceDropDown"
				   k-value.two-way="model.defaultServiceId"
				   style="width: 100%">
	<select></select>
</ak-drop-down-list>
```
Also,  `style="width: 400px;"` makes no difference.

Applying a class also makes no difference, e.g. a class of 
```
.myDdl{
    width: 400px;
}
```
applied as follows makes no difference.
```
<ak-drop-down-list k-data-text-field="description"
				   k-data-value-field="id"
				   k-data-source.bind="serviceDataSource"
				   k-enable.bind="true"
				   k-widget.bind="serviceDropDown"
				   k-value.two-way="model.defaultServiceId"
				   k-auto-width.bind="true"
				   class="myDdl">
	<select></select>
</ak-drop-down-list>
```
I also tried `k-auto-width.bind="true"`, to no avail:
```
<ak-drop-down-list k-data-text-field="description"
				   k-data-value-field="id"
				   k-data-source.bind="serviceDataSource"
				   k-enable.bind="true"
				   k-widget.bind="serviceDropDown"
				   k-value.two-way="model.defaultServiceId"
				   k-auto-width.bind="true"
				   style="width: 100%">
	<select></select>
</ak-drop-down-list>
```
Calling `this.serviceDropDown.list.width(250);` does alter the width of the drop down, but not the width of the control at rest.

Perhaps I am missing something obvious and would appreciate your insights.

Thanks,
Alastair McDonald

**Comment by JeroenVinke** [comment]
Hi @alastair-mcdonald,

Does [this](https://gist.run/?id=af084ced8c45a0fd55b9f79c3c110137) do what you want to do?

**Comment by alastair-mcdonald** [comment]
Hi Jeroen, yes it does, many thanks for your quick response which does solve the problem.

I am happy for this to be closed.

Thanks again,
Alastair
