### ISSUE TITLE
Scheduler Server Side Filtering

### ISSUE THREAD

**Issue by jrabalais** [aurelia-ui-toolkits/aurelia-kendoui-bridge#718]
I am trying to implment server filtering for the scheduler control as in the below Kendo example:
http://www.telerik.com/support/code-library/kendoui-scheduler-server-filtering

However, my scheduler control is not in scope when the parameterMap is called and I get an undefined error.  I also tried adding the @delayed attribute to my datasource, but that did not help either.  See attached for my View and ViewModel code.

<img width="372" alt="view" src="https://cloud.githubusercontent.com/assets/18606484/23731703/b3ca219e-0434-11e7-8744-dc814831a83d.PNG">

<img width="397" alt="viewmodel" src="https://cloud.githubusercontent.com/assets/18606484/23731710/ba36cef6-0434-11e7-95b2-4e8122a5a73d.PNG">

**Comment by JeroenVinke** [comment]
Could you please create a gist? [here](https://aurelia-ui-toolkits.github.io/demo-kendo/#/help) are some instructions. Thanks.

**Comment by jrabalais** [comment]
I can't really because my project is quite large and has a lot of
dependencies.

**Comment by alastair-mcdonald** [comment]
I am trying to do the same thing and am having a very similar problem.

Here is a [link to a gist](https://gist.run/?id=b747661a477d49db2c1c5f93e5337509&sha=d64b48714abc883785683876e9724ed8211a08ee) which demos the problem. 

I am attempting to solve the problem by calling the function this.getAppointments() as per the code below. When `setKendoDataSource()` is run the variable `this` contains the function `getAppointments()`, however when kendo processes the call, `this` becomes a transport object and does not contain the function `getAppointments()`. 


```
Diary.prototype.setKendoDataSource = function () {
	this.dataSource = new kendo.data.SchedulerDataSource({
		transport: {
			read: function (options) {
				this.getAppointments()
					.then(function (data) {                            
					options.success(data);
				});
			},
			update: {},
			create: {},
			destroy: {},
			parameterMap: function (options, operation) {
				if (operation == "read") {
					var result = {
						startDate: this.scheduler().view().startDate(),
						endDate: this.scheduler().view().endDate()
					};
					return kendo.stringify(result);
				}
				else if (operation !== "read" && options.models) {
					return { models: kendo.stringify(options.models) };
				}
			}
		},
		serverFiltering: true
	});
	this.scheduler.setDataSource(this.dataSource);
};
```
The error received is 
![image](https://cloud.githubusercontent.com/assets/20189666/24100930/2f1a8f9a-0d6e-11e7-9275-80da67a5935c.png)

What is the correct way to get the transport object to call a function which can then call a data service? as per 

```
transport: {
	read: function (options) {
		this.getAppointments()
			.then(function (data) {                            
			options.success(data);
	}
```

**Comment by millman82** [comment]
The context of this changes during execution. You need to add:

`var self = this;`

as the first statement in your method and then update all this. to self.

See this working example. [https://gist.run/?id=69f86cead74ef83fbec9ae223fcf8164](url)

The important bits:

`Diary.prototype.setKendoDataSource = function () {
            var self = this;
            self.dataSource = new kendo.data.SchedulerDataSource({
                transport: {
                    read: function (options) {
                        self.getAppointments()
                            .then(function (data) {                            
                            options.success(data);
                        });
                    },
                    update: {},
                    create: {},
                    destroy: {},
                    parameterMap: function (options, operation) {
                        if (operation == "read") {
                            var result = {
                                startDate: self.scheduler().view().startDate(),
                                endDate: self.scheduler().view().endDate()
                            };
                            return kendo.stringify(result);
                        }
                        else if (operation !== "read" && options.models) {
                            return { models: kendo.stringify(options.models) };
                        }
                    }
                },
                serverFiltering: true
            });
            self.scheduler.setDataSource(self.dataSource);
        };`

**Comment by adriatic** [comment]
Thanks for this contribution @millman82 :-)

**Comment by alastair-mcdonald** [comment]
Thank you @millman82 for your solution - I am now getting data back from the database. Fixed it for me 👍
