### ISSUE TITLE
How can I deploy Aurelia bundles to another directory during build?

### ISSUE THREAD

**Issue by BikashDas19** [aurelia-ui-toolkits/aurelia-kendoui-bridge#725]
Hi,

How can I deploy the index.html and all the script file to a different folder  on au build commend.

Can i do it without using gulp task for the same( only by modifying Aurelia.json).

Regards,
Bikash

**Comment by JeroenVinke** [comment]
Hi, please ask this in the Aurelia gitter channel / stackoverflow, or open an issue in the CLI repository if you do not get an answer.
