### ISSUE TITLE
Global resources and webpack

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia-ui-toolkits/aurelia-kendoui-bridge#727]
Hi,

when I try to export kendo global resources in my main.ts, webpack does not find the modules.

if I try to do this:

```
.plugin('aurelia-kendoui-bridge', (config: KendoConfigBuilder) => {
    config.kendoAutoComplete();
})
```

does not work unless I manually add each resources to my package.json like so:

```
"aurelia": {
    "build": {
      "resources": [
        "aurelia-kendoui-bridge/autocomplete/autocomplete"
      ]
    }
  }
```

This become painful if I want all components by calling .pro()

I think one possible solution could be to add all resources in your package.json, so when installing with npm, we could get everything in place in case of need.

What do you think?

**Comment by JeroenVinke** [comment]
Sounds like a good idea. Can you submit a PR?

**Comment by enrico-padovani** [comment]
Done: #729 :)

**Comment by JeroenVinke** [comment]
closed via https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/pull/729, will be released shortly
