### ISSUE TITLE
npm kendo credentials stored in the package.json

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#728]
Hi,

I'm using the Aurelia CLI module loader instructions for installing Kendo Professional. It all works great. How would I handle not storing my username/password in the package.json but still have other people on the team be able to get the project up and running?

Thanks,
Jason

**Comment by JeroenVinke** [comment]
I can only refer you to http://docs.telerik.com/kendo-ui/intro/installation/npm unfortunately.
