### ISSUE TITLE
Changing kendoDataSource does not render the grid

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia-ui-toolkits/aurelia-kendoui-bridge#732]
Hi,

I'm aware that the datasource is copied into the kendo widget and that you loose the reference on it. For that reason, I'm trying to create a new datasource each time I need to change the grid (ex: change page, change filters, ...). But nothing happens.

The only way is to remove the ak-grid from the DOM each time.

Do you have any suggestion in how to solve this?

**Comment by JeroenVinke** [comment]
Try calling the setDataSource() function on the widget

**Comment by enrico-padovani** [comment]
Yes it works,

need a ref to k-widget.bind="gridWidget" and then in the vm: this.gridWidget.setDataSource(myDs);
