### ISSUE TITLE
kendoCombox : setOptions({autoWidth:true}) applied on k-on-ready.delegate breaks list content template

### ISSUE THREAD

**Issue by pKrav75** [aurelia-ui-toolkits/aurelia-kendoui-bridge#737]
Context : 
- Bridge 1.5.0
- Kendo UI v2016.3.914 
- All browsers : FF / Chrome

How to reproduce : https://gist.run/?id=6915dd9a1f7648a753c02946904ffe5d 
Click to display list.

Since trying to set k-auto-width.bind="true" was not working, I've decided to apply autoWidth option directly on kendo widget. Works when data source is fetched over the network, but not if data is predefined. 
In this case, list template is not compiled.

**Comment by JeroenVinke** [comment]
👍

**Comment by pKrav75** [comment]
Besides i can confirm that the ```javascript k-auto-width.bind="true"``` has no effect on the kendo combo box

**Comment by pKrav75** [comment]
Actually, adding autoWidth to common/bindable.js does solve my initial issue. Can i change / push that somewhere ?

**Comment by JeroenVinke** [comment]
Sorry for the delay. I'm releasing 1.5.2 now which should fix this

**Comment by JeroenVinke** [comment]
https://gist.run/?id=410805e60c51ca6b67070de751a483b3 is the updated gist

**Comment by pKrav75** [comment]
Many thanks Jeroen
