### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by arnederuwe** [aurelia-ui-toolkits/aurelia-kendoui-bridge#738]
The installation docs for Kendo PRO seem out of date. Telerik recently moved their pro code to an npm registry, the code isn't in node_modules/kendo anymore, but in node_modules\\@progress\kendo-ui
see http://docs.telerik.com/kendo-ui/intro/installation/npm#kendo-ui-professional

**Comment by JeroenVinke** [comment]
I believe they're up to date now
