### ISSUE TITLE
Grid detail template valueConverter

### ISSUE THREAD

**Issue by tmrajmohan** [aurelia-ui-toolkits/aurelia-kendoui-bridge#740]
Hello,
I am facing an issue in detail grid column template.

colum template:
```
<span>
    <span class="v-middle">
        ${orderDate | dateTime} // dateTime is a valueConverter
    </span>
</span>
```

Column template might have some value converters, so the value converters declared globally, but the column template doesn't seem to recognize the value converters.

please look at the below mentioned gist run.

Not Working version: https://gist.run/?id=168a6b4cecfbacbe0629f39d2f786cf6 `template: () =>{ } `
Working version: https://gist.run/?id=7d122a1e7ada851ef1fe4f621a0458f6 `template: '<span>hello ${OrderID}</span>'`

The only difference is the 'OrderID' columns template field.

Please give us a solution to make it working.

Thanks,

**Comment by davismj** [comment]
Any solution where you have to start manually instantiating kendo components (like in the detail intit callback) seems fundamentally broken. Is there no solution where you can just use the bridge components inside the detail template?

**Comment by JeroenVinke** [comment]
Sure, you can do all kinds of crazy stuff: https://gist.run/?id=1c3cc53ce4b609d59fd874e8a2ebaee2

**Comment by davismj** [comment]
Awesome! Probably should be updated in the docs. I think people are getting confused by that detail-init example.

**Comment by JeroenVinke** [comment]
You're right, will fix that

**Comment by ersandgamp** [comment]
> Sure, you can do all kinds of crazy stuff: https://gist.run/?id=1c3cc53ce4b609d59fd874e8a2ebaee2

Thanks for the sample. As I can see in this example the inner grid does not what was selected in the parent. Can you show me how to connect the inner grid with the parent's selection?

**Comment by JeroenVinke** [comment]
Sure, take a look at: https://gist.run/?id=3509ebc8920a10c889fcb5a2c28d90d4 and https://gist.run/?id=74598dce91e5cee43059e2a4336bc4d0

**Comment by JeroenVinke** [comment]
Added this one as https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid-detail-template
