### ISSUE TITLE
Custom edit template for scheduler not working.

### ISSUE THREAD

**Issue by alastair-mcdonald** [aurelia-ui-toolkits/aurelia-kendoui-bridge#744]
I need to add a custom edit event template to a scheduler control but am having difficulties. Specifically, when the webpage containing the scheduler loads I get the error 
`bluebird.min.js:31 Unhandled rejection Error: au property not found on element AK-TEMPLATE. Did you load this custom element via <require> or via main.js?
    at HTMLElement.eval (http://localhost:9000/jspm_packages/npm/aurelia-kendoui-bridge@1.2.0/common/util.js:126:17)`

I noticed in [issue 491](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/491) that the correct syntax should be 

```
        <ak-template for="editable.template">
          <h3>Edit template</h3>
        </ak-template>
```

The template I am using looks like this
```
<template>
    <require from="aurelia-kendoui-bridge/scheduler/scheduler"></require>
    <div class="spaceUnderTopMenu"></div>
    <div class="container">
        <div class="row">
            <ak-scheduler
                k-timezone.bind="Etc/UTC"
                k-date.bind="date"
                k-views.bind="[
                    {type: 'month', selected: true},
                    'week',
                    'workWeek',
                    'day',
                    'agenda'
                ]"
                k-height.bind="650"
                k-editable.bind="true"
                k-widget.bind="scheduler">
                <ak-template for="editable.template">
                    <h3>Event Template</h3>
               </ak-template>
            </ak-scheduler>
        </div>
    </div>
</template>
```
and if I remove the `<ak-template for="editable.template">...</ak-template>` element the scheduler works with no errors.

Is there additional configuration or a `<require>` needed to get custom edit templates to work?

Thanks,
Alastair

**Comment by JeroenVinke** [comment]
Hey. Yes, you need to require `aurelia-kendoui-bridge/common/template `. If you need to compare it to something, I believe it is used in the basic use sample of the Grid control on the catalog website

**Comment by alastair-mcdonald** [comment]
Hi @JeroenVinke , thank you for your quick response.

With the following require in place
`<require from="aurelia-kendoui-bridge/common/template"></require>`
I get the new error 
	bluebird.min.js:31 Unhandled rejection TypeError: Cannot create property 'template' on boolean 'true'
    at AccessMember.assign (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.2.1/aurelia-binding.js:1499:27)
    at eval (http://localhost:9000/jspm_packages/npm/aurelia-kendoui-bridge@1.2.0/common/template-gatherer.js:69:24)

Stepping through the code (shown below) I find that in aurelia-binding.js, line 1499, the variable `instance` has the value of true (it is a boolean, not a collection or an object.

```
    AccessMember.prototype.assign = function assign(scope, value) {
      var instance = this.object.evaluate(scope);

      if (instance === null || instance === undefined) {
        instance = {};
        this.object.assign(scope, instance);
      }
      
      // line 1499, instance has the value of true, which generates the error
      instance[this.name] = value;
      return value;
    };
```
Is this enough for you to recognise the problem? If not, I will put a gist together.

Thanks,
Alastair

**Comment by JeroenVinke** [comment]
Try `k-editable.bind={}` or removing `k-editable.bind="true" `altogether.

**Comment by alastair-mcdonald** [comment]
Much appreciated @JeroenVinke, both these suggestions worked, many thanks.
🥇
