### ISSUE TITLE
KendoGrid - scrollable not working on mobile

### ISSUE THREAD

**Issue by avizcaino** [aurelia-ui-toolkits/aurelia-kendoui-bridge#745]
Hi,

I'm having some trouble with scrolling in mobile devices with kendoGrid. Is anyone having the same problem. It works fine on desktop but when trying to scroll on a mobile device or emulating with chrome-console, it's not working...

I've tried with `k-scrollable.bind="{virtual: true}"`, which seems works on both environments, but when updating the grid content (such as applying filters) it attaches a second grid at the bottom of the original one.

If I use `k-scrollable.bind="true"`, it doesn't work.

Thanks,

**Comment by JeroenVinke** [comment]
Hey @avizcaino, could you provide the steps necessary to reproduce the issue?

**Comment by avizcaino** [comment]
Basically I have the following InlineViewStrategy where I build kendoGrid.

```
public getViewStrategy() {
    let fields = this.model.fields;

    let markup = '<template><busy-indicator is-busy.bind="loading">' +
      '<require from="kendo-ui/styles/kendo.common-material.min.css!"></require>' +
      '<require from="kendo-ui/styles/kendo.material.min.css!"></require>' +
      '<require from="aurelia-kendoui-bridge/grid/grid"></require>' +
      '<require from="aurelia-kendoui-bridge/grid/col"></require>' +
      '<require from="aurelia-kendoui-bridge/common/template"></require>' +
      '<require from="list-view/behaviors/toggle-grid-item-selection"></require>' +
      '<require from="list-view/behaviors/kendo-height"></require>' +
      '<require from="common/ui/converters/user-format-converters"></require>' +
      '<ak-grid k-sortable.bind="true" k-reorderable.bind="true" view-model.ref="gridVM" k-pageable.bind="{ refresh: false, pageSizes: true, buttonCount: 10 }" ' +
      'k-data-source.bind="datasource" k-scrollable.bind="{virtual: true}" k-selectable.bind="true" k-groupable.bind="groupable" k-on-change.trigger="selectRow($event.detail)" k-editable.bind="model.isDetail" k-excel.bind="{ allPages: true }" k-on-excel-export.trigger="excelExport($event.detail)">';
    
    fields.forEach(f => {
      markup += '<ak-col k-title="' + f.label + '" k-field="' + f.key + '" k-width="' + f.width + '" >';
      markup += '<ak-template>${' + f.key + '}</ak-template>'
      markup += '</ak-col>'
    });
    markup += '</ak-grid></busy-indicator></template>';
    return new InlineViewStrategy(markup);
  }
```

As you can see, in this example, the scrollable value is `k-scrollable.bind="{virtual: true}"`. This works on both desktop and mobile devices. If I exchange this with `k-scrollable.bind="true"`. It stops working on mobile...

**Comment by JeroenVinke** [comment]
@avizcaino I wasn't able to confirm this behavior. I've used this app: https://github.com/JeroenVinke/aurelia-kendoui-745. Could you run that app, see what's needed to reproduce the issue and get back to me? Thanks
