### ISSUE TITLE
Row number in Grid

### ISSUE THREAD

**Issue by arnevdv** [aurelia-ui-toolkits/aurelia-kendoui-bridge#750]
Is there any way to display the row number in a grid?
For example:
```
<ak-col k-title="Row Number" k-field="$index" k-width.bind="40">
   <ak-template>
      <span>${$index}</span>
   </ak-template>
</ak-col>
```
Or any other simple and clean way to achieve this?

This is the official documentation about it:
http://docs.telerik.com/kendo-ui/controls/data-management/grid/how-to/Templates/add-row-numbers

**Comment by JeroenVinke** [comment]
Hey @arnevdv. What do you think about https://gist.run/?id=023c72bbef47863e9d3b1c8ed9638279?

**Comment by arnevdv** [comment]
This works but I do not think it is a good practice. For now I have found a solution where I put the rownumber in the object.

**Comment by JeroenVinke** [comment]
That's good as well. At which point are you doing this, in the `read` callback of your datasource?

**Comment by arnevdv** [comment]
In my aplication I add one row at a time in a validate function because that's the way my application uses the grid:
![image](https://user-images.githubusercontent.com/15064170/26968489-79931104-4d02-11e7-9ff7-36d8f447aec0.png)
Otherwise I would do this in the read callback I think

**Comment by JeroenVinke** [comment]
I see, thanks for sharing!
