### ISSUE TITLE
TabStrip: data binding with compose element

### ISSUE THREAD

**Issue by gautamsi** [aurelia-ui-toolkits/aurelia-kendoui-bridge#751]
is it possible to make something like this?

```html
<div id="tabstrip" ak-tabstrip="k-animation.bind: { open: { effects: 'fadeIn' }}">
      <ul>
        <li repeat.for="tab of myTabs">
          ${tab.label} 
        </li>        
      </ul>
      <div  repeat.for="tab of myTabs">
        <compose view-model.bind="tab.viewModel"></compose>        
      </div>
    </div>
```

or may be someone can provide details on how to append content with compose element

**Comment by JeroenVinke** [comment]
As a one time rendering you mean? Or do you want to push new tabs to `myTabs` as well?

If you need a dynamic tabstrip, take a look at https://gist.run/?id=b3df9d740a3cf3d31098c83c9ffe8614 which was made by @len-ro

**Comment by gautamsi** [comment]
One time rendering works but i want to push new tabs as well.

I saw the gist earlier, seems complex for simple requirement.

**Comment by JeroenVinke** [comment]
Yes, it is complex. The thing is that all changes (such as adding a tab, removing a tab) should be done by the Kendo control via the API functions they provide so that the control can deal with the change internally. If this were not the case, it would be more straight forward.

**Comment by gautamsi** [comment]
that is the reason, I went with js code porting in my project [aurelia-OfficeUIFagric](https://github.com/gautamsi/aurelia-OfficeUIFabric). I will see if this would be easier for me to use js code directly where I want to use limited number of control.

**Comment by gautamsi** [comment]
I ended up using CollectionObserver over my array to ad modify Tabs in TabStrip at run time. 
Other annoyance is to use compose element all the time in content, can not use global resource.
