### ISSUE TITLE
New component resources missing in package.json

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia-ui-toolkits/aurelia-kendoui-bridge#756]
Hi,

I've notice that the new components: kendoDateInput, kendoListBox, kendoMobileButtonGroup, kendoMediaPlayer are missing in package.json under aurelia => build => resources.

Please consider to add them in the next release.

Thanks!

**Comment by JeroenVinke** [comment]
Ah yes. It's quite easy to miss. I'll try and add them today

**Comment by JeroenVinke** [comment]
This should be fixed in 1.6.3

**Comment by enrico-padovani** [comment]
Yes it is. Thanks Jeroen
