### ISSUE TITLE
Grid ignoring bind changes

### ISSUE THREAD

**Issue by CesarAfonso** [aurelia-ui-toolkits/aurelia-kendoui-bridge#758]
Hi,

Well I want to set the buttons, 'create', 'edit', 'destroy' based on user input, but it seems that the grid after initializing correctly the toolbar and the commands with the binding values. The grid won't reflect future changes to the binding source.

Here is the use case : https://gist.run/?id=0475d643f42c8d5f2a1b2a85e7e08c9b

If it's impossible to do this, is there any other way to show the buttons based on one condition?

**Comment by JeroenVinke** [comment]
Hey @CesarAfonso 

No such thing as two way binding when working with Kendo, unfortunately. You could give this a shot: https://gist.run/?id=aed43d994f402a679a93e40e58ad0aea

**Comment by CesarAfonso** [comment]
Ok @JeroenVinke, thank you for the quick answer. That's not a pretty solution, but I think it will work I originally thought that I could observe the command list like I can observe the data list.

I'm gonna close the issue them.
