### ISSUE TITLE
canot format grid aggragtion  

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#768]
@JeroenVinke long time no speak :)

I created that [Gist](https://gist.run/?id=93b31fb2cb6df849a478a8559dc180ac) demonstrate when aggregate  column , format is not apply.

Any idea mate?

**Comment by eliavmaman** [comment]
@JeroenVinke  what to do : ) ?

**Comment by JeroenVinke** [comment]
Hey. You need to format it yourself, for example with a value converter

**Comment by eliavmaman** [comment]
10x man.. will do. will u come to Israel soon ?
