### ISSUE TITLE
Components Catalog is broken

### ISSUE THREAD

**Issue by tapoinde** [aurelia-ui-toolkits/aurelia-kendoui-bridge#769]
None of the component examples are loading in the components catalog.

![aurelia-kendo-bridge](https://user-images.githubusercontent.com/16900347/31774558-164bfc7c-b4b4-11e7-815d-898bf0b33575.PNG)

**Comment by adriatic** [comment]
Based on the details of the failure messages, this is a temporary issue, based on networking problem between the server in US and in Netherlands.

@JeroenVinke is in the best position to verify this, as he controlls one of the servers.

**Comment by JeroenVinke** [comment]
Thanks, it should be back up. I moved the gist-serve application to a new server, which will save me a lot of money on a yearly basis
