### ISSUE TITLE
Disable AutoComplete for the filter in kendo Grid

### ISSUE THREAD

**Issue by loicndjoyi** [aurelia-ui-toolkits/aurelia-kendoui-bridge#772]
Hi,

We do a server filtering with the kendo Grid. The autoComplete (enable by default) use the same datasource as the grid. We need to disable it or at least disable the server filtering of the AutoComplete.

Thanks!

**Comment by JeroenVinke** [comment]
Hey @Lloyc,

Interesting use case, for which I don't know the solution unfortunately. If you figure out how to do it with kendo, then I can help you with doing that using the bridge

**Comment by Lloyc** [comment]
Hi @JeroenVinke ,

Thank you for the quick reply. We use Typescript as transpiler for our Aurelia project. I found 2 ways to do it with kendo: 
1)
![image](https://user-images.githubusercontent.com/11031281/32661070-6be2709e-c5f3-11e7-8eea-c2ac20608865.png)
2)
![image](https://user-images.githubusercontent.com/11031281/32661099-8b62d85a-c5f3-11e7-919f-547d79d8c2b0.png)

Unfortunatly, I can't make it work. If you need a reproducible example I can create a sample Repo.

Thank you!

**Comment by adriatic** [comment]
@Lloyc knowing that @JeroenVinke really busy at this time, I checked your issue. It seems that you are not aware of our **[KendoUI Bridge Catalog application](http://aurelia-ui-toolkits.github.io/demo-kendo/)**, since it demonstrates the way to disable the server filtering of the AutoComplete. 

Have a look at: http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/autocomplete-server-filtering and check the code for **`app.js`**, to see

```
export class RemoteData {
  constructor() {
    this.datasource = {
      type: 'odata',
      serverFiltering: true,
      transport: {
        read: '//demos.telerik.com/kendo-ui/service/Northwind.svc/Products'
      }
    };
  }
}
```

Note: disregard the name of this class - this is a sloppy consequence of copy and paste that has no bearing on the actual use.

**Comment by Lloyc** [comment]
Thank you @adriatic for the reply. I'm aware of your catalog. However this sample in your answer is not for the autocomplete in the Grid. I use the Kendo Grid like [here](https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid-multi-select). I do a server Filtering in the grid with the filterable mode "row". The AutoComplete is enable by default in the Grid and use the same datasource as the Grid(by default). Whenever I type a single letter into filter input then grid makes a call to WebApi.  I just want to know if it is possible to turn it off or make that only when I will unfocus input or click key Enter or something else.

**Comment by JeroenVinke** [comment]
If you could create the sample we can take closer look. Thanks!

**Comment by adriatic** [comment]
I am being curious: why do you use autocomplete control in the grid and want to disable the key property of the autocomplete (to provide you with some guidance after each keystroke)?

If you find my curiosity inappropriate, please ignore it as a most likely do not use your use case scenario 😄. @JeroenVinke will definitively provide you with best possible answer to your question.

**Comment by Lloyc** [comment]
Thank you @adriatic for the question. I use the Grid control with the ServerFiltering option. In the input of the filtering option 
![image](https://user-images.githubusercontent.com/11031281/32676783-e5aeba28-c629-11e7-9844-9dfc7316b3bb.png)
, there is by default an Autocomplete. I didn't add it myself. I want to disable it to prevent performance issues. Tell me if there is something unclear. English is not my first language.

@JeroenVinke I'll create it as soon as possible. 

Thank you!
