### ISSUE TITLE
Aurelia commercial visibility 

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia-ui-toolkits/aurelia-kendoui-bridge#773]
Hi,

maybe It's not the best place to post this, but since we're kendo ui pro users and we do use the bridge for kendo components with ease, I'd like to see the official Aurelia support on the kendoui home page where now the have jquery, angular, react and vue.

[![untitled](https://user-images.githubusercontent.com/7766472/33313850-25169874-d42c-11e7-8960-e3aad5e85676.png)](https://www.telerik.com/kendo-ui)

I think this will increase a lot the Aurelia visibility in the industries / line of business applications. Did you reach out to telerik team?

**Comment by tonydrake** [comment]
LOL.. I saw that before I realized what it was and went - "What, telerik official Aurelia!!" and clicked through - then though - Oh, what's happened...    ;-(

**Comment by enrico-padovani** [comment]
So that confirms that It'll be awesome :)

**Comment by adriatic** [comment]
This idea is well and alive - to the point that we are in communications with KendoUI product manager defining what and when should be done.

**Comment by enrico-padovani** [comment]
That's good news! Maybe we can use this issue to keep track of the progress. Please keep the community updated, It's always good to have feedback even if they are for just work in progress things.

I've been using kendo ui directives for angular 1 and I can tell you that with Aurelia bridge is a much cleaner approach, less to code, less hacks.

**Comment by adriatic** [comment]
You can track the progress directly at the place where this project will be coordinated. Initally, this is the repository **[kendoui-bridge-next](https://github.com/aurelia-ui-toolkits/kendoui-bridge-next)** where aurelia-ui-toolkits team provides the ideas for the improvements of the current jQuery based KendoUI SDK - see this **[list of issues](https://github.com/aurelia-ui-toolkits/kendoui-bridge-next/issues)**. 

This work was scheduled to start in late 2017, so I need to check with KendoUI team when will they be ready to start. 

Our biggest issue is the lack of collaborators from Aurelia Community - at the moment, the whole team consists of @JeroenVinke and me (@adriatic) - which is barely enough to maintain the current bridge.

**Comment by enrico-padovani** [comment]
So, I'm closing this and I'll keep an eye on the "bridge next" I guess you'll accept some contributions.

Thanks for the explanation and the effort you are putting into it.

**Comment by adriatic** [comment]
I would love to get contributors @enrico-padovani 👍
