### ISSUE TITLE
Column-level sortable/compare

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-kendoui-bridge#775]
Hi,

I have a column that is bound to an object like so:

```html
itemInventoryTemplate = '${itemInventory.name}';  
<ak-col k-field="itemInventory" k-template.bind="itemInventoryTemplate">
```

The sorting on that field is messed up since it's bound to an object and not the `itemInventory.name` property. I think I need to do something like this on the column (based on https://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.sortable.compare):

```html
<ak-col k-sortable.bind="{
                    compare: function(a, b) {                        
                        return a.itemInventory.name - b.itemInventory.name;
                    }
                }
```

But that's not working and I'm not sure what I'm doing wrong.

**Comment by jasonhjohnson** [comment]
Somebody? Anybody?

**Comment by adriatic** [comment]
Sorry @jasonhjohnson - you are clearly a very patient person and are waiting way too long. I will warn @JeroenVinke (who is in the middle of the several months long 20 hours a day effort)

**Comment by JeroenVinke** [comment]
@jasonhjohnson are you sure that this is possible with kendo? https://www.telerik.com/forums/sorting-filtering-complex-objects#vqADQPwZJUWOvQlWzHaf1A

**Comment by JeroenVinke** [comment]
ah, I see that this works: https://gist.run/?id=d9eb40ca9a9ef2717587cf9c20215d24

**Comment by jasonhjohnson** [comment]
Thank you @JeroenVinke and @adriatic. This works great.
