### ISSUE TITLE
onDataBound combobox

### ISSUE THREAD

**Issue by owlcode** [aurelia-ui-toolkits/aurelia-kendoui-bridge#779]
**Problem** dataOnBound event firing twice makes input clear itself
**Reproduction** [Go to GistRun](https://gist.run/?id=81feb1b3bc970ceb7755700f78d65eb9), type one letter into combobox - input is cleared, dataBound is fired twice
**Expected behaviour** [Doc example](https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/combobox-events) 

Thing is a little bit weird for me, because mentioned gist is being generated from doc example after clicking "Run" button and even though it is not working properly. I think there might be some version mismatch. This situation happens only when you type anything first time after initialization, later on everything seems to work properly.

**Comment by JeroenVinke** [comment]
Sorry for the late response. That gist was very outdated, after updating the bridge and Kendo it works like it should now. When the sample runs in the catalog (so not in gist.run) it doesn't execute index.html (so it uses Kendo, Aurelia and the bridge versions of the catalog, which were up to date). When you run a gist in gist.run it does use index.html, so it was using an older aurelia, kendo and bridge.

Let me know if you have more issues
