### ISSUE TITLE
all bridge controls min.js.map,are not found only in IE

### ISSUE THREAD

**Issue by eliavmaman** [aurelia-ui-toolkits/aurelia-kendoui-bridge#789]
when page is loaded , there are many calls that returns error 404. 
 that happened only in IE.
![image](https://user-images.githubusercontent.com/6911449/40657330-267a02b0-6350-11e8-8494-0e9f74233411.png)

Kendo bridge version is  "aurelia-kendoui-bridge": "npm:aurelia-kendoui-bridge@0.11.9".
@JeroenVinke  can u please help us?

**Comment by eliavmaman** [comment]
@JeroenVinke  i couldn't tell which settings cause this problem.. can u please tell me if so i can  change them my friend ?

**Comment by JeroenVinke** [comment]
These 404's are harmless. The browser only tries to fetch these `.map` files when you have the developer console open and refresh the page, which a normal user would not do. I don't know which setting you can use in internet explorer to turn this behavior off, but this is not a problem specific to the bridge
