### ISSUE TITLE
Beware of the package.json - config.js relationship

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#79]
Here is the **[issue](https://github.com/jspm/jspm-cli/issues/1306)** I raised with jspm-cli (Guy Bedford) and his comments. 

#### Very useful if you did not know about `jspm update` and always used `jspm install`

**Comment by JeroenVinke** [comment]
@adriatic can you mention this in the documentation for plugin developers, and then close this issue?

**Comment by adriatic** [comment]
+ack
