### ISSUE TITLE
editor component and placeholder issue

### ISSUE THREAD

**Issue by miniben-90** [aurelia-ui-toolkits/aurelia-kendoui-bridge#798]
Hello,

I try to add placeholder to the editor component, but It doesn't work at all. I tried to add k-placeholder and placeholder as attribute and as parameters for ak-rich-editor but nothing works.

gistrun: [https://gist.run/?id=1ea958a21f31390ff5147451536e4b84](https://gist.run/?id=1ea958a21f31390ff5147451536e4b84)

```html
  <require from="aurelia-kendoui-bridge/editor/editor"></require>
  <div id="example">
    <textarea
    ak-rich-editor="k-tools.bind:['bold'];k-messages.bind: { bold: 'TEsBol' };k-placeholder.bind: 'test';"
    placeholder="test"
    ak-placeholder="test"
    style="height:440px">
  </div>
```
Any idea to make it run as well?

Thanks you for your help.

**Comment by JeroenVinke** [comment]
Hey,

Thanks for reporting this issue. We probably need to update our dictionary of which properties are supported. I'll let you know when a new version is out.

**Comment by JeroenVinke** [comment]
Actually, you can fix this by updating kendo. I think that propert was added in 2018: https://gist.run/?id=face093f33190e54059b99a7c81edb7b

Then the k-placeholder inside ak-rich-editor should be enough

**Comment by miniben-90** [comment]
Hi,
Ok thanks for your answer!
