### ISSUE TITLE
DateRangePicker (feature request)

### ISSUE THREAD

**Issue by Tim-Erwin** [aurelia-ui-toolkits/aurelia-kendoui-bridge#801]
Kendo offers a [DateRangePicker](https://demos.telerik.com/kendo-ui/daterangepicker/index), it would be nice to have it eposed via the bridge.

**Comment by JeroenVinke** [comment]
Hey, I just released 1.9.0 which contains this wrapper. Here is how you can use it: http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/daterangepicker-basic-usage

Let me know if you run into issues :)

**Comment by Tim-Erwin** [comment]
Thanks 👍
