### ISSUE TITLE
Arc Gauge support

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia-ui-toolkits/aurelia-kendoui-bridge#803]
Hi there!

can ArcGauge be added to the bridge?

https://demos.telerik.com/kendo-ui/arc-gauge/index

**Comment by JeroenVinke** [comment]
Hey, sure! I'll see if I can put something together this weekend

**Comment by enrico-padovani** [comment]
That's great! Thanks mate :)

**Comment by JeroenVinke** [comment]
http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/arc-gauge-basic-use

Done in 1.10.0 😄

**Comment by enrico-padovani** [comment]
Thanks Jeroen, just tested and it works like a charm! Cheers :)
