### ISSUE TITLE
aurelia-ui-toolkits-1.gitbook.io refused to connect.

### ISSUE THREAD

**Issue by tactical-drone** [aurelia-ui-toolkits/aurelia-kendoui-bridge#805]
The installation instructions at https://aurelia-ui-toolkits.github.io/demo-kendo/#/installation does not seem to want to load.

**Comment by JeroenVinke** [comment]
Apparently gitbook does not allow itself to be inside an iframe anymore. I've changed it, it now shows an url. Not pretty, but it works ;)

Thanks!
